### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by echoix** [comment]
Npm doesn't install. Stylelint released a v16 today, and the dev/linters job of stylelint doesn't work. PHP Codesniffer changed organization with the new maintainer that finally got commit access this summer, but the original maintainer isn't working at the company behind anymore, but that company doesn't want to allow the transfer to an organization or have her with more rights, and all being very slow to react. When they finally confirmed that the only way was to have a fork, and have all the users now refile their issues in the new repo (since it wasn't transferred). She released a version today with minimal changes, but with the new organization. The original maintainer responded a couple of times in that announcement thread. Some package managers allow to use the old name for the new fork. But it fails, something from GPG, either the usual downtime since we didn't add the new mirror yet, or since it was a new key/new maintainer. I saw a log with "Justine" (the new maintainer) in it, so might be the latter. 

_Originally posted by @echoix in https://github.com/oxsecurity/megalinter/pull/3181#issuecomment-1848075920_





~~~~~~~~~
That means we are blocked :S 
I'm imagining what our workflows would be like if we managed to get to full version pinning, and update the deps when they don't break the rest. (Since now if we rerun a previously passing job, it would fail, we are time-dependant)

**Comment by nvuillam** [comment]
@echoix any idea about how to solve all the failing CI jobs ? :'(

**Comment by echoix** [comment]
How did they pass in this PR?

**Comment by echoix** [comment]
> @echoix any idea about how to solve all the failing CI jobs ? :'( 

Maybe start by pinning stylelint to its downgraded version before checking the rest

**Comment by nvuillam** [comment]
I want to release a version this weekend do probably what i'll do ^^

**Comment by nvuillam** [comment]
> How did they pass in this PR?

I have no idea 🥹

**Pull request merged**
