### PR TITLE
Add support for master branch in TEMPLATES/mega-linter.yml

### PR DESCRIPTION
**Pull request by rasa**
### Author/Contributor
- [X] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@rasa great PR, but unfortunately I merged another PR that generated conflicts , please can you merge them ? :)

**Comment by rasa** [comment]
> @rasa great PR, but unfortunately I merged another PR that generated conflicts , please can you merge them ? :)

I resolved the conflicts, but haven't tested them.

**Review by nvuillam — APPROVED** [review]
Thanks a lot for your contribution :)
@rasa if you can test it with beta version before next release, it would be nice ^^

**Comment by rasa** [comment]
@nvuillam Tested and working locally.

**Comment by nvuillam** [comment]
@rasa great, thanks :)

note: you should anyway rename master into main on your repos for more inclusivity ^^

**Pull request merged**
