### PR TITLE
Use docker/build-push-action@ in CI instead of upload-docker.sh

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4148517177)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|❌ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |[225](https://github.com/oxsecurity/megalinter/actions/runs/4148517177)|0.35s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.29s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.44s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.48s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.97s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.26s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.64s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    0|[232](https://github.com/oxsecurity/megalinter/actions/runs/4148517177)|5.67s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.18s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|14.8s       |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.51s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4148517177) |1.86s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|3.7s        |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.71s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.68s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.37s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|10.37s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4148517177)|16.17s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |25.81s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.33s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |11.17s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.35s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|17.31s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.73s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.36s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.69s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|55.82s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.13s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4148517177)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4149129620)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.16s       |
|✅ BASH      |[shfmt](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.78s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|7.19s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.66s       |
|✅ JSON      |[jsonlint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.59s       |
|✅ JSON      |[v8r](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.71s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/markdown_markdownlint)                        |  309|    2|[232](https://github.com/oxsecurity/megalinter/actions/runs/4149129620)|5.8s        |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.25s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|14.67s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.6s        |
|⚠️ PYTHON    |[bandit](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4149129620) |2.03s       |
|✅ PYTHON    |[black](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_black)                                        |  176|    0|                                                                      0|3.19s       |
|✅ PYTHON    |[flake8](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.76s       |
|✅ PYTHON    |[isort](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.53s       |
|✅ PYTHON    |[mypy](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.62s       |
|✅ PYTHON    |[pylint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_pylint)                                      |  176|     |                                                                      0|10.36s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4149129620)|15.44s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.23s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4149129620) |1.25s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |3.47s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.05s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |6.49s       |
|✅ REPOSITORY|[syft](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.87s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |15.91s      |
|✅ SPELL     |[cspell](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/spell_cspell)                                       |  729|     |                                                                      0|16.54s      |
|✅ SPELL     |[misspell](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/spell_misspell)                                   |  550|    2|                                                                      0|0.51s       |
|✅ XML       |[xmllint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.49s       |
|✅ YAML      |[v8r](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|51.9s       |
|✅ YAML      |[yamllint](https://megalinter.io/df547fefea0ec200767ed17a1d61a092c938d190/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.14s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4149129620)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam congratulations for this great achievement! It will help us to unlock several PRs like #2273 #2299 #2314

**Comment by nvuillam** [comment]
@bdovaz I knew you would like it haha ^^

And it will be a game changer for releases.... until now we always rebuilt the images, so there was 1h between the release (with dependabot & renovate creating automated PRs in repos using MegaLinter), and that provoked issues because the new images were not released yet... 

Now we'll just take beta images, retag them & push them, and it is done in 2 mn ^^

**Comment by bdovaz** [comment]
@nvuillam yes, little by little we are getting rid of the technical debt inherited from superlinter in terms of CI and that's really great!

**Pull request merged**
