### PR TITLE
Allow merge lists with extends

### PR DESCRIPTION
**Pull request by bdovaz**
Resolves https://github.com/oxsecurity/megalinter/issues/3466

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Review by nvuillam — CHANGES_REQUESTED** [review]
plz check comments

**Comment by nvuillam** [comment]
@bdovaz I'm sorry but validating this PR would provoke issues in many places

Example:

base contains:

```
SALESFORCE_SFDX_SCANNER_APEX_ARGUMENTS:
  - --pmdconfig
  - ./config/pmd-ruleset.xml
```

local want to override:

```
SALESFORCE_SFDX_SCANNER_APEX_ARGUMENTS:
  - --pmdconfig
  - ./my-other-file-name.xml
```

With your update, the result would be equivalent to:

```
SALESFORCE_SFDX_SCANNER_APEX_ARGUMENTS:
  - --pmdconfig
  - ./config/pmd-ruleset.xml
  - --pmdconfig
  - ./my-other-file-name.xml
```

**Comment by nvuillam** [comment]
To make it work, we might need a new argument like "CONFIG_PROPERTIES_TO_APPEND"

ex: 
```
CONFIG_PROPERTIES_TO_APPEND: ENABLE_LINTERS,XXXXXX
```

And if the property is flagged as to append, then call merge_dicts, otherwise keep current behaviour

**Comment by bdovaz** [comment]
@nvuillam done!

**Comment by bdovaz** [comment]
@nvuillam the errors are from a broken link detected by lychee, nothing from this particular PR.

**Comment by nvuillam** [comment]
@bdovaz great :)
Let's merge once the infamous eslint-plugin-jsonc is solved to not break beta version :)

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
@bdovaz it's finally merged, you can test with beta version if you want :)

**Pull request merged**
