### PR TITLE
Use relative file paths to call linters

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/oxsecurity/megalinter/issues/1875

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: ❌ [**ERROR**](https://github.com/oxsecurity/megalinter/actions/runs/3063977108)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                   |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.02s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.26s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.28s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |2.6s        |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  104|     |                                                                          0|7.58s       |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|2.03s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.23s       |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   21|     |                                                                          0|14.6s       |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  292|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3063977108)  |5.42s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  292|     |                                                                          0|4.67s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  292|    0|                                                                          0|7.25s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|0.79s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  169|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3063977108) |2.56s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  169|    1|                                                                          0|4.64s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  169|     |                                                                          0|2.26s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  169|    1|                                                                          0|0.66s       |
|❌ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  169|     |[**1**](https://github.com/oxsecurity/megalinter/actions/runs/3063977108)  |16.51s      |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  169|     |                                                                          0|11.3s       |
|:warning: PYTHON  |[pyright](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pyright)                                    |  169|     |[**278**](https://github.com/oxsecurity/megalinter/actions/runs/3063977108)|16.51s      |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                         |15.99s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.3s        |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |6.72s       |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |20.36s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  701|     |                                                                          0|18.6s       |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  530|    0|                                                                          0|0.71s       |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.0s        |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   79|    0|                                                                          0|2.72s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|37.79s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   80|     |                                                                          0|1.3s        |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3063977108)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
How is it going? What is blocking it?

**Comment by nvuillam** [comment]
@bdovaz memory crash within the docker image... really hard to debug :/
but you can try with temp docker image generated by CI job

**Comment by nvuillam** [comment]
image

:/

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam-patch) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/3757393487)

| Descriptor  |                                                      Linter                                                      |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-nuillam-patch/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.08s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-nuillam-patch/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.64s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-nuillam-patch/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-nuillam-patch/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.05s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-nuillam-patch/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|9.32s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam-patch/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.72s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-nuillam-patch/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.19s       |
|✅ JSON      |[v8r](https://megalinter.io/test-nuillam-patch/descriptors/json_v8r)                                              |   21|     |                                                                      0|13.92s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam-patch/descriptors/markdown_markdownlint)                        |  297|    2|[11](https://github.com/oxsecurity/megalinter/actions/runs/3757393487) |5.37s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-nuillam-patch/descriptors/markdown_markdown_link_check)          |  297|     |                                                                      0|5.23s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-nuillam-patch/descriptors/markdown_markdown_table_formatter)|  297|    2|                                                                      0|13.42s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-nuillam-patch/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.74s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-nuillam-patch/descriptors/python_bandit)                                      |  171|     |[43](https://github.com/oxsecurity/megalinter/actions/runs/3757393487) |3.35s       |
|✅ PYTHON    |[black](https://megalinter.io/test-nuillam-patch/descriptors/python_black)                                        |  171|    0|                                                                      0|3.6s        |
|✅ PYTHON    |[flake8](https://megalinter.io/test-nuillam-patch/descriptors/python_flake8)                                      |  171|     |                                                                      0|1.92s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-nuillam-patch/descriptors/python_isort)                                        |  171|    0|                                                                      0|0.41s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-nuillam-patch/descriptors/python_mypy)                                          |  171|     |                                                                      0|6.99s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-nuillam-patch/descriptors/python_pylint)                                      |  171|     |                                                                      0|11.01s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-nuillam-patch/descriptors/python_pyright)                                    |  171|     |[272](https://github.com/oxsecurity/megalinter/actions/runs/3757393487)|17.43s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-nuillam-patch/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.35s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-nuillam-patch/descriptors/repository_devskim)                                |yes  |     |[60](https://github.com/oxsecurity/megalinter/actions/runs/3757393487) |1.14s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-nuillam-patch/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.45s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-nuillam-patch/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.03s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-nuillam-patch/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |3.35s       |
|✅ REPOSITORY|[syft](https://megalinter.io/test-nuillam-patch/descriptors/repository_syft)                                      |yes  |     |no                                                                     |2.78s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-nuillam-patch/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |20.16s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-nuillam-patch/descriptors/spell_cspell)                                       |  712|     |                                                                      0|17.52s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-nuillam-patch/descriptors/spell_misspell)                                   |  536|    2|                                                                      0|0.48s       |
|✅ XML       |[xmllint](https://megalinter.io/test-nuillam-patch/descriptors/xml_xmllint)                                       |    3|     |                                                                      0|0.0s        |
|✅ YAML      |[prettier](https://megalinter.io/test-nuillam-patch/descriptors/yaml_prettier)                                    |   80|    0|                                                                      0|2.42s       |
|✅ YAML      |[v8r](https://megalinter.io/test-nuillam-patch/descriptors/yaml_v8r)                                              |   22|     |                                                                      0|41.65s      |
|✅ YAML      |[yamllint](https://megalinter.io/test-nuillam-patch/descriptors/yaml_yamllint)                                    |   81|     |                                                                      0|1.38s       |

See errors details in [artifact MegaLinter reports on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3757393487)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [oxsecurity/megalinter/flavors/python@test-nvuillam-patch](https://megalinter.io/test-nuillam-patch/flavors/python/) (57 linters)


_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam can you make a rebase? To at least check from time to time if this problem has been solved.

I would do it myself but I have doubts with `utils.py` and I prefer you to solve it.

**Comment by nvuillam** [comment]
@bdovaz done :)

**Comment by bdovaz** [comment]
@nvuillam Is it just me or seeing the result of the jobs, the random error that occurred no longer exists?

**Comment by bdovaz** [comment]
> @nvuillam Is it just me or seeing the result of the jobs, the random error that occurred no longer exists?

ping @nvuillam

**Comment by nvuillam** [comment]
The error was not random... it was always and hard to diagnose its source ^^

**Comment by nvuillam** [comment]
Not crashing indeed !
But did i rebuild?

**Comment by nvuillam** [comment]
@bdovaz I have a good feeling about this one... :D :D

**Comment by nvuillam** [comment]
@bdovaz @echoix @Kurt-von-Laven 

Now I'm kind a afraid to release a new version... this PR is potentially very impacting, if you have some time please use beta versions in your repos to make sure that it still works well with relative files :) ( I'll obviously do the same on my side ^^ )

**Comment by echoix** [comment]
You could release a RC in the weekend and look at the number of pulls the following week to make sure that there was enough pulls.

**Comment by Kurt-von-Laven** [comment]
Thanks for the heads up, @nvuillam. I tried the `documentation`, `dotnet`, `javascript`, and `python` flavors of the beta version on all of our repositories and encountered three issues. I am listing them all here for now since the second and third seem like they could potentially be related, but I am happy to file issues about these when I have more time tomorrow. The third issue is a preexisting issue that was made more visible by #2455, because previously ESLint silently didn't run at all locally.

1. CSharpier is broken; I am curious whether anyone else encounters this issue:
    
    ```
    ❌ Linted [CSHARP] files with [csharpier]: Found 1 error(s) - (1.18s)
    --Error detail:
    Run "dotnet tool restore" to make the "dotnet-csharpier" command available.

    Unable to get number of errors with regex_number and Issues found: ([0-9]+) in .* files
    ```

1. CSpell is broken when importing dictionaries that aren't bundled:

    ```
    ❌ Linted [SPELL] files with [cspell]: Found 1 error(s) - (18.84s)
    --Error detail:
    Configuration Error: Failed to read config file: "/tmp/lint/@cspell/dict-medicalterms/cspell-ext.json"
    CSpell: Files checked: 0, Issues found: 0 in 0 files

    ❌ Error(s) have been found during linting
    ```

    Our `cspell.config.yaml` contains:

    ```yaml
    import:
      - "@cspell/dict-medicalterms/cspell-ext.json"
    ```

    Our `.mega-linter.yaml` contains:

    ```yaml
    SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
    SPELL_CSPELL_PRE_COMMANDS:
      - command: npm install @cspell/dict-medicalterms@3.0.0
    ```

1. In our Yarn TypeScript projects, there is one error per file of the following form:

    ```
    ❌ Linted [TYPESCRIPT] files with [eslint]
    --Error detail:

    /tmp/lint/some_file.ts
      0:0  error  Parsing error: File '@tsconfig/node18-strictest-esm/tsconfig.json' not found
    ```

    Our `tsconfig.json` contains:

    ```json
    {
      "extends": "@tsconfig/node18-strictest-esm/tsconfig.json"
    }
    ```

    Our `package.json` contains:

    ```json
    {
      "devDependencies": {
        "@tsconfig/node18-strictest-esm": "1.0.1"
      }
    }
    ```

    Our `.eslintrc.yaml` is:

    ```yaml
    root: true
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
      - prettier
    parser: "@typescript-eslint/parser"
    parserOptions:
      project:
        - tsconfig.json
    plugins:
      - "@typescript-eslint"
    env:
      node: true
    ```

**Comment by nvuillam** [comment]
@Kurt-von-Laven I'm trying to fix that in #2601 ... the idea is the following:

- check if PRE_COMMANDS contain "npm" or "yarn"
- if yes:
  - copy /node_deps into workspace+"node_modules"
  - Add workspace+"node_modules" in PATH
  - run the PRE_COMMANDS

Do you think it could work ? ^^

**Pull request merged**
