### PR TITLE
WIP: Change the way Azure Devops project 

### PR DESCRIPTION
**Pull request by EtienneDeneuve**
Should fix issue #2300

### CODE REVIEW

**Review by Kurt-von-Laven — COMMENTED** [review]
Should we do the same with `SYSYSTEM_COLLECTIONURI`?

**Comment by EtienneDeneuve** [comment]
I was searching, I've a doubt if we can create an Azure DevOps org with a white space.

Many company use space in the project or repo name, maybe it's better to sanatize all, just in case, don't you think so?
________________________________

**Comment by nvuillam** [comment]
By definition, an URI does not need to be encoded / decoded , so if SYSTEM_COLLECTIONURI is a valid URI, it should not be necessary to manipulate it :)

**Review by nvuillam — APPROVED** [review]
Thanks for the catch and thanks for the PR :)

**Comment by nvuillam** [comment]
The megalinter-runner job issue is not related to this PR, that's why I force its merge

**Comment by EtienneDeneuve** [comment]
And thanks for megalinter and the merge ;)
________________________________

**Comment by nvuillam** [comment]
@EtienneDeneuve you're welcome :)
Posting on Azure is not in the GitHub related CI... if you can confirm that your fix well with docker image **oxsecurity/megalinter:beta** before our next release (that should happen soon) , it would be nice ;)

Note: ghcr.io seems down, or in bad shape... so the build of beta is currently failing ... when it will be available I'll notify here :)

**Pull request merged**
