### PR TITLE
Allow use of configuration files with v8r

### PR DESCRIPTION
**Pull request by bdovaz**
#1974

### CODE REVIEW

**Comment by bdovaz** [comment]
Any news?

**Comment by nvuillam** [comment]
We still need to make pass the PR that uses relative paths :/

**Comment by bdovaz** [comment]
No stale, waiting for #1877

**Comment by bdovaz** [comment]
@nvuillam It could be merged already, couldn't it? Already been unlocked by #1877

**Comment by nvuillam** [comment]
@bdovaz if the CI jobs are ok, yes:)

**Review by nvuillam — APPROVED** [review]

**Pull request merged**
