### PR TITLE
Update base image to 3.12.1-alpine3.19

### PR DESCRIPTION
**Pull request by bdovaz**
https://hub.docker.com/_/python/tags?page=1&name=alpine3.19

There is the tag `3.12-alpine3.19` but I understand that seeing the value that was set we want a certain determinism, right @nvuillam?

### CODE REVIEW

**Comment by echoix** [comment]
You changed revive and the base image in this PR?

**Comment by bdovaz** [comment]
The change of revive is because I was getting an error that I thought that maybe leaving the previous installation method (the one that was commented) was going to fix it.

I don't know either but it seems that the revive error is caused by Alpine 3.19.

Do you know @echoix what is happening?

**Comment by echoix** [comment]
Nope, I don't know (yet). But alpine 3.19 changes the go version, but it should have been built with a higher version anyways because of the very loose tag on the building image.

The revive in the docker image they provide still didn't include the version number last time I tried.

**Comment by bdovaz** [comment]
@echoix the revive problem is recent, it is from the release of a few days ago (1.3.5): https://github.com/mgechev/revive/issues/956

I just encountered that problem and I thought it was because of the Alpine version.

I have downgraded to 1.3.4 for now.

**Comment by bdovaz** [comment]
Now it only fails: https://github.com/oxsecurity/megalinter/actions/runs/7423769467/job/20204128689?pr=3266

Specifically, this linter: https://megalinter.io/latest/descriptors/clojure_cljstyle/

Do you know what it could be?

cc @nvuillam @echoix

**Comment by echoix** [comment]
Can you test like locally a dockerfile that installs cljstyle only, like the one used in the smaller image, and add a call to the linter help and version, see if 1) if launches, and 2) what the version is (to know if it is the regex that is bad). 
I think however the problem is before that, since it seems no tests at all pass.

**Comment by bdovaz** [comment]
@echoix leaving the entrypoint.sh file with:

```bash
#!/usr/bin/env bash

/usr/local/bin/cljstyle version
```

With Alpine 3.18:

`mvxcvi/cljstyle 0.15.0 (1f58e2e7af4c193aa77ad0695f6c2b9ac2c5c5ec)`

With Alpine 3.19:

`/entrypoint.sh: line 3:     7 Segmentation fault      /usr/local/bin/cljstyle version`

Any way to debug the Segmentation fault?

I also see that although in the last month there has been some activity, the reality is that the project has been stopped for 2 years, the last release is from 2021 (I do not know if it may have to do with some kind of incompatibility in recent versions of Alpine): 

https://github.com/greglook/cljstyle/commits/main/

https://github.com/greglook/cljstyle/releases

**Comment by echoix** [comment]
Segfaults are real "bugs". Like invalid memory accesses by the program, or serious errors. The binary is not compatible as is. Is there a way to recompile, or have a newer binary (from the same sources, but needs to be recompiled at some point for sure)

**Comment by nvuillam** [comment]
there is still an issue with lychee new version, I investigate and try to fix that in main

**Comment by nvuillam** [comment]
There is no alpine based lychee docker image for their previous version.... i check if I find another way :/

cf https://github.com/lycheeverse/lychee/issues/1338

**Comment by bdovaz** [comment]
@nvuillam ready?

**Review by nvuillam — APPROVED** [review]
Great job @bdovaz :)

**Pull request merged**
