### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by echoix** [comment]
Jsonc seems broken for a couple of days, do we know what's wrong?

**Comment by nvuillam** [comment]
@echoix eslint has released a v9 with breaking changes  that does not support a parameter we use 

I quickly tried something but... didn't work >_<

**Comment by nvuillam** [comment]
I think ifound it :)

https://github.com/eslint/eslint/blob/1fa66220ad130eeb69cfa0207d3896b7bb09c576/docs/src/use/configure/migration-guide.md?plain=1#L596

**Comment by echoix** [comment]
We might want to add a note in the changelog, unless you want to answer issues afterwards

**Comment by nvuillam** [comment]
It still does not work, I posted an issue https://github.com/ota-meshi/eslint-plugin-jsonc/issues/328

If no one finds a workaround... we might have to downgrade eslint :/

**Pull request merged**
