### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by echoix** [comment]
Too much api requests for php I think... And we could try updating to python 3.11.6 image while waiting for 3.12 to work. I'll do it after the scheduled run of today to execute, as it would be overwritten

**Comment by echoix** [comment]
Too soon, docs for the new linter wasn’t published yet

**Comment by echoix** [comment]
@nvuillam do you know how to un-force push, partially? The automatic run of the merge of the new linter overwrote what I was finishing working on. I forgot about that trigger

**Comment by echoix** [comment]
I’d like to keep most of this https://github.com/oxsecurity/megalinter/commit/1406253f959108fc6ccba2eab56b327b265891cd , but integrate the really new stuff from https://github.com/oxsecurity/megalinter/compare/1406253f959108fc6ccba2eab56b327b265891cd..f11bd5cc5ada7e2c296c9eaebfe6488e32304e03

**Comment by echoix** [comment]
I found out how to force-push the old version (without the new linter), and will integrate the new linter with a new run of auto-update linter

**Review by echoix — APPROVED** [review]

**Comment by nvuillam** [comment]
@echoix usually when i want to avoid manual updates on such branch to be overwritten by the force push, i create another branch & PR just to be sure ^^

**Comment by echoix** [comment]
I'm pretty sure it's possible, by setting checking out this branch on next runs, I just didn't find out yet how to do something equivalent to : checkout a branch only if it exist, else checkout main. Since actions/checkout fails if the branch doesn't exist yet.

**Pull request merged**
