### PR TITLE
Configure renovate version comments for some linters

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
@echoix I validated, please merge if you need to :)

**Comment by echoix** [comment]
It is ready as is (I reworked the commits I had two weeks ago). I would do another PR for gitleaks, or should I pass it in this one?

**Comment by echoix** [comment]
I'll just merge this one now

**Comment by echoix** [comment]
Or do you want to add a changelog? I need to go now, and it probably won't be approved after

**Comment by nvuillam** [comment]
It's ok, before releasing I add manually changelog entries when I see them missing :)

**Pull request merged**
