### PR TITLE
Update dotnet linters to .NET 7

### PR DESCRIPTION
**Pull request by bdovaz**
Upgrade dotnet linters to .NET 7 whenever possible.

Unfortunately we can't install only the .NET 7 SDK, we have to keep the .NET 6 one for these linters that don't have .NET 7 compatibility yet:

https://www.nuget.org/packages/TSQLLint#supportedframeworks-body-tab

https://www.nuget.org/packages/Microsoft.CST.DevSkim.CLI#supportedframeworks-body-tab

### CODE REVIEW

**Comment by bdovaz** [comment]
@nvuillam @echoix what do you think? Do we keep this PR indefinitely open until every dotnet linter has .NET 7 compatibility or merge it with the hassle of having to have 2 SDKs coexisting at the same time?

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4296962717)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.36s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.86s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|17.42s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.19s       |
|✅ JSON      |[jsonlint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.24s       |
|✅ JSON      |[v8r](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.07s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/markdown_markdownlint)                        |  309|    1|[230](https://github.com/oxsecurity/megalinter/actions/runs/4296962717)|6.68s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.5s        |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/markdown_markdown_table_formatter)|  309|    1|                                                                      0|18.38s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.69s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4296962717) |2.03s       |
|✅ PYTHON    |[black](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_black)                                        |  183|    0|                                                                      0|4.6s        |
|✅ PYTHON    |[flake8](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.91s       |
|✅ PYTHON    |[isort](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.74s       |
|✅ PYTHON    |[mypy](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_mypy)                                          |  183|     |                                                                      0|6.8s        |
|✅ PYTHON    |[pylint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_pylint)                                      |  183|     |                                                                      0|12.11s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/python_pyright)                                    |  183|     |[254](https://github.com/oxsecurity/megalinter/actions/runs/4296962717)|17.86s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/repository_checkov)                                |yes  |     |no                                                                     |29.57s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.35s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |14.11s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |27.55s      |
|✅ SPELL     |[cspell](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/spell_cspell)                                       |  745|     |                                                                      0|20.67s      |
|✅ SPELL     |[misspell](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/spell_misspell)                                   |  566|    0|                                                                      0|0.94s       |
|✅ XML       |[xmllint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.36s       |
|✅ YAML      |[prettier](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.95s       |
|✅ YAML      |[v8r](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|60.18s      |
|✅ YAML      |[yamllint](https://megalinter.io/15b09868588e808ee1125bbb5c99bdfe4585f2ff/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.0s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4296962717)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
I'm still lost when we talk about dotnet, I let the professionals give advices ^^

**Comment by Kurt-von-Laven** [comment]
I'm guessing the .NET Docker image is noticeably bigger with both SDKs installed? Might help guide the decision to quantify how much bigger.

**Comment by nvuillam** [comment]
Wouldn't be good to add 400 megas to the main docker image, indeed ^^

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4297010264)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.16s       |
|✅ BASH      |[shfmt](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.05s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.44s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|18.05s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.21s       |
|✅ JSON      |[jsonlint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.27s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.79s       |
|✅ JSON      |[v8r](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.1s       |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/markdown_markdownlint)                        |  309|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4297010264)|7.27s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|6.53s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|21.62s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|2.0s        |
|⚠️ PYTHON    |[bandit](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4297010264) |2.54s       |
|✅ PYTHON    |[black](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_black)                                        |  183|    0|                                                                      0|3.99s       |
|✅ PYTHON    |[flake8](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_flake8)                                      |  183|     |                                                                      0|2.12s       |
|✅ PYTHON    |[isort](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.5s        |
|✅ PYTHON    |[mypy](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_mypy)                                          |  183|     |                                                                      0|8.44s       |
|✅ PYTHON    |[pylint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_pylint)                                      |  183|     |                                                                      0|13.49s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/python_pyright)                                    |  183|     |[251](https://github.com/oxsecurity/megalinter/actions/runs/4297010264)|19.59s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_checkov)                                |yes  |     |no                                                                     |35.25s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4297010264) |1.53s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.24s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.05s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |9.57s       |
|✅ REPOSITORY|[syft](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.15s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |24.41s      |
|✅ SPELL     |[cspell](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/spell_cspell)                                       |  745|     |                                                                      0|23.09s      |
|✅ SPELL     |[misspell](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/spell_misspell)                                   |  566|    2|                                                                      0|0.68s       |
|✅ XML       |[xmllint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.08s       |
|✅ YAML      |[v8r](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|65.63s      |
|✅ YAML      |[yamllint](https://megalinter.io/1ba8a12328c828766712c81157f488a168d69336/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.38s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4297010264)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
I have taken some time to build the flavor of dotnet in the 2 branches (main and features/net7) and the differences are remarkable:

image

So I understand that we will have to wait until all the dotnet linters are available for .net7... 😞

**Comment by Kurt-von-Laven** [comment]
Or we can convince Microsoft to reduce the size of the SDK!

**Comment by echoix** [comment]
I think they reduced to a minimum on .net 5 or .net 6, but its really hard to go less. And it's cumulative, they can't take away stuff. Only add.


For the increased size, is it because you have two SDKs? (And do you remember, if what you shown was the compressed or uncompressed size?)

**Comment by bdovaz** [comment]
@echoix I have only made a flavors/dotnet/Dockerfile build in each branch and I have run locally `docker images` (screenshot).

If that is not enough, give me some guidelines please. I am not a specialist in docker commands 😅

Thanks!

**Comment by Kurt-von-Laven** [comment]
I was just kidding, but that's helpful to know. In case anyone reading this thread in the future is confused, the issue is that we can't get rid of the .NET 6 SDK until all tools are on .NET 7. Those are uncompressed image sizes according to [this helpful guide](https://gist.github.com/MichaelSimons/fb588539dcefd9b5fdf45ba04c302db6). The v6.19.0 dotnet flavor is 3.31 GB uncompressed for comparison. It compresses down to 1.0 GB when using [docker-cache](https://github.com/ScribeMD/docker-cache), which uses zstd compression. That probably isn't the compressed size you were referring to though.

**Comment by Kurt-von-Laven** [comment]
In the case of MegaLinter flavors, the zstd compression we are using produces compressed sizes of about 88% of the size as [the standard compressed sizes](https://megalinter.io/latest/flavors/) I assume you were referring to @echoix.

**Comment by echoix** [comment]
We might need to plan soon about .NET 8. 
It will be released near November 14, 2023. It will be a LTS release. It is now in "go-live", with its 8.0.0-RC2 release being the latest one. I suggest another PR for that work. I don't think we need to be the first to have it, but probably have our linters support it first.

**Comment by bdovaz** [comment]
@echoix of course, you will have to consider upgrading to .NET 8 LTS.

And to put some context on this PR.

DevSkim supports .NET 7: https://www.nuget.org/packages/Microsoft.CST.DevSkim.CLI#supportedframeworks-body-tab

TSQLLint does not support it (only .NET 6): https://www.nuget.org/packages/TSQLLint#supportedframeworks-body-tab

That's why I haven't been able so far to merge anything.

It's a bit frustrating because in that repo I created a PR (https://github.com/tsqllint/tsqllint/pull/324) but nobody has been able to communicate with me why it hasn't been merged, I don't know if it's that it only has LTS support policy (.NET 7 is not) or it's that the project is half abandoned (in this year there are 3 commits).

**Comment by Kurt-von-Laven** [comment]
Given that there is a high cost in disk space (at least) to shipping multiple versions of .NET, should we consider removing TSQLLint?

**Comment by nvuillam** [comment]
About removing linters. I think about DevSkim, who is very chatty, triggers strange git errors, and it historically not very relevant compared to the other linters ...

Maybe we should add some anonymous telemetry to know which linters are used and which ones are not, so we know the impact of removing one ?

**Comment by echoix** [comment]
Well, for the specific case of tsqllint I'm not too concerned, since it can be easily used standalone, like a 40 mb tgz download. It doesn't _require_ to be used as a dotnet tool. They even have a package on npm to call it and the install.js simply downloads the archive and extracts it. So we are able to use it on its own. Since the npm way of "using" it doesn't talk about having .net installed, I assume the releases are compiled as "self-contained", that means that the runtime shouldn't be needed. In the other case we could always compile ourselves and cache it.

For me it's the one that is really tightly integrated with the dotnet dev sdk, I think it's dotnet format. Does it require that all projects that will be linted to be a .NET project too?

What other linters are written in a dotnet language? (Not necessarily the ones that are in the dotnet flavor)

**Comment by Kurt-von-Laven** [comment]
> Well, for the specific case of tsqllint I'm not too concerned, since it can be easily used standalone, like a 40 mb tgz download. It doesn't require to be used as a dotnet tool. They even have a package on npm to call it and the install.js simply downloads the archive and extracts it. So we are able to use it on its own. Since the npm way of "using" it doesn't talk about having .net installed, I assume the releases are compiled as "self-contained", that means that the runtime shouldn't be needed. In the other case we could always compile ourselves and cache it.

I think you're right that TSQLLint, while written in C#, does not depend on .NET.

> For me it's the one that is really tightly integrated with the dotnet dev sdk, I think it's dotnet format. Does it require that all projects that will be linted to be a .NET project too?

I have never experimented with this, but you might be able to abuse [`--include`](https://github.com/dotnet/format/blob/553764f5f88d2aef6942295200409624acf9d7ca/README.md#common-options-for-all-commands) to run `dotnet-format` on a non-.NET project. I'm skeptical that this is a significant use case we should account for though. I've never heard of anyone running `dotnet-format` on non-.NET projects.

> What other linters are written in a dotnet language?

I believe it's just CSharpier, PSScriptAnalyzer, `dotnet-format`, and TSQLLint that are written in C#, and the first two use .NET. `dotnet-format` is literally part of the .NET SDK.

**Comment by nvuillam** [comment]
Would this PR deserve to be revived ? :)

**Comment by echoix** [comment]
I think if it would be, it would be for .Net 8. And maybe want to only have the dotnet-format only to be run like a dotnet tool. Thus we could decouple the .net sdk version from the tools.

All of this assuming that a project must already be upgraded to .NET 8 to work with a new release. That's something that needs to be checked

**Comment by Kurt-von-Laven** [comment]
I know CSharpier can be run as a dotnet tool, but it does still require a compatible version of the .NET SDK to be installed.

**Comment by bdovaz** [comment]
I have created another PR that tries to solve what @jberkers42 mentioned about RIDs

https://github.com/tsqllint/tsqllint/pull/330

**Comment by Kurt-von-Laven** [comment]
Personally, I am all for trimming the least maintained/highest false positive linters from our dependencies. Anyone who wants to keep running them can do so with relatively little effort, and we can probably deliver the best experience to our ecosystem if we don't have to spend disproportionate effort patching up/working around/waiting on such linters.

> Maybe we should add some anonymous telemetry to know which linters are used and which ones are not, so we know the impact of removing one?

Sorry, I missed this question, @nvuillam. As the bulk of my career historically has been dedicated to the development of ethical anonymous telemetry, I would certainly never object to having more insight into patterns of use. I also don't feel telemetry is entirely necessary to answer this specific question of whether to keep TSQLLint. Regardless of their usage patterns, it's to be expected that any tool that attempts to aggregate many others may occasionally make strategic deprecations of some as their popularities' ebb and flow. [The average lifespan of an open-source project in days tends to be approximately the same as the number of files in its repository](https://arxiv.org/pdf/1710.11540.pdf). If we were to track something, the best metric I have thought of would be the counts of explicitly disabled linters. The number of unique users of each flavor might also be helpful if we don't already have access to that, but I don't have as concrete of a use case for that personally. As much as I love them, there are several major obstacles to making a data-driven decision here:

1. [TSQLLint](https://github.com/oxsecurity/megalinter/blob/f17e9932a9a378ad0c01e4ff4e0b4baacfd0982b/megalinter/descriptors/sql.megalinter-descriptor.yml#L52-L88) runs on [any `.sql` files](https://github.com/oxsecurity/megalinter/blob/f17e9932a9a378ad0c01e4ff4e0b4baacfd0982b/megalinter/descriptors/sql.megalinter-descriptor.yml#L6-L7) by default, and I suspect that very few users will disable it even if it adds no value to them or they don't even use TSQL.
2. The rate with which a linter is disabled may serve as a proxy for its troublesome-ness to the end user, but less so for its maintenance burden.
3. Even if we had perfect insight into the value users place on keeping TSQLLint in MegaLinter, that is only one side of the coin. Users have no non-painful option to upgrade MegaLinter to .NET 7 or 8 if they require this support. Some may have already abandoned us because of it without communicating with us, and I haven't thought of any clever ways to use telemetry to shed light on how many users care about this. The best I have come up with is [polling the community using GitHub Discussions](https://github.blog/changelog/2022-04-12-discussions-polls/). I imagine this draft would need to be revised, but for the sake of concreteness, I am imagining something like this:

    Dear MegaLinter + .NET Community,
    
    We are facing a crossroads in #2402 and request your guidance. As a linter aggregator, we endeavor to avoid removing linters when possible while keeping dependencies up-to-date, and occasionally these goals come in conflict with one another. For example, we have been attempting to upgrade from .NET 6 to .NET 7 or 8, but TSQLLint does not currently support .NET 7+. Which of the following options best reflects the views of you or your team?

    - [ ] "We'd rather keep TSQLlint in MegaLinter, and remain on .NET 6 for now."
    - [ ] "We'd rather keep TSQLLint in MegaLinter, and increase the uncompressed disk size of the dotnet flavor by 0.4 GB from 3.1 to 3.5 GB by installing .NET 7 alongside .NET 6."
    - [ ] "We'd rather run TSQLLint separately if desired, but have MegaLinter support .NET 7 within the next few months."
    - [ ] "We'd rather run TSQLLint separately if desired, but have MegaLinter support .NET 8 within the next few months."
    - [ ] "We either don't use TSQLLint or don't have an opinion on this matter."

    Please feel free to clarify, propose alternatives, etc. in the comments below. Thank you for using MegaLinter and for helping us make it better.

**Comment by jberkers42** [comment]
While I initially suggested the inclusion of tsqllint into MegaLinter, I cannot speak for anyone else regarding how it may be being used, however, our use-case for tsqllint was that the existing SQL linters did not cover the TSQL syntax variant used by Microsoft SQL Server. We found that it had enough variation that the existing ones did not suit our requirements entirely.

In the context of what we are doing with it, the *.sql files are not part of a .NET project, per se. We are using a collection of scripts (pwsh/PowerShell) to automate some ETL of data from a SQL Server instance into ElasticSearch for aggregation of statistical data generated by multiple instances of LogRhythm on separate servers. This allows us central visibility and reporting of key statistical data.

We have also expanded to use this for similar cases where we are doing an ETL, so our use-case is somewhat niche, I would guess. Rather than being part of a software development project that entails stored procedures, database triggers, schema files, etc. among frontend application components, we are using it for very select SQL scripts/statements.

If it were to be removed from MegaLinter it would not be a show stopper, but would be a loss to us nonetheless. We can appreciate that integrations that are themselves not maintained frequently can present their challenges.

**Comment by nvuillam** [comment]
Thanks to all of you for your valuable inputs !

@Kurt-von-Laven > About telemetry, I'm convinced that with anonymous stats it would help us improve MegaLinter for everyone, for example by diminishing image sizes by removing unused linters, but... would users be ok with that, even if we are very transparent about what info we collect ?
Or maybe we could disable it by default, and at installation ask users if they are ok to collect anonyous usage data, and collect it only if MEGALINTER_TELEMETRY == "true" for example ?

@jberkers42 @Kurt-von-Laven @bdovaz  About tsqllint (and dotnet tools in general), from the beginning we kind of wait for all of them to be compliant with the latest .NET version before upgrading it... 
I see the last commit is in june, is it really abandonware ? ( @bdovaz doesn't seem to have replies to his PR)
If it is really abandonware, at some point we'll have to choose between:
- removing it (because we can't force all our users to use  .NET 6 and old linter versions for one single linter)
- hard-fork tsqllint, to maintain it ourselves ? Or maybe find a benevolent maintainer, because we already have so much on our MegaLinter plate ? ^^

**Comment by Kurt-von-Laven** [comment]
> @Kurt-von-Laven > About telemetry, I'm convinced that with anonymous stats it would help us improve MegaLinter for everyone, for example by diminishing image sizes by removing unused linters, but... would users be ok with that, even if we are very transparent about what info we collect ?

It probably won't come as a surprise to anyone that I am a huge believer in the power of data, and I wholeheartedly agree that it could be leveraged to help us help our community, likely in many more ways than I have yet stopped to consider. The experience of the U.S.-based telemetry teams I have worked on has been that many users and open-source developers initially have a strong negative reaction to any form of telemetry because of the ubiquity with which it is deployed to suit the interests of the product owners at the expense of its users' privacy, informed consent, etc. Making the telemetry opt-in, fully anonymous, and clearly communicating these facts seems likely to address most concerns.

> I see the last commit is in june, is it really abandonware ? ( @bdovaz doesn't seem to have replies to his PR)

It's a little tough to know where to draw the line on the continuum, and maybe I am being overly harsh here, but I begin to have doubts about TSQLLint's future given that we are a week shy of .NET 7's first birthday and two weeks shy of .NET 8's launch. I don't have any deeper knowledge of the project though, so I'm all ears.

> hard-fork tsqllint, to maintain it ourselves ? Or maybe find a benevolent maintainer, because we already have so much on our MegaLinter plate ? ^^

I know nothing about the current maintainer or their perspective, but if anyone feels inspired to reach out to them to volunteer their time in whatever capacity, they certainly have my thanks. I am not thrilled about maintaining our own dependencies as a long-term strategy. I assume a few of them will inevitably die off every few years, so I expect that would limit what we can offer in the core and our ability to continue to offer the best linter aggregation features and performance. Personally, I prefer keeping appraised of new linters (a benefit we receive for free from our lovely community), and gradually replacing the dying ones with the highest quality upstarts over the years. I think this harmonizes the most efficiently with our expertise and brand and helps us focus. I assume there are already a number of fabulous, well-maintained linters out there that we don't currently distribute, and we would offer more user value per unit of maintenance cost by adding them than by taking ownership of a TSQLLint fork. I have been impressed by how many linters have been added on account of user demand.

**Comment by Kurt-von-Laven** [comment]
@nvuillam do you remember if TSQLLint tended to be faster to adopt new versions of .NET in the past?

**Comment by bdovaz** [comment]
Coincidence or not, but https://github.com/tsqllint/tsqllint/pull/324 and https://github.com/tsqllint/tsqllint/pull/330 have been merged between yesterday and today.

But I guess they are missing: https://github.com/tsqllint/tsqllint_common/pull/19

**Comment by nvuillam** [comment]
@Kurt-von-Laven it seems you have experience... would you like to lead a MegaLinter anonymous and opt-in telemetry project ? ^^

@bdovaz if they started to merge your PRs, maybe just mention the maintainers in the pending PR and they'll merge it too ^^

**Comment by bdovaz** [comment]
It looks like we may be able to unlock this PR:

https://github.com/Ellerbach/docfx-companion-tools/issues/45#issuecomment-1824496383

The `--roll-forward Major` parameter seems to be the key.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet#rollforward

Let's see if I get some time this weekend to test it and this PR is converted to .NET 8 (which has been released recently).

**Comment by bdovaz** [comment]
@nvuillam adding the `DOTNET_ROLL_FORWARD = LatestMajor` environment variable has solved the problem that even though tsqllint only targets .NET 6 it can run on .NET 7.

I have taken the opportunity to make some more changes in the linters that depend on .NET:

1. install the SDK with APK which greatly simplifies the command to run: https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#install-net-7
2. Add a `DotNetToolLinter` which is the class that is responsible for setting environment variables. All linters that are dotnet tools use it.
3. I have removed the `DotnetLinter` class that was only needed for `csharpier` and it is solvable with `cli_executable: dotnet-csharpier`.

cc @echoix @Kurt-von-Laven

**Comment by echoix** [comment]
> @nvuillam the only thing I see that fails is trivy, shall I exclude it?
> 
> 
> 
> image
> 
> 

It also blocks the auto updates PRs, even npm-groovy-lint is one of the linters causing it ;)

**Comment by echoix** [comment]
Installing from apk is such a great addition! It seems quite new and will probably mean smaller images and faster building, since it was quite long and sometimes buggy

**Comment by nvuillam** [comment]
> > @nvuillam the only thing I see that fails is trivy, shall I exclude it?
> > 
> > 
> > 
> > image
> > 
> > 
> 
> It also blocks the auto updates PRs, even npm-groovy-lint is one of the linters causing it ;)

Go :)

**Comment by bdovaz** [comment]
@nvuillam ready for review!

**Comment by bdovaz** [comment]
@nvuillam I don't know what is going on....

The 4 workflows that start with "MegaLinter" complain about "ModuleNotFoundError: No module named 'megalinter.linters.DotnetLinter'" but that class no longer exists, I have removed it in this PR.

And the remaining "Build & Deploy - DEV" the lychee one is:

image

**Comment by echoix** [comment]
The first of the two lychee errors, I started handling them, the guy's blog he changed something and all his pages have shifted by a number, there's already an issue. I also tried to check about the other certificate failures, it seems to be either inside the linter or lychee, since on another project this afternoon, building lychee from the crate and running it (in Gitpod) I got the same thing for some other links. Maybe something of ça-certificate. Or that we need to have a new beta image that uses the python 3.11.6 alpine 3.18.5 instead of the python 3.11.6 alpine 3.18.4 that is the latest working build we had. 
So, for now, we have to add ignores for them since we are stuck

**Review by echoix — APPROVED** [review]

**Comment by bdovaz** [comment]
@nvuillam How do I unblock the 2 problems? The one mentioned by @echoix and the one mentioned by me of "module not found"

**Pull request merged**
