### PR TITLE
Upgrade to python 3.12.0

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
Not all dependencies have 3.12 compatibilty.. let's wait :)

**Comment by echoix** [comment]
What a shame... On my list is to find what are the deps that don't work with 3.12

**Comment by nvuillam** [comment]
aiohttp for now :)

**Comment by Kurt-von-Laven** [comment]
Here is the relevant issue so we can follow along with their progress: aio-libs/aiohttp#7739. The good news is that they have a beta version with Python 3.12 support at this point.

**Comment by echoix** [comment]
Seems aiohttp released 3.9.0 and 3.9.1 since this PR.

**Pull request merged**
