### PR TITLE
Updated sources automatically committed

### PR DESCRIPTION
**Pull request by lukelloyd1985**
Addresses #4153 

## Proposed Changes

When `APPLY_FIXES` is set the fixed files get automatically committed & pushed to the PR source branch

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
Theres some Pylint to fix manually that makes two required jobs fail

**Comment by lukelloyd1985** [comment]
> Theres some Pylint to fix manually that makes two required jobs fail

Anything stopping this getting merge?

**Comment by echoix** [comment]
Only required jobs that I keep restarting

**Comment by lukelloyd1985** [comment]
> Only required jobs that I keep restarting

Stuff for me to sort or other things failing?

**Comment by nvuillam** [comment]
I think there is an issue with the latest markdown-links-check 😑

**Review by nvuillam — APPROVED** [review]
thanks for the PR :)

**Review by nvuillam — APPROVED** [review]
Let's go ! ;)

**Pull request merged**
