### PR TITLE
Remove openssl reinstall, as base image has updated version from alpine 3.18.5

### PR DESCRIPTION
**Pull request by echoix**
Removes a fix added in #3086, since the python base image is based off alpine 3.18.5, released recently, and it includes a fixed version of the package.

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
I want to keep only the first commit, remove the  build changes, and rebase from main

**Comment by nvuillam** [comment]
> I want to keep only the first commit, remove the build changes, and rebase from main

@echoix are you playing with AI ? 👼

**Comment by echoix** [comment]
No, I just don't know how, I tried the other day once the CI was unblocked, but there was so many conflicts and just gave up for the time that I had

**Comment by echoix** [comment]
Npm doesn't install. Stylelint released a v16 today, and the dev/linters job of stylelint doesn't work. PHP Codesniffer changed organization with the new maintainer that finally got commit access this summer, but the original maintainer isn't working at the company behind anymore, but that company doesn't want to allow the transfer to an organization or have her with more rights, and all being very slow to react. When they finally confirmed that the only way was to have a fork, and have all the users now refile their issues in the new repo (since it wasn't transferred). She released a version today with minimal changes, but with the new organization. The original maintainer responded a couple of times in that announcement thread. Some package managers allow to use the old name for the new fork. But it fails, something from GPG, either the usual downtime since we didn't add the new mirror yet, or since it was a new key/new maintainer. I saw a log with "Justine" (the new maintainer) in it, so might be the latter.

**Review by nvuillam — APPROVED** [review]
I merged by branch is yours, let's see if it solves the CI :)

**Comment by echoix** [comment]
Does it need to trigger a new build.sh?

**Comment by nvuillam** [comment]
> Does it need to trigger a new build.sh?

I did one locally in your branch, the result was the same :)

**Pull request merged**
