### PR TITLE
Disable SEMGREP by default if no rulesets are defined

### LINKED ISSUE #1635: semgrep vs gitleaks
**Describe the bug**
With a default config, semgrep detects the .gitleaks.toml file as a problem.

**To Reproduce**

1. Default install
2. Copy configs to root of project folder, which includes `.gitleaks.toml`
3. Run

**Expected behavior**
A default config shouldn't have one linter flagging the config of another linter.

**Screenshots**
```console
❌ Linted [REPOSITORY] files with [semgrep]: Found 2 error(s) - (44.07s)
- Using [semgrep v0.103.0] https://oxsecurity.github.io/megalinter/latest/v6/descriptors/repository_semgrep
- MegaLinter key: [REPOSITORY_SEMGREP]
- Rules config: identified by [semgrep]
--Error detail:
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Fetching rules from https://semgrep.dev/registry.

Scanning across multiple languages:
    <multilang> |  54 rules × 284 files
           json |   4 rules ×  10 files
         csharp |  40 rules ×   6 files
           yaml |  23 rules ×   5 files
         python | 282 rules ×   2 files


Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1 files larger than 1.0 MB
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1204 rules on 142 files: 2 findings.

Findings:

  /tmp/lint/.gitleaks.toml
     generic.secrets.security.detected-google-gcm-service-account.detected-google-gcm-service-account
        Google (GCM) Service account detected
        Details: https://sg.run/6nXj

         78┆ regex = '''"type": "service_account"'''
```

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/oxsecurity/megalinter/issues/1635

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/latest) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/2766797002)

|    Descriptor    |                                                         Linter                                                         |Files|Fixed|                                  Errors                                  |Elapsed time|
|------------------|------------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/latest/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.01s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/latest/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.25s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/latest/descriptors/bash_shfmt)                                          |    7|    0|                                                                         0|0.3s        |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/latest/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.72s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/latest/descriptors/dockerfile_hadolint)                              |  102|     |                                                                         0|17.77s      |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/latest/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|1.95s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/latest/descriptors/json_jsonlint)                                    |   18|     |                                                                         0|3.62s       |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/latest/descriptors/json_v8r)                                              |   20|     |                                                                         0|11.63s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdownlint)                        |  279|    0|[**4**](https://github.com/oxsecurity/megalinter/actions/runs/2766797002) |4.09s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdown_link_check)          |  279|     |                                                                         0|4.55s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdown_table_formatter)|  279|    0|                                                                         0|5.29s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/latest/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.73s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/latest/descriptors/python_bandit)                                      |  163|     |[**50**](https://github.com/oxsecurity/megalinter/actions/runs/2766797002)|1.98s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/latest/descriptors/python_black)                                        |  163|    0|                                                                         0|3.04s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/latest/descriptors/python_flake8)                                      |  163|     |                                                                         0|2.13s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/latest/descriptors/python_isort)                                        |  163|    0|                                                                         0|0.59s       |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/latest/descriptors/python_mypy)                                          |  163|     |                                                                         0|82.7s       |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/latest/descriptors/python_pylint)                                      |  163|     |                                                                         0|12.72s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.29s       |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |9.2s        |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |20.11s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/latest/descriptors/spell_cspell)                                       |  656|     |                                                                         0|17.03s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/latest/descriptors/spell_misspell)                                   |  488|    0|                                                                         0|0.62s       |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/latest/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.0s        |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/latest/descriptors/yaml_prettier)                                    |   79|    0|                                                                         0|1.95s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/latest/descriptors/yaml_v8r)                                              |   22|     |                                                                         0|25.03s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/latest/descriptors/yaml_yamllint)                                    |   80|     |                                                                         0|1.09s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/2766797002)

**Comment by ivanbaldo** [comment]
I was expecting that SemGrep would run by default and that we didn't need anything special to have at least some basic checks from it.
Why not just ignore some of the files that Megalinter generates and proposes to the repo instead, like the ones mentioned in the issue report?

**Comment by nvuillam** [comment]
@ivanbaldo there are thousands of semgrep rules, like there can be thousands of languages combination in a repo handlede by megalinter, so it's better to let the users decide of semgrep rules if they want to use them :)

**Comment by ivanbaldo** [comment]
So enabling all community rules isn't an option?
What was the prior behaviour before this patch then?

**Comment by ivanbaldo** [comment]
I see that enabling it is as simple as adding the following:
`REPOSITORY_SEMGREP_RULESETS: "auto"`

I didn't see any false positives with it yet (tested only on a small repo for now though).

Maybe the documentation could be made a bit clearer about the need to add that option in order to enable it?

As always: thanks a lot for all you do!

**Comment by nvuillam** [comment]
@ivanbaldo if you want to update the documention, your PR will be greatly appreciated :)

(linter_text in semgrep descriptor yml ^^ )

**Pull request merged**
