### PR TITLE
Fix `/build` slash command to checkout the correct PR branch

### PR DESCRIPTION
**Pull request by echoix**
The /build slash command was not checking out the correct branch when used. It was always using the base branch of the upstream repo. This was because it was called from a workflow_dispatch, so not tied to any event, nor pull request. The dispatcher (another workflow run), only had access to an issue event context, that doesn’t include information from the repo of the pull request. So, in order to hand the checkout action appropriate inputs, the build command is passed additional inputs, for the ref and repo name. These are obtained by using an api call from the pull request number in the repo (since it is available), and extracting the fields from the json. 

I tried using some pre-made actions, but didn’t get the repo name easily, and they weren’t mainstream. So, it is just using a custom script with actions/github-script to do the api call, and set outputs.

Documentation for the usage is the same, it should do exactly the same as expected. 

Fixes # … I’m not sure we reported it officially, but we (maintainers) are aware that it didn’t work directly as wanted.

## Proposed Changes

1. ...
2. ...
3. ...

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/echoix/megalinter/actions/runs/4646448719)

| Descriptor  |                                               Linter                                               |Files|Fixed|                              Errors                               |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    6|     |                                                                  0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    6|     |                                                                  0|0.14s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    6|    0|                                                                  0|0.42s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                 |2.83s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  116|     |                                                                  0|19.72s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                  0|2.44s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                  0|0.22s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                  0|14.69s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  312|    0|[230](https://github.com/echoix/megalinter/actions/runs/4646448719)|7.83s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  312|     |                                                                  0|6.22s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  312|    0|                                                                  0|24.1s       |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                  0|1.51s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  185|     |[54](https://github.com/echoix/megalinter/actions/runs/4646448719) |2.25s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  185|    0|                                                                  0|5.17s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  185|     |                                                                  0|1.88s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  185|    0|                                                                  0|0.88s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  185|     |                                                                  0|8.07s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  185|     |                                                                  0|12.66s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  185|     |[251](https://github.com/echoix/megalinter/actions/runs/4646448719)|17.96s      |
|✅ PYTHON    |[ruff](https://megalinter.io/beta/descriptors/python_ruff)                                          |  185|    0|                                                                  0|0.47s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                 |37.87s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                 |0.4s        |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                 |15.93s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                 |34.77s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  753|     |                                                                  0|23.19s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  572|    0|                                                                  0|1.07s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                  0|0.42s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                  0|3.21s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                  0|61.35s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                  0|1.3s        |

See detailed report in [MegaLinter reports](https://github.com/echoix/megalinter/actions/runs/4646448719)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
Please squash-merge rather than merge this PR. I had to make a lot of commits since it was Actions-related work

**Comment by Kurt-von-Laven** [comment]
I think as long as the proper `permissions` block is specified the first limitation will be/already is addressed. When someone forks a repo, those `permissions` being specified in the workflow keeps them the same between repositories even when some users have chosen to default them to `read-all` instead of `write-all`. I believe organization admins can limit those permissions, but there's nothing further we can do about that besides ask people to reopen the PR from a personal fork without such restrictions.

**Comment by echoix** [comment]
That's not really what I meant actually. It's that when testing, the final state that I'm adding is like my 4th or 5th approach, and one of the failed attempts that was working was using a ref of `refs/pull/${{ github.event.inputs.issue-number }}/head `, but finally it is read-only, it couldn't be pushed to. So I just couldn't test that there isn't a remaining permission that would block in a same manner, that I couldn't have encountered yet.

**Comment by Kurt-von-Laven** [comment]
Was `${{ github.event.inputs.issue-number }}` the PR number? Do I understand correctly that you are asking whether pushing to `<branch name>` rather than `refs/pull/<PR number>/head` will work when future PRs are opened by non-maintainers who have checked the box to allow edits by maintainers, and a maintainer comments `/build` on their PR while logged into GitHub?

**Comment by echoix** [comment]
Yes, that's what I'm not sure.  And yes, the issue-number is the PR number. There is no distinction on that matter api-wise

**Comment by Kurt-von-Laven** [comment]
I edited my reply to basically say, in that case it sounds like you did the right thing.

**Comment by echoix** [comment]
I think it is ready to merge, there's nothing left to do.

**Comment by nvuillam** [comment]
@echoix except conflict it's ok :)

**Pull request merged**
