### PR TITLE
feature: add 🐊Putout (#1127)

### LINKED ISSUE #1127: Add 🐊`Putout` integration for JavaScript
Hi, thank you for such a useful project!
**Is your feature request related to a problem? Please describe.**
Would be great to have 🐊[`Putout`](https://github.com/coderaiser/putout) linter integration with `megalinter` to lint (and maybe `fix`) `JavaScript`, `TypeScript`, `JSON`, `Markdown` and `Yaml` files. But first of all `JavaScript` :)! 
**Describe the solution you'd like**
What do you think about adding 🐊`Putout` to `megalinter`? What should be done from my side to get things working?

### PR DESCRIPTION
**Pull request by coderaiser**
Fixes #1127 

## Proposed Changes

Added 🐊[`Putout`](https://github.com/coderaiser/putout) linter.

1. ...
2. ...
3. ...

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
Unfortunately , MegaLinter is not able yet to share descriptors between languages, that's why for example eslint is described in  javascript, jsx, typescript , tsx and json descriptor files.
If you want putout to be present for all these file extensions, you'll have to:
- add it in all related descriptors
- add property `active_only_if_file_found: [".putout.json"]` ( for now I don't want putout to run by default on all repos, as it would scare users to see their code rewritten ^^ )
- maybe enhance a little linter_text content ? it is what will appear in MegaLinter online documentation
- run `bash build.sh` , as described in contribution guide, so Dockerfiles and python test classes will be automatically generated

**Comment by coderaiser** [comment]
Done, thank you :)!
- [x] fixed link to run `megalinter` locally
- [x] let's start from `JavaScript`
- [x] added property active_only_if_file_found: [".putout.json"]
- [x] enhanced a little bit linter_text content
- [x] run bash build.sh

Thanks for detailed explanation, I never contributed to python projects, but things was straight forward :)!

**Comment by nvuillam** [comment]
Thanks for your updates, now let's see what CI says :)

**Comment by coderaiser** [comment]
It says that it cannot find the image:

```
1) CLI
78
       (CLI) run on own code base:
79
     Error: Command failed: mega-linter-runner --path ./.. --release test-nvuillam-merge -e "ENABLE=YAML" --nodockerpull
80
Unable to find image 'megalinter/megalinter:test-nvuillam-merge' locally
81
docker: Error response from daemon: manifest for megalinter/megalinter:test-nvuillam-merge not found: manifest unknown: manifest unknown.
82
See 'docker run --help'.
83
```

And something with spell, maybe this is the link I fixed in documentation 🤔

**Comment by nvuillam** [comment]
part of CI is broken... not your fault , and not even mine ^^
It will finally work sometime ^^

**Comment by nvuillam** [comment]
@coderaiser not yet sorry (lack of free time/priorities) but I unstaled to not forget :)

**Comment by coderaiser** [comment]
Any progress on this?

**Comment by Kurt-von-Laven** [comment]
CI just passed for me, so I am curious to see what happens if we re-run it.

**Comment by Kurt-von-Laven** [comment]
Looks like it needs a rebase first though.

**Comment by coderaiser** [comment]
Done.

**Comment by Kurt-von-Laven** [comment]
Looks like CI found two test failures and one misspelling that are specific to this branch.

**Comment by coderaiser** [comment]
Just fixed spell, could you please help me with tests

**Comment by coderaiser** [comment]
ping @Kurt-von-Laven

**Review by Kurt-von-Laven — CHANGES_REQUESTED** [review]
Sorry for the slow reply. I think the issue is that no tests were added. See https://github.com/oxsecurity/megalinter/tree/main/.automation/test/javascript for examples of tests. Also, there should be a corresponding `TYPESCRIPT_PUTOUT` linter.

See ["Add a new linter"](https://oxsecurity.github.io/megalinter/latest/contributing/#add-a-new-linter):

> - Have two test files in `.automation/test`: one for success and one for failure

**Pull request closed without merging**
