### PR TITLE
Fix Value for container-name of type String required

### PR DESCRIPTION
**Pull request by AlbanAndrieu**
Fixes #

Fix Value for container-name of type String required when running `pre-commit run megalinter-incremental`

## Proposed Changes

1. ...
2. ...
3. ...

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
I'm a newbie with pre-commit... :D 
@Kurt-von-Laven  , your opinion ? :)

**Comment by AlbanAndrieu** [comment]
It seems working for me on Ubuntu LTS with node v18.12.1.
I tested it on node, PHP, java, python and devops project.

If some other want workaround : 

```  - repo: https://github.com/oxsecurity/megalinter
    rev: v6.15.0
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        args:
          - mega-linter-runner
          - --containername
          - "megalinter-incremental"
          - --remove-container
          - --fix
          - --env
          - "'APPLY_FIXES=all'"
          - --env
          - "'CLEAR_REPORT_FOLDER=true'"
          - --env
          - "'LOG_LEVEL=warning'"
          - --filesonly
        stages:
          - commit
```

**Review by nvuillam — APPROVED** [review]
Let's have a leap of faith, you seem to know what you are doing :)

**Comment by AlbanAndrieu** [comment]
@nvuillam Thanks budy

**Review by Kurt-von-Laven — COMMENTED** [review]
This looks fine, although I the quotes don't do anything. Did you encounter some issue using the original pre-commit hook? It's possible there are some differences in behavior between platforms.

**Pull request merged**
