### PR TITLE
Drone CI generator support + Drone CI docs improvement

### PR DESCRIPTION
**Pull request by NebulaOnion**
https://github.com/oxsecurity/megalinter/issues/2047

Fixes #

## Proposed Changes

1. ...
2. ...
3. ...

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
> @nvuillam How do I build and run the mega-linter-runner generator? To test the changes.

@NebulaOnion just call `npm link` at the root of mega-linter-runner folder

Then call `mega-linter-runner --install` :)

**Comment by nvuillam** [comment]
Not possible for now, let's hope you or someone find the syntax soon :)
But it won't prevent this PR to get merge, it's a start :)

**Comment by bdovaz** [comment]
@NebulaOnion apart from the CHANGELOG.md conflict you have to do a rebase with main to solve the trivy error.

**Review by nvuillam — APPROVED** [review]
Great, thanks a lot for your contribution :)

**Pull request merged**
