### PR TITLE
Use latest jscpd version

### PR DESCRIPTION
**Pull request by bdovaz**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4128650720)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.39s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.37s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.1s        |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|9.14s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.12s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.26s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.09s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    0|[229](https://github.com/oxsecurity/megalinter/actions/runs/4128650720)|6.0s        |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.33s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|18.79s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.98s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4128650720) |1.91s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|3.68s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.8s        |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.75s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.64s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.32s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4128650720)|17.16s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |27.05s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.34s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |12.92s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.65s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|17.94s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.93s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.36s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.91s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|58.04s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|0.99s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4128650720)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-bdoaz-unlock-jscpd) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4128650718)

| Descriptor  |                                                        Linter                                                         |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|-----------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.51s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.05s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.87s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|10.24s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.18s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.28s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.89s       |
|✅ JSON      |[v8r](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/json_v8r)                                              |   21|     |                                                                      0|13.92s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/markdown_markdownlint)                        |  309|    2|[229](https://github.com/oxsecurity/megalinter/actions/runs/4128650718)|7.4s        |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|6.38s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|20.47s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.07s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4128650718) |2.3s        |
|✅ PYTHON    |[black](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_black)                                        |  176|    0|                                                                      0|3.89s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_flake8)                                      |  176|     |                                                                      0|2.05s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.5s        |
|✅ PYTHON    |[mypy](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_mypy)                                          |  176|     |                                                                      0|8.51s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_pylint)                                      |  176|     |                                                                      0|13.56s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4128650718)|20.33s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_checkov)                                |yes  |     |no                                                                     |32.48s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4128650718) |1.58s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.2s        |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |10.02s      |
|✅ REPOSITORY|[syft](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_syft)                                      |yes  |     |no                                                                     |3.86s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.78s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/spell_cspell)                                       |  730|     |                                                                      0|20.98s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/spell_misspell)                                   |  551|    2|                                                                      0|0.67s       |
|✅ XML       |[xmllint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.04s       |
|✅ YAML      |[prettier](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.01s       |
|✅ YAML      |[v8r](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|65.94s      |
|✅ YAML      |[yamllint](https://megalinter.io/test-bdoaz-unlock-jscpd/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.34s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4128650718)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam can you approve? Thanks!

**Review by nvuillam — APPROVED** [review]
:)

**Pull request merged**
