### PR TITLE
feat: update standard to v17.0.0

### PR DESCRIPTION
**Pull request by ahmadnassri**
v17.0.0 brings a lot of major changes, most importantly: 

> Use of ESLint 8, which allows for support for all of the latest syntax that ESLint 8 includes, such as top level await

as top-level await has been made available in environments such as aws lambda and others, v15 would be erroring with any modern JS code, thus upgrading to 17 is essential

## Proposed Changes

1. update standard to v17

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
You need to 
- update https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/javascript.megalinter-descriptor.yml
- update https://github.com/oxsecurity/megalinter/blob/main/megalinter/descriptors/typescript.megalinter-descriptor.yml

Then run `bash build.sh` ,it will propagate to all the Dockerfiles :)

As far as I remember, I downgraded the version because there was a crash... maye you can run test cases locally

Please see [contributing guide](https://oxsecurity.github.io/megalinter/latest/contributing/) :)

**Comment by ahmadnassri** [comment]
admitittly I didn't read the guide and I shluld have.

will do those things now

**Comment by ahmadnassri** [comment]
being a py n00b, might need some help here, go to the point of attempting to run the build, but fails with this error:

```
Traceback (most recent call last):
  File "./.automation/build.py", line 20, in <module>
    import megalinter
  File "/tmp/megalinter/megalinter/__init__.py", line 4, in <module>
    from .MegaLinter import Megalinter
  File "/tmp/megalinter/megalinter/MegaLinter.py", line 16, in <module>
    from megalinter import (
  File "/tmp/megalinter/megalinter/flavor_factory.py", line 151, in <module>
    def are_all_repository_linters(linter_names: list[str]) -> bool:
TypeError: 'type' object is not subscriptable
```

running on Python v3.7.3

**Comment by nvuillam** [comment]
@ahmadnassri what is your installed python version ?
That's strange :/

**Comment by echoix** [comment]
Typings were improved in Python 3.9, so the version used is a good question.

In Python 3.9, type hinting for standard collections were added. When I used typings a couple years ago, I had to import a typing module and list was a capital L.

Here is some useful reading

https://stackoverflow.com/questions/63460126/typeerror-type-object-is-not-subscriptable-in-a-function-signature

https://stackoverflow.com/questions/39458193/using-list-tuple-etc-from-typing-vs-directly-referring-type-as-list-tuple-etc

https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

**Comment by ahmadnassri** [comment]
I'm on Python v3.7.3

trying to install 3.9 now

**Comment by nvuillam** [comment]
> @nvuillam is Python 3.7.3 a supported version of this project? If so, there's a way to use imports like `from __future__ import annotations` or something like this to make older/oldish versions of Python work with newer functionalities, which won't change (or minimally) the functionality of newer versions (remember the Python 2 to 3 migration?)

@echoix I think the best is to use the python version used by the docker image (3.10.4)  ^^
But i am with 3.10.3 and it works well ^^

**Comment by ahmadnassri** [comment]
well I learned a lot today about python, virtual env, and debian quirks ... works great on 3.9

currently building and will submit updated to this PR :)

**Comment by ahmadnassri** [comment]
running `./build.sh --doc` got stuck on this step:

```
2022-08-25 14:00:50,311 [INFO] Running command: ['bash', 'format-tables.sh'] in cwd /tmp/megalinter/.automation
```

just hangs there, 10 minutes and counting...

**Comment by ahmadnassri** [comment]
I ran again without `--doc`, but it still hangs at that same step ... I did find the `Dockerfile` changes, and committed those ...

in 403a0050c15bf7c6faa890ad9cd494f0516e8422 i found more files that didn't get automatically updated with the build script, so I manually did those.

**Comment by ahmadnassri** [comment]
hopefully my challenges with python 3.7 and build process would help future contributors!

**Comment by nvuillam** [comment]
You don't need the `--doc` , another automated process will do it after we merge your PR :)

format markdown tables uses npx, do you have node.js installed on your computer ?

**Comment by nvuillam** [comment]
image

It seems for some reason standard ignores the files we want to analyze >_<

**Comment by nvuillam** [comment]
@ahmadnassri I posted an issue.... let's see what they say ^^

https://github.com/standard/standard/issues/1841

**Comment by ahmadnassri** [comment]
> format markdown tables uses npx, do you have node.js installed on your computer ?

indeed I do

**Comment by ahmadnassri** [comment]
the `.automation` folder is being automatically ignored because it starts with a `.` 

this was a change in v16.

left a comment on your issues for anybody else to see...

when I'm back at my office I can see about adding the explicit override to allow tests to pass

**Comment by nvuillam** [comment]
> > format markdown tables uses npx, do you have node.js installed on your computer ?
> 
> indeed I do, running on nvm with node 18

You may try `npm i markdown-table-formatter -g` , but even with npx it should work because it is called with --`yes` so there shouldn't be a prompt

`npx --yes markdown-table-formatter@latest --verbose "./**/*.md"` ( code [here](https://github.com/oxsecurity/megalinter/blob/main/.automation/format-tables.sh))

As I see you're former npm CTO, you probably know better than me, any advice would be gladly appreciated ^^




> the `.automation` folder is being automatically ignored because it starts with a `.`
> 
> this was a change in v16.
> 
> left a comment on your issues for anybody else to see...
> 
> when I'm back at my office I can see about adding the explicit override to allow tests to pass

That won't probably be that simple... test methods are called with linters default arguments
But there is a way to force global variables in some test classes, like here -> https://github.com/oxsecurity/megalinter/blob/main/megalinter/tests/test_megalinter/linters/action_actionlint_test.py

you could send exclude arguments within `JAVASCRIPT_STANDARD_ARGUMENTS` and `JAVASCRIPT_STANDARD_ARGUMENTS`

**Comment by ahmadnassri** [comment]
now that I got py 3.9 working, I'll figure out why ./build is freezing for me ...

but I can also manually build and run the docker image to at least validate the standard ignore issue ... we may be able to use a dummy `package.json` to add additional configuration to standard without affecting the test scripts ...

at least that's my first idea, I'll tinker a bit and see what can be done when back at a keyboard ...

**Comment by nvuillam** [comment]
@ahmadnassri did you have any luck with the standard arguments allowing files in .automation not to be ignored ?
If it's not possible, I/we could implement some hack that could copy test files in a temp folder before calling standard

**Comment by ahmadnassri** [comment]
sorry weekend mode took over...

I tried the following:

1. build test image

```
docker build -f Dockerfile-quick -t megalinter .
```

2. run test image with `TEST_KEYWORDS="standard"`:

```
docker run -e TEST_CASE_RUN=true -e OUTPUT_FORMAT=text -e OUTPUT_FOLDER=test-results -e OUTPUT_DETAIL=detailed -e TEST_KEYWORDS="standard" -e MEGALINTER_VOLUME_ROOT="$(pwd)" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v $(pwd):/tmp/lint megalinter
```

success!

it's now running the full test slowly ... and I'm gonna take my dog for a walk.

my aim is to replicate the error we saw in GH Action, then attempt to add dummy `package.json` to the root/working directory with the appropriate overrides for `standard` to read from.

taking my dog for a walk while the test runs :)

**Comment by nvuillam** [comment]
No need to apologize haha, week-ends and dogs come first :D 

Have a good walk :)

**Comment by ahmadnassri** [comment]
I wasn't able to get the local build working, after a couple of attempts I realized `Dockerfile-quick`, I would ask if there is a detailed guide for running tests locally, as I'm just trying to replicate the steps in `deploy-DEV.yml` and might have missed some ...

I'm traveling this week, so I wont be able to continue testing till next Monday.

**Comment by nvuillam** [comment]
@ahmadnassri if it's ok for you, please can you push or paste here the arguments you send to standard , and I may complete the PR ?

Have a nice trip :)

**Comment by ahmadnassri** [comment]
my attempt was to add the following in a `package.json` at the root of the repo (or wherever the working director tests were executed from)

```
{
  "standard": {
    "ignore": ["!automation/**"]
  }
}
```

but since I didn't get to successfully run the docker image, I couldn't verify if this would even work

**Comment by ahmadnassri** [comment]
for context: standard's `ignore` property, is just [an extension](https://github.com/standard/standard-engine/blob/5f66f04535f4bb9de7bf2e51cce2285ab7b67e28/lib/resolve-eslint-config.js#L48-L51) of (ESLint's ignore)[https://eslint.org/docs/latest/user-guide/configuring/ignoring-code], which uses [`node-ignore`](https://github.com/kaelzhang/node-ignore) under the hood

**Comment by nvuillam** [comment]
Please can you push so the CI can test ? :)

**Comment by Kurt-von-Laven** [comment]
Looks like this needs a rebase in order for CI to run.

**Comment by ahmadnassri** [comment]
rebased

**Comment by ahmadnassri** [comment]
looks like it didn't pick up the package.json file 

```
/tmp/lint/.automation/test/sample_project_fixes/javascript_for_fixes_1.js:0:0: File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override. (undefined) (warning)
```

what is the working directory for the executed test? maybe it's not the repo root (where I placed the package.json file)?

**Comment by echoix** [comment]
> > @nvuillam is Python 3.7.3 a supported version of this project? If so, there's a way to use imports like `from __future__ import annotations` or something like this to make older/oldish versions of Python work with newer functionalities, which won't change (or minimally) the functionality of newer versions (remember the Python 2 to 3 migration?)
> 
> @echoix I think the best is to use the python version used by the docker image (3.10.4) ^^ But i am with 3.10.3 and it works well ^^

So then, it might be good to update the contributing guide, so we know what we need to install:
https://github.com/oxsecurity/megalinter/blob/75aa3c042abcfc615796cceba98f099c875d2a7d/.github/CONTRIBUTING.md?plain=1#L12

**Comment by nvuillam** [comment]
> > > @nvuillam is Python 3.7.3 a supported version of this project? If so, there's a way to use imports like `from __future__ import annotations` or something like this to make older/oldish versions of Python work with newer functionalities, which won't change (or minimally) the functionality of newer versions (remember the Python 2 to 3 migration?)
> > 
> > 
> > @echoix I think the best is to use the python version used by the docker image (3.10.4) ^^ But i am with 3.10.3 and it works well ^^
> 
> So then, it might be good to update the contributing guide, so we know what we need to install:
> 
> https://github.com/oxsecurity/megalinter/blob/75aa3c042abcfc615796cceba98f099c875d2a7d/.github/CONTRIBUTING.md?plain=1#L12

Nice idea, maybe u'd make a PR ? ^^

**Comment by nvuillam** [comment]
> looks like it didn't pick up the package.json file
> 
> ```
> /tmp/lint/.automation/test/sample_project_fixes/javascript_for_fixes_1.js:0:0: File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override. (undefined) (warning)
> ```
> 
> what is the working directory for the executed test? maybe it's not the repo root (where I placed the package.json file)?

CWD is docker image root when cli_lint_mode is `file` or `list_of_files` ... (inheritance from Super-Linter architecture) 
there is some time now I think it's not good but I've been afraid to break stuff if I change that... but there is probably something to be done

But I don't really like the idea to have a dummy package.json at the root of the repo just for a test class.... did you try by using standard arguments ? 

ex: `JAVASCRIPT_STANDARD_ARGUMENTS: ["--ignore-pattern","!xxxxx"]`

**Comment by nvuillam** [comment]
Example to add custom variables to linter test classes: https://github.com/oxsecurity/megalinter/blob/main/megalinter/tests/test_megalinter/linters/action_actionlint_test.py

**Comment by ahmadnassri** [comment]
I can give that a try, but since I don't have a functional local setup, I'll just commit it and let GH Actions do the testing for me (might wanna end up squashing the PR at the end)

**Comment by ahmadnassri** [comment]
actually, `standard` doesn't have a specific cli argument for that purpose, it just accepts a list of files, is there a way to modify the list of files passed to the cli? 

```
standard - Use JavaScript Standard Style (https://standardjs.com)

Usage:
    standard <flags> [FILES...]

    If FILES is omitted, all JavaScript source files (*.js, *.jsx, *.mjs, *.cjs)
    in the current working directory are checked, recursively.

    Certain paths (node_modules/, coverage/, vendor/, *.min.js, and
    files/folders that begin with '.' like .git/) are automatically ignored.

    Paths in a project's root .gitignore file are also automatically ignored.

Flags:
        --fix       Automatically fix problems
        --version   Show current version
    -h, --help      Show usage information

Flags (advanced):
        --stdin     Read file text from stdin
        --ext       Specify JavaScript file extensions
        --global    Declare global variable
        --plugin    Use custom eslint plugin
        --env       Use custom eslint environment
        --parser    Use custom js parser (e.g. babel-eslint)
```

**Comment by nvuillam** [comment]
I think we'll finally make some hack to copy test files in a /tmp folder to avoid paths starting with a dot, it will be quicker ^^

**Comment by ahmadnassri** [comment]
seems to still be ignoring the files...

```
/tmp/lint/.automation/test/sample_project_fixes/javascript_for_fixes_1.js:0:0: File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override. (undefined) (warning)
```

doesn't look there was any change to the paths though ... the `/tmp/lint`  is just the docker volume mount point

**Comment by nvuillam** [comment]
image

@ahmadnassri  Only test errors are not standard test methods, I think that with my last update it should be ok and I could release a new minor version of MegaLinter tomorrow with standard 17.0.0 :)

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
Only error was a python linting issue about an unused import, I solved it and forced the merge to not wait for 1h of CI again :)

**Comment by ahmadnassri** [comment]
excellent news! thank you for your patience and your help! 🎉

**Comment by nvuillam** [comment]
All that time spent because of a single dot haha 🎉

**Pull request merged**
