### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by echoix** [comment]
R lintr fails since it complains that the configuration file is malformed. Must end in newline? Lintr wasn't updated in this PR, so is there a breaking change somewhere?

**Comment by nvuillam** [comment]
Who knows... maybe they patched an existing version ?
Let's give him a newline at the end of the config ? ^^

**Comment by echoix** [comment]
Will retry

**Comment by echoix** [comment]
Docker registry seems down since 30 mins https://github.com/docker/setup-qemu-action/issues/110

**Review by echoix — APPROVED** [review]

**Comment by nvuillam** [comment]
amazing @echoix 🎉

**Comment by echoix** [comment]
;) Since we lost 4 or 5 days of flavor stats (that I rebuilt from individual force pushes), I'm testing out working from the same PR branch to not loose the changes. Or when I changed something manually, and it got lost since the scheduled run forced-pushed the branch.

I have 30 mins left of spare

**Comment by echoix** [comment]
Also, once our base python alpine images are updated with a new OpenSSL version, we good remove the line added in constants.py

**Pull request merged**
