### PR TITLE
Override npm-package-json-lint flavors

### PR DESCRIPTION
**Pull request by bdovaz**
https://github.com/oxsecurity/megalinter/pull/2150#issuecomment-1363392109

@nvuillam I have added dotnet to the suggested ones because in our case we develop with Unity (videogame engine in which we program in C#) and since a few years ago it has a package system based on npm.

Context:

https://docs.unity3d.com/Manual/CustomPackages.html

https://docs.unity3d.com/Manual/cus-layout.html

https://docs.unity3d.com/Manual/pack-safe.html

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
Great :)

**Comment by nvuillam** [comment]
@bdovaz MegaLinter is quite poor relating dotnet linting capacities ... if you want to make PRs to enhance that ( like @llaville did for PHP some time ago ^^ ), you are very welcome ;)

Note: there is currently a PR to upgrade to donetv6 / v7, so soon MegaLinter will be v6 and/or v7 -> https://github.com/oxsecurity/megalinter/pull/1680

**Comment by nvuillam** [comment]
I was thinking https://github.com/dotnet/roslyn-analyzers for example ^^

**Comment by bdovaz** [comment]
@nvuillam But as far as I know these analyzers (the most currently used is Microsoft.CodeAnalysis.NetAnalyzers) are not a cli tool (Installed with dotnet tool install) but are included with the SDK directly (.NET 5+) when compiling the project or you install it as a NuGet package in each project.

https://www.nuget.org/packages/dotnet-format

image

vs

https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers

image

**Comment by nvuillam** [comment]
they must have CLI version :) ( dotnet-format is already in MegaLinter ^^ )

**Comment by Kurt-von-Laven** [comment]
> @bdovaz MegaLinter is quite poor relating dotnet linting capacities ... if you want to make PRs to enhance that ( like @llaville brillantly did with PHP linters ^^ ), you are very welcome ;)

If you do decide to take this on, I recommend considering [CSharpier](https://csharpier.com/), which is far faster than dotnet-format and automates considerably more formatting. It is inspired by Prettier, and we have been happy with the output for quite a while. It's available as a NuGet package and dotnet tool.

**Pull request merged**
