### PR TITLE
Remove dotnet format install command

### PR DESCRIPTION
**Pull request by bdovaz**
In .NET 6 it is included in the SDK

https://github.com/oxsecurity/megalinter/issues/2310#issuecomment-1418189697

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4097884484)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.37s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.35s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.15s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.36s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.07s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.69s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    3|[229](https://github.com/oxsecurity/megalinter/actions/runs/4097884484)|6.46s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|4.82s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    3|                                                                      0|14.76s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.81s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4097884484) |2.26s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|   20|                                                                      0|6.16s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|2.07s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|   20|                                                                      0|0.74s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.53s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.45s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4097884484)|16.06s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |25.79s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.47s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |7.35s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.3s       |
|❌ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |[5](https://github.com/oxsecurity/megalinter/actions/runs/4097884484)  |18.79s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.77s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.36s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.29s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|56.12s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.5s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4097884484)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
The title may be misleading, we are removing dotnet-format (the tool), not the dotnet format. 

We might as well change the "linter name", to have the documentation page not having contradictions. => would there be any obvious side effects? (Like does it break too much links, does something else depend on the exact name?) 
At least the env variable name would be the same and correct, not like the poor choice of the first powershell linter that was called powershell instead of PSScriptAnalyzer.

**Comment by bdovaz** [comment]
@nvuillam about the `linter_name` property question do you know anything? In theory I understand that it would not generate any breaking change no? That only affects the documentation I imagine.

@echoix I guess you want to change it to `linter_name: dotnet format`? Or do you mean something else?

**Comment by nvuillam** [comment]
linter_name can probably be updated without major break, but I can't promise about documentation... so better not change it ^^

**Review by nvuillam — APPROVED** [review]
Good, it will decrease the size of some docker images ^^

**Comment by nvuillam** [comment]
tflint failing test case is because of github API limits , so I forced the merge ^^

**Pull request merged**
