### PR TITLE
Add GITHUB_AUTH_TOKEN as arg to Dockerfile to RUN commands using phive

### PR DESCRIPTION
**Pull request by bdovaz**
Context: https://github.com/oxsecurity/megalinter/pull/2312#issuecomment-1418263938

### CODE REVIEW

**Comment by nvuillam** [comment]
I think that we should stop maintaining the shell files calling docker and use docker-build github action, like discussed in this thread -> https://github.com/oxsecurity/megalinter/issues/2256

**Comment by bdovaz** [comment]
@nvuillam please read the following message carefully so that you understand how this PR makes sense regardless of whether we continue using `upload-docker.sh` or not please.... I have tried in several messages to make you understand but either I don't explain myself well or I don't know :(

https://github.com/oxsecurity/megalinter/pull/2312#issuecomment-1418273874

**Comment by nvuillam** [comment]
> That is, we have to modify the descriptor to pass that environment variable to each phive command. Example:
>
> Line 133 in [b0bb50f](https://github.com/oxsecurity/megalinter/commit/b0bb50f24c6be17112953780a2b921d740bd1d75)

>           RUN phive --no-progress install psalm -g --trust-gpg-keys 8A03EA3B385DBAA1,12CE0F1D262429A5

I think I understand that, and I agree, I just would prefer that GITHUB_TOKEN was sent through docker-build standard action, so we could do some same for all other linters also requiring it ^^

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4098620901)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.39s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.34s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.39s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.56s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.48s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.22s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.53s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    0|[229](https://github.com/oxsecurity/megalinter/actions/runs/4098620901)|5.99s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.13s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|17.85s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.77s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4098620901) |2.38s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|4.2s        |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.89s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.75s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.66s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|12.42s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4098620901)|17.5s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.32s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.42s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |7.83s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.05s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|19.1s       |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.87s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.85s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.92s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|58.33s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.3s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4098620901)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam as I say, to solve the problem that this PR pretends to solve it is not relevant if it is done with the bash script or with the action that you mention...

To get to the point that you comment it is necessary to rewrite all the logic of `upload-docker.sh` to use that action instead of the bash script and that is a titanic task and that requires a lot of precision because that script is very big and has many conditions, etc...

That must be done with time.... Besides that it is going to require that at least 2 people review it because of the regressions that it can have.

I don't know if @echoix feels up to the task that would benefit us in #2273.

**Comment by echoix** [comment]
_(Read the following as a code review, not bashing 😜)_
I think that there's a little better way to implement what you have just added, as what I understand, it might appear in the image's history.

First of all, I think that the variable should be "GITHUB_TOKEN", as that's what I think you're using to authenticate. It'll be easier to follow along knowing that GITHUB_AUTH_TOKEN is in reality GITHUB_TOKEN, where there is more help on the web.

Then, here is some docs https://docs.docker.com/build/ci/github-actions/examples/#secrets and https://docs.docker.com/engine/reference/commandline/buildx_build/#secret
We can use the secrets feature of docker building. Look also at https://stackoverflow.com/questions/68275321/how-to-use-github-token-in-dockerfile-that-is-built-in-github-actions-and-trying, where in the question his usage is right.
I'm not sure, but maybe the syntax dockerfile won't be needed (see the second link, in the env section).

I need to go, without finishing my message, but it's a good start

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-bdoaz-set-github-token-in-phie) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4098620904)

| Descriptor  |                                                              Linter                                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|-----------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.39s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.41s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|7.53s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.75s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.23s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.52s       |
|✅ JSON      |[v8r](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/json_v8r)                                              |   21|     |                                                                      0|13.57s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/markdown_markdownlint)                        |  309|    2|[229](https://github.com/oxsecurity/megalinter/actions/runs/4098620904)|5.88s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.14s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|14.1s       |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.79s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4098620904) |2.46s       |
|✅ PYTHON    |[black](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_black)                                        |  176|    0|                                                                      0|3.75s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.9s        |
|✅ PYTHON    |[isort](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.42s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.92s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.52s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4098620904)|17.11s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.2s       |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4098620904) |1.25s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.36s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |3.86s       |
|✅ REPOSITORY|[syft](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_syft)                                      |yes  |     |no                                                                     |3.29s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |17.38s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/spell_cspell)                                       |  730|     |                                                                      0|17.73s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/spell_misspell)                                   |  551|    2|                                                                      0|0.48s       |
|✅ XML       |[xmllint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.48s       |
|✅ YAML      |[v8r](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|56.1s       |
|✅ YAML      |[yamllint](https://megalinter.io/test-bdoaz-set-github-token-in-phie/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.47s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4098620904)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
@bdovaz https://github.com/github/super-linter/blob/13e5f8b29a34bbf7ce2476292477fa385bec2578/scripts/install-phive.sh#L6-L15

**Comment by bdovaz** [comment]
@echoix about the variable name, it is not a mistake, it is called that way in PHIVE:

https://github.com/phar-io/phive/blob/c5985a10f95be9a21b79e7ee19bef39dc85e9f95/src/shared/config/EnvironmentAuthConfig.php#L18

And about the rest, you are right I understand that it would serve with a:

`RUN export GITHUB_AUTH_TOKEN="$(cat /run/secrets/GITHUB_TOKEN)" && phive`

That's what you mean, isn't it?

But it is true that for that both this PR and #2299 depend on rewriting all workflows to remove the bash script from `upload-docker.sh` and use the native actions for Docker.

**Comment by nvuillam** [comment]
I don't think that using docker action is so complicated to migrate (because it basically does the same than what we do, and our bash scripts are SuperLinter ones, and they migrated ), 

So I can probably try to do that next week ^^

**Comment by echoix** [comment]
I don't think that only by using docker build action the GITHUB_TOKEN would be used everywhere for every call inside the build environnement (building the containers), we will still need to add them in the generated Dockerfiles

**Comment by echoix** [comment]
@bdovaz ok, if PHIVE needs it called that way, fine, but everywhere else that value is called GITHUB_TOKEN, and the value that we will pass it will be called GITHUB_TOKEN, including what GitHub will give us.

**Pull request merged**
