### PR TITLE
Update and improve GitHub action template and clean up documentation

### PR DESCRIPTION
**Pull request by vkucera**
Fixes #

## Proposed Changes

1. Update the GitHub action template file `TEMPLATES/mega-linter.yml` from the code in `README.md`.
2. Remove the code from `README.md` and `docs/install-github.md` since the template is already linked in both documents just above.
3. Improve the pull request step for applying fixes.
    1. Add `body`, `branch` (otherwise not unique if default), `delete-branch`.
    2. Add error message with the PR link, printed at the end of the step run.
    3. Exit the action run with error (to make it obvious that fixes are required).

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by vkucera** [comment]
The `contains(fromJSON` pieces were present in the template but not in the docs. Not sure whether they should stay or not.

**Comment by nvuillam** [comment]
Thanks for the PR :)

I'd like the workflows to remain in the documentation (they are in collapsable sections), because for some reasons someone could want to define manually the workflows, and it can also have impact on SEO

About reformatting, there has been another PR ,and the jsonContains should be everywhere , and I think you invest some of its updates -> https://github.com/oxsecurity/megalinter/pull/2891 , by @andrewvaughan 

Many thanks !

**Review by nvuillam — CHANGES_REQUESTED** [review]
Plz check comments :)

**Comment by vkucera** [comment]
Hi @nvuillam , thanks for the comments. Indeed, I see now that the template is the actual up-to-date reference and this PR would revert the changes in the PR you refer which is not what I intended.
It is not clear to me how removing the code from the docs prevents anyone from grabbing the template and rewriting it to their liking but fine with me if you prefer to keep it. In that case, would it be possible to generate the docs and paste the template there automatically to keep them synced?

**Comment by nvuillam** [comment]
> Hi @nvuillam , thanks for the comments. Indeed, I see now that the template is the actual up-to-date reference and this PR would revert the changes in the PR you refer which is not what I intended. It is not clear to me how removing the code from the docs prevents anyone from grabbing the template and rewriting it to their liking but fine with me if you prefer to keep it. In that case, would it be possible to generate the docs and paste the template there automatically to keep them synced?

`.automation.build.py` already does many things in that style :)
You should succeed to perform such operation by reading the content of the github workflow and using method replace_in_file and HTML tags :)

image

**Comment by vkucera** [comment]
Thanks, I will have a look into it.
Otherwise, are you fine with the suggested changes in the pull request step (see https://github.com/oxsecurity/megalinter/pull/2940/commits/320dbe067d3b09e5a5faad03b9485cc67e13bb5f)?
If yes, I can move it to a separate PR and keep this one as a draft until I come back to the automatic template sync.

**Pull request closed without merging**
