### PR TITLE
Fix `.pre-commit-hooks.yaml` link in docs

### PR DESCRIPTION
**Pull request by mondeja**
The link is currently raising a 404 error.

### CODE REVIEW

**Comment by nvuillam** [comment]
@Kurt-von-Laven you can merge if you like, it will be in tomorrow 's patch :)

**Comment by Kurt-von-Laven** [comment]
I think GitHub stripped all of my privileges as a security precaution when we moved orgs.

**Comment by nvuillam** [comment]
@Kurt-von-Laven check your mails, you have a pending invite since sunday :)

image

**Comment by Kurt-von-Laven** [comment]
Whoops, thank you for straightening me out. The invite got caught by my over-aggressive filters, but I accepted it now!

**Pull request merged**
