### PR TITLE
Remove checkov rust compiler dependency

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by echoix** [comment]
The merged PR failed building a docker image with no space left ... :(

**Comment by nvuillam** [comment]
@echoix ooooops, I check

**Comment by echoix** [comment]
But the Auto-update step in the following PR #3008, which also builds the image, finished building the docker image now, without problem

**Comment by nvuillam** [comment]
@echoix I suspect either GitHub to have reduced free space on runners, either one of our linter or dependency to take much more space that it should ^^

Anyway, should be solved by https://github.com/oxsecurity/megalinter/pull/3009 as it provides 30GB additional space earlier in the process :)

**Comment by echoix** [comment]
Looking at https://github.com/actions/runner-images/blob/ubuntu22/20231001.1/images/linux/Ubuntu2204-Readme.md, there is an announcement for 

https://github.com/actions/runner-images/issues/8383

Starting October 9, taking 3-4 days. 

We failed with image 20231001.1.0, that was two weeks ago. I don't understand how an existing image version can change later on without a new number/date. 

We had some runs with that version of the image work less than 7 hours ago, and some others that failed. 

Also look at https://github.com/super-linter/super-linter/issues/4735, and I suspect they use less space than us.

**Pull request merged**
