### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by echoix** [comment]
Somethings weird with revive @nvuillam

**Comment by nvuillam** [comment]
Very strange indeed...

@mgechev do you know what recent change in revive could have caused the following error ?

`linting - retrieving failures channel: command go list: exec: "go": executable file not found in $PATH`

-> https://github.com/oxsecurity/megalinter/actions/runs/10118420125/job/27987015465?pr=3802

**Comment by echoix** [comment]
I'm downgrading revive and setting renovate for the GitHub tag.

**Review by echoix — APPROVED** [review]

**Pull request merged**
