### PR TITLE
feat: add ts-standard linter for ts standard

### PR DESCRIPTION
**Pull request by janderssonse**
This replaces the usage of javascript standard for typescript with the nowadays recommended standard variant ts-standard. It can be seen as a new linter in essence.

Fixes #https://github.com/oxsecurity/megalinter/issues/2736

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by janderssonse** [comment]
I don't expect this to be 100% correct, but maybe it is a start, as it is my first linter try. :) 

Some questions: When I created tests for typescript_ts_standard folder, I still had to duplicate from the test typescript folder. Other tests also seems to do this. Why is that take? How should I do?
Also, why does a lot of tests have same tests duplicated like good_1., good_2, but there is no difference in them.

I also removed references to the Atom editor in the docs for this linter, as that editor is dead.

**Comment by nvuillam** [comment]
@janderssonse great initiative, thanks :)

Duplicating the test folders is when the initial one (with just the descriptor name) that works for most linters do not work with a specific one: in that create we create a test folder just for the linter

About multiple good or bad tests, it's to test the capability of the linters to accept a list of files and not a single file :)

**Comment by janderssonse** [comment]
@nvuillam I didn't see the use case for a specific typescript_ts_standard test folder after the test explanation, so that is gone now. PR updated. No hurries, when you get the time to look at it, please also tell me what I did wrong with this one so next linter adventure can improve. I might have some further PR's for the project in mind, but let's get this one right first:)

**Comment by nvuillam** [comment]
@janderssonse looks good, but please can you merge main in your branch &  solve conflicts ? :)

**Comment by nvuillam** [comment]
(you can ignore the issue about the new doc page not found)

**Review by nvuillam — CHANGES_REQUESTED** [review]
The content seems very good, except one think: you can not change the key of the linter (you can force it with `name` property in the descriptor if necessary), else it would require a deprecation then a major release.

If ts-standard is done by the same team than standard, and works the same, the linked key can remain unchanged :)

**Comment by janderssonse** [comment]
> The content seems very good, except one think: you can not change the key of the linter (you can force it with `name` property in the descriptor if necessary), else it would require a deprecation then a major release.
> 
> If ts-standard is done by the same team than standard, and works the same, the linked key can remain unchanged :)

Another go, now it is called TYPESCRIPT_STANDARD (not ...TYPESCRIPT_TS_STANDARD after some quick replaces, as it was originally called

**Comment by nvuillam** [comment]
Thanks for the update, and for the whole PR :)

**Pull request merged**
