### PR TITLE
Update terrascan

### PR DESCRIPTION
**Pull request by bdovaz**

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4151106473)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.4s        |
|✅ COPYPASTE |[jscpd](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.49s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.55s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.68s       |
|✅ JSON      |[jsonlint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[v8r](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.82s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/markdown_markdownlint)                        |  309|    0|[231](https://github.com/oxsecurity/megalinter/actions/runs/4151106473)|5.7s        |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.17s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|14.43s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.51s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4151106473) |1.86s       |
|✅ PYTHON    |[black](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_black)                                        |  176|    0|                                                                      0|3.83s       |
|✅ PYTHON    |[flake8](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.7s        |
|✅ PYTHON    |[isort](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.78s       |
|✅ PYTHON    |[mypy](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.46s       |
|✅ PYTHON    |[pylint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_pylint)                                      |  176|     |                                                                      0|10.33s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4151106473)|15.86s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.18s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.4s        |
|✅ REPOSITORY|[secretlint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |11.26s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.46s      |
|✅ SPELL     |[cspell](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/spell_cspell)                                       |  729|     |                                                                      0|17.44s      |
|✅ SPELL     |[misspell](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/spell_misspell)                                   |  550|    0|                                                                      0|0.9s        |
|✅ XML       |[xmllint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.93s       |
|✅ YAML      |[prettier](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.91s       |
|✅ YAML      |[v8r](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|55.46s      |
|✅ YAML      |[yamllint](https://megalinter.io/c2150036484341ffe1653735a7328e91f5640bbe/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.12s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4151106473)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4151106480)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.19s       |
|✅ BASH      |[shfmt](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.02s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.06s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.82s       |
|✅ JSON      |[jsonlint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.31s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.63s       |
|✅ JSON      |[v8r](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.38s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/markdown_markdownlint)                        |  309|    2|[231](https://github.com/oxsecurity/megalinter/actions/runs/4151106480)|6.18s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.45s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|17.18s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.72s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4151106480) |2.05s       |
|✅ PYTHON    |[black](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_black)                                        |  176|    0|                                                                      0|3.2s        |
|✅ PYTHON    |[flake8](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.73s       |
|✅ PYTHON    |[isort](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.46s       |
|✅ PYTHON    |[mypy](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.14s       |
|✅ PYTHON    |[pylint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.49s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4151106480)|17.51s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.8s       |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4151106480) |1.29s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |3.18s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.01s       |
|✅ REPOSITORY|[syft](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.02s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |19.81s      |
|✅ SPELL     |[cspell](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/spell_cspell)                                       |  729|     |                                                                      0|18.83s      |
|✅ SPELL     |[misspell](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/spell_misspell)                                   |  550|    2|                                                                      0|0.56s       |
|✅ XML       |[xmllint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.53s       |
|✅ YAML      |[v8r](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|57.78s      |
|✅ YAML      |[yamllint](https://megalinter.io/42f7cd4bc1e2c3a4c9c209f9bdc1359b6282b28c/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.11s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4151106480)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam can you check the trivy vulnerability? Thanks!

**Comment by nvuillam** [comment]
@bdovaz  Solved in https://github.com/oxsecurity/megalinter/pull/2299 :)

**Pull request merged**
