### PR TITLE
feat: add option to skip def_ws prefix in sarif reports

### LINKED ISSUE #2006: DEFAULT_WORKSPACE is prefixed to SARIF-output field uri but should not be.
**Describe the bug**
DEFAULT_WORKSPACE is prefixed to uri in the SARIF-output, in my case, breaks SARIF-Viewer/VSCode, but would be the same for any alike setup.

**To Reproduce**
Example: 

Run the megalinter container, here standing in the root of the repo you want to check: 

1. podman run --volume $(pwd):/repo DEFAULT_WORKSPACE=/repo -e LOG_LEVEL=INFO oxsecurity/megalinter:v6.13.0
2. Open up your fav editor, for example VSCode, (with SARIF-Vieever extension installed)
3. Open a sarif file from VSCode.(from megalinter-reports/sarif
4. While rules are shown, notice VSCode cant find the path to the error. Look in the SARIF-FILE, see that all "uri"s have the DEFAULT_WORKSPACE prefixed to them., EG /repo/src/main etc. 
5. Removing the prefixed DEFAULT_WORKSPACE so we have expected src/main. Now it works!

**Expected behavior**
DEFAULT_WORKSPACE should not be prefixed to SARIF-output. This variable is something that most likely only exists during runtime generation, and makes the SARIF-output closely tied to that run.

### PR DESCRIPTION
**Pull request by janderssonse**
Fixes #2006 
 
This PR is a suggestion for solving the use case
of needing to remove the DEFAULT_WORKSPACE from
the out put in the generated SARIF output.
(https://github.com/oxsecurity/megalinter/issues/2006).

It moves the SARIF logic to an earlier phase, to be handled before the aggregate SARIF generation.
It replaces the prefix if the flag
SARIF_REPORTER_NORMALIZE_LINTERS_OUTPUT: true is set (default: true)
(see clear_default_workspace_prefix(...

Implementation is done by line parsing and replacing, as a node traversal solution quickly would grew due to
the many places in the sarif out put the uri can be found (metris, relatedLocations, and so on), and the code is much simpler this way to maintain.

Improvements and suggestions:
- Could json dumps() and resulting json string be used in
a reliable way to stream line parse an json file? I didn't find a good way.
- Should the option be renamed to
SARIF_REPORTER_DISABLE_DEFAULT_WORKSPACE_IN_OUTPUT or alike. As the pre existing normalization still happens? (We don't change that pre existing behaviour in this PR, only the DEFAULT_WORKSPACE prefix part).

## Proposed Changes

1. Move the SARIF Logic to an earlier phase 
2. Add optional removal of DEFAULT_WORKSPACE prefix
3. Activated by SARIF_REPORTER_NORMALIZE_LINTERS_OUTPUT

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
That seems great :)

I think SARIF_REPORTER_NORMALIZE_LINTERS_OUTPUT  should be true by default :)

**Comment by janderssonse** [comment]
Thanks, fixed so it is default true now. Btw,How can I make the checks failing tests succed, if i interprets the checks logs correct they would need permission conf (PAT)? Learning for this and future fixes.:)

**Comment by Kurt-von-Laven** [comment]
I believe the errors are the linter violations, not the bit about the PAT, which you can ignore.

**Comment by janderssonse** [comment]
> I believe the errors are the linter violations, not the bit about the PAT, which you can ignore.
Uh, oh, I see now, preparing a fix for these.

**Review by nvuillam — APPROVED** [review]
Indeed green, well done , thanks :):

**Pull request merged**
