### PR TITLE
Fixup changes/no changes exit codes for build-command

### PR DESCRIPTION
**Pull request by echoix**
Seems like the handling of the exit codes to determine if changes are to be committed didn't work well once used in an action. ~~Going simpler in bash, using only `git diff` with `--exit-code` in order to show the diff, but have the exit code. Then the exit code is handled by the outcome (using continue-on-error) to use the `success` or `failure` outcome of a step.~~

~~https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context ~~
~~https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#about-exit-codes~~
~~https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---exit-code~~
~~vs https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---quiet~~

**_Edit_**:
 Since this approach didn't end up going smoothly, I changed the approach and used the https://github.com/stefanzweifel/git-auto-commit-action to commit and set an output if there were changes. With this, it works as expected.

## Proposed Changes

1. Be able to commit changes with the build command (without the step being always skipped) -> using https://github.com/stefanzweifel/git-auto-commit-action
2. Disable workflow runs for slash command dispatcher and its commands on PR/pushes where possible: these files can't change the flavors by themselves
3. ...

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
## [🦙 MegaLinter](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b) status: ⚠️ [WARNING](https://github.com/echoix/megalinter/actions/runs/4228611424)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                              Errors                               |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/bash_bash_exec)                                  |    6|     |                                                                  0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/bash_shellcheck)                                |    6|     |                                                                  0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/bash_shfmt)                                          |    6|    0|                                                                  0|0.4s        |
|✅ COPYPASTE |[jscpd](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                 |2.52s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/dockerfile_hadolint)                              |  114|     |                                                                  0|15.49s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                  0|1.99s       |
|✅ JSON      |[jsonlint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/json_jsonlint)                                    |   19|     |                                                                  0|0.24s       |
|✅ JSON      |[v8r](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/json_v8r)                                              |   21|     |                                                                  0|12.19s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/markdown_markdownlint)                        |  309|    0|[230](https://github.com/echoix/megalinter/actions/runs/4228611424)|5.9s        |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/markdown_markdown_link_check)          |  309|     |                                                                  0|5.21s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                  0|15.04s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/openapi_spectral)                                 |    1|     |                                                                  0|1.64s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/echoix/megalinter/actions/runs/4228611424) |1.98s       |
|✅ PYTHON    |[black](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_black)                                        |  183|    1|                                                                  0|3.97s       |
|✅ PYTHON    |[flake8](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_flake8)                                      |  183|     |                                                                  0|1.68s       |
|✅ PYTHON    |[isort](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_isort)                                        |  183|    1|                                                                  0|0.76s       |
|✅ PYTHON    |[mypy](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_mypy)                                          |  183|     |                                                                  0|6.26s       |
|✅ PYTHON    |[pylint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_pylint)                                      |  183|     |                                                                  0|11.02s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/python_pyright)                                    |  183|     |[249](https://github.com/echoix/megalinter/actions/runs/4228611424)|16.38s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/repository_checkov)                                |yes  |     |no                                                                 |27.2s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/repository_git_diff)                              |yes  |     |no                                                                 |0.41s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/repository_secretlint)                          |yes  |     |no                                                                 |12.06s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/repository_trivy)                                    |yes  |     |no                                                                 |25.43s      |
|✅ SPELL     |[cspell](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/spell_cspell)                                       |  745|     |                                                                  0|17.79s      |
|✅ SPELL     |[misspell](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/spell_misspell)                                   |  566|    0|                                                                  0|0.97s       |
|✅ XML       |[xmllint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/xml_xmllint)                                       |    3|    0|                                                                  0|0.42s       |
|✅ YAML      |[prettier](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/yaml_prettier)                                    |   81|    2|                                                                  0|2.9s        |
|✅ YAML      |[v8r](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/yaml_v8r)                                              |   23|     |                                                                  0|58.16s      |
|✅ YAML      |[yamllint](https://megalinter.io/e90b3452049a19fa23a8a75d68c8089402cfcd9b/descriptors/yaml_yamllint)                                    |   82|     |                                                                  0|1.27s       |

See detailed report in [MegaLinter reports](https://github.com/echoix/megalinter/actions/runs/4228611424)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
Giving up. The theory worked, the shell commands worked, but I wasn't able to get it working as expected on GH actions on my fork's branch (the status handling, it was even worse). So I just went and looked for an action that does what I wanted.
https://github.com/echoix/megalinter/pull/2
It works there now. So I'll port the changes here and retry.

**Comment by echoix** [comment]
@nvuillam could you take a look at this?

**Comment by echoix** [comment]
The failure is about the extends test, unrelated and won't help nor worsen that test

image

**Comment by bdovaz** [comment]
@echoix the culprit seems to be me.

In workflows I started to pass the branch to the container (GITHUB_REF_NAME):

https://github.com/oxsecurity/megalinter/blob/e90b3452049a19fa23a8a75d68c8089402cfcd9b/.github/workflows/deploy-DEV.yml#L210

I do this because the remote tests use a url that was previously fixed to the `main` branch but now I make it vary based on that environment variable:

https://github.com/oxsecurity/megalinter/blob/e90b3452049a19fa23a8a75d68c8089402cfcd9b/megalinter/tests/test_megalinter/config_test.py#L22

I don't know if it is because it is a fork the source of the PR but the url is weird, it equals to PR ID (2381):

image

And it returns a 404: https://raw.githubusercontent.com/oxsecurity/megalinter/2381/merge/.automation/test/mega-linter-config-test/remote/custom.mega-linter.yml

**Comment by echoix** [comment]
I see how it fails, and it seems we just need to find the correct variable/url to send.
Either way, I'm only waiting for a review to approve that PR to continue the Golang dependabot PR.

**Comment by Kurt-von-Laven** [comment]
@bdovaz, we encountered this issue as well. [Here](https://github.com/ScribeMD/slack-templates/blob/13bac2001073b594b879bab8fc6f6881e125d8f5/src/slack_notification.py#L106-L116) is how we solved it. Basically, the branch names is usually `GITHUB_REF_NAME`, but you want `GITHUB_HEAD_REF` instead when `GITHUB_EVENT_NAME` is `"pull_request"`, `"pull_request_target"`, or I think anything else that starts with `"pull_request"`.

**Comment by nvuillam** [comment]
@echoix  I fixed a CI issue in main branch, please can u merge it in your branch so it passes more easily ?

**Comment by echoix** [comment]
@nvuillam Done :)

**Comment by nvuillam** [comment]
@echoix these test cases do not fail in other branches... ^^

**Comment by echoix** [comment]
Because they come from a branch of the repo. This comes from a fork.

**Comment by nvuillam** [comment]
Does it means that https://github.com/oxsecurity/megalinter/pull/2375 broke CI jobs from forks ? ^^ cc @bdovaz

**Comment by echoix** [comment]
See https://github.com/oxsecurity/megalinter/pull/2381#issuecomment-1439168963

**Comment by bdovaz** [comment]
> Does it means that #2375 broke CI jobs from forks ? ^^ cc @bdovaz

Indeed, either someone will find the time to fix it or you will have to wait for me to be able to do so before the end of this week.

**Comment by echoix** [comment]
In the meantime could you merge to continue?

**Comment by echoix** [comment]
Thanks!

**Comment by echoix** [comment]
@nvuillam I don't understand now. What was working for even a PR in my branch, and that time I was sure (it's the third iteration of all what was supposed to work), still doesn't work on the PR https://github.com/oxsecurity/megalinter/pull/2380. My other option is to use the fetch depth of at least 2 instead of the default that is 1, since I read that detecting if changes were made may not always work if the fetch depth is 1.

**Comment by echoix** [comment]
Or maybe there is something special with the dependabot PRs?

**Comment by Kurt-von-Laven** [comment]
There is, yes. [They are essentially treated like PRs opened from a fork.](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)

**Pull request merged**
