### PR TITLE
MegaLinter v6

### PR DESCRIPTION
**Pull request by nvuillam**
- New reporter **SARIF_REPORTER** that aggregates all SARIF output files into a single one
    - Correct SARIF files for known format errors
  - Manage offline run of `bash build.sh` for those who want to code in planes :)
  - Automate update of CHANGELOG.md after release (pilot)
  - Rename default report folder from `report` to `megalinter-reports`
  - Accelerate internal CI testing performances
  - Display GitHub stars in linters summary table in documentation 

- Linters:
  - Add [DevSkim](https://github.com/microsoft/DevSkim) security linter by Microsoft
  - Add [dustilock](https://github.com/Checkmarx/dustilock) to check for dependency confusion attacks with node and python packages
  - Add [gitleaks](https://github.com/zricethezav/gitleaks) to lint git repository
  - Add [goodcheck](https://github.com/sider/goodcheck) as regex-based linter
  - Add [PMD](https://pmd.github.io/) to lint java files (disabled for now)
  - Add [semgrep](https://github.com/returntocorp/semgrep) as regex-based linter with many community rules
  - Add [syft](https://github.com/anchore/syft) to generate SBOM (Software Bill Of Materials)
  - Add [trivy](https://github.com/aquasecurity/trivy) security linter
  - Remove **dockerfilelint**, as it is not maintained anymore and hadolint contains all its rules
  - SARIF management for:
    - bandit
    - checkov
    - checkstyle
    - cfn-lint
    - devskim
    - eslint
    - gitleaks
    - hadolint
    - ktlint
    - npm-groovy-lint
    - psalm
    - semgrep
    - secretlint
    - revive
    - terrascan
    - tflint
    - trivy

- Descriptors:
  - New flavor **Security**
  - New descriptor **repository**: contains secretlint, git_diff, gitleaks and goodcheck
    - remove CREDENTIALS and GIT descriptors

- mega-linter-runner
  - Propose to test ox.security service
  - --upgrade option can now upgrade repos MegaLinter config to v6

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io/v6-alpha) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/1674834108)

|   Descriptor   |                                                         Linter                                                         |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.03s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.28s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/bash_shfmt)                                          |    7|    1|                                                                         0|1.57s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.87s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/dockerfile_hadolint)                              |  100|     |                                                                         0|11.78s      |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.75s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.87s       |
|✅ JSON         |[v8r](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/json_v8r)                                              |   21|     |                                                                         0|11.77s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/markdown_markdownlint)                        |  206|    8|                                                                         0|4.48s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/markdown_markdown_link_check)          |  206|     |                                                                         0|41.72s      |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/markdown_markdown_table_formatter)|  206|    8|                                                                         0|4.17s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.16s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/python_bandit)                                      |  150|     |[**45**](https://github.com/megalinter/megalinter/actions/runs/1674834108)|2.41s       |
|✅ PYTHON       |[black](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/python_black)                                        |  150|    9|                                                                         0|3.84s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.27s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/python_isort)                                        |  150|   10|                                                                         0|0.52s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/python_mypy)                                          |  150|     |                                                                         0|55.79s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/python_pylint)                                      |  150|     |                                                                         0|18.11s      |
|✅ REPOSITORY   |[gitleaks](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/repository_gitleaks)                              |yes  |     |no                                                                        |3.45s       |
|✅ REPOSITORY   |[git_diff](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.23s       |
|✅ REPOSITORY   |[secretlint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |15.25s      |
|✅ REPOSITORY   |[trivy](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |17.75s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/spell_cspell)                                       |  764|     |                                                                         0|35.78s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/spell_misspell)                                   |  601|   19|                                                                         0|0.57s       |
|✅ XML          |[xmllint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.01s       |
|✅ YAML         |[prettier](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/yaml_prettier)                                    |   77|    6|                                                                         0|2.54s       |
|✅ YAML         |[v8r](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/yaml_v8r)                                              |   19|     |                                                                         0|14.46s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/v6-alpha/v6-alpha/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.3s        |


See errors details in [**artifact MegaLinter reports** on GitHub Action page](https://github.com/megalinter/megalinter/actions/runs/1674834108)

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io/v6-alpha) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2212944496)

|     Descriptor     |                                                    Linter                                                     |Files|Fixed|                                  Errors                                  |Elapsed time|
|--------------------|---------------------------------------------------------------------------------------------------------------|-----|-----|--------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://megalinter.github.io/v6-alpha/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.03s       |
|✅ BASH             |[shellcheck](https://megalinter.github.io/v6-alpha/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.25s       |
|✅ BASH             |[shfmt](https://megalinter.github.io/v6-alpha/descriptors/bash_shfmt)                                          |    7|    1|                                                                         0|0.29s       |
|✅ COPYPASTE        |[jscpd](https://megalinter.github.io/v6-alpha/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.76s       |
|✅ DOCKERFILE       |[hadolint](https://megalinter.github.io/v6-alpha/descriptors/dockerfile_hadolint)                              |  102|     |                                                                         0|11.99s      |
|✅ JSON             |[eslint-plugin-jsonc](https://megalinter.github.io/v6-alpha/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.6s        |
|✅ JSON             |[jsonlint](https://megalinter.github.io/v6-alpha/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|6.36s       |
|✅ JSON             |[v8r](https://megalinter.github.io/v6-alpha/descriptors/json_v8r)                                              |   21|     |                                                                         0|13.46s      |
|✅ MARKDOWN         |[markdownlint](https://megalinter.github.io/v6-alpha/descriptors/markdown_markdownlint)                        |  276|    4|                                                                         0|5.37s       |
|✅ MARKDOWN         |[markdown-link-check](https://megalinter.github.io/v6-alpha/descriptors/markdown_markdown_link_check)          |  276|     |                                                                         0|3.69s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://megalinter.github.io/v6-alpha/descriptors/markdown_markdown_table_formatter)|  276|    4|                                                                         0|5.76s       |
|✅ OPENAPI          |[spectral](https://megalinter.github.io/v6-alpha/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.08s       |
|:warning: PYTHON    |[bandit](https://megalinter.github.io/v6-alpha/descriptors/python_bandit)                                      |  162|     |[**45**](https://github.com/megalinter/megalinter/actions/runs/2212944496)|2.22s       |
|✅ PYTHON           |[black](https://megalinter.github.io/v6-alpha/descriptors/python_black)                                        |  162|    9|                                                                         0|4.84s       |
|✅ PYTHON           |[flake8](https://megalinter.github.io/v6-alpha/descriptors/python_flake8)                                      |  162|     |                                                                         0|2.42s       |
|✅ PYTHON           |[isort](https://megalinter.github.io/v6-alpha/descriptors/python_isort)                                        |  162|   11|                                                                         0|0.62s       |
|✅ PYTHON           |[mypy](https://megalinter.github.io/v6-alpha/descriptors/python_mypy)                                          |  162|     |                                                                         0|77.53s      |
|✅ PYTHON           |[pylint](https://megalinter.github.io/v6-alpha/descriptors/python_pylint)                                      |  162|     |                                                                         0|15.4s       |
|✅ REPOSITORY       |[git_diff](https://megalinter.github.io/v6-alpha/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.27s       |
|✅ REPOSITORY       |[secretlint](https://megalinter.github.io/v6-alpha/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |10.77s      |
|:warning: REPOSITORY|[semgrep](https://megalinter.github.io/v6-alpha/descriptors/repository_semgrep)                                |yes  |yes  |[**1**](https://github.com/megalinter/megalinter/actions/runs/2212944496) |85.57s      |
|✅ REPOSITORY       |[trivy](https://megalinter.github.io/v6-alpha/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |14.85s      |
|✅ SPELL            |[cspell](https://megalinter.github.io/v6-alpha/descriptors/spell_cspell)                                       |  855|     |                                                                         0|20.5s       |
|✅ SPELL            |[misspell](https://megalinter.github.io/v6-alpha/descriptors/spell_misspell)                                   |  689|   16|                                                                         0|0.67s       |
|✅ XML              |[xmllint](https://megalinter.github.io/v6-alpha/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.01s       |
|✅ YAML             |[prettier](https://megalinter.github.io/v6-alpha/descriptors/yaml_prettier)                                    |   76|    7|                                                                         0|3.35s       |
|✅ YAML             |[v8r](https://megalinter.github.io/v6-alpha/descriptors/yaml_v8r)                                              |   18|     |                                                                         0|16.35s      |
|✅ YAML             |[yamllint](https://megalinter.github.io/v6-alpha/descriptors/yaml_yamllint)                                    |   77|     |                                                                         0|1.9s        |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2212944496)

**Comment by llaville** [comment]
@nvuillam With commit ce385de7c16f23f79759cfa985694cc7d124734a adding composer to PATH is no more required.

Only reason was to previous PHPLint v3.x installation (from Composer), PHPStan, PHPCS and Psalm were installed via PHIVE (PHP Archive : PHAR, that include all required dependencies)

**Comment by nvuillam** [comment]
thanks @llaville :)

**Pull request merged**
