### PR TITLE
Added bitbucket template + Fix icon in console logs

### LINKED ISSUE #1324: Bitbucket Pipeline Support
**Is your feature request related to a problem? Please describe.**
In my company we're using Bitbucket. It would be great if MegaLinter would support it out of the box

**Describe the solution you'd like**
Provide a similar solution as for GitHub Actions

**Describe alternatives you've considered**
Install and run it inside a Bitbucket Pipeline Container similar as I would do locally

**Additional context**

- https://support.atlassian.com/bitbucket-cloud/docs/what-are-pipes/
- https://support.atlassian.com/bitbucket-cloud/docs/write-a-pipe-for-bitbucket-pipelines/

### PR DESCRIPTION
**Pull request by Doommius**
Fixes #1324 

Updates doc with template for bitbucket pipeline.

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by Doommius** [comment]
Also added a fix for the console reporter where it used the incorrect char, This might break some outside if people manually added a fix to use the correct char.

image

**Comment by nvuillam** [comment]
Nice :)
CI is currently broken but I'm working to solve it, I'll merge your PR jsut after :)

**Comment by nvuillam** [comment]
> Also added a fix for the console reporter where it used the incorrect char, This might break some outside if people manually added a fix to use the correct char.
> 
> image

MegaLinter can output many formats, including JSON and SARIF, this table is not supposed to be parsed, so for me it's ok, nice enhancement :)

**Comment by nvuillam** [comment]
@Doommius please can you merge main into your branch ? CI is repaired :)

Also: installation.md is generated from README.md, please can you update the README to add bitbucket instructions ? :)

**Review by nvuillam — APPROVED** [review]
Thanks @Doommius for this PR and for sharing with the community the recipe to use MegaLinter on Bitbucket pipelines :)

**Pull request merged**
