### PR TITLE
Bump actions/upload-artifact from 2 to 3

### PR DESCRIPTION
**Pull request by rasa**
See https://github.com/oxsecurity/megalinter/pull/1392/files

### CODE REVIEW

**Comment by nvuillam** [comment]
@rasa there are other references to actions/upload-artifact@v2 in ML sources, please can you also update them in your PR ? :)

**Comment by rasa** [comment]
@nvuillam done.

**Comment by rasa** [comment]
There are a few `actions/checkout@v2` that should be `v3`, per https://github.com/oxsecurity/megalinter/search?q=actions%2Fupload-artifact&type=code
Should I add these to this PR or spin a new one?

**Comment by nvuillam** [comment]
> There are a few `actions/checkout@v2` that should be `v3`, per https://github.com/oxsecurity/megalinter/search?q=actions%2Fupload-artifact&type=code Should I add these to this PR or spin a new one?

Sure, thanks ! :)

**Comment by rasa** [comment]
> Sure, thanks ! :)

@nvuillam done. I checked a couple of other actions and they appear to be updated:
https://github.com/oxsecurity/megalinter/search?q=peter-evans%2Fcreate-pull-request&type=code
https://github.com/oxsecurity/megalinter/search?q=stefanzweifel%2Fgit-auto-commit-action&type=code

**Comment by nvuillam** [comment]
@rasa normally dependabot takes care of that :)
Thanks a lot for your research and feedback :)

**Review by nvuillam — APPROVED** [review]
Great catch, thanks a lot for your contribution :)

**Pull request merged**
