### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3178699900)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                   |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.02s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.26s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.29s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |1.85s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|8.57s       |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|2.13s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.47s       |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   21|     |                                                                          0|15.87s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  294|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3178699900)  |5.8s        |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  294|     |                                                                          0|5.16s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  294|    0|                                                                          0|6.88s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|1.54s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  170|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3178699900) |2.54s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  170|    0|                                                                          0|4.02s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  170|     |                                                                          0|2.2s        |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  170|    0|                                                                          0|1.16s       |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  170|     |                                                                          0|6.96s       |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  170|     |                                                                          0|11.98s      |
|:warning: PYTHON  |[pyright](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pyright)                                    |  170|     |[**274**](https://github.com/oxsecurity/megalinter/actions/runs/3178699900)|17.03s      |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                         |28.46s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.29s       |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |10.31s      |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |18.02s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  706|     |                                                                          0|18.44s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  533|    0|                                                                          0|0.72s       |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.01s       |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|2.82s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|36.29s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.28s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3178699900)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
It seems that many links are pointing to beta instead of 6.11.1, is it expected? How are the links generated so that this changes on an automated PR like that?

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/test-nuillam-patch) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3178699893)

|     Descriptor     |                                                               Linter                                                               |Files|Fixed|                                  Errors                                   |Elapsed time|
|--------------------|------------------------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.02s       |
|✅ BASH             |[shellcheck](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.39s       |
|✅ BASH             |[shfmt](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.04s       |
|✅ COPYPASTE        |[jscpd](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |3.11s       |
|✅ DOCKERFILE       |[hadolint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|9.75s       |
|✅ JSON             |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|2.43s       |
|✅ JSON             |[jsonlint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.5s        |
|✅ JSON             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/json_v8r)                                              |   21|     |                                                                          0|18.45s      |
|:warning: MARKDOWN  |[markdownlint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/markdown_markdownlint)                        |  294|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3178699893)  |6.47s       |
|✅ MARKDOWN         |[markdown-link-check](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/markdown_markdown_link_check)          |  294|     |                                                                          0|6.14s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/markdown_markdown_table_formatter)|  294|    0|                                                                          0|7.46s       |
|✅ OPENAPI          |[spectral](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|1.72s       |
|:warning: PYTHON    |[bandit](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_bandit)                                      |  170|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3178699893) |3.62s       |
|✅ PYTHON           |[black](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_black)                                        |  170|    0|                                                                          0|4.82s       |
|✅ PYTHON           |[flake8](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_flake8)                                      |  170|     |                                                                          0|2.75s       |
|✅ PYTHON           |[isort](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_isort)                                        |  170|    0|                                                                          0|0.57s       |
|✅ PYTHON           |[mypy](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_mypy)                                          |  170|     |                                                                          0|10.79s      |
|✅ PYTHON           |[pylint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_pylint)                                      |  170|     |                                                                          0|15.67s      |
|:warning: PYTHON    |[pyright](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/python_pyright)                                    |  170|     |[**272**](https://github.com/oxsecurity/megalinter/actions/runs/3178699893)|23.34s      |
|✅ REPOSITORY       |[checkov](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_checkov)                                |yes  |     |no                                                                         |37.49s      |
|:warning: REPOSITORY|[devskim](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_devskim)                                |yes  |     |[**59**](https://github.com/oxsecurity/megalinter/actions/runs/3178699893) |1.61s       |
|✅ REPOSITORY       |[dustilock](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_dustilock)                            |yes  |     |no                                                                         |2.65s       |
|✅ REPOSITORY       |[git_diff](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.04s       |
|✅ REPOSITORY       |[secretlint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |6.1s        |
|✅ REPOSITORY       |[syft](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_syft)                                      |yes  |     |no                                                                         |2.82s       |
|✅ REPOSITORY       |[trivy](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |18.71s      |
|✅ SPELL            |[cspell](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/spell_cspell)                                       |  706|     |                                                                          0|27.03s      |
|✅ SPELL            |[misspell](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/spell_misspell)                                   |  533|    0|                                                                          0|0.63s       |
|✅ XML              |[xmllint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.0s        |
|✅ YAML             |[prettier](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|3.32s       |
|✅ YAML             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|44.48s      |
|✅ YAML             |[yamllint](https://oxsecurity.github.io/megalinter/test-nuillam-patch/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.83s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3178699893)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**oxsecurity/megalinter/flavors/python@test-nvuillam-patch**](https://oxsecurity.github.io/megalinter/test-nuillam-patch/flavors/python/) (56 linters)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
> It seems that many links are pointing to beta instead of 6.11.1, is it expected? How are the links generated so that this changes on an automated PR like that?

Every link is generated from `bash build.sh`, that can take --version argument.

Until there is an official release, content of branch main is published as beta version :)

**Comment by echoix** [comment]
Perfect! Thanks!

**Pull request merged**
