### PR TITLE
Improve config test

### PR DESCRIPTION
**Pull request by bdovaz**
Context: https://github.com/oxsecurity/megalinter/pull/2418#issuecomment-1455742230

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4342126796)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.38s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.44s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|15.06s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.98s       |
|✅ JSON      |[jsonlint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.18s       |
|✅ JSON      |[v8r](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.7s       |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/markdown_markdownlint)                        |  309|    0|[230](https://github.com/oxsecurity/megalinter/actions/runs/4342126796)|6.58s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.31s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|19.58s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.29s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4342126796) |2.01s       |
|✅ PYTHON    |[black](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_black)                                        |  183|    0|                                                                      0|4.38s       |
|✅ PYTHON    |[flake8](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.81s       |
|✅ PYTHON    |[isort](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.78s       |
|✅ PYTHON    |[mypy](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_mypy)                                          |  183|     |                                                                      0|6.68s       |
|✅ PYTHON    |[pylint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_pylint)                                      |  183|     |                                                                      0|11.03s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/python_pyright)                                    |  183|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4342126796)|15.24s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.33s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.39s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |13.17s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |28.33s      |
|✅ SPELL     |[cspell](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/spell_cspell)                                       |  745|     |                                                                      0|20.05s      |
|✅ SPELL     |[misspell](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/spell_misspell)                                   |  566|    0|                                                                      0|0.95s       |
|✅ XML       |[xmllint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.42s       |
|✅ YAML      |[prettier](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.66s       |
|✅ YAML      |[v8r](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|53.5s       |
|✅ YAML      |[yamllint](https://megalinter.io/632f0476ee68bbc6b9c5ce47f197eebfb163bf33/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.07s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4342126796)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam do I put the ignore in this branch or do you do it in main?

image

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4342126793)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.16s       |
|✅ BASH      |[shfmt](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.96s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|14.37s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.84s       |
|✅ JSON      |[jsonlint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.15s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.6s        |
|✅ JSON      |[v8r](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.9s       |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/markdown_markdownlint)                        |  309|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4342126793)|5.85s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.13s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|16.0s       |
|✅ OPENAPI   |[spectral](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.44s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4342126793) |2.2s        |
|✅ PYTHON    |[black](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_black)                                        |  183|    0|                                                                      0|3.33s       |
|✅ PYTHON    |[flake8](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.82s       |
|✅ PYTHON    |[isort](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.43s       |
|✅ PYTHON    |[mypy](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_mypy)                                          |  183|     |                                                                      0|7.07s       |
|✅ PYTHON    |[pylint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_pylint)                                      |  183|     |                                                                      0|10.82s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/python_pyright)                                    |  183|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4342126793)|16.05s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.71s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4342126793) |1.36s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.14s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |6.75s       |
|✅ REPOSITORY|[syft](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.05s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.54s      |
|✅ SPELL     |[cspell](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/spell_cspell)                                       |  745|     |                                                                      0|18.15s      |
|✅ SPELL     |[misspell](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/spell_misspell)                                   |  566|    2|                                                                      0|0.55s       |
|✅ XML       |[xmllint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.6s        |
|✅ YAML      |[v8r](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|26.18s      |
|✅ YAML      |[yamllint](https://megalinter.io/3fcd7b681f39280b1bc2b02d27ae54ef20b87bad/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.08s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4342126793)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Review by nvuillam — APPROVED** [review]
Much better indeed :)
trivy issue is fixed in another PR

**Pull request merged**
