### PR TITLE
update DISABLE_LINTERS in readme

### PR DESCRIPTION
**Pull request by SoumayaMauthoorMOJ**
Fixes #

## Proposed Changes

1. Cosmetic change to explain how to disable multiple linters

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by Kurt-von-Laven — APPROVED** [review]
Thank you!

**Comment by nvuillam** [comment]
@Kurt-von-Laven for such small PR that can not create regression, once MegaLinter job is ok you can merge directly :)

**Comment by SoumayaMauthoorMOJ** [comment]
@Kurt-von-Laven would you mind approving running the workflows? I had to rebase the PR

**Comment by Kurt-von-Laven** [comment]
@nvuillam, which job is the MegaLinter job for my education?

**Comment by nvuillam** [comment]
@Kurt-von-Laven this one :)
image

And it's probably failing because of me haha

**Comment by SoumayaMauthoorMOJ** [comment]
@Kurt-von-Laven sorry I still dohn't have permission to merge :-)

**Comment by nvuillam** [comment]
CI fixed, normally :)
@Kurt-von-laven you can merge :)

**Comment by Kurt-von-Laven** [comment]
@nvuillam, GitHub tells me all required checks to be green in order for me to be able to merge. I am guessing this is a difference between admin and non-admin privileges.

**Comment by nvuillam** [comment]
@Kurt-von-Laven after CI you should be abble to merge :) ( i disabled standalone linters for jobs from forks )

**Comment by Kurt-von-Laven** [comment]
My eyes are shining seeing all these green check marks! Thank you for fixing the CI pipeline, @nvuillam! I am still unable to merge, so I am rebasing the branch.

**Comment by nvuillam** [comment]
@Kurt-von-Laven i did lot of updates/fixes today so it was indeed not up to date ^^

**Comment by nvuillam** [comment]
(and I still have a pending one... flake8 released a major version so ML 6.2.0 will wait for tomorrow -it"s almost 3 AM here ^^- )
You can merge this one -> https://github.com/oxsecurity/megalinter/pull/1677 when it is completed then rebase here again haha ^^

**Comment by nvuillam** [comment]
(FYI i just removed the flag that forces a branch to be up to date before merging)

**Comment by nvuillam** [comment]
yay \o/

**Comment by Kurt-von-Laven** [comment]
Sorry I didn't read your instructions carefully enough about merging #1677 first!

**Comment by nvuillam** [comment]
@Kurt-von-Laven that's ok, I had to add tiny updates anyway :)

**Pull request merged**
