### PR TITLE
feat(descriptors, lua): add `stylua` support

### LINKED ISSUE #3971: Add `LUA` support
**Is your feature request related to a problem? Please describe.**

The `LUA` projects are not benefitting from this project

**Describe the solution you'd like**

In the `LUA` ecosystem there are 2 linters (at least this are the ones I know), [luacheck](https://github.com/mpeterv/luacheck) (which hasn't been updated since 6 years ago) and [selene](https://github.com/Kampfkarren/selene) (currently updating), and 1 formatter, [stylua](https://github.com/JohnnyMorganz/StyLua).

> [!note]
> The listed ones, are those which are popular and widely used.

In my personal opinion, I think that `selene` is better because, apart from being currently maintained, it has a more *human-like* way of configuring and displaying the errors than `luacheck`.

**Describe alternatives you've considered**

**Additional context**

I have made a [selene linter action](https://github.com/AlejandroSuero/selene-linter-action) and there is [one for stylua](https://github.com/marketplace/actions/stylua).

### PR DESCRIPTION
**Pull request by AlejandroSuero**
Fixes #3971

## Proposed Changes

1. Add `stylua` to descriptors
2. Modify `cspell.json` to include stylua related words
3. Modify tests to fit `stylua`, `luacheck` and `selene` test cases

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
Does stylua have sensible defaults without a template config file?

**Comment by AlejandroSuero** [comment]
@echoix I think it uses [these default options](https://github.com/JohnnyMorganz/StyLua#options) without a config file.

Running `stylua --check .automation/test/lua` outputs this:

Screenshot 2024-09-10 at 15 06 44

And this in the current `main` branch:

Screenshot 2024-09-10 at 15 08 20

**Comment by echoix** [comment]
I don't know what to conclude about the two screenshots, but I see that it is a linter that can work by itself with a config when not specified.

**Comment by echoix** [comment]
@nvuillam can you confirm that the arguments to call are correct in the descriptor, especially when multiple config file names are possible and when no config is given?

**Comment by echoix** [comment]
Ok, it seems that test files need to be adjusted (lua files).

**Comment by echoix** [comment]
For this job to work https://github.com/oxsecurity/megalinter/actions/runs/10792898658/job/29933585678#step:11:1

**Comment by echoix** [comment]
If you want a faster feedback, you can create a PR from the same branch as this PR, but against your fork. It will run the builds of individual linters, which when at the lua stylua, will take somewhere between 30secs and 2 minutes to build and test with only that linter.

**Comment by echoix** [comment]
For example: https://github.com/AlejandroSuero/megalinter/compare/main...AlejandroSuero:megalinter:add-lua-stylua-support

**Comment by nvuillam** [comment]
About test failure: lua_bad_1.lua must be wrongly formatted, and lua formatter be called with something like --check

**Comment by nvuillam** [comment]
About test_format_fix, you need to have a lua_fix_1.lua that will be updated after the call

**Comment by nvuillam** [comment]
about test version

DEBUG    root:Linter.py:1130 Linter version command: ['/usr/bin/stylua', '--version']
DEBUG    root:Linter.py:1146 Linter version result: -11 

is --version the good argument to get stylua version ? otherwise you need to define `cli_version_arg_name: -v` for example

**Comment by AlejandroSuero** [comment]
@echoix according to `stylua --help`, to get the version, there are the following flags:

- `stylua --version`
- `stylua -V`

Screenshot 2024-09-10 at 23 14 42

**Comment by AlejandroSuero** [comment]
In the PR that I created in my fork https://github.com/AlejandroSuero/megalinter/pull/2, there is this error too:

```txt
- Using [stylua vERROR] https://megalinter.io/pr-2/descriptors/lua_stylua
- MegaLinter key: [LUA_STYLUA]
- Rules config: identified by [stylua]
[stylua] lua_good_1.lua - ERROR - 1 error(s)
--Error detail:
Fatal error while calling stylua: [Errno 2] No such file or directory: 'stylua'
```

**Comment by echoix** [comment]
For the stylua file not found at first, check that the folder copied to corresponds to a folder that is on path. That means to look in the full dockerfile in what folder binaries are copied to

**Comment by AlejandroSuero** [comment]
> For the stylua file not found at first, check that the folder copied to corresponds to a folder that is on path. That means to look in the full dockerfile in what folder binaries are copied to

Is it because of this `COPY --link --from=stylua /stylua /usr/bin/stylua`? the example of kubeconform does it like `/kubeconform /usr/bin/`

**Comment by echoix** [comment]
The last argument would be the destination, and would be a folder, not a file. You can specify multiple source files, but one destination. 

https://docs.docker.com/reference/dockerfile/#source-1

https://docs.docker.com/reference/dockerfile/#copy---from

**Comment by AlejandroSuero** [comment]
@echoix I figured, will do a PR on `stylua` repo to fix the instructions on https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#docker

**Comment by echoix** [comment]
Is there multiple binaries to be copied to?

Ah, well, it might also be working, as it doesn't end with a slash... let me reread. (Or if you have a locally built image, go log into it and explore the folder hierarchy to find out without guessing)

**Comment by echoix** [comment]
An excerpt: 
> Trailing slashes are significant. For example, `COPY test.txt /abs` creates a file at `/abs`, whereas `COPY test.txt /abs/` creates `/abs/test.txt`.

**Comment by AlejandroSuero** [comment]
@echoix when trying to build it locally it errors with this output:

```text
Dockerfile:65
--------------------
  63 |     FROM ghcr.io/yannh/kubeconform:${KUBERNETES_KUBECONFORM_VERSION} AS kubeconform
  64 |     FROM ghcr.io/assignuser/chktex-alpine:latest AS chktex
  65 | >>> FROM johnnymorganz/stylua:${LUA_STYLUA_VERSION} AS stylua
  66 |     FROM yoheimuta/protolint:${PROTOBUF_PROTOLINT_VERSION} AS protolint
  67 |     FROM golang:alpine AS dustilock
--------------------
ERROR: failed to solve: johnnymorganz/stylua:0.20.0: no match for platform in manifest: not found
```

But according to the DockerHub of stylua https://hub.docker.com/r/johnnymorganz/stylua/tags it exists there.

**Comment by AlejandroSuero** [comment]
I removed it and now it fails on `jdkato/vale`:

```txt
Dockerfile:71
--------------------
  69 |     FROM checkmarx/kics:${REPOSITORY_KICS_VERSION} AS kics
  70 |     FROM trufflesecurity/trufflehog:${REPOSITORY_TRUFFLEHOG_VERSION} AS trufflehog
  71 | >>> FROM jdkato/vale:${SPELL_VALE_VERSION} AS vale
  72 |     FROM lycheeverse/lychee:latest-alpine AS lychee
  73 |     FROM ghcr.io/terraform-linters/tflint:v${TERRAFORM_TFLINT_VERSION} AS tflint
--------------------
ERROR: failed to solve: jdkato/vale:v3.7.0: no match for platform in manifest: not found
```

**Comment by AlejandroSuero** [comment]
I managed to get it to work using cargo install [04aaf36](https://github.com/AlejandroSuero/megalinter/pull/2/commits/04aaf365d4733af83010ca1d74d094291e5ae943) and not using `is_formatter: true` since the test with the `is_formatter` failed the test with the following:

<details>
<summary>lua_stylua Job</summary>

```txt
=================================== FAILURES ===================================
_______________________ lua_stylua_test.test_format_fix ________________________
[gw0] linux -- Python 3.12.5 /usr/local/bin/python

self = <lua_stylua_test.lua_stylua_test testMethod=test_format_fix>

    def test_format_fix(self):
        self.request_id = str(uuid.uuid1())
        utilstest.linter_test_setup({"request_id": self.request_id})
        linter = self.get_linter_instance(self.request_id)
        linter.pre_test()
>       utilstest.test_linter_format_fix(linter, self)

megalinter/tests/test_megalinter/LinterTestRoot.py:90: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

linter = <megalinter.Linter.Linter object at 0x7fd4d47024e0>
test_self = <lua_stylua_test.lua_stylua_test testMethod=test_format_fix>

    def test_linter_format_fix(linter, test_self):
        if (
            linter.disabled is True
            or "all" in getattr(linter, "descriptor_flavors_exclude", [])
            or (linter.is_formatter is False and linter.cli_lint_fix_arg_name is None)
        ):
            raise unittest.SkipTest("Linter doesn't format and can't apply fixes")
        test_folder = linter.test_folder
        workspace = (
            config.get(linter.request_id, "DEFAULT_WORKSPACE") + os.path.sep + test_folder
        )
        # Special cases when files must be copied in a temp directory before being linted
        if os.path.isdir(workspace + os.path.sep + "fix"):
            workspace = workspace + os.path.sep + "fix"
        tmp_report_folder = tempfile.gettempdir() + os.path.sep + str(uuid.uuid4())
        assert os.path.isdir(workspace), f"Test folder {workspace} is not existing"
    
        file_map = {}
    
        search_glob_pattern = workspace.replace("\\", "/") + "/**/*"
    
        files = glob.glob(search_glob_pattern, recursive=True)
    
        filter_regex_exclude = []
    
        if linter.test_format_fix_regex_exclude is not None:
            filter_regex_exclude = [linter.test_format_fix_regex_exclude]
    
        file_extensions = linter.file_extensions
    
        if len(linter.test_format_fix_file_extensions) > 0:
            file_extensions = linter.test_format_fix_file_extensions
    
        filtered_files = utils.filter_files(
            all_files=files,
            filter_regex_include="_fix_",
            filter_regex_exclude=filter_regex_exclude,
            file_names_regex=[],
            file_extensions=file_extensions,
            ignored_files=[],
            ignore_generated_files=False,
        )
    
        for file in filtered_files:
            with open(file, "r", encoding="utf-8") as f_expected:
                content_expected = f_expected.read()
                file_map[file] = content_expected
    
        if len(file_map) == 0:
>           raise Exception(f"[test] No files found in: {workspace}")
E           Exception: [test] No files found in: /tmp/lint/.automation/test/lua
```

</details>

> [!note]
> All of this was tested in https://github.com/AlejandroSuero/megalinter/pull/2

**Comment by echoix** [comment]
> @echoix when trying to build it locally it errors with this output:
> 
> 
> 
> ```text
> 
> Dockerfile:65
> 
> --------------------
> 
>   63 |     FROM ghcr.io/yannh/kubeconform:${KUBERNETES_KUBECONFORM_VERSION} AS kubeconform
> 
>   64 |     FROM ghcr.io/assignuser/chktex-alpine:latest AS chktex
> 
>   65 | >>> FROM johnnymorganz/stylua:${LUA_STYLUA_VERSION} AS stylua
> 
>   66 |     FROM yoheimuta/protolint:${PROTOBUF_PROTOLINT_VERSION} AS protolint
> 
>   67 |     FROM golang:alpine AS dustilock
> 
> --------------------
> 
> ERROR: failed to solve: johnnymorganz/stylua:0.20.0: no match for platform in manifest: not found
> 
> ```
> 
> 
> 
> But according to the DockerHub of stylua https://hub.docker.com/r/johnnymorganz/stylua/tags it exists there.

You must be working on a M1 macOS right? In that case trying locally might only bring more problems than it's worth

**Comment by AlejandroSuero** [comment]
@echoix yeah, I'm using a M1, but trying it on the branch, for some reason `stylua` fails the test for getting the help and version with `dockerfile` but works with `cargo`.

**Comment by nvuillam** [comment]
@AlejandroSuero it might be a bug on stylia side ^^
you can declare it to them, meanwhile it seems u'll have to use cargo :)

**Comment by echoix** [comment]
I looked at their docker image, they use distroless-cc as production image, meaning that it is a minimal glibc binary, not muslc. The problem might be there. But stylua is also packaged on apk in the community channel (we don't use it I think).

**Comment by AlejandroSuero** [comment]
@nvuillam I'll point it to them in an issue.

On thing that failed in the last commit is that `lua_stylua_test.py::lua_stylua_test::test_get_linter_help`, but also work when calling `stylua -h`.

<details>
<summary>Build & Deploy - Dev output</summary>

```txt
------------------------------ Captured log call -------------------------------
DEBUG    root:Linter.py:477 [Activation] + LUA_STYLUA (LUA) was activated by default strategies
DEBUG    root:Linter.py:1179 Linter help command: ['stylua', '-h']
DEBUG    root:Linter.py:1194 Linter help result: 0 stylua 0.20.0
A utility to format Lua code

USAGE:
    stylua [OPTIONS] [FILES]...

ARGS:
    <FILES>...    A list of files to format

OPTIONS:
    -a, --allow-hidden
            Whether to traverse hidden files/directories

    -c, --check
            Runs in 'check' mode

        --color <COLOR>
            Use colored output [default: Auto] [possible values: Always, Auto, Never]

    -f, --config-path <CONFIG_PATH>
            Specify path to stylua.toml configuration file

    -g, --glob <GLOB>
            Glob patterns to test against which files to check

    -h, --help
            Print help information

        --no-editorconfig
            Disables the EditorConfig feature

        --num-threads <NUM_THREADS>
            The number of threads to use to format files in parallel [default: 4]

        --output-format <OUTPUT_FORMAT>
            Configures the diff output when using 'check' mode [default: Standard] [possible values:
            Standard, Unified, Json, Summary]

        --range-end <RANGE_END>
            An ending range to format files, given as a byte offset from the beginning of the file

        --range-start <RANGE_START>
            A starting range to format files, given as a byte offset from the beginning of the file

        --respect-ignores
            Respect .styluaignore and glob matching for file paths provided directly to the tool

    -s, --search-parent-directories
            Search parent directories for stylua.toml, if not found in current directory. Ignored if
            config_path is provided

        --stdin-filepath <STDIN_FILEPATH>
            Specify the location of the file that is being passed into stdin. Ignored if not taking
            in input from stdin

    -v, --verbose
            Enables verbose output

    -V, --version
            Print version information

        --verify
            Verifies the output correctness after formatting

FORMATTING OPTIONS:
        --call-parentheses <CALL_PARENTHESES>
            Specify whether to apply parentheses on function calls with single string or table arg
            [possible values: Always, NoSingleString, NoSingleTable, None, Input]

        --collapse-simple-statement <COLLAPSE_SIMPLE_STATEMENT>
            Specify whether to collapse simple statements [possible values: Never, FunctionOnly,
            ConditionalOnly, Always]

        --column-width <COLUMN_WIDTH>
            The column width to use to attempt to wrap lines

        --indent-type <INDENT_TYPE>
            The type of indents to use [possible values: Tabs, Spaces]

        --indent-width <INDENT_WIDTH>
            The width of a single indentation level

        --line-endings <LINE_ENDINGS>
            The type of line endings to use [possible values: Unix, Windows]

        --quote-style <QUOTE_STYLE>
            The style of quotes to use in string literals [possible values: AutoPreferDouble,
            AutoPreferSingle, ForceDouble, ForceSingle]

        --sort-requires
            Enable requires sorting
```

Then at the end it says:

```txt
=========================== short test summary info ============================
FAILED megalinter/tests/test_megalinter/linters/lua_stylua_test.py::lua_stylua_test::test_get_linter_help
===== 1 failed, 601 passed, 332 skipped, 52 warnings in 610.01s (0:10:10) ======
Pytest exited 1
Error(s) found by Pytest
Error: Process completed with exit code 1.
```

</details>

Not sure what can be causing that.

**Comment by nvuillam** [comment]
I think it might be just bad luck because of parallel tetibg updating the same file, i strarted it again :)

**Comment by echoix** [comment]
> I think it might be just bad luck because of parallel tetibg updating the same file, i strarted it again :)

Why don't we just add https://github.com/pytest-dev/pytest-rerunfailures?tab=readme-ov-file, like what https://hatch.pypa.io/latest/tutorials/testing/overview/#retry-failed-tests does (that we use). It might only help us a bit.

**Comment by nvuillam** [comment]
@echoix that would save us time indeed :)
I didn't knew it existed, i almost don't use python except for MegaLinter ^^

**Comment by AlejandroSuero** [comment]
@echoix @nvuillam I made a branch from `main` [adding `pytest-rerunfailures`](https://github.com/AlejandroSuero/megalinter/tree/add-pytest-rerunfailures) in case you want me to do a PR for that.

**Comment by echoix** [comment]
> @echoix @nvuillam I made a branch from `main` [adding `pytest-rerunfailures`](https://github.com/AlejandroSuero/megalinter/tree/add-pytest-rerunfailures) in case you want me to do a PR for that.

I wasn't implying that you needed to do it at all, or that it was needed for this PR, just mentioning the solution when thinking about it, as it's been a recurring pain in the last months. I read the diff of your branch, and it's exactly what I had in mind and would have done myself if I was on a full computer with time for that.

**Comment by AlejandroSuero** [comment]
> I wasn't implying that you needed to do it at all, or that it was needed for this PR, just mentioning the solution when thinking about it, as it's been a recurring pain in the last months. I read the diff of your branch, and it's exactly what I had in mind and would have done myself if I was on a full computer with time for that.

It was more like I did it on my own, I knew you didn't mean to say to add it. But in case you want to add it, I can make the PR or you can copy what I did.

Of course it can be improve since I don't know where the point of failures might be or if there is some failures that don't need be retried it can use `--rerun-except` flag or using decorators to lower certain reruns.

**Comment by AlejandroSuero** [comment]
@echoix I think that's all for this PR. I will open an issue in Stylua's repo to see why might be failing with Docker and not with Cargo (maybe because of the distroless-cc, but uses cargo to build it too)

**Comment by echoix** [comment]
> @echoix I think that's all for this PR. I will open an issue in Stylua's repo to see why might be failing with Docker and not with Cargo (maybe because of the distroless-cc, but uses cargo to build it too)

The part where we use alpine is important. It doesn't use glibc (by default) (it uses musl), and it is often expected to use static linking to have binaries that can just be copied and just run.

I suspect that it could probably be copied from the docker image to any glibc-based image (almost any other distribution)

**Comment by echoix** [comment]
> > I wasn't implying that you needed to do it at all, or that it was needed for this PR, just mentioning the solution when thinking about it, as it's been a recurring pain in the last months. I read the diff of your branch, and it's exactly what I had in mind and would have done myself if I was on a full computer with time for that.
> 
> 
> 
> It was more like I did it on my own, I knew you didn't mean to say to add it. But in case you want to add it, I can make the PR or you can copy what I did.
> 
> 
> 
> Of course it can be improve since I don't know where the point of failures might be or if there is some failures that don't need be retried it can use `--rerun-except` flag or using decorators to lower certain reruns.

Go ahead with a PR. We might just try it and find what we need to adjust more. But it's probably better than nothing, and waiting 30+min for a rerun.

**Pull request merged**
