### PR TITLE
Review MegaLinter's own cspell word list for outdated exclusions

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

Words in cspell's word's list are words that can be suggested when fixing typos. Over time, many words have been automatically added to the list without checking actively. I went over the list, searching for usage of words that seemed unusual or something that shouldn't be considered a valid word suggestion. In the case that it was a valid exclusion, but wasn't a word that should be used, it was added to another field, `ignoreWords` that are ignored but not suggested. For example, partial words in regexes or some strings appearing in the ASCII art, or anything that shouldn't really be a word.

## Proposed Changes

1. Remove old exclusions
2. Move some words to `ignoreWords`
3. A file (`.github/linters/valestyles`) was excluded in the cspell config, but not in misspell in our .mega-linter.yml file. misspell will be removed/or deprecated soon in v7 as I understand.

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
Note: some words with Unicode characters were encoded with backslash-u codes. They were automatically converted to a character when opening in a VS Code IDE.

**Comment by nvuillam** [comment]
@echoix please can you directly disable misspell, as we'll remove it in v7 ? :)

**Comment by echoix** [comment]
> @echoix please can you directly disable misspell, as we'll remove it in v7 ? :)

Well, shouldn't it be a separate PR so we can track additional changes and be able to isolate unrelated changes?

**Comment by nvuillam** [comment]
> > @echoix please can you directly disable misspell, as we'll remove it in v7 ? :)
> 
> Well, shouldn't it be a separate PR so we can track additional changes and be able to isolate unrelated changes?

In a perfect world yes, but as you are a trustee , if you just update the PR title to add "+ disable MISSPELL" it's ok for me ^^

**Comment by echoix** [comment]
The tests failed because of a time-out. At line 1833 https://github.com/oxsecurity/megalinter/actions/runs/5038755387/jobs/9036467074#step:14:1834 , there is an error with the codecov uploader mentioning 

`{'detail': ErrorDetail(string='Missing "owner" argument. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`

And the next line is written 404. 

Then, the remaining 1h 10+min are spent trying to upload (about 3000 lines).

**Comment by nvuillam** [comment]
Codecov is not very reliable these days... just launch ot again and i'll validate tomorrow:)

**Review by nvuillam — APPROVED** [review]
Nice cleanup , thanks 😍

**Pull request merged**
