### PR TITLE
Replace setup.py usage with pyproject.toml using hatch

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
My changelog entry: 

Replace usage of setup.py with a pyproject.toml package install, by @echoix in [#3893](https://github.com/oxsecurity/megalinter/pull/3893)

**Comment by echoix** [comment]
I can't get the individual linters to work, as I changed a file that was excluded for PRs. I wrote my changelog entry in a comment

**Comment by echoix** [comment]
It was last weekend, I added the changelog back. Either run the build command inside this or after. (But it doesn't really matter if there weren't any merge conflicts when you updated from main, it's at different places of the Dockerfiles)

**Comment by echoix** [comment]
Recently uv finally announced their new functionality that allows to manage the complete project, run scripts, being the backend to build. + docs website. It was in the last week. It takes the same place as hatchling, and setuptools. If I would have known that is was coming, maybe I would've tried it to be all-on uv. But I never used it before, and almost no info to help exist appart their new docs website.

**Review by nvuillam — APPROVED** [review]

**Comment by nvuillam** [comment]
@echoix we'll see in the next auto-update-linters job if it's all running well ;)

**Pull request merged**
