### PR TITLE
Upgrade python version

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4098222379)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.37s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.35s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.07s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.45s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.99s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.21s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.44s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    3|[229](https://github.com/oxsecurity/megalinter/actions/runs/4098222379)|6.29s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.04s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    3|                                                                      0|14.99s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.74s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4098222379) |2.31s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|   20|                                                                      0|6.07s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.88s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|   20|                                                                      0|0.88s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.7s        |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.35s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4098222379)|16.81s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |25.93s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.48s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |6.87s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.83s      |
|❌ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |[5](https://github.com/oxsecurity/megalinter/actions/runs/4098222379)  |18.89s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.82s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.36s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.77s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|55.03s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.49s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4098222379)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
I think we'll need to take time to properly test that release out, since we are completely changing the available packages in the alpine repos and all. Plus the Python version.

**Comment by nvuillam** [comment]
> I think we'll need to take time to properly test that release out, since we are completely changing the available packages in the alpine repos and all. Plus the Python version.

Agreed, as the latest release is today, it gives us time to check before the next one :)

**Comment by bdovaz** [comment]
@nvuillam I see that the **php_psalm** one has failed because of the API limit and that one in particular they comment that it is possible to pass an environment variable with the token to solve the problem:

https://github.com/phar-io/phive/issues/127#issuecomment-354552572

Would you know how to do it? Because being in the context of Docker I am not clear how to get that information and how to pass it.

**Comment by nvuillam** [comment]
The key is to solve the case for all linters, and to do that we must use official docker build action + manage all cases tht requires github auth ^^

**Comment by bdovaz** [comment]
@nvuillam I have my doubts of if this concrete case that I mention is going to solve it with what you say... This case is seen to expressly use an environment variable with a very specific name:

https://github.com/phar-io/phive/blob/c5985a10f95be9a21b79e7ee19bef39dc85e9f95/src/shared/config/EnvironmentAuthConfig.php#L18

That is why I believe that this case should be treated differently and solved now with a PR if you think it is possible or create an issue if it is not feasible because it depends on other tasks.

What do you think about it?

**Comment by nvuillam** [comment]
If you find a way to solve it in a standalone PR, of course you can ^^
Plz update the doc to make sure users see it, especially if they are using gitlab or azure ^^

**Comment by bdovaz** [comment]
> If you find a way to solve it in a standalone PR, of course you can ^^ Plz update the doc to make sure users see it, especially if they are using gitlab or azure ^^

I think you didn't understand me or you didn't look at the links I posted.

The problem is in **phive** as I have put that is the one in charge of installing the mentioned PHP linter. That is, the problem is in the Dockerfile file when installing the linter through **phive** so we have to pass that environment variable to run in the GitHub workflows.

That is, we have to modify the descriptor to pass that environment variable to each phive command. Example:

https://github.com/oxsecurity/megalinter/blob/b0bb50f24c6be17112953780a2b921d740bd1d75/megalinter/descriptors/php.megalinter-descriptor.yml#L133

I have created #2314

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam-base-docker) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4107021324)

| Descriptor  |                                                         Linter                                                         |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-nuillam-base-docker/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-nuillam-base-docker/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.47s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-nuillam-base-docker/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-nuillam-base-docker/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.85s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-nuillam-base-docker/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|9.49s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam-base-docker/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.17s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-nuillam-base-docker/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.28s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-nuillam-base-docker/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.8s        |
|✅ JSON      |[v8r](https://megalinter.io/test-nuillam-base-docker/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.45s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam-base-docker/descriptors/markdown_markdownlint)                        |  309|    2|[229](https://github.com/oxsecurity/megalinter/actions/runs/4107021324)|6.92s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-nuillam-base-docker/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.97s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-nuillam-base-docker/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|17.43s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-nuillam-base-docker/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.09s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-nuillam-base-docker/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4107021324) |2.2s        |
|✅ PYTHON    |[black](https://megalinter.io/test-nuillam-base-docker/descriptors/python_black)                                        |  176|    0|                                                                      0|3.56s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-nuillam-base-docker/descriptors/python_flake8)                                      |  176|     |                                                                      0|2.74s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-nuillam-base-docker/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.57s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-nuillam-base-docker/descriptors/python_mypy)                                          |  176|     |                                                                      0|8.95s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-nuillam-base-docker/descriptors/python_pylint)                                      |  176|     |                                                                      0|13.55s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-nuillam-base-docker/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4107021324)|21.85s      |
|❌ REPOSITORY|[checkov](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_checkov)                                |yes  |     |[19](https://github.com/oxsecurity/megalinter/actions/runs/4107021324) |33.24s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4107021324) |1.59s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.63s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.87s       |
|✅ REPOSITORY|[syft](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_syft)                                      |yes  |     |no                                                                     |3.7s        |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-nuillam-base-docker/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |20.85s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-nuillam-base-docker/descriptors/spell_cspell)                                       |  730|     |                                                                      0|22.84s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-nuillam-base-docker/descriptors/spell_misspell)                                   |  551|    2|                                                                      0|0.61s       |
|✅ XML       |[xmllint](https://megalinter.io/test-nuillam-base-docker/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/test-nuillam-base-docker/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.83s       |
|✅ YAML      |[v8r](https://megalinter.io/test-nuillam-base-docker/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|64.08s      |
|✅ YAML      |[yamllint](https://megalinter.io/test-nuillam-base-docker/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.99s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4107021324)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
