### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Comment by echoix** [comment]
Reran since the two websites that lychee failed works, so either it's transient, or a something else. I find lychee is quite strict, since most of the time I recheck errors they don't really exist. Is there a way for lychee to maybe juste take another look a bit after before really failing?

**Comment by nvuillam** [comment]
@echoix when i see a lychee error, i check the url and if it works i force the merge ^^
I think sometimes it just fails because of temporary remote server issues ^^

**Comment by echoix** [comment]
I have another idea. Are all the transient 403 forbidden errors on sourgeforge links? I know sourceforge uses many tricks to rate limit, and even has different rules for example, package managers can download a software with a direct link, but a browser would fail and serve content in another webpage. Maybe some user-agent string. I encountered that when adding a new software update entry in the winget repos. I found it weird at the time.
But maybe something's going on, either all the sourceforge links 403 with lychee in Ci, or it's if we have a lot of sourgeforge links and after a certain amount they return 403.

**Comment by Kurt-von-Laven** [comment]
I am reminded of ScribeMD/slack-templates#42, which fixed an issue where all docs.github.com links started responding to markdown-link-check with 400s. They had made compression mandatory, so we needed to add a header to accept the compression.

**Pull request merged**
