### PR TITLE
Fix problems with r-lintr, add unit tests

### LINKED ISSUE #2885: Issue with lintr under mega-linter-runner
**Describe the bug**
When using `npx mega-linter-runner` to run locally, R files in subfolders cannot be linted successfully. This does not seem to happen when running as a GitHub action.

**To Reproduce**

1. `$ mkdir tester && cd tester && echo "a <- 1" > source.R`
2. `$ npx mega-linter-runner -e "'ENABLE=R'"` works successfully

    ```console
    +----SUMMARY-+--------+------+-------+-------+--------+--------------+
    | Descriptor | Linter | Mode | Files | Fixed | Errors | Elapsed time |
    +------------+--------+------+-------+-------+--------+--------------+
    | ✅ R       | lintr  | file |     1 |       |      0 |        1.74s |
    +------------+--------+------+-------+-------+--------+--------------+
    ```
4. `$ mkdir src && mv source.R src/`
5. `$ npx mega-linter-runner -e "'ENABLE=R'"` fails

```console
+----MATCHING LINTERS-+-----------------+----------------+------------+
| Descriptor | Linter | Criteria        | Matching files | Format/Fix |
+------------+--------+-----------------+----------------+------------+
| R          | lintr  | .r|.R|.Rmd|.RMD | 1              | no         |
+------------+--------+-----------------+----------------+------------+

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/megalinter/run.py", line 14, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 236, in run
    self.process_linters_serial(active_linters)
  File "/megalinter/MegaLinter.py", line 285, in process_linters_serial
    linter.run()
  File "/megalinter/Linter.py", line 749, in run
    return_code, stdout = self.process_linter(file)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/Linter.py", line 908, in process_linter
    command = self.build_lint_command(file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/megalinter/linters/RLinter.py", line 18, in build_lint_command
    copyfile(self.config_file, dir_name + os.path.sep + self.config_file_name)
  File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src/.lintr'
```

**Expected behavior**
Running locally should behave the same as running in the cloud.

**Additional context**
In trying to debug I cloned this repo locally (in `../megalinter`) and built/ran it with this little bash script (inspired by the [docs](https://megalinter.io/latest/contributing/#execute-linter-tests-inside-the-container)):

```bash
#!/bin/bash
set -euo pipefail

pushd ../megalinter && docker buildx build -f ../megalinter/linters/r_lintr/Dockerfile . --tag r_lintr
popd
docker run \
    -e OUTPUT_DETAIL=detailed \
    -v "$(pwd)":/tmp/lint \
    --rm -it \
    r_lintr
```

That reproduces the error, but adding `-w /tmp/lint` to the docker call fixes the issue.

### LINKED ISSUE #2886: lintr crashes with any lints
**Describe the bug**
The R shim code used to extract the number of errors from the lintr`output seems to rely on outdated behavior in either the lintr or purrr libraries. Any code lints cause a crash.

**To Reproduce**

1. Create an R file with a trailing semicolon:`mkdir tester && cd tester && echo "a <- 1;" > source.R`
2. Run Megalinter, either in GitHub actions or locally
3. See error

```console
❌ Linted [R] files with [lintr]: Found 1 error(s) - (2.47s)
- Using [lintr v0.0.0] https://megalinter.io/7.3.0/descriptors/r_lintr
- MegaLinter key: [R_LINTR]
- Rules config: [.lintr]
- Number of files analyzed: [1]
[lintr] source.R - ERROR - 1 error(s)
--Error detail:
/tmp/lint/source.R:1:7: style: [semicolon_linter] Trailing semicolons are not needed.
a <- 1;
      ^
Error in `purrr::keep()`:
ℹ In index: 1.
ℹ With name: /tmp/lint/source.R.
Caused by error in `.fn()`:
! object '.type' not found
Backtrace:
     ▆
  1. ├─purrr::keep(lints, ~.type == "error")
  2. │ └─purrr:::where_if(.x, .p, ...)
  3. │   └─purrr:::map_(.x, .p, ..., .type = "logical", .purrr_error_call = .purrr_error_call)
  4. │     ├─purrr:::with_indexed_errors(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     ├─purrr:::call_with_cleanup(...)
  7. │     └─purrr (local) .f(.x[[i]], ...)
  8. │       └─global .fn(...)
  9. └─base::.handleSimpleError(...)
 10.   └─purrr (local) h(simpleError(msg, call))
 11.     └─cli::cli_abort(...)
 12.       └─rlang::abort(...)
Execution halted
```

**Expected behavior**
Lints should not crash the linter.

**Screenshots**
Example of the same bug in GitHub actions:
Screenshot 2023-08-14 at 12 10 39 PM

**Additional context**
I think this change is sufficient to resolve the issue:

```diff
diff --git a/megalinter/linters/RLinter.py b/megalinter/linters/RLinter.py
index e9714da1bf..9cde7e4ca9 100644
--- a/megalinter/linters/RLinter.py
+++ b/megalinter/linters/RLinter.py
@@ -20,7 +20,7 @@ class RLinter(Linter):
         r_commands = [
             f"lints <- lintr::lint('{file}');",
             "print(lints);",
-            "errors <- purrr::keep(lints, ~ .type == 'error');",
+            "errors <- purrr::keep(lints, \(x) x$type == 'error');",
             "quit(save = 'no', status = if (length(errors) > 0) 1 else 0)",
         ]
         # Build shell command
```

### PR DESCRIPTION
**Pull request by nwiltsie**
Fixes #2885, fixes #2886.

I'm back to try again after I was stymied with #2887!

## Proposed Changes

1. Remove the `purrr::keep` filter for lints.
    * First, as-written the filter crashes if there are any lints (#2886). This hasn't been caught because only the "bad" files produce lints, and crashes aren't distinguished from clean error exits.
    * Second, theoretically lintr lints are typed as "style", "warning", and "error", but in practice I couldn't find any syntactically-valid code that raised errors. The existing "bad" test case only produces style and warning lints.
1. Add additional test case files for lintr.
    * I added duplicates of the existing good and bad files in a subfolder, testing #2885.
    * I added another subfolder with a "good" file containing lints that are disabled by a `.lintr` file. 
    * I also removed a bunch of stray comments from the existing "good" test case file.
1. Remove `TEMPLATE/.lintr` file and update logic for supplying user value.
    * lintr does not require that a `.lintr` file be present - it will search up the directory tree, and finally [fall back to default settings](https://lintr.r-lib.org/reference/read_settings.html) if no configuration file is found.
    * If the user provides a specific configuration file, it will [short-circuit the search](https://github.com/r-lib/lintr/blob/4de229f55e9387379beb42f61c235266bbc68dcd/R/settings_utils.R#L60-L63).

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
Sorry, it is not a real approval, I just mispressed on the phone

**Review by echoix — CHANGES_REQUESTED** [review]
I remember having to update the R tests, I think the test files (with the comments), were directly from the projects' test files.

The good files should be what the bad file should be once formatted by the tool. So I would be suprised that the comments removed only in the good file (that were there from the project test files) would work as expected. (Unless the tool strips comments). You can wait to see test failures to be sure.

**Comment by nwiltsie** [comment]
> The good files should be what the bad file should be once formatted by the tool. So I would be suprised that the comments removed only in the good file (that were there from the project test files) would work as expected.

It seems like the R tests passed just fine - 2/3 of the failed checks seem unrelated to these changes, and the third seems to be an over-aggressive spell-checker. I'm not sure how to proceed from here - do you have any advice?

(No rush, it's a long weekend here in the US and I'm idly checking this.)

### Tests + Deploy Docker Image - DEV

[Line 1309](https://github.com/oxsecurity/megalinter/actions/runs/11751740069/job/32743746232?pr=4235#step:11:1310): `[gw2] [ 63%] PASSED megalinter/tests/test_megalinter/linters/r_lintr_test.py::r_lintr_test::test_failure`

[Line 1337](https://github.com/oxsecurity/megalinter/actions/runs/11751740069/job/32743746232?pr=4235#step:11:1338): `[gw2] [ 64%] PASSED megalinter/tests/test_megalinter/linters/r_lintr_test.py::r_lintr_test::test_success`

It seems like the errors were with the markdown tests?

```
=========================== short test summary info ============================
FAILED megalinter/tests/test_megalinter/linters/markdown_markdown_link_check_test.py::markdown_markdown_link_check_test::test_failure
FAILED megalinter/tests/test_megalinter/linters/markdown_markdown_link_check_test.py::markdown_markdown_link_check_test::test_success
= 2 failed, 604 passed, 328 skipped, 52 warnings, 6 rerun in 642.74s (0:10:42) =
Pytest exited 1
Error(s) found by Pytest
```

### Gitpod / build:

These errors relate to installing `uv`?

```
------
Dockerfile:94
--------------------
  93 |     # hadolint ignore=SC1090,SC1091
  94 | >>> RUN curl  -LsSf https://astral.sh/uv/install.sh | sh \
  95 | >>>     && source "$HOME/.cargo/env"
  96 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c curl  -LsSf https://astral.sh/uv/install.sh | sh     && source \"$HOME/.cargo/env\"" did not complete successfully: exit code: 1
make[1]: *** [.config/make/gitpod.mak:4: gitpod-build] Error 1
make: *** [.config/make/gitpod.mak:12: gitpod-tests] Error 2
Error: Final attempt failed. Child_process exited with error code 2
```

### Megalinter

The spell-checker is complaining about the embedded R-code:

```
  megalinter/linters/RLinter.py:17:15     - Unknown word (setwd)      -- f"setwd('{Path(file).parent
  	 Suggestions: [stew, stead, steed, stews, stewed]
```

**Comment by nvuillam** [comment]
@nwiltsie thanks for your PR :)

You can update .cspell.json to add **setwd** in allowed words

The other issues are indeed not related to your PR, once we'll fix them in main you'll be able to merge the new main in your branch and your PR will pass :)

**Comment by nvuillam** [comment]
@nwiltsie i updated your branch, let's see if it passes :)

**Comment by nwiltsie** [comment]
Thanks @nvuillam!

**Pull request merged**
