### PR TITLE
Fix config tests

### PR DESCRIPTION
**Pull request by bdovaz**
Attemp to fix them with the help of @Kurt-von-Laven in https://github.com/oxsecurity/megalinter/pull/2381#issuecomment-1439326190

### CODE REVIEW

**Comment by bdovaz** [comment]
@Kurt-von-Laven can you help me to fix it? It's quite hopeless to have to wait more than half an hour for the 5 tests I want to fix config to run.

I'm using certain github variables to resolve the repository name and branch correctly.

I'm not sure if I'm doing it right and since I can't debug the values I get as I'm a bit blind.

**Comment by nvuillam** [comment]
@bdovaz you can set the following in the commit message when you just update python code and want to reduce the tested methodes
```
quick build
TEST_KEYWORDS=config_test
```

**Comment by bdovaz** [comment]
@nvuillam it did not work for me on: https://github.com/oxsecurity/megalinter/pull/2388/commits/0c2014fa1f37f6ee900cd51a05398972590ce3e8

**Comment by nvuillam** [comment]
In a bar, can't act now :/
But i'd like to release a new version this weekend, i'll try to help :)

**Comment by bdovaz** [comment]
@nvuillam @Kurt-von-Laven I give up, I can't find the right combination to correctly resolve the variables for the owner and repository name when coming from a fork.

If you help me I would appreciate it 

Also, this quick build does not work with a test commit I have done and it is even more frustrating to have to wait more than half an hour between tests.

**Comment by nvuillam** [comment]
Rollback ? ^^

**Comment by bdovaz** [comment]
@nvuillam @Kurt-von-Laven looks like the key was:

https://docs.github.com/en/actions/learn-github-actions/contexts

image

Looking at the contents of `github` I could see how to get the repository and branch correctly when it is a pull request or when it is not.

In this build I have passed the tests only as I had not done rebase I got an error fixed in main:

https://github.com/oxsecurity/megalinter/actions/runs/4269559713/jobs/7432816126

I have launched a new build and I hope it is the final one and I can unlock @echoix.

**Comment by bdovaz** [comment]
@nvuillam can you solve the checkov problems please? I'm not at home 😅

**Review by nvuillam — APPROVED** [review]
Great :)

**Comment by Kurt-von-Laven** [comment]
> Looking at the contents of `github` I could see how to get the repository and branch correctly when it is a pull request or when it is not.

Yeah, you can get the repository and branch out of the `github` context, but the environment variables I mentioned previously should work equally well, and I found them a little easier to work with.

**Comment by bdovaz** [comment]
@nvuillam but at the end you have merged it without solving checkov errors. I say this because anyone who wants to merge is going to encounter the same problem.

**Comment by bdovaz** [comment]
> > Looking at the contents of `github` I could see how to get the repository and branch correctly when it is a pull request or when it is not.
> 
> Yeah, you can get the repository and branch out of the `github` context, but the environment variables I mentioned previously should work equally well, and I found them a little easier to work with.

Lo he usado como me dijiste pero en modo variable se GitHub en vez de variable se entorno por coherencia con el código de workflows

**Comment by nvuillam** [comment]
@bdovaz i did it in another PR :)

**Pull request merged**
