### PR TITLE
Add Trivy config file parameters

### PR DESCRIPTION
**Pull request by bdovaz**
- Add config_file_name and cli_config_arg_name
- Change configuration url to a more suitable one
- Change old urls to the current version
- Fix broken banner image url

### CODE REVIEW

**Comment by bdovaz** [comment]
I have doubts whether to put /v0.35/ or /latest/.

v0.35:
- Difficult to maintain, it is easy to forget to update the version....
- Aim for the version that corresponds to the one in the image.

latest:
- Not to be maintained.
- It always points to the latest version and it doesn't have to be the one in the image.

**Comment by nvuillam** [comment]
@bdovaz I don't remember why we did not use latest
If it works with latest (and returns correctly the version number), go with latest , that's the default way for other linters

**Comment by bdovaz** [comment]
@nvuillam changed!

**Review by nvuillam — APPROVED** [review]
Great, many thanks for your contribution :)

**Pull request merged**
