### PR TITLE
Upgrade checkov

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3744875047)

|    Descriptor    |                                               Linter                                               |Files|Fixed|                                  Errors                                   |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.02s       |
|✅ BASH           |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.4s        |
|✅ BASH           |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.3s        |
|✅ COPYPASTE      |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |2.52s       |
|✅ DOCKERFILE     |[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|8.22s       |
|✅ JSON           |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|2.16s       |
|✅ JSON           |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.26s       |
|✅ JSON           |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                          0|15.09s      |
|:warning: MARKDOWN|[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  297|    0|[**11**](https://github.com/oxsecurity/megalinter/actions/runs/3744875047) |5.95s       |
|✅ MARKDOWN       |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  297|     |                                                                          0|4.86s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  297|    0|                                                                          0|17.24s      |
|✅ OPENAPI        |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|0.76s       |
|:warning: PYTHON  |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  171|     |[**43**](https://github.com/oxsecurity/megalinter/actions/runs/3744875047) |3.73s       |
|✅ PYTHON         |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  171|    0|                                                                          0|4.56s       |
|✅ PYTHON         |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  171|     |                                                                          0|2.55s       |
|✅ PYTHON         |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  171|    0|                                                                          0|0.74s       |
|✅ PYTHON         |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  171|     |                                                                          0|6.71s       |
|✅ PYTHON         |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  171|     |                                                                          0|11.11s      |
|:warning: PYTHON  |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  171|     |[**274**](https://github.com/oxsecurity/megalinter/actions/runs/3744875047)|17.16s      |
|✅ REPOSITORY     |[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                         |26.3s       |
|✅ REPOSITORY     |[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.31s       |
|✅ REPOSITORY     |[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |7.33s       |
|✅ REPOSITORY     |[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |23.95s      |
|✅ SPELL          |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  712|     |                                                                          0|18.35s      |
|✅ SPELL          |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  536|    0|                                                                          0|0.74s       |
|✅ XML            |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.01s       |
|✅ YAML           |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|2.62s       |
|✅ YAML           |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|39.64s      |
|✅ YAML           |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.24s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3744875047)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam-checko2) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3745211236)

|     Descriptor     |                                                       Linter                                                       |Files|Fixed|                                  Errors                                   |Elapsed time|
|--------------------|--------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://megalinter.io/test-nuillam-checko2/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.03s       |
|✅ BASH             |[shellcheck](https://megalinter.io/test-nuillam-checko2/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.41s       |
|✅ BASH             |[shfmt](https://megalinter.io/test-nuillam-checko2/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.03s       |
|✅ COPYPASTE        |[jscpd](https://megalinter.io/test-nuillam-checko2/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |2.41s       |
|✅ DOCKERFILE       |[hadolint](https://megalinter.io/test-nuillam-checko2/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|8.51s       |
|✅ JSON             |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam-checko2/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|1.79s       |
|✅ JSON             |[jsonlint](https://megalinter.io/test-nuillam-checko2/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.21s       |
|✅ JSON             |[v8r](https://megalinter.io/test-nuillam-checko2/descriptors/json_v8r)                                              |   21|     |                                                                          0|15.25s      |
|:warning: MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam-checko2/descriptors/markdown_markdownlint)                        |  297|    0|[**11**](https://github.com/oxsecurity/megalinter/actions/runs/3745211236) |5.34s       |
|✅ MARKDOWN         |[markdown-link-check](https://megalinter.io/test-nuillam-checko2/descriptors/markdown_markdown_link_check)          |  297|     |                                                                          0|4.91s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://megalinter.io/test-nuillam-checko2/descriptors/markdown_markdown_table_formatter)|  297|    0|                                                                          0|16.02s      |
|✅ OPENAPI          |[spectral](https://megalinter.io/test-nuillam-checko2/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|0.72s       |
|:warning: PYTHON    |[bandit](https://megalinter.io/test-nuillam-checko2/descriptors/python_bandit)                                      |  171|     |[**43**](https://github.com/oxsecurity/megalinter/actions/runs/3745211236) |3.04s       |
|✅ PYTHON           |[black](https://megalinter.io/test-nuillam-checko2/descriptors/python_black)                                        |  171|    0|                                                                          0|3.66s       |
|✅ PYTHON           |[flake8](https://megalinter.io/test-nuillam-checko2/descriptors/python_flake8)                                      |  171|     |                                                                          0|3.68s       |
|✅ PYTHON           |[isort](https://megalinter.io/test-nuillam-checko2/descriptors/python_isort)                                        |  171|    0|                                                                          0|0.41s       |
|✅ PYTHON           |[mypy](https://megalinter.io/test-nuillam-checko2/descriptors/python_mypy)                                          |  171|     |                                                                          0|7.16s       |
|✅ PYTHON           |[pylint](https://megalinter.io/test-nuillam-checko2/descriptors/python_pylint)                                      |  171|     |                                                                          0|11.17s      |
|:warning: PYTHON    |[pyright](https://megalinter.io/test-nuillam-checko2/descriptors/python_pyright)                                    |  171|     |[**272**](https://github.com/oxsecurity/megalinter/actions/runs/3745211236)|17.85s      |
|✅ REPOSITORY       |[checkov](https://megalinter.io/test-nuillam-checko2/descriptors/repository_checkov)                                |yes  |     |no                                                                         |26.5s       |
|:warning: REPOSITORY|[devskim](https://megalinter.io/test-nuillam-checko2/descriptors/repository_devskim)                                |yes  |     |[**60**](https://github.com/oxsecurity/megalinter/actions/runs/3745211236) |1.14s       |
|✅ REPOSITORY       |[dustilock](https://megalinter.io/test-nuillam-checko2/descriptors/repository_dustilock)                            |yes  |     |no                                                                         |1.67s       |
|✅ REPOSITORY       |[git_diff](https://megalinter.io/test-nuillam-checko2/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.03s       |
|✅ REPOSITORY       |[secretlint](https://megalinter.io/test-nuillam-checko2/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |4.09s       |
|✅ REPOSITORY       |[syft](https://megalinter.io/test-nuillam-checko2/descriptors/repository_syft)                                      |yes  |     |no                                                                         |2.83s       |
|✅ REPOSITORY       |[trivy](https://megalinter.io/test-nuillam-checko2/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |19.34s      |
|✅ SPELL            |[cspell](https://megalinter.io/test-nuillam-checko2/descriptors/spell_cspell)                                       |  712|     |                                                                          0|17.96s      |
|✅ SPELL            |[misspell](https://megalinter.io/test-nuillam-checko2/descriptors/spell_misspell)                                   |  536|    0|                                                                          0|0.5s        |
|✅ XML              |[xmllint](https://megalinter.io/test-nuillam-checko2/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.01s       |
|✅ YAML             |[prettier](https://megalinter.io/test-nuillam-checko2/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|2.45s       |
|✅ YAML             |[v8r](https://megalinter.io/test-nuillam-checko2/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|42.7s       |
|✅ YAML             |[yamllint](https://megalinter.io/test-nuillam-checko2/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.53s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3745211236)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**oxsecurity/megalinter/flavors/python@v5**](https://megalinter.io/test-nuillam-checko2/flavors/python/) (57 linters)


_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by Kurt-von-Laven** [comment]
I see the following error in CI:

```
executor failed running [/bin/sh -c PYTHONDONTWRITEBYTECODE=1 pip3 install --no-cache-dir --upgrade pip && PYTHONDONTWRITEBYTECODE=1 pip3 install --no-cache-dir --upgrade setuptools virtualenv     && mkdir -p "/venvs/checkov" && cd "/venvs/checkov" && virtualenv . && source bin/activate && PYTHONDONTWRITEBYTECODE=1 pip3 install --no-cache-dir packaging==21.3 checkov==2.2.185 && deactivate && cd ./../..      && find . | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf && rm -rf /root/.cache]: exit code: 1
2022-12-21 00:18:53 [FATAL]   failed to [build] Dockerfile!
Error: Process completed with exit code 1.
```

I find this failure very opaque considering how many actions are taken together in conjunction, which I'm guessing may be a holdover from our Super-Linter heritage. I wonder if the best step would be split these steps into separate lines in a separate pull request so that we know more specifically where we're going off the rails?

**Comment by nvuillam** [comment]
still waiting to be able to upgrade python version, when the new releas of multiprocessing-logging will be done :/

**Comment by nvuillam** [comment]
Will be handled by #2312

**Pull request closed without merging**
