### PR TITLE
Roslynator repo url change

### PR DESCRIPTION
**Pull request by TommyE123**
Hi,

I noticed that the URLs and logo locations in the documentation were now slightly incorrect for [Roslynator](https://github.com/dotnet/Roslynator), so I've made the following changes to address this issue.

## Proposed Changes

1. Updated the incorrect URL to remove the need for a redirection currently in place.
2. Fixed the logo file location which is currently broken in the documentation page. [Roslynator config](https://megalinter.io/latest/descriptors/csharp_roslynator/)

### Additional help required:

I believe that a comment on this PR with `/build` can automatically correct all the locations affected by these changes? Could someone with access to this feature please consider initiating this to ensure that all related files are updated accordingly for me?

Regards
Tom

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
After that you can do an empty commit or anything else, like reporting an empty line in the changelog to retrigger the CI

**Comment by TommyE123** [comment]
Will do, Thank you 🙂

> After that you can do an empty commit or anything else, like reporting an empty line in the changelog to retrigger the CI

**Comment by echoix** [comment]
Ok, it might need a bigger run to fully update the docs, but it will still get updated in the next auto PR after merging if you don't mind.

**Comment by nvuillam** [comment]
CI is broken because of some other dependencies, it will finally pass so we'll be able to merge your PR before the next release :)

**Review by nvuillam — APPROVED** [review]
Thanks :)

**Pull request merged**
