### PR TITLE
Add my blog post to the list of English articles

### PR DESCRIPTION
**Pull request by wesley-dean-flexion**
Added "5 ways MegaLinter upped our DevSecOps game" by Wes Dean to the list of English articles

## Proposed Changes

1. Add a link to the list in the same format as other articles in the list

## Readiness Checklist

yup, ready

### Author/Contributor

n/a

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@wesley-dean-flexion we add articles from latest to oldest, so you can put yours at the top of the list :)

**Comment by wesley-dean-flexion** [comment]
> @wesley-dean-flexion we add articles from latest to oldest, so you can put yours at the top of the list :)

One day I'm going to submit a PR that doesn't require correction.  That's my life's ambition at this point :)

**Comment by nvuillam** [comment]
@wesley-dean-flexion one day we'll document enough to PRs won't need corrections 🤣

**Comment by nvuillam** [comment]
@wesley-dean-flexion by the way: https://www.linkedin.com/posts/nicolas-vuillamy_5-ways-megalinter-upped-our-devsecops-game-activity-7201998763148656640-DOyq?utm_source=share&utm_medium=member_desktop :)

**Comment by wesley-dean-flexion** [comment]
> @wesley-dean-flexion one day we'll document enough to PRs won't need corrections 🤣

oh, I think you underestimate my creativity in finding new, interesting, and unexpected ways to do something poorly :rofl: 

Thank you for the LinkedIn posting and the kind words.

**Pull request merged**
