### PR TITLE
Fix internal git diff --check

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/3783961897)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.46s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.35s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.87s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|12.08s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.61s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.31s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|16.15s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  299|    0|[133](https://github.com/oxsecurity/megalinter/actions/runs/3783961897)|6.91s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  299|     |                                                                      0|5.43s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  299|    0|                                                                      0|17.58s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.9s        |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  173|     |[43](https://github.com/oxsecurity/megalinter/actions/runs/3783961897) |2.82s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  173|    0|                                                                      0|5.9s        |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  173|     |                                                                      0|2.13s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  173|    0|                                                                      0|0.84s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  173|     |                                                                      0|8.8s        |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  173|     |                                                                      0|14.24s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  173|     |[279](https://github.com/oxsecurity/megalinter/actions/runs/3783961897)|21.13s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |31.42s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.34s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |7.35s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |29.26s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  716|     |                                                                      0|26.42s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  538|    0|                                                                      0|0.87s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                      0|0.0s        |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   80|    0|                                                                      0|3.33s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                      0|47.44s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   81|     |                                                                      0|1.82s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/3783961897)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by Kurt-von-Laven** [comment]
Does this PR modify all line endings in some way or something like that? I ask since I know there is a lot of vibrant activity on this repository over the holidays, and I anticipate some confusion from contributors rebasing across this sweeping change.

**Comment by nvuillam** [comment]
@Kurt-von-Laven i thought I fixed the git-diff bug but... it does not work :/

**Comment by Kurt-von-Laven** [comment]
Oh, gotcha. Is [this](https://github.com/oxsecurity/megalinter/pull/2176#issuecomment-1365163446) the symptom this PR seeks to address?

**Comment by nvuillam** [comment]
Yes :/

**Comment by nvuillam** [comment]
image

I think i'm getting crazy :D

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam--git-eof) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/3787796962)

| Descriptor  |                                                       Linter                                                        |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|---------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-nuillam--git-eof/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-nuillam--git-eof/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.4s        |
|✅ BASH      |[shfmt](https://megalinter.io/test-nuillam--git-eof/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-nuillam--git-eof/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.08s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-nuillam--git-eof/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|10.3s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam--git-eof/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.84s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-nuillam--git-eof/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.2s        |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-nuillam--git-eof/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.56s       |
|✅ JSON      |[v8r](https://megalinter.io/test-nuillam--git-eof/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.08s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam--git-eof/descriptors/markdown_markdownlint)                        |  299|    0|[133](https://github.com/oxsecurity/megalinter/actions/runs/3787796962)|4.96s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-nuillam--git-eof/descriptors/markdown_markdown_link_check)          |  299|     |                                                                      0|5.57s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-nuillam--git-eof/descriptors/markdown_markdown_table_formatter)|  299|    0|                                                                      0|13.48s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-nuillam--git-eof/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.77s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-nuillam--git-eof/descriptors/python_bandit)                                      |  173|     |[43](https://github.com/oxsecurity/megalinter/actions/runs/3787796962) |2.37s       |
|✅ PYTHON    |[black](https://megalinter.io/test-nuillam--git-eof/descriptors/python_black)                                        |  173|    0|                                                                      0|3.73s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-nuillam--git-eof/descriptors/python_flake8)                                      |  173|     |                                                                      0|1.92s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-nuillam--git-eof/descriptors/python_isort)                                        |  173|    0|                                                                      0|0.41s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-nuillam--git-eof/descriptors/python_mypy)                                          |  173|     |                                                                      0|7.39s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-nuillam--git-eof/descriptors/python_pylint)                                      |  173|     |                                                                      0|11.15s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-nuillam--git-eof/descriptors/python_pyright)                                    |  173|     |[277](https://github.com/oxsecurity/megalinter/actions/runs/3787796962)|16.93s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.99s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_devskim)                                |yes  |     |[60](https://github.com/oxsecurity/megalinter/actions/runs/3787796962) |1.19s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.79s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |3.49s       |
|✅ REPOSITORY|[syft](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_syft)                                      |yes  |     |no                                                                     |2.73s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-nuillam--git-eof/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |20.84s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-nuillam--git-eof/descriptors/spell_cspell)                                       |  716|     |                                                                      0|17.64s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-nuillam--git-eof/descriptors/spell_misspell)                                   |  538|    0|                                                                      0|0.43s       |
|✅ XML       |[xmllint](https://megalinter.io/test-nuillam--git-eof/descriptors/xml_xmllint)                                       |    3|     |                                                                      0|0.0s        |
|✅ YAML      |[prettier](https://megalinter.io/test-nuillam--git-eof/descriptors/yaml_prettier)                                    |   80|    0|                                                                      0|2.4s        |
|✅ YAML      |[v8r](https://megalinter.io/test-nuillam--git-eof/descriptors/yaml_v8r)                                              |   22|     |                                                                      0|42.58s      |
|✅ YAML      |[yamllint](https://megalinter.io/test-nuillam--git-eof/descriptors/yaml_yamllint)                                    |   81|     |                                                                      0|1.35s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/3787796962)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
