### PR TITLE
Remove apk go requirement when possible

### LINKED ISSUE #2315: Why does shfmt require apk: go when a Docker install is used
I was analyzing megalinter's image sizes.
I observed that we install go (as the build system) from apk, which shouldn't be needed in production images since it's the packages needed to compile from source. Go binaries are static, single file, and can be easily compiled for (almost) all OSes. Installing Go from apk adds at least 384 MB in the usr/bin/lib/go folder (for the ci_light flavor)
Throughout many other questions that I'm going through to make sure that taking away go won't break anything, I want to ask:
 Why was there a comment/trace saying that shfmt required go, when we use it from a docker image?

### PR DESCRIPTION
**Pull request by echoix**
Fixes #2315 (continued optimization)

Installing go from apk is like installing gcc or build requirements. Removing this package install completely will at least remove at least 384 MB in the usr/bin/lib/go folder (for the ci_light flavor). Go programs are very portable, they are statically compiled and a file for the appropriate OS type and CPU arch will run without problems. Thus, if a Go linter binary is available, it is better to use it directly.

Furthermore, if when I checked at a linter, they had a published docker image of a single file, and it was kept up to date by some CI (so it won't get not updated later on), I changed the installation method to a pair of dockerfile "`FROM`" and "`COPY`" instructions. Building with this is way faster, especially with buildx that is now used, since these can be done in parallel. A further optimisation should be done by using a dockerfile frontend (adding `# syntax=docker/dockerfile:1` as the first line in the dockerfiles, starting with the `#` character) in order to use `COPY --link`. This would enable the buildkit to not invalidate the rest of the cache is this changes, and it could, if possible, rebase an image without pulling, pushing or building layers from the registry. See https://docs.docker.com/engine/reference/builder/#benefits-of-using---link. Adding that magic comment should be done in another PR later on. In the meantime, the new copy instructions that I added include the full file path on destination in order to make sure that there won't be overwriting problems when using `COPY --link`, since the destination handling has a little difference. I confirm by inspecting the images with dive that it is a file and not a folder on the destination.

## Proposed Changes

1. Remove apk go package from go descriptor, installing revive from Docker image by copying binary.
2. Install shellcheck from Docker image by copying binary.
3. Remove apk go package from action descriptor, installing actionlint Docker image by copying binary.
    - Shellcheck and pyflakes are dependencies of actionlint. 
    - pyflakes is installed by apk: py3-pyflakes
    - Shellcheck is installed by Docker image by copying binary. It is added again directly inside the action descriptor. Duplicating the from and COPY operations adds a 0B layer, and has no real impact, except for me making sure that any future use of the actionlint in a flavor will have the dependencies generated.
    - (Super-Linter installs it the same way as I figured out to do here)
4. Install checkmake from Docker image by copying binary.
    -  ```dockerfile
          # make is included in the mrtazz/checkmake:latest image 
          # (DIGEST:sha256:eb6919b20b22d1701a976856e4a224627df0a74b118246101fb6cf5c2e03049f)
          # It may not be a real dependency, like their pandoc mention in the README,
          # that is not included in the docker image they provide.
         ```
5. Remove apk go package from go descriptor:
    - install revive as a binary from a build stage (temporarly until the version returned is fixed https://github.com/mgechev/revive/issues/787 and that a `:latest` tag can be used https://github.com/mgechev/revive/pull/794 https://github.com/mgechev/revive/issues/786)
    - add apk go as an install requirement for golangci-lint
6. Remove apk go install for repository dustilock, installing dustilock by copying binary from a Docker build stage since no container image is published but supports it.
7. Use `COPY --link` when copying a single file in order to not invalidate caches (it adds them in a layer that is independent of the preceding, and can thus be kept the same if not changed). That implied adding a `# syntax=docker/dockerfile:1` at the first line of the Dockerfiles.
See a test image built to illustrate that duplicating from and copy --link isn't that bad.
![image](https://user-images.githubusercontent.com/27212526/216887759-26f29d08-cb44-4e5a-8072-bc7cf143453d.png)

To be continued, so it is not ready to merge yet, there are missing some linters with Go to change, like dustilock that doesn't include any prebuilt binaries.
## Readiness Checklist

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
There was a test failure in my fork with revive version. However, I don't see why it could fail, as the latest image, and my temporary tag that was pushed to the registry seems to give the same result: 
image

**Comment by nvuillam** [comment]
@echoix for some reason revive does not return a version, that's why it fails :/

image

**Comment by nvuillam** [comment]
About the rest of the PR... if you could use latest tags of docker images, it would prevent to have dozens of PRs at each version  upgrade, and let auto-upgrade-linters job do his nightly work with just a merge from us after ^^

**Comment by echoix** [comment]
> About the rest of the PR... if you could use latest tags of docker images, it would prevent to have dozens of PRs at each version upgrade, and let auto-upgrade-linters job do his nightly work with just a merge from us after ^^

How do you keep track of what tool version is in which MegaLinter release then, if it is only tagged "latest"? Doesn't it mean if you run docker build on the same Dockerfile at two different times apart (weeks) with the repo at the same commit we won't get the same image? (or start including a broken version without us checking it, or worse, start including a vulnerable version, ie: supply chain attacks) Isn't the dependabot there to help us allow when we want each linter to change version?

**Comment by nvuillam** [comment]
@echoix new versions arrive in beta :)

About vulnerable versions... we have [OX Security](https://www.ox.security/) itself :)

**Comment by nvuillam** [comment]
And about trace, auto-update-linters job (trigger at each new commit in main, + schduld daily) calls for the version during unit tests and store the result in a JSON, which itself is reused for documentation :)

**Comment by echoix** [comment]
I encountered something really strange when simply pulling the go flavour image. (Trying to understand why the revive call to version bugs)

`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /node-deps/node_modules/character-parser/LICENSE: invalid argument`
image

I never heard about that and, seems related to rootless docker (gitpod is running my environment in a container, on a shared machine). https://github.com/moby/moby/issues/43576 Did you ever see something like this?

**Comment by echoix** [comment]
> About vulnerable versions... we have [OX Security](https://www.ox.security/) itself :)
Where do we see that they monitor, or keep monitoring? Relying on someone else seems a little easy.

> And about trace, [auto-update-linters ](https://github.com/oxsecurity/megalinter/blob/main/.github/workflows/auto-update-linters.yml)job (trigger at each new commit in main, + schduled daily) calls for the version during unit tests and store the result in a [JSON](https://github.com/oxsecurity/megalinter/blob/main/.automation/generated/linter-versions.json), which itself is reused for documentation :)
So we document, but the code is not stateful?

**Comment by nvuillam** [comment]
@echoix there is a dashboard on ox.security, where I monitor all my repos (not only MegaLinter)

image

About that... @llaville please could you add 2FA auth to your Github account ? It would remove the last high severity issue found :)

The code is stateful within an official released version of MegaLinter, we don't call docker images while linting, we just use them when building then copy their executables within MegaLinter image

The safest way to use MegaLinter is indeed to use a released version, not the beta one (even if the beta one is also monitored)

**Comment by echoix** [comment]
The new beta image of a few minutes ago still jams, but not the released one (latest is still v6.19.0):
image

**Comment by nvuillam** [comment]
image

Latest beta image is ok

But since yesterday, [all images are built using docker-build-push action](https://github.com/oxsecurity/megalinter/pull/2342), so maybe something changed somewhere :/

**Comment by echoix** [comment]
image
Nope, main oxsecurity/megalinter:beta doesn't work while oxsecurity/megalinter:v6.19.0 does.

You are on a windows platform, so the UID stuff doesn't seem to affect.
Its a permission thing that we need to check in what files are included.  https://github.com/moby/moby/issues/43576#issuecomment-1135817093

**Comment by echoix** [comment]
> But since yesterday, [all images are built using docker-build-push action](https://github.com/oxsecurity/megalinter/pull/2342), so maybe something changed somewhere :/

I imagine it might have hidden something on our side.
Users that run CI using containers on shared machine might stumble on this I imagine.

**Comment by echoix** [comment]
Ok, lets file a real bug to look at this. Until we don't understand what it is, I consider it blocking the release. It's not normal.

**Comment by echoix** [comment]
## [🦙 MegaLinter](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2) status: ❌ [ERROR](https://github.com/echoix/megalinter/actions/runs/4159177112)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                              Errors                               |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/bash_bash_exec)                                  |    6|     |                                                                  0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/bash_shellcheck)                                |    6|     |                                                                  0|0.22s       |
|✅ BASH      |[shfmt](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/bash_shfmt)                                          |    6|    0|                                                                  0|0.06s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                 |3.79s       |
|❌ DOCKERFILE|[hadolint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/dockerfile_hadolint)                              |  105|     |[1](https://github.com/echoix/megalinter/actions/runs/4159177112)  |12.38s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                  0|2.53s       |
|✅ JSON      |[jsonlint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/json_jsonlint)                                    |   19|     |                                                                  0|0.33s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                 |0.92s       |
|✅ JSON      |[v8r](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/json_v8r)                                              |   21|     |                                                                  0|16.42s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/markdown_markdownlint)                        |  309|    2|[231](https://github.com/echoix/megalinter/actions/runs/4159177112)|7.67s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/markdown_markdown_link_check)          |  309|     |                                                                  0|6.91s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                  0|20.61s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/openapi_spectral)                                 |    1|     |                                                                  0|2.43s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/echoix/megalinter/actions/runs/4159177112) |2.82s       |
|✅ PYTHON    |[black](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_black)                                        |  176|    0|                                                                  0|4.69s       |
|✅ PYTHON    |[flake8](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_flake8)                                      |  176|     |                                                                  0|2.32s       |
|✅ PYTHON    |[isort](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_isort)                                        |  176|    0|                                                                  0|0.59s       |
|✅ PYTHON    |[mypy](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_mypy)                                          |  176|     |                                                                  0|10.26s      |
|✅ PYTHON    |[pylint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_pylint)                                      |  176|     |                                                                  0|15.5s       |
|⚠️ PYTHON    |[pyright](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/echoix/megalinter/actions/runs/4159177112)|23.75s      |
|❌ REPOSITORY|[checkov](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_checkov)                                |yes  |     |[14](https://github.com/echoix/megalinter/actions/runs/4159177112) |38.09s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/echoix/megalinter/actions/runs/4159177112) |1.74s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_dustilock)                            |yes  |     |no                                                                 |1.65s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_git_diff)                              |yes  |     |no                                                                 |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_secretlint)                          |yes  |     |no                                                                 |10.1s       |
|✅ REPOSITORY|[syft](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_syft)                                      |yes  |     |no                                                                 |1.33s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/repository_trivy)                                    |yes  |     |no                                                                 |24.37s      |
|❌ SPELL     |[cspell](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/spell_cspell)                                       |  729|     |[7](https://github.com/echoix/megalinter/actions/runs/4159177112)  |28.51s      |
|✅ SPELL     |[misspell](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/spell_misspell)                                   |  550|    2|                                                                  0|0.69s       |
|✅ XML       |[xmllint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/xml_xmllint)                                       |    3|    0|                                                                  0|0.04s       |
|✅ YAML      |[prettier](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/yaml_prettier)                                    |   81|    2|                                                                  0|3.44s       |
|✅ YAML      |[v8r](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/yaml_v8r)                                              |   23|     |                                                                  0|70.87s      |
|✅ YAML      |[yamllint](https://megalinter.io/da4808b48e1c2290d929b12c97e3790c58b150a2/descriptors/yaml_yamllint)                                    |   82|     |                                                                  0|1.66s       |

See detailed report in [MegaLinter reports](https://github.com/echoix/megalinter/actions/runs/4159177112)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
## [🦙 MegaLinter](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6) status: ❌ [ERROR](https://github.com/echoix/megalinter/actions/runs/4159695327)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                              Errors                               |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/bash_bash_exec)                                  |    6|     |                                                                  0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/bash_shellcheck)                                |    6|     |                                                                  0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/bash_shfmt)                                          |    6|    0|                                                                  0|0.38s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                 |2.5s        |
|❌ DOCKERFILE|[hadolint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/dockerfile_hadolint)                              |  105|     |[1](https://github.com/echoix/megalinter/actions/runs/4159695327)  |8.26s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                  0|2.02s       |
|✅ JSON      |[jsonlint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/json_jsonlint)                                    |   19|     |                                                                  0|0.26s       |
|✅ JSON      |[v8r](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/json_v8r)                                              |   21|     |                                                                  0|11.6s       |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/markdown_markdownlint)                        |  309|    0|[231](https://github.com/echoix/megalinter/actions/runs/4159695327)|6.37s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/markdown_markdown_link_check)          |  309|     |                                                                  0|4.92s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                  0|14.12s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/openapi_spectral)                                 |    1|     |                                                                  0|1.61s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_bandit)                                      |  177|     |[45](https://github.com/echoix/megalinter/actions/runs/4159695327) |1.97s       |
|✅ PYTHON    |[black](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_black)                                        |  177|    0|                                                                  0|4.38s       |
|✅ PYTHON    |[flake8](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_flake8)                                      |  177|     |                                                                  0|1.76s       |
|✅ PYTHON    |[isort](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_isort)                                        |  177|    0|                                                                  0|0.75s       |
|✅ PYTHON    |[mypy](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_mypy)                                          |  177|     |                                                                  0|6.42s       |
|✅ PYTHON    |[pylint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_pylint)                                      |  177|     |                                                                  0|10.25s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/python_pyright)                                    |  177|     |[245](https://github.com/echoix/megalinter/actions/runs/4159695327)|15.37s      |
|❌ REPOSITORY|[checkov](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/repository_checkov)                                |yes  |     |[14](https://github.com/echoix/megalinter/actions/runs/4159695327) |25.89s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/repository_git_diff)                              |yes  |     |no                                                                 |0.38s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/repository_secretlint)                          |yes  |     |no                                                                 |11.91s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/repository_trivy)                                    |yes  |     |no                                                                 |22.12s      |
|❌ SPELL     |[cspell](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/spell_cspell)                                       |  730|     |[13](https://github.com/echoix/megalinter/actions/runs/4159695327) |17.32s      |
|✅ SPELL     |[misspell](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/spell_misspell)                                   |  551|    0|                                                                  0|0.84s       |
|✅ XML       |[xmllint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/xml_xmllint)                                       |    3|    0|                                                                  0|0.41s       |
|✅ YAML      |[prettier](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/yaml_prettier)                                    |   81|    1|                                                                  0|2.8s        |
|✅ YAML      |[v8r](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/yaml_v8r)                                              |   23|     |                                                                  0|56.05s      |
|✅ YAML      |[yamllint](https://megalinter.io/6f9080ac2fe2e43a4cd8d7d5c44d2d95c3b459a6/descriptors/yaml_yamllint)                                    |   82|     |                                                                  0|1.12s       |

See detailed report in [MegaLinter reports](https://github.com/echoix/megalinter/actions/runs/4159695327)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
So theres a test failure with golangci-lint. I wasn't exactly sure if it was safe to remove the GOROOT and GOPATH env since there wasn't go anymore, but it seems that it might need it still. Especially once I read the related issue mentionned in their Dockerfile
https://github.com/golangci/golangci-lint/blob/dd45e44838ed636965c9d2fd1b1abb78f3b7cca9/build/alpine.Dockerfile#L17-L27

And maybe that linter would still need go installed, even if it comes with binaries. To be continued...

**Comment by echoix** [comment]
If this passes, it should be ready to merge. For now, golangci-lint really needs go installed, so it must be present. I added it in the apk install key for that linter only.

I tested locally with the following commands (used a filter here since the tests are wayyyyyy too long to run.
```shell
docker buildx build --pull --rm -f "flavors/go/Dockerfile" -t megalinter-go:test-echoix .
```
```shell
TEST_KEYWORDS_TO_USE="go_golangci_lint"
docker run -e TEST_CASE_RUN=true -e OUTPUT_DETAIL=detailed -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="." -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v $(pwd):/tmp/lint megalinter-go:test-echoix
```
and 
```shell
TEST_KEYWORDS_TO_USE="go"
docker run -e TEST_CASE_RUN=true -e OUTPUT_DETAIL=detailed -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="." -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v $(pwd):/tmp/lint megalinter-go:test-echoix
```

**Comment by echoix** [comment]
@nvuillam I think it is done!

**Comment by echoix** [comment]
There are some changes in the build.py that were required for hadolint

**Review by nvuillam — APPROVED** [review]
Great :)
Let's see how it decreases the docker mage sizes ^^

**Comment by echoix** [comment]
It's sad that golangci-lint really needs go. Without it, it would be even smaller, since it was only really removed for flavors: documentation, dotnet, java, javascript, php, python, ruby, rust, salesforce, security, swift, terraform. Oh, finally it might not be as bad...

**Comment by bdovaz** [comment]
@echoix I am a little concerned that you have changed the installation of several linters to be through the docker image. Have you checked if with that change we lose compatibility in #2273? The fact of installing them in through bash scripts gives that possibility in most cases but installing through docker images not because not all publish the version in arm64, most are in amd64 only....

**Comment by echoix** [comment]
My rationale was to have the current state working as best as it could, and that linter specific overrides can be added when it will be a blocker for arm64 images.
What I made sure before changing them to a Docker image was that their repos had their docker images CI-released so they are published at the same time.

The linters changed that way were written in Go, so they can be compiled to arm64 super easily.
If ever a PR to the linter's repo to add these won't be merged in time, we could add an override with the following install (like dustilock or revive):

```yaml
    install:
      dockerfile:
          # The golang image used as a builder is a temporary workaround 
        - |
          FROM golang:alpine as revive
          RUN GOBIN=/usr/bin go install github.com/mgechev/revive@latest
        - COPY --link --from=revive /usr/bin/revive /usr/bin/revive
```


actionlint is released with platforms linux/amd64,linux/arm64
shellcheck is released with platforms linux/amd64,linux/arm/v6,linux/arm64
checkmake is released with platforms linux/amd64 -> so are the github releases, unofficial docker images exist, but we could go without it.

These are the only ones which the installation method "changed".
For dustilock, it was build in a RUN command, it is still built, but is now built in a stage then copied (that repo is not in good shape/active, but they have a dockerfile and showed how it could be done).
For revive, it was build in a RUN command, it is still built, but is now built in a stage then copied.

Thats pretty much it.

**Pull request merged**
