### PR TITLE
PHP PHIVE: Use keys.openpgp.org and fingerprint for phive key verification

### PR DESCRIPTION
**Pull request by echoix**
Matches the current PHIVE installation instructions

Should fix transient php installation failures 

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by nvuillam — CHANGES_REQUESTED** [review]
The only update in this PR is the changelog file ^^

**Comment by echoix** [comment]
I didn't find another place that had the phive installation text, so I thought it was the Dockerfile the ground truth. Seems it got overwritten while building. You can check the first commit. Where should it be changed? (I also changed the order of the servers to the main one, next the other live, and the slowest at the end. Removed the dead one.)

**Comment by nvuillam** [comment]
@echoix it's here :) https://github.com/oxsecurity/megalinter/blob/61557e30a73db90f3329f7f9f3732d66271c16ab/megalinter/descriptors/php.megalinter-descriptor.yml#L23

**Review by nvuillam — APPROVED** [review]

**Pull request merged**
