### PR TITLE
Remove additional `--update` for apk in Dockerfile

### PR DESCRIPTION
**Pull request by PeterDaveHello**
There is no need to use `--update` with `--no-cache` when using `apk` on Alpine Linux, as using `--no-cache` will fetch the index every time and leave no local cache, so the index will always be the latest without temporary files remain in the image.

## Proposed Changes

- Remove `--no-cache` for `apk add`

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by sanmai-NL** [comment]
@nvuillam ping

**Comment by nvuillam** [comment]
@PeterDaveHello @sanmai-NL Dockerfiles are automatically generated by build.py
So to remove the way apk is called , it must be updated there :)

https://megalinter.io/latest/contributing/#without-write-access

**Comment by PeterDaveHello** [comment]
Thanks @nvuillam, PR updated!

**Comment by sanmai-NL** [comment]
I think there's a better solution, for repeated build runs and for the chance that `apk add` is run more than once.

https://docs.docker.com/build/cache/#use-the-dedicated-run-cache

**Comment by PeterDaveHello** [comment]
Not sure why I should do here 👀

**Comment by bdovaz** [comment]
cc @nvuillam

**Comment by nvuillam** [comment]
let's go :)

**Pull request merged**
