### PR TITLE
Use pipenv instead of pip to install python packages

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: ❌ [**ERROR**](https://github.com/oxsecurity/megalinter/actions/runs/3010786213)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                  |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.02s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.26s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                         0|0.21s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.73s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  104|     |                                                                         0|7.89s       |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|1.95s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   18|     |                                                                         0|0.2s        |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   20|     |                                                                         0|11.43s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  282|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3010786213) |4.71s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  282|     |                                                                         0|4.54s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  282|    0|                                                                         0|5.91s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.77s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  168|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3010786213)|2.17s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  168|    0|                                                                         0|3.52s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  168|     |                                                                         0|1.95s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  168|    0|                                                                         0|0.48s       |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  168|     |                                                                         0|85.18s      |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  168|     |                                                                         0|14.38s      |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                        |12.09s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.52s       |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |14.61s      |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |25.06s      |
|❌ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  689|     |[**8**](https://github.com/oxsecurity/megalinter/actions/runs/3010786213) |17.74s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  519|    0|                                                                         0|0.6s        |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.0s        |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   79|    0|                                                                         0|2.55s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                         0|26.25s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   80|     |                                                                         0|1.19s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3010786213)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Review by Kurt-von-Laven — COMMENTED** [review]
Fair warning that we switched from [Pipenv](https://pipenv.pypa.io/) to [Poetry](https://python-poetry.org/) last year because the former did not reliably function at its central task of dependency resolution when we experimented with it last year. Hopefully, Pipenv has improved since then. In my opinion, the main benefit of each relative to pip is their ability to lock transitive dependencies.

**Comment by nvuillam** [comment]
@Kurt-von-Laven  The situation today is that there are incompatible dependencies between different python pacckages

pipenv seems to tell that it is automatically able to solve them.... do you confirm ?

**Comment by nvuillam** [comment]
It already happened in the past and I solved that by analyzing all dependencies and force the downgrade of some versions... but I'm kind of bored to do that each time it happens, and also bored to have to downgrade versions :D 

See here -> https://github.com/oxsecurity/megalinter/runs/8236730182?check_suite_focus=true

**Comment by nvuillam** [comment]
It still seems quite complicated....

The neighbours of super-linter create a venv for each python based linter, then add /bin folder in the $PATH ... do you think it's a good idea @Kurt-von-Laven ?

**Comment by Kurt-von-Laven** [comment]
In theory dependency resolution should be one of Pipenv's central features as a package manager. When we tested it at version 2021.5.29, we ran into situations where pip could install packages, such as prospector, that Pipenv could not because of issues with dependency resolution. Hopefully those issues have since been addressed. I agree that MegaLinter (and really most everyone) shouldn't be using pip, although my understanding of Pipenv's current dependency resolution strategy is that [it simply calls pip for this purpose](https://github.com/pypa/pipenv/issues/4724#issuecomment-998821293). We have also found that fewer tools work with Pipenv than with Poetry (e.g., [asdf](https://github.com/asdf-vm/asdf-plugins/blob/87382a01ba88df8594863aee7864d91446a723dc/README.md#plugin-list)).

The Python community loves virtual environments, and I think it's reasonable to go with the flow there. It may be a bit cleaner to run [`pipenv shell`](https://pipenv.pypa.io/en/latest/#other-commands) (or [`poetry shell`](https://python-poetry.org/docs/cli/#shell)) followed eventually by `exit` in lieu of directly manipulating the path.

**Comment by nvuillam** [comment]
Ok I'll go for venvs so , thanks for the support:)

**Comment by Kurt-von-Laven** [comment]
My pleasure. My other two cents are that we have found lock files overall decrease our maintenance burden on other projects, because whenever there are dependency-related issues, we at least have the reassurance of knowing precisely which transitive closure was used and that it doesn't vary across development environments at a given version.

**Pull request closed without merging**
