### PR TITLE
Update descriptors for authenticating Github API calls

### PR DESCRIPTION
**Pull request by bdovaz**
Partly solves #2256

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4038370711)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.44s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.41s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.15s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|10.53s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.48s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.29s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|15.96s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    0|[229](https://github.com/oxsecurity/megalinter/actions/runs/4038370711)|7.26s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.54s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|18.02s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.94s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4038370711) |2.79s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|5.15s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|2.36s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.99s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|8.68s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|15.55s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[282](https://github.com/oxsecurity/megalinter/actions/runs/4038370711)|21.13s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |31.88s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.4s        |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.26s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |29.1s       |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|26.07s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|1.0s        |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.4s        |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.94s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|64.07s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.62s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4038370711)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Review by nvuillam — APPROVED** [review]
Once CI passes, this PR will be life-saving for concurrent builds :)

**Comment by nvuillam** [comment]
`cat: can't open '/run/secrets/GITHUB_TOKEN': No such file or directory`

ooooops

**Comment by nvuillam** [comment]
image

At super-linter they do that in their Dockerfile

`ARG GITHUB_TOKEN` in Dockerfile

Add `--mount=type=secret,id=GITHUB_TOKEN` at the beginning of a RUN instruction

Do you want to try, or do you prefer I try on your branch ?

**Comment by bdovaz** [comment]
@nvuillam more info: https://github.com/docker/build-push-action/issues/754

If you can give me a hand better because I have to leave soon and I won't be able to do anything until tomorrow.

**Comment by nvuillam** [comment]
Sure, I'll try to fix that :)

Have a good afternoon:)

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4151212408)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.15s       |
|✅ BASH      |[shfmt](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.03s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.94s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.69s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.78s       |
|✅ JSON      |[jsonlint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.26s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.63s       |
|✅ JSON      |[v8r](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.12s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/markdown_markdownlint)                        |  309|    0|[231](https://github.com/oxsecurity/megalinter/actions/runs/4151212408)|6.02s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.28s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|16.75s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.64s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4151212408) |2.14s       |
|✅ PYTHON    |[black](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_black)                                        |  176|    0|                                                                      0|3.2s        |
|✅ PYTHON    |[flake8](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.71s       |
|✅ PYTHON    |[isort](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.47s       |
|✅ PYTHON    |[mypy](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.0s        |
|✅ PYTHON    |[pylint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.27s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4151212408)|17.37s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_checkov)                                |yes  |     |no                                                                     |27.79s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4151212408) |1.24s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.31s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.03s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.44s       |
|✅ REPOSITORY|[syft](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.96s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |20.41s      |
|✅ SPELL     |[cspell](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/spell_cspell)                                       |  729|     |                                                                      0|17.5s       |
|✅ SPELL     |[misspell](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/spell_misspell)                                   |  550|    0|                                                                      0|0.54s       |
|✅ XML       |[xmllint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.02s       |
|✅ YAML      |[prettier](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.51s       |
|✅ YAML      |[v8r](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|58.91s      |
|✅ YAML      |[yamllint](https://megalinter.io/acd4d2cd4101e791ef33215bfb4b2db9f998f714/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.13s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4151212408)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
