### PR TITLE
New article in French

### PR DESCRIPTION
**Pull request by nvuillam**
[MegaLinter: un linter pour les gouverner tous](https://blog.wescale.fr/megalinter-un-linter-pour-les-gouverner-tous) (FR), by [Guillaume Arnaud](https://www.linkedin.com/in/guillaume-arnaud/) from [WeScale](https://www.wescale.fr/)

Fixes https://github.com/oxsecurity/megalinter/issues/3829

### CODE REVIEW

**Comment by echoix** [comment]
Just run the build command again, there was a commit between pulling and the small time between commit and push

**Comment by nvuillam** [comment]
It can be done later after merge by the autoupdate ^^

**Comment by nvuillam** [comment]
It seems we have many trivy errors... I don't know where the docker one can be from, we might wait for new updates from linter authors to validate :(

**Pull request merged**
