### PR TITLE
Bump Docker base image from python3.9.7-alpine3.13 to python3.10.5-alpine3.16

### LINKED ISSUE #1406: Vulnerabilities in python:3.9.7-alpine3.13 base image
Hey all, loving the tool. Just wanted to bring some security vulnerabilities snyk.io found in the python:3.9.7-alpine3.13 base image.

There are 8 vulnerabilities listed as `critical` coming from the `expat` package in the alpine:3.13 image.

https://snyk.io/vuln/alpine%3A3.13%3Aexpat

Critical Vulnerabilities Found

- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342171
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342172
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2342173
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2406625
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2406626
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407739
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407752
- https://security.snyk.io/vuln/SNYK-ALPINE313-EXPAT-2407757

This was found on the python flavor, but I believe this applies to all flavors.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Upgrade base Docker image.

Fixes #1406, and maybe this will help with #1446 as well.

## Proposed Changes

1. Upgrade Docker base image from Python 3.9 to Python 3.10.

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2547238449)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.03s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.23s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.26s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |2.37s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.59s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.24s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.81s       |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.25s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|2.37s       |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.75s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|19.74s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  255|    1|                                                                         0|4.79s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  255|     |                                                                         0|4.43s       |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  255|    1|                                                                         0|4.44s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.03s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  150|     |[**65**](https://github.com/megalinter/megalinter/actions/runs/2547238449)|1.92s       |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  150|    0|                                                                         0|2.96s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.08s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  150|    0|                                                                         0|0.56s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  150|     |                                                                         0|101.62s     |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  150|     |                                                                         0|14.89s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  534|     |                                                                         0|14.54s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  378|    1|                                                                         0|0.57s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.01s       |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|2.6s        |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|30.37s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.25s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2547238449)

**Comment by Kurt-von-Laven** [comment]
@nvuillam, surprisingly, the Docker build step failed but was marked successful, resulting of course in the image not being found in the subsequent step.

**Comment by nvuillam** [comment]
I think it's an old issue of the ci job , that should be fixed someday indeed...

**Comment by nvuillam** [comment]
Managed in v6 :)

**Pull request closed without merging**
