### PR TITLE
Fix broken link to documentation when using v6

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/oxsecurity/megalinter/issues/1819

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3028193490)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                  |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.05s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.29s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                         0|0.31s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.73s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  104|     |                                                                         0|7.02s       |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.01s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   18|     |                                                                         0|0.2s        |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   20|     |                                                                         0|11.43s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  282|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3028193490) |4.75s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  282|     |                                                                         0|4.31s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  282|    0|                                                                         0|6.08s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.76s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  168|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3028193490)|3.6s        |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  168|    0|                                                                         0|3.66s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  168|     |                                                                         0|1.86s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  168|    0|                                                                         0|0.57s       |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  168|     |                                                                         0|13.85s      |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  168|     |                                                                         0|9.8s        |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                        |12.86s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.33s       |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |7.03s       |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |20.48s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  689|     |                                                                         0|17.65s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  519|    0|                                                                         0|0.71s       |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.0s        |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   79|    0|                                                                         0|2.58s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                         0|32.2s       |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   80|     |                                                                         0|1.24s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3028193490)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
I had a quick look at this last weekend since I had an error too that wasn't redirected well, and I think the real solution and problem lies in the deployment of the docs with Mike. It seems the steps are inefficient (copying to latest and also version, without the good canonical url when the versions change). This may also be an SEO problem. If you could take a new look at the deployment steps/instructions with Mike, I don't think deleting and recreating is the direct way. With using aliases, it might be the correct way, in a way that the "real" content is in the versionned folder, these indicate that the real page for the search engine might be for the latest, and the latest or any any other folder is a symlink (not duplicated) to the real content. 
Especially, look at using the -u (update aliases) command. Aliases could be for latest, v6 and 6, so older urls could be redirected correctly for existing versions.

**Comment by nvuillam** [comment]
I struggled for hours to solve the mike versioning deployment... I'm afraid to go back in that :D 
But if you want to try, please be my guest :)

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3028193487)

|     Descriptor     |                                                                 Linter                                                                 |Files|Fixed|                                  Errors                                  |Elapsed time|
|--------------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.02s       |
|✅ BASH             |[shellcheck](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.36s       |
|✅ BASH             |[shfmt](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/bash_shfmt)                                          |    7|    0|                                                                         0|0.05s       |
|✅ COPYPASTE        |[jscpd](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |2.32s       |
|✅ DOCKERFILE       |[hadolint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/dockerfile_hadolint)                              |  104|     |                                                                         0|9.77s       |
|✅ JSON             |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.4s        |
|✅ JSON             |[jsonlint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/json_jsonlint)                                    |   18|     |                                                                         0|0.32s       |
|✅ JSON             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/json_v8r)                                              |   20|     |                                                                         0|11.36s      |
|:warning: MARKDOWN  |[markdownlint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/markdown_markdownlint)                        |  282|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3028193487) |5.78s       |
|✅ MARKDOWN         |[markdown-link-check](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/markdown_markdown_link_check)          |  282|     |                                                                         0|5.99s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/markdown_markdown_table_formatter)|  282|    0|                                                                         0|7.84s       |
|✅ OPENAPI          |[spectral](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|1.69s       |
|:warning: PYTHON    |[bandit](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/python_bandit)                                      |  168|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3028193487)|2.93s       |
|✅ PYTHON           |[black](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/python_black)                                        |  168|    0|                                                                         0|3.84s       |
|✅ PYTHON           |[flake8](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/python_flake8)                                      |  168|     |                                                                         0|3.14s       |
|✅ PYTHON           |[isort](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/python_isort)                                        |  168|    0|                                                                         0|0.37s       |
|✅ PYTHON           |[mypy](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/python_mypy)                                          |  168|     |                                                                         0|17.38s      |
|✅ PYTHON           |[pylint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/python_pylint)                                      |  168|     |                                                                         0|13.3s       |
|✅ REPOSITORY       |[checkov](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_checkov)                                |yes  |     |no                                                                        |16.32s      |
|:warning: REPOSITORY|[devskim](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_devskim)                                |yes  |     |[**61**](https://github.com/oxsecurity/megalinter/actions/runs/3028193487)|1.41s       |
|✅ REPOSITORY       |[dustilock](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_dustilock)                            |yes  |     |no                                                                        |2.09s       |
|✅ REPOSITORY       |[git_diff](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.03s       |
|✅ REPOSITORY       |[secretlint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |4.56s       |
|✅ REPOSITORY       |[syft](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_syft)                                      |yes  |     |no                                                                        |2.09s       |
|✅ REPOSITORY       |[trivy](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |20.92s      |
|✅ SPELL            |[cspell](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/spell_cspell)                                       |  689|     |                                                                         0|21.57s      |
|✅ SPELL            |[misspell](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/spell_misspell)                                   |  519|    0|                                                                         0|0.53s       |
|✅ XML              |[xmllint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.01s       |
|✅ YAML             |[prettier](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/yaml_prettier)                                    |   79|    0|                                                                         0|2.94s       |
|✅ YAML             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/yaml_v8r)                                              |   22|     |                                                                         0|38.56s      |
|✅ YAML             |[yamllint](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/descriptors/yaml_yamllint)                                    |   80|     |                                                                         0|1.5s        |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3028193487)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**oxsecurity/megalinter/flavors/python@v5**](https://oxsecurity.github.io/megalinter/test-nuillam-fix-6-url/flavors/python/) (55 linters)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
