### PR TITLE
Replace babel-eslint with @babel/eslint-parser

### LINKED ISSUE #2444: Replace babel-eslint with @babel/eslint-parser
**Is your feature request related to a problem? Please describe.**
Investigating the npm building logs, I saw that babel-eslint was deprecated three years ago when they changed to a mono repo. 

```
#58 53.11 npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
```

**Describe the solution you'd like**

Change to https://www.npmjs.com/package/@babel/eslint-parser?activeTab=readme, and possibly other babel packages, fixing breaking changes due to the 30 versions released between the previous package used.

**Describe alternatives you've considered**
--

**Additional context**

### PR DESCRIPTION
**Pull request by bdovaz**
Fixes #2444

### CODE REVIEW

**Comment by bdovaz** [comment]
@echoix how to run `/build`? I saw you this comment: https://github.com/oxsecurity/megalinter/pull/2406#issuecomment-1450874172

But it doesn't work for me, it doesn't do anything. Do I have to do something different?

I have not launched in my build.sh branch on purpose to test this new flow.

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4362172897)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.27s       |
|✅ BASH      |[shfmt](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.34s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.8s        |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|17.35s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.97s       |
|✅ JSON      |[jsonlint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.19s       |
|✅ JSON      |[v8r](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.59s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/markdown_markdownlint)                        |  309|    3|[230](https://github.com/oxsecurity/megalinter/actions/runs/4362172897)|6.63s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.69s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/markdown_markdown_table_formatter)|  309|    3|                                                                      0|19.11s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.38s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4362172897) |1.97s       |
|✅ PYTHON    |[black](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_black)                                        |  183|    0|                                                                      0|4.5s        |
|✅ PYTHON    |[flake8](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.75s       |
|✅ PYTHON    |[isort](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.65s       |
|✅ PYTHON    |[mypy](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_mypy)                                          |  183|     |                                                                      0|6.9s        |
|✅ PYTHON    |[pylint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_pylint)                                      |  183|     |                                                                      0|11.59s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/python_pyright)                                    |  183|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4362172897)|15.79s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/repository_checkov)                                |yes  |     |no                                                                     |29.41s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.33s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |14.19s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |29.92s      |
|❌ SPELL     |[cspell](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/spell_cspell)                                       |  745|     |[1](https://github.com/oxsecurity/megalinter/actions/runs/4362172897)  |20.59s      |
|✅ SPELL     |[misspell](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/spell_misspell)                                   |  566|    0|                                                                      0|0.9s        |
|✅ XML       |[xmllint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.28s       |
|✅ YAML      |[prettier](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.82s       |
|✅ YAML      |[v8r](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|52.33s      |
|✅ YAML      |[yamllint](https://megalinter.io/7411316caa2897b3839af1834e5fd8ebd5b7b81e/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.03s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4362172897)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@echoix but there is one thing I don't quite understand.

I thought that command was to create an additional commit with the `build.sh` changes **in my branch** and not in the `main` branch.

Because for example in my PR that only affects descriptors, the checks only make sense to be executed if I run `build.sh` by hand before and commit the changes in my branch so that it modifies the `Dockerfile` files.

image

cc @nvuillam @Kurt-von-Laven

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4362240831)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.14s       |
|✅ BASH      |[shfmt](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.42s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|16.74s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.9s        |
|✅ JSON      |[jsonlint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.19s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.85s       |
|✅ JSON      |[v8r](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.74s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/markdown_markdownlint)                        |  309|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4362240831)|6.45s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|6.12s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|20.54s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.61s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4362240831) |2.3s        |
|✅ PYTHON    |[black](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_black)                                        |  183|    0|                                                                      0|3.63s       |
|✅ PYTHON    |[flake8](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.99s       |
|✅ PYTHON    |[isort](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.51s       |
|✅ PYTHON    |[mypy](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_mypy)                                          |  183|     |                                                                      0|8.14s       |
|✅ PYTHON    |[pylint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_pylint)                                      |  183|     |                                                                      0|12.83s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/python_pyright)                                    |  183|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4362240831)|17.49s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_checkov)                                |yes  |     |no                                                                     |33.57s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4362240831) |1.43s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.26s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.89s       |
|✅ REPOSITORY|[syft](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.25s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.85s      |
|✅ SPELL     |[cspell](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/spell_cspell)                                       |  745|     |                                                                      0|22.39s      |
|✅ SPELL     |[misspell](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/spell_misspell)                                   |  566|    2|                                                                      0|0.65s       |
|✅ XML       |[xmllint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.04s       |
|✅ YAML      |[prettier](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.82s       |
|✅ YAML      |[v8r](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|61.09s      |
|✅ YAML      |[yamllint](https://megalinter.io/f5ca4992a4443600c382b6cbef4dc436b95dc68e/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.39s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4362240831)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
> @echoix but there is one thing I don't quite understand.
> 
> 
> 
> I thought that command was to create an additional commit with the `build.sh` changes **in my branch** and not in the `main` branch.
> 
> 
> 
> Because for example in my PR that only affects descriptors, the checks only make sense to be executed if I run `build.sh` by hand before and commit the changes in my branch so that it modifies the `Dockerfile` files.
> 
> 
> 
> image
> 
> 


@Bdovaz I know, I need another PR to use the correct branch for actions/checkout. In the meantime, add ref=branchname to the command. And in a PR, it can also be something like the branch name that starts with refs/... and has /pull/(pr number) but I don't remember the exact format. 

And for the time it takes to start executing, if there's no runner left to start it, it can't start yet.

**Pull request merged**
