### PR TITLE
Fix npm permissions in v6.20.0 #2434

### LINKED ISSUE #2348: Beta (2023-02-11container images errors when pulling
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by echoix**
- Fixes [Container images errors when pulling](https://github.com/oxsecurity/megalinter/issues/2348), by @echoix 
- Fixes [Pre npm install not resolving](https://github.com/oxsecurity/megalinter/issues/2428), by @echoix
- Add build date in Beta docker images, by @nvuillam

## Proposed Changes

1. Disable temporarily stylelint-config-sass-guidelines (see https://github.com/bjankord/stylelint-config-sass-guidelines/issues/273)
2. Remove `--force` flag of `npm install`

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4350658024)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.14s       |
|✅ BASH      |[shfmt](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.38s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.63s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|14.77s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.03s       |
|✅ JSON      |[jsonlint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.24s       |
|✅ JSON      |[v8r](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.03s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/markdown_markdownlint)                        |  309|    0|[230](https://github.com/oxsecurity/megalinter/actions/runs/4350658024)|5.77s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.04s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|15.01s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.37s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4350658024) |2.09s       |
|✅ PYTHON    |[black](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_black)                                        |  183|    0|                                                                      0|3.7s        |
|✅ PYTHON    |[flake8](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.8s        |
|✅ PYTHON    |[isort](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.76s       |
|✅ PYTHON    |[mypy](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_mypy)                                          |  183|     |                                                                      0|6.24s       |
|✅ PYTHON    |[pylint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_pylint)                                      |  183|     |                                                                      0|10.31s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/python_pyright)                                    |  183|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4350658024)|14.54s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.96s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.4s        |
|✅ REPOSITORY|[secretlint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |11.39s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |25.48s      |
|✅ SPELL     |[cspell](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/spell_cspell)                                       |  745|     |                                                                      0|18.43s      |
|✅ SPELL     |[misspell](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/spell_misspell)                                   |  566|    0|                                                                      0|0.91s       |
|✅ XML       |[xmllint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.4s        |
|✅ YAML      |[prettier](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.88s       |
|✅ YAML      |[v8r](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|58.18s      |
|✅ YAML      |[yamllint](https://megalinter.io/aa69ff0d2d7f328b0e7918b004c340e562bb29c7/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.1s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4350658024)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
@Kurt-von-Laven If you'd like to test out the image when it'll be on the registry, it could be helpful. It's really late and it'll have to go to tomorrow for me.

**Comment by echoix** [comment]
Ok, so this iteration doesn't seem to fix as Slim.ai can't pull the image. I'd like to see at what layer it crashes though (I'm on my cellphone)

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4351013639)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.16s       |
|✅ BASH      |[shfmt](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.27s       |
|❌ DOCKERFILE|[hadolint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/dockerfile_hadolint)                              |  114|     |[1](https://github.com/oxsecurity/megalinter/actions/runs/4351013639)  |18.32s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.35s       |
|✅ JSON      |[jsonlint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.23s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.81s       |
|✅ JSON      |[v8r](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/json_v8r)                                              |   21|     |                                                                      0|14.44s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/markdown_markdownlint)                        |  309|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4351013639)|6.98s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|6.6s        |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|22.06s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.76s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4351013639) |2.59s       |
|✅ PYTHON    |[black](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_black)                                        |  183|    0|                                                                      0|4.31s       |
|❌ PYTHON    |[flake8](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_flake8)                                      |  183|     |[1](https://github.com/oxsecurity/megalinter/actions/runs/4351013639)  |2.23s       |
|✅ PYTHON    |[isort](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.55s       |
|✅ PYTHON    |[mypy](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_mypy)                                          |  183|     |                                                                      0|8.72s       |
|✅ PYTHON    |[pylint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_pylint)                                      |  183|     |                                                                      0|13.48s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/python_pyright)                                    |  183|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4351013639)|19.87s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_checkov)                                |yes  |     |no                                                                     |36.59s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4351013639) |1.52s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.13s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |10.82s      |
|✅ REPOSITORY|[syft](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_syft)                                      |yes  |     |no                                                                     |2.35s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |26.07s      |
|✅ SPELL     |[cspell](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/spell_cspell)                                       |  745|     |                                                                      0|23.86s      |
|✅ SPELL     |[misspell](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/spell_misspell)                                   |  566|    2|                                                                      0|0.63s       |
|✅ XML       |[xmllint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.09s       |
|✅ YAML      |[v8r](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|65.93s      |
|✅ YAML      |[yamllint](https://megalinter.io/69e9bd8c63eef83b02e206c8e1a44fcd79b52596/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.37s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4351013639)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
@echoix great research !
It seems it could fix #2428 and #2348 ... is the PR mergeable after removing npm doctor ?

**Comment by echoix** [comment]
Since I had to finally add the chown, as only removing one package was enough, would you like to keep it like this or re-add the broken dependency in the css descriptor?

You can remove the second `npm doctor` (after the chown) to have it build, and one of us can do a quick check. The easiest is if Slim.ai is able to pull the image and give complete insights, the pull issue is probably not there.
That would help release faster today at your time rather than waiting for the end of my day

**Comment by echoix** [comment]
This image seems ok since it didn't fail

image
image

**Comment by nvuillam** [comment]
@echoix I'm ok with removing this obscure stylelint dependency, I'll generate a beta, quickly test and release tonight
What can't I remove both npm doctor ?

**Comment by echoix** [comment]
The last image of this beach seems ok : 
image
image
image
image
image

**Review by nvuillam — APPROVED** [review]
That's what I call a rescue, thanks again for all stuck users @echoix :)
I release 6.20.1 tonight :)

**Comment by Kurt-von-Laven** [comment]
I just pulled and ran oxsecurity/megalinter-javascript:beta without issues. Big thank you to both of you!

**Comment by nvuillam** [comment]
Release of 6.20.1 in progress, available in minutes :)

**Pull request merged**
