### PR TITLE
Fix swiftlint error that is unable to find lintable swift files

### LINKED ISSUE #440: Linting swift code does not work. Error: No lintable files found at paths: '/tmp/lint'
**Describe the bug**

Linting swift code does not work. The error appears:
```
...
Status: Downloaded newer image for norionomura/swiftlint:latest
The `swiftlint autocorrect` command is no longer available.
Please use `swiftlint --fix` instead.
Error: No lintable files found at paths: '/tmp/lint'
Correcting Swift files at paths /tmp/lint
```

**To Reproduce**

1. Follow the quick start CLI to add mega-linter to the iOS Swift project
2. Accept default values (except one case where you choose that it's a Swift project)
3. Push to the repo, create a PR to trigger the GitHub Action
4. See swift-lint error (not related to the codebase)

**Expected behavior**

- `swift-lint` starts linting the code base.

**Screenshots**

Screenshot 2021-04-29 at 13 26 35

- Contents of `ERROR-SWIFT_SWIFTLINT.log`
```
Results of swiftlint linter (version 0.43.1)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/swift_swiftlint/
-----------------------------------------------

❌ [ERROR] for workspace /github/workspace
Linter raw log:
Unable to find image 'norionomura/swiftlint:latest' locally
latest: Pulling from norionomura/swiftlint
34667c7e4631: Pulling fs layer
d18d76a881a4: Pulling fs layer
119c7358fbfc: Pulling fs layer
2aaf13f3eff0: Pulling fs layer
969975223755: Pulling fs layer
1ea85296b57d: Pulling fs layer
178f29677290: Pulling fs layer
5f015d65fccd: Pulling fs layer
2aaf13f3eff0: Waiting
969975223755: Waiting
1ea85296b57d: Waiting
178f29677290: Waiting
5f015d65fccd: Waiting
d18d76a881a4: Verifying Checksum
d18d76a881a4: Download complete
119c7358fbfc: Verifying Checksum
119c7358fbfc: Download complete
2aaf13f3eff0: Verifying Checksum
2aaf13f3eff0: Download complete
1ea85296b57d: Verifying Checksum
1ea85296b57d: Download complete
34667c7e4631: Verifying Checksum
34667c7e4631: Download complete
5f015d65fccd: Verifying Checksum
5f015d65fccd: Download complete
969975223755: Verifying Checksum
969975223755: Download complete
34667c7e4631: Pull complete
178f29677290: Verifying Checksum
178f29677290: Download complete
d18d76a881a4: Pull complete
119c7358fbfc: Pull complete
2aaf13f3eff0: Pull complete
969975223755: Pull complete
1ea85296b57d: Pull complete
178f29677290: Pull complete
5f015d65fccd: Pull complete
Digest: sha256:2b118a4b74998159c4aa3cd3ccf6d73074bec6ad70cfab0be28f4459754a0640
Status: Downloaded newer image for norionomura/swiftlint:latest
The `swiftlint autocorrect` command is no longer available.
Please use `swiftlint --fix` instead.
Error: No lintable files found at paths: '/tmp/lint'
Correcting Swift files at paths /tmp/lint
```

- Contents of `.swiftlint.yml`
```
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - force_try # Remove when done
  - type_name
  - identifier_name
  - type_body_length
  - file_length

cyclomatic_complexity:
  ignores_case_statements: true
```

### PR DESCRIPTION
**Pull request by Noraldeno**
- Update swiftlint documentation

- Update to use [swiftlint's Docker image](https://github.com/realm/SwiftLint?tab=readme-ov-file#docker)

- Add "lintable" to cspell exclusion

Fixes #440

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
Great work!
@nvuillam Do you want to take a look? The test cases pass, but not the Megalinter part.

**Comment by Noraldeno** [comment]
@echoix Thx! Happy to help!

Looks like the linting [error](https://github.com/oxsecurity/megalinter/actions/runs/12477772393/job/34830580404?pr=4427#step:12:207) is the spell check. How do you usually handle spelling errors like this?

```
CHANGELOG.md:24:104    - Unknown word (lintable)   -- linter is unable to find lintable files. Fixes [#440]
	 Suggestions: [linable, liftable, lineable, linkable, listable]
```

**Comment by echoix** [comment]
> @echoix Thx! Happy to help!
> 
> 
> 
> Looks like the linting [error](https://github.com/oxsecurity/megalinter/actions/runs/12477772393/job/34830580404?pr=4427#step:12:207) is the spell check. How do you usually handle spelling errors like this?
> 
> 
> 
> ```
> 
> CHANGELOG.md:24:104    - Unknown word (lintable)   -- linter is unable to find lintable files. Fixes [#440]
> 
> 	 Suggestions: [linable, liftable, lineable, linkable, listable]
> 
> ```

If it's not a typo, add them to the cspell exclusion (dict)

You can download the artifact and use the pre-populated changed file in report, removing the unnecessary changes if there's some typos to fix: https://github.com/oxsecurity/megalinter/actions/runs/12477772394

image

**Comment by Noraldeno** [comment]
> > @echoix Thx! Happy to help!
> > Looks like the linting [error](https://github.com/oxsecurity/megalinter/actions/runs/12477772393/job/34830580404?pr=4427#step:12:207) is the spell check. How do you usually handle spelling errors like this?
> > ```
> > 
> > CHANGELOG.md:24:104    - Unknown word (lintable)   -- linter is unable to find lintable files. Fixes [#440]
> > 
> > 	 Suggestions: [linable, liftable, lineable, linkable, listable]
> > ```
> 
> If it's not a typo, add them to the cspell exclusion (dict)
> 
> You can download the artifact and use the pre-populated changed file in report, removing the unnecessary changes if there's some typos to fix: https://github.com/oxsecurity/megalinter/actions/runs/12477772394
> 
> image

I added the word "lintable" to cspell exclusion

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
Should #1757 be closed now?

**Pull request merged**
