### PR TITLE
Set downgraded linters

### PR DESCRIPTION
**Pull request by bdovaz**
The linter checkov does not reflect the `downgraded_version` variable correctly.

Possibly now the fixed version can be removed from the "packaging" package but for the moment at least I make it consistent.

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4147824459)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.38s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.36s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.99s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|9.89s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.08s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.3s        |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.82s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    1|[231](https://github.com/oxsecurity/megalinter/actions/runs/4147824459)|6.42s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.53s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    1|                                                                      0|17.89s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.69s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4147824459) |1.94s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|4.62s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.8s        |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.8s        |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.0s        |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|12.04s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4147824459)|17.27s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.58s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.34s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |14.18s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.58s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|19.28s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.88s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.35s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.81s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|60.02s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.06s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4147824459)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
Current MegaLinter beta is with 2.2.356, and the next checkov version is 3.3.0 (released yesterday) , and will be catched by the next auto-update-linters job, so why declare it as downgraded ? ^^
https://github.com/bridgecrewio/checkov/releases

**Comment by bdovaz** [comment]
@nvuillam because of this:

image

Or is it that another criteria is followed in these cases? I understand that if the linter has some dependency with a fixed version, it should be marked as downgraded, no?

**Comment by nvuillam** [comment]
@bdovaz it was a workaround because checkov installation was crashing... I don't remember why, but you can try to undowngrade the packaging dependency, it may work now ^^

**Comment by nvuillam** [comment]
Dockerfiles have not been updated... mayb e build ? ^^ ( no need for the --doc )

**Comment by bdovaz** [comment]
@nvuillam done! Thank you!

**Review by nvuillam — APPROVED** [review]
If CI agrees, how could I not agree ? :p

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4151049509)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.21s       |
|✅ BASH      |[shfmt](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.05s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.77s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|10.02s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.23s       |
|✅ JSON      |[jsonlint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.31s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.71s       |
|✅ JSON      |[v8r](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/json_v8r)                                              |   21|     |                                                                      0|13.56s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/markdown_markdownlint)                        |  309|    0|[231](https://github.com/oxsecurity/megalinter/actions/runs/4151049509)|7.03s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|6.54s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|20.78s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|2.02s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4151049509) |2.48s       |
|✅ PYTHON    |[black](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_black)                                        |  176|    0|                                                                      0|4.02s       |
|✅ PYTHON    |[flake8](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_flake8)                                      |  176|     |                                                                      0|2.77s       |
|✅ PYTHON    |[isort](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.56s       |
|✅ PYTHON    |[mypy](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_mypy)                                          |  176|     |                                                                      0|8.42s       |
|✅ PYTHON    |[pylint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_pylint)                                      |  176|     |                                                                      0|13.56s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4151049509)|20.92s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_checkov)                                |yes  |     |no                                                                     |34.0s       |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4151049509) |1.56s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.53s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |9.53s       |
|✅ REPOSITORY|[syft](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.15s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.06s      |
|✅ SPELL     |[cspell](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/spell_cspell)                                       |  729|     |                                                                      0|21.4s       |
|✅ SPELL     |[misspell](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/spell_misspell)                                   |  550|    0|                                                                      0|0.63s       |
|✅ XML       |[xmllint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.07s       |
|✅ YAML      |[v8r](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|64.88s      |
|✅ YAML      |[yamllint](https://megalinter.io/81c789bbdd5902df5acbd3a418415b23bd8ce2cd/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.37s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4151049509)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
