### PR TITLE
Remove trailing space from build script

### PR DESCRIPTION
**Pull request by parkerbxyz**
Many editors are configured to trim trailing whitespace upon saving files. When this happens, it can often clutter up diffs with whitespaces changes.

## Proposed Changes

Remove trailing space from build script to ensure trailing spaces don't end up in files generated/edited by the build script.

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
Good catch for hacktoberfest haha :)
Totally useless as PR but just for the research I accept it :D

**Comment by nvuillam** [comment]
Oops you have to merge conflicts before ^^

**Comment by parkerbxyz** [comment]
> Good catch for hacktoberfest haha :) Totally useless as PR but just for the research I accept it :D

Haha! That wasn't the motivation here, I almost did this in my other PR (#1934), because that's where I experienced the problem that motivated this change (https://github.com/oxsecurity/megalinter/pull/1934/commits/5ccc1e0d94fec498afe6464d2fd2e8c0faaeb7bf), but I was doing my best to follow the contributing guidelines. 😉 

> Keep your change as focused as possible. If there are multiple changes you would like to make that are not dependent upon each other, consider submitting them as separate pull requests.

**Comment by parkerbxyz** [comment]
> Oops you have to merge conflicts before ^^

I'm not seeing any merge conflicts :eyes:

**Review by Kurt-von-Laven — APPROVED** [review]

**Comment by nvuillam** [comment]
@parkerbxyz please can you make your branch up to date with main ? it will fix CI issues not related to your PR :)

**Pull request merged**
