### PR TITLE
Do not push to docker from dev PRs

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by echoix** [comment]
But now, how do the tests run?
In the new line 209, we pull the image to be able to run the test cases. Maybe like a local exporter, local registry? Also, in the future, we might still have problems with multiplatform images if nothing changes on the Docker side (currently it was impossible to load locally built image when it was a multi platform image, thus the load: true)

**Comment by nvuillam** [comment]
@echoix as the same docker instance is used to build & to test I assume it will find the image it just built ?

**Comment by echoix** [comment]
Not when you add a multi platform image in the mix, at least for the last time we tried. There are many kinds of exporters, and the default one cannot do that.

**Comment by echoix** [comment]
But for now it should kinda work. However I'd like to still see a real test from a pulled container when it's on the main branch (or about to be in the main/beta branch), to be sure we test what the users will be receiving.

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4973410630)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.18s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.34s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |4.95s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  116|     |                                                                      0|17.7s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   23|    0|                                                                      0|2.49s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   21|     |                                                                      0|0.21s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   23|     |                                                                      0|17.64s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  307|    0|[228](https://github.com/oxsecurity/megalinter/actions/runs/4973410630)|170.25s     |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  307|     |                                                                      0|7.4s        |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  307|    0|                                                                      0|23.58s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.47s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  188|     |[58](https://github.com/oxsecurity/megalinter/actions/runs/4973410630) |2.72s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  188|    2|                                                                      0|7.06s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  188|     |                                                                      0|2.24s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  188|    2|                                                                      0|0.91s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  188|     |                                                                      0|9.93s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  188|     |                                                                      0|14.51s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  188|     |[301](https://github.com/oxsecurity/megalinter/actions/runs/4973410630)|24.62s      |
|✅ PYTHON    |[ruff](https://megalinter.io/beta/descriptors/python_ruff)                                          |  188|    2|                                                                      0|0.47s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |37.9s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.33s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |18.87s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |29.75s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  612|     |                                                                      0|28.04s      |
|⚠️ SPELL     |[vale](https://megalinter.io/beta/descriptors/spell_vale)                                           |  219|     |[62](https://github.com/oxsecurity/megalinter/actions/runs/4973410630) |33.97s      |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.34s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |  156|    0|                                                                      0|4.8s        |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   98|     |                                                                      0|149.37s     |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |  157|     |                                                                      0|1.67s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4973410630)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
> Not when you add a multi platform image in the mix, at least for the last time we tried. There are many kinds of exporters, and the default one cannot do that.

True :)

That will be another story ... to test :)

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam-secure-build) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4973459495)

| Descriptor  |                                                         Linter                                                          |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|-------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-nuillam-secure-build/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-nuillam-secure-build/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.18s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-nuillam-secure-build/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-nuillam-secure-build/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |4.99s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-nuillam-secure-build/descriptors/dockerfile_hadolint)                              |  116|     |                                                                      0|22.31s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam-secure-build/descriptors/json_eslint_plugin_jsonc)              |   23|    0|                                                                      0|2.52s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-nuillam-secure-build/descriptors/json_jsonlint)                                    |   21|     |                                                                      0|0.27s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-nuillam-secure-build/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.85s       |
|✅ JSON      |[v8r](https://megalinter.io/test-nuillam-secure-build/descriptors/json_v8r)                                              |   23|     |                                                                      0|19.29s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam-secure-build/descriptors/markdown_markdownlint)                        |  307|    2|[228](https://github.com/oxsecurity/megalinter/actions/runs/4973459495)|185.2s      |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-nuillam-secure-build/descriptors/markdown_markdown_link_check)          |  307|     |                                                                      0|7.0s        |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-nuillam-secure-build/descriptors/markdown_markdown_table_formatter)|  307|    2|                                                                      0|24.74s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-nuillam-secure-build/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.82s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-nuillam-secure-build/descriptors/python_bandit)                                      |  188|     |[58](https://github.com/oxsecurity/megalinter/actions/runs/4973459495) |3.75s       |
|✅ PYTHON    |[black](https://megalinter.io/test-nuillam-secure-build/descriptors/python_black)                                        |  188|    0|                                                                      0|5.98s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-nuillam-secure-build/descriptors/python_flake8)                                      |  188|     |                                                                      0|2.67s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-nuillam-secure-build/descriptors/python_isort)                                        |  188|    0|                                                                      0|0.67s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-nuillam-secure-build/descriptors/python_mypy)                                          |  188|     |                                                                      0|11.46s      |
|✅ PYTHON    |[pylint](https://megalinter.io/test-nuillam-secure-build/descriptors/python_pylint)                                      |  188|     |                                                                      0|17.0s       |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-nuillam-secure-build/descriptors/python_pyright)                                    |  188|     |[301](https://github.com/oxsecurity/megalinter/actions/runs/4973459495)|29.43s      |
|✅ PYTHON    |[ruff](https://megalinter.io/test-nuillam-secure-build/descriptors/python_ruff)                                          |  188|    0|                                                                      0|0.17s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_checkov)                                |yes  |     |no                                                                     |42.75s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_devskim)                                |yes  |     |[913](https://github.com/oxsecurity/megalinter/actions/runs/4973459495)|5.64s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.83s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.05s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |17.7s       |
|✅ REPOSITORY|[syft](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.41s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-nuillam-secure-build/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |31.31s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-nuillam-secure-build/descriptors/spell_cspell)                                       |  625|     |                                                                      0|37.32s      |
|⚠️ SPELL     |[vale](https://megalinter.io/test-nuillam-secure-build/descriptors/spell_vale)                                           |  219|     |[62](https://github.com/oxsecurity/megalinter/actions/runs/4973459495) |38.67s      |
|✅ XML       |[xmllint](https://megalinter.io/test-nuillam-secure-build/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/test-nuillam-secure-build/descriptors/yaml_prettier)                                    |  156|    0|                                                                      0|5.06s       |
|✅ YAML      |[v8r](https://megalinter.io/test-nuillam-secure-build/descriptors/yaml_v8r)                                              |   98|     |                                                                      0|159.89s     |
|✅ YAML      |[yamllint](https://megalinter.io/test-nuillam-secure-build/descriptors/yaml_yamllint)                                    |  157|     |                                                                      0|1.86s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4973459495)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
