### PR TITLE
Port Beta workflows to use docker/metadata-action

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

## Proposed Changes

1. Align Beta workflows with our dev workflows, as started with https://github.com/oxsecurity/megalinter/pull/3193
2. Formatted the files

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
We might want to add an editorconfig entry to trim trailing whitespaces in our workflows.

**Comment by nvuillam** [comment]
> > Build command workflow failed.

@echoix it looks strange... please can you try to build on your computer then push ?

**Comment by echoix** [comment]
Triggered in https://github.com/echoix/megalinter/pull/102#issuecomment-2282820828

**Comment by echoix** [comment]
I know I didn't run the build at the time so I wouldn't have many conflicts when it would be time to file the PR.

**Comment by echoix** [comment]
> > > Build command workflow failed.
> 
> 
> 
> @echoix it looks strange... please can you try to build on your computer then push ?

I think I know: the GitHub token is used instead of PAT, so can't push to a fork, as GitHub actions (bot) isn't a "maintainer" that would be allowed with "allow maintainers to edit and have access to secrets"

**Comment by echoix** [comment]
Ah, it failed on my fork too... We are changing a workflow file, there are extra permissions required I think. A PAT can have the extra scope, but for the amount of times it happens vs the risks, it's not worth it

**Comment by echoix** [comment]
Nothing really changed here

**Comment by nvuillam** [comment]
@echoix if you are 100% sure of your update, tell me and i force the merge :)

**Comment by echoix** [comment]
> @echoix if you are 100% sure of your update, tell me and i force the merge :)

I'm sure that the failure isn't related, and I'm sure that the beta workflows work the same way as the dev ones to. The pattern didn't change.

**Comment by nvuillam** [comment]
so let's go :)

**Pull request merged**
