### PR TITLE
Correct behavior of `EXTENDS`

### LINKED ISSUE #1516: `EXTENDS` in `.mega-linter.yml`: Properties from extended file override properties in extending file
**Describe the bug**
To simplify the configuration of MegaLinter across multiple repos I want to have one [base config in my `.github` repo](https://github.com/lars-reimann/.github/blob/2a05588583f77cc571d4b7a5dae0b0b3f0fe6b8e/.mega-linter.yml) and then have a short configuration in each other repo that adds properties or overrides the ones from the base config. For example, in one repository I want to override the `FILTER_REGEX_EXCLUDE` property:

```yml
EXTENDS: https://raw.githubusercontent.com/lars-reimann/.github/main/.mega-linter.yml

# Config
FILTER_REGEX_EXCLUDE: (\.github/workflows/|someOtherFolder/)
```

However, this does not seem to work as expected: The `FILTER_REGEX_EXCLUDE` property from the extended config overrides the property defined here rather than the other way around. This means the base config can only contain properties that I know I'll never want to override.

**To Reproduce**

1. Create a base config.
2. Create another config that extends the base config and overrides one of its properties.
3. Observe the behavior of the linter.

**Expected behavior**
The property in the extending file should have precedence.

**Additional context**
At first glance this seems to cause this behavior: https://github.com/megalinter/megalinter/blob/100a4d937a48c79e0eb5de8325d4d2b22601d861/megalinter/config.py#L82

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Ensure that local config keys overwrite inherited config keys rather than the other way around.

Fixes #1516.

## Proposed Changes

1. Correct the casing of "VsCode" to "VSCode."
1. Document that extended configs are applied left to right, so the rightmost takes precedence.
1. Create a new dictionary, and apply updates from the inherited configs in the order in which they are specified in `EXTENDS`. Finally, apply updates from the local config.

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3356742929)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                   |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.05s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.28s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.33s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |1.77s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|6.27s       |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|2.14s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.23s       |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   21|     |                                                                          0|16.39s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  294|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3356742929)  |4.91s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  294|     |                                                                          0|4.98s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  294|    0|                                                                          0|6.46s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|0.75s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  170|     |[**42**](https://github.com/oxsecurity/megalinter/actions/runs/3356742929) |3.58s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  170|    0|                                                                          0|4.04s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  170|     |                                                                          0|2.08s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  170|    0|                                                                          0|0.7s        |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  170|     |                                                                          0|6.91s       |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  170|     |                                                                          0|10.35s      |
|:warning: PYTHON  |[pyright](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pyright)                                    |  170|     |[**273**](https://github.com/oxsecurity/megalinter/actions/runs/3356742929)|15.31s      |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                         |25.04s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.32s       |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |7.06s       |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |20.17s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  706|     |                                                                          0|17.09s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  533|    0|                                                                          0|0.9s        |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.0s        |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|2.53s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|43.15s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.26s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3356742929)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
@Kurt-von-Laven the MegaLinter error is very strange... i've never seen auto-commit step like that :o

**Review by nvuillam — APPROVED** [review]
Great, if build & deploy - DEV passes, it can be merged :) ( we can solve MegaLinter error in another PR, that's not an issue related to your code)

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config) status: ❌ [**ERROR**](https://github.com/oxsecurity/megalinter/actions/runs/3357500331)

|     Descriptor     |                                                                  Linter                                                                  |Files|Fixed|                                  Errors                                   |Elapsed time|
|--------------------|------------------------------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.01s       |
|✅ BASH             |[shellcheck](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.26s       |
|✅ BASH             |[shfmt](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.04s       |
|❌ COPYPASTE        |[jscpd](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/copypaste_jscpd)                                     |yes  |     |[**1**](https://github.com/oxsecurity/megalinter/actions/runs/3357500331)  |1.98s       |
|✅ DOCKERFILE       |[hadolint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|8.32s       |
|✅ JSON             |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|1.72s       |
|✅ JSON             |[jsonlint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.21s       |
|✅ JSON             |[v8r](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/json_v8r)                                              |   21|     |                                                                          0|15.78s      |
|:warning: MARKDOWN  |[markdownlint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/markdown_markdownlint)                        |  294|    2|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3357500331)  |5.14s       |
|✅ MARKDOWN         |[markdown-link-check](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/markdown_markdown_link_check)          |  294|     |                                                                          0|5.12s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/markdown_markdown_table_formatter)|  294|    2|                                                                          0|5.49s       |
|✅ OPENAPI          |[spectral](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|0.69s       |
|:warning: PYTHON    |[bandit](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_bandit)                                      |  170|     |[**42**](https://github.com/oxsecurity/megalinter/actions/runs/3357500331) |2.21s       |
|✅ PYTHON           |[black](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_black)                                        |  170|    0|                                                                          0|3.29s       |
|✅ PYTHON           |[flake8](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_flake8)                                      |  170|     |                                                                          0|2.14s       |
|✅ PYTHON           |[isort](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_isort)                                        |  170|    0|                                                                          0|0.39s       |
|✅ PYTHON           |[mypy](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_mypy)                                          |  170|     |                                                                          0|6.83s       |
|✅ PYTHON           |[pylint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_pylint)                                      |  170|     |                                                                          0|10.2s       |
|:warning: PYTHON    |[pyright](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/python_pyright)                                    |  170|     |[**271**](https://github.com/oxsecurity/megalinter/actions/runs/3357500331)|16.43s      |
|✅ REPOSITORY       |[checkov](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_checkov)                                |yes  |     |no                                                                         |25.68s      |
|:warning: REPOSITORY|[devskim](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_devskim)                                |yes  |     |[**59**](https://github.com/oxsecurity/megalinter/actions/runs/3357500331) |1.12s       |
|✅ REPOSITORY       |[dustilock](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_dustilock)                            |yes  |     |no                                                                         |2.49s       |
|✅ REPOSITORY       |[git_diff](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.04s       |
|✅ REPOSITORY       |[secretlint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |3.32s       |
|✅ REPOSITORY       |[syft](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_syft)                                      |yes  |     |no                                                                         |2.03s       |
|✅ REPOSITORY       |[trivy](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |17.68s      |
|✅ SPELL            |[cspell](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/spell_cspell)                                       |  706|     |                                                                          0|16.01s      |
|✅ SPELL            |[misspell](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/spell_misspell)                                   |  533|    2|                                                                          0|0.4s        |
|✅ XML              |[xmllint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.0s        |
|✅ YAML             |[prettier](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|2.34s       |
|✅ YAML             |[v8r](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|42.54s      |
|✅ YAML             |[yamllint](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.41s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3357500331)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**oxsecurity/megalinter/flavors/python@v5**](https://oxsecurity.github.io/megalinter/test-Kurt-on-Laen-config/flavors/python/) (56 linters)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by Kurt-von-Laven** [comment]
I fixed the test failure the first run of Build & Deploy - DEV detected. I think the failure this time is the one you are saying to ignore?

**Comment by nvuillam** [comment]
@Kurt-von-Laven nope, this is now a copy-paste detection issue :p

**Pull request merged**
