### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by nvuillam** [comment]
@echoix do you have an idea about what's happening with gitpod ? it seems related to uv setup :/

**Comment by echoix** [comment]
> @echoix do you have an idea about what's happening with gitpod ? it seems related to uv setup :/

Yep, rereading the error now I understand. Look at the second point of the uv's breaking changes for 0.5.0: https://github.com/astral-sh/uv/releases/tag/0.5.0

> **Use XDG (i.e. ~/.local/bin) instead of the Cargo home directory in the installer (# 8420)**
> 
> Previously, uv's installer used `$CARGO_HOME` or `~/.cargo/bin` for its target install directory. It's been a longstanding complaint that uv uses this directory, as there's no relationship to Cargo. Now, uv will be installed into `$XDG_BIN_HOME`, `$XDG_DATA_HOME/../bin`, or `~/.local/bin` (in that order). Note that `$UV_INSTALL_DIR` can always be used to override the target directory. Upgrading with `uv self update` will not move uv to the new install directory.

**Comment by nvuillam** [comment]
> > @echoix do you have an idea about what's happening with gitpod ? it seems related to uv setup :/
> 
> Yep, rereading the error now I understand. Look at the second point of the uv's breaking changes for 0.5.0: https://github.com/astral-sh/uv/releases/tag/0.5.0
> 
> > **Use XDG (i.e. ~/.local/bin) instead of the Cargo home directory in the installer (# 8420)**
> > Previously, uv's installer used `$CARGO_HOME` or `~/.cargo/bin` for its target install directory. It's been a longstanding complaint that uv uses this directory, as there's no relationship to Cargo. Now, uv will be installed into `$XDG_BIN_HOME`, `$XDG_DATA_HOME/../bin`, or `~/.local/bin` (in that order). Note that `$UV_INSTALL_DIR` can always be used to override the target directory. Upgrading with `uv self update` will not move uv to the new install directory.

Thanks :)

I'll merge this PR to unlock other ones ^^

Do you think you can handle the gitpod error in another PR ?

**Comment by echoix** [comment]
Not tonight.

**Comment by nvuillam** [comment]
> Not tonight.

Of course, this is open source, it's when you can :)

**Pull request merged**
