### PR TITLE
Deploy additional Docker images to GitHub Container Registry

### PR DESCRIPTION
**Pull request by lars-reimann**
Fixes partially #1472

## Proposed Changes

1. Deploy additional Docker images to GitHub Container Registry. This would later allow [action.yml](https://github.com/oxsecurity/megalinter/blob/main/action.yml) to pull the MegaLinter image from GitHub instead of Docker Hub, which _should_ speed up the pull phase of the action.

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by lars-reimann** [comment]
Some questions about this:

1. Should other `deploy` workflows also be updated? This includes
    * deploy-ALPHA-flavors.yml
    * deploy-BETA-flavors.yml
    * deploy-BETA-linters.yml
    * deploy-DEV.yml
    * deploy-DEV-linters.yml
    * deploy-RELEASE-linters.yml
2. Should this PR also update `action.yml` or should this be done in a separate PR?
3. How can I test these changes?

Once these questions are answered, I'll update the `CHANGELOG` accordingly.

**Comment by bdovaz** [comment]
Ping @nvuillam, can you answer this questions?

**Comment by nvuillam** [comment]
@bdovaz beta, beta-flavors and beta-linters will validate that it work, so the release jobs have more chances to work too :)

**Comment by lars-reimann** [comment]
I recently found [this discussion](https://github.com/orgs/community/discussions/27080) claiming that GHCR is no faster than Docker for GitHub Actions. So, I wonder whether it makes sense to further pursue this PR.

**Comment by nvuillam** [comment]
docker pulls on docker hub has download limitations (not applied on github actions), so it still can be iteresting to use ghcr image, especially for self hossted runners :)

**Comment by Kurt-von-Laven** [comment]
Thai Pangsakulyanont [reported improved performance building and pushing to GHCR](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei), which makes me skeptical that pulling is somehow slower. I wrote [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache), automating approach 📦 in the blog post, and it outperforms pulling directly from Docker Hub. In any case, we should measure the performance ourselves since it may have changed over time.

**Comment by echoix** [comment]
And what about simply when there are some outages? Its native to GitHub, and the whole build doesn't need to be done twice anyway, only two pushes instead of one.

**Comment by lars-reimann** [comment]
I can continue with this next week. If someone else wants to work on it in the meantime, feel free to do so.

**Review by nvuillam — APPROVED** [review]
Great PR, nice job, thanks a lot for your contribution :)

**Comment by nvuillam** [comment]
When i try to merge i have an error :/

**Comment by echoix** [comment]
> When i try to merge i have an error :/
> 
> 

Did you try on web instead of app? I can't imagine why an OAuth app is involved in that. Of course I never saw the settings on admin side, but changes to workflows have been done even during the holidays without problems.

**Comment by Kurt-von-Laven** [comment]
By default, bots can't edit `.github/workflows` for security reasons (c.f., [orgs/community#25222](https://github.com/orgs/community/discussions/25222), [orgs/community#26164](https://github.com/orgs/community/discussions/26164)). In this case, since the error is coming from an OAuth App, it's possible to grant it the [`workflow` scope](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes) if desired. I don't know which OAuth App this is though, so I can't comment on whether granting it the ability to execute arbitrary code in our name would be wise.

**Comment by nvuillam** [comment]
@Kurt-von-Laven @echoix  it worked thru web UI :)

**Comment by nvuillam** [comment]
thanks again @lars-reimann :)

**Pull request merged**
