### PR TITLE
Submitted Mustache plugin

### PR DESCRIPTION
**Pull request by Yann-J**
Replaces #1944 to implement logstash linting via plugin

### CODE REVIEW

**Comment by nvuillam** [comment]
@Yann-J you have (easy) conflicts :)

**Comment by nvuillam** [comment]
Please could you 
- share the result log of a MegaLinter run using the plugin ?
- Add tag `megalinter` on repo https://github.com/one-acre-fund/mega-linter-plugin-logstash

**Comment by Yann-J** [comment]
Ah, sorry my fork was behind...

Here's a successful run:

```
$ docker run -v $(PWD):/tmp/lint oxsecurity/megalinter:v6
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Skipped setting git safe.directory DEFAULT_WORKSPACE:  ...
Setting git safe.directory default: /github/workspace ...
Setting git safe.directory to /tmp/lint ...
[MegaLinter init] ONE-SHOT RUN
[config] /tmp/lint/.mega-linter.yml + Environment variables
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2022-09-19T20:35:45Z
 - Image Revision: bd93146
 - Image Version: v6
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://oxsecurity.github.io/megalinter/latest
----------------------------------------------------------------------------------------------------
MegaLinter initialization

[Plugins] Loaded plugin descriptor /megalinter-descriptors/logstash.megalinter-descriptor.yml from https://raw.githubusercontent.com/one-acre-fund/mega-linter-plugin-logstash/main/mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml
[Plugins] Successful initialization of LOGSTASH plugins
MARKDOWN_REMARK_LINT has been temporary disabled in MegaLinter, please use a previous MegaLinter version or wait for the next one !
Skipped linters: ACTION_ACTIONLINT, ANSIBLE_ANSIBLE_LINT, ARM_ARM_TTK, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, CLOJURE_CLJ_KONDO, CLOUDFORMATION_CFN_LINT, COFFEE_COFFEELINT, COPYPASTE_JSCPD, CPP_CPPLINT, CSHARP_DOTNET_FORMAT, CSS_SCSS_LINT, CSS_STYLELINT, C_CPPLINT, DART_DARTANALYZER, DOCKERFILE_HADOLINT, EDITORCONFIG_EDITORCONFIG_CHECKER, ENV_DOTENV_LINTER, GHERKIN_GHERKIN_LINT, GO_GOLANGCI_LINT, GO_REVIVE, GRAPHQL_GRAPHQL_SCHEMA_LINTER, GROOVY_NPM_GROOVY_LINT, HTML_DJLINT, HTML_HTMLHINT, JAVASCRIPT_ES, JAVASCRIPT_PRETTIER, JAVASCRIPT_STANDARD, JAVA_CHECKSTYLE, JAVA_PMD, JSON_ESLINT_PLUGIN_JSONC, JSON_JSONLINT, JSON_PRETTIER, JSON_V8R, JSX_ESLINT, KOTLIN_KTLINT, KUBERNETES_KUBECONFORM, KUBERNETES_KUBEVAL, LATEX_CHKTEX, LUA_LUACHECK, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, MARKDOWN_REMARK_LINT, OPENAPI_SPECTRAL, PERL_PERLCRITIC, PHP_PHPCS, PHP_PHPLINT, PHP_PHPSTAN, PHP_PSALM, POWERSHELL_POWERSHELL, PROTOBUF_PROTOLINT, PUPPET_PUPPET_LINT, PYTHON_BANDIT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_MYPY, PYTHON_PYLINT, PYTHON_PYRIGHT, RAKU_RAKU, REPOSITORY_CHECKOV, REPOSITORY_DEVSKIM, REPOSITORY_DUSTILOCK, REPOSITORY_GITLEAKS, REPOSITORY_GIT_DIFF, REPOSITORY_GOODCHECK, REPOSITORY_SECRETLINT, REPOSITORY_SEMGREP, REPOSITORY_SYFT, REPOSITORY_TRIVY, RST_RSTCHECK, RST_RST_LINT, RUBY_RUBOCOP, RUST_CLIPPY, R_LINTR, SALESFORCE_SFDX_SCANNER_APEX, SALESFORCE_SFDX_SCANNER_AURA, SALESFORCE_SFDX_SCANNER_LWC, SCALA_SCALAFIX, SNAKEMAKE_LINT, SNAKEMAKE_SNAKEFMT, SPELL_CSPELL, SPELL_MISSPELL, SPELL_PROSELINT, SQL_SQLFLUFF, SQL_SQL_LINT, SQL_TSQLLINT, SWIFT_SWIFTLINT, TEKTON_TEKTON_LINT, TERRAFORM_CHECKOV, TERRAFORM_KICS, TERRAFORM_TERRAFORM_FMT, TERRAFORM_TERRAGRUNT, TERRAFORM_TERRASCAN, TERRAFORM_TFLINT, TSX_ESLINT, TYPESCRIPT_ES, TYPESCRIPT_PRETTIER, TYPESCRIPT_STANDARD, VBDOTNET_DOTNET_FORMAT, XML_XMLLINT, YAML_PRETTIER, YAML_V8R, YAML_YAMLLINT
To receive reports as email, please set variable EMAIL_REPORTER_EMAIL

MegaLinter now collects the files to analyse
Listing all files in directory [/tmp/lint], then filter with:
- File extensions: .conf
- Excluding .gitignored files [29]: /tmp/lint/megalinter-reports/IDE-config.txt, /tmp/lint/megalinter-reports/IDE-config/.markdownlint.json, /tmp/lint/megalinter-reports/IDE-config/.vscode/extensions.json, /tmp/lint/megalinter-reports/linters_logs/ERROR-DOCKERFILE_HADOLINT.log, /tmp/lint/megalinter-reports/linters_logs/ERROR-LOGSTASH_MUSTACHE.log, /tmp/lint/megalinter-reports/linters_logs/ERROR-RUBY_RUBOCOP.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-JSON_PRETTIER.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-LOGSTASH_MUSTACHE.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-MARKDOWN_MARKDOWNLINT.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-RUBY_RUBOCOP.log,...(full list in DEBUG)
Kept [24] files on [72] found files

+----MATCHING LINTERS---+----------+----------------+------------+
| Descriptor | Linter   | Criteria | Matching files | Format/Fix |
+------------+----------+----------+----------------+------------+
| LOGSTASH   | mustache | .conf    | 21             | no         |
+------------+----------+----------+----------------+------------+

Unable to extract version with regex re.compile('\\d+(\\.\\d+)+') from mustache version (unknown)

✅ Linted [LOGSTASH] files with [mustache] successfully - (0.77s)
- Using [mustache vERROR] https://github.com/breml/logstash-config
- MegaLinter key: [LOGSTASH_MUSTACHE]
- Rules config: identified by [mustache]
- Number of files analyzed: [21]


+----SUMMARY--+----------+---------------+-------+-------+--------+--------------+
| Descriptor  | Linter   | Mode          | Files | Fixed | Errors | Elapsed time |
+-------------+----------+---------------+-------+-------+--------+--------------+
| ✅ LOGSTASH | mustache | list_of_files |    21 |       |      0 |        0.77s |
+-------------+----------+---------------+-------+-------+--------+--------------+

[flavors] You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
[flavors] Use the following link to request the new flavor: https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%0A%0ALOGSTASH_MUSTACHE%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A

[Updated Sources Reporter] Unable to copy mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml to /tmp/lint/megalinter-reports/updated_sources/mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml ([Errno 2] No such file or directory: 'mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml')
[Updated Sources Reporter] copied 2 fixed source files in folder /tmp/lint/megalinter-reports/updated_sources.
Download it from artifacts then copy-paste it in your local repo to apply linters updates
::set-output name=has_updated_sources::0
✅ Successfully linted all files without errors
```

and a failed run:

```
$ docker run -v $(PWD):/tmp/lint oxsecurity/megalinter:v6
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Skipped setting git safe.directory DEFAULT_WORKSPACE:  ...
Setting git safe.directory default: /github/workspace ...
Setting git safe.directory to /tmp/lint ...
[MegaLinter init] ONE-SHOT RUN
[config] /tmp/lint/.mega-linter.yml + Environment variables
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2022-09-19T20:35:45Z
 - Image Revision: bd93146
 - Image Version: v6
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://oxsecurity.github.io/megalinter/latest
----------------------------------------------------------------------------------------------------
MegaLinter initialization

[Plugins] Loaded plugin descriptor /megalinter-descriptors/logstash.megalinter-descriptor.yml from https://raw.githubusercontent.com/one-acre-fund/mega-linter-plugin-logstash/main/mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml
[Plugins] Successful initialization of LOGSTASH plugins
MARKDOWN_REMARK_LINT has been temporary disabled in MegaLinter, please use a previous MegaLinter version or wait for the next one !
Skipped linters: ACTION_ACTIONLINT, ANSIBLE_ANSIBLE_LINT, ARM_ARM_TTK, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, CLOJURE_CLJ_KONDO, CLOUDFORMATION_CFN_LINT, COFFEE_COFFEELINT, COPYPASTE_JSCPD, CPP_CPPLINT, CSHARP_DOTNET_FORMAT, CSS_SCSS_LINT, CSS_STYLELINT, C_CPPLINT, DART_DARTANALYZER, DOCKERFILE_HADOLINT, EDITORCONFIG_EDITORCONFIG_CHECKER, ENV_DOTENV_LINTER, GHERKIN_GHERKIN_LINT, GO_GOLANGCI_LINT, GO_REVIVE, GRAPHQL_GRAPHQL_SCHEMA_LINTER, GROOVY_NPM_GROOVY_LINT, HTML_DJLINT, HTML_HTMLHINT, JAVASCRIPT_ES, JAVASCRIPT_PRETTIER, JAVASCRIPT_STANDARD, JAVA_CHECKSTYLE, JAVA_PMD, JSON_ESLINT_PLUGIN_JSONC, JSON_JSONLINT, JSON_PRETTIER, JSON_V8R, JSX_ESLINT, KOTLIN_KTLINT, KUBERNETES_KUBECONFORM, KUBERNETES_KUBEVAL, LATEX_CHKTEX, LUA_LUACHECK, MAKEFILE_CHECKMAKE, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_LINK_CHECK, MARKDOWN_MARKDOWN_TABLE_FORMATTER, MARKDOWN_REMARK_LINT, OPENAPI_SPECTRAL, PERL_PERLCRITIC, PHP_PHPCS, PHP_PHPLINT, PHP_PHPSTAN, PHP_PSALM, POWERSHELL_POWERSHELL, PROTOBUF_PROTOLINT, PUPPET_PUPPET_LINT, PYTHON_BANDIT, PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_ISORT, PYTHON_MYPY, PYTHON_PYLINT, PYTHON_PYRIGHT, RAKU_RAKU, REPOSITORY_CHECKOV, REPOSITORY_DEVSKIM, REPOSITORY_DUSTILOCK, REPOSITORY_GITLEAKS, REPOSITORY_GIT_DIFF, REPOSITORY_GOODCHECK, REPOSITORY_SECRETLINT, REPOSITORY_SEMGREP, REPOSITORY_SYFT, REPOSITORY_TRIVY, RST_RSTCHECK, RST_RST_LINT, RUBY_RUBOCOP, RUST_CLIPPY, R_LINTR, SALESFORCE_SFDX_SCANNER_APEX, SALESFORCE_SFDX_SCANNER_AURA, SALESFORCE_SFDX_SCANNER_LWC, SCALA_SCALAFIX, SNAKEMAKE_LINT, SNAKEMAKE_SNAKEFMT, SPELL_CSPELL, SPELL_MISSPELL, SPELL_PROSELINT, SQL_SQLFLUFF, SQL_SQL_LINT, SQL_TSQLLINT, SWIFT_SWIFTLINT, TEKTON_TEKTON_LINT, TERRAFORM_CHECKOV, TERRAFORM_KICS, TERRAFORM_TERRAFORM_FMT, TERRAFORM_TERRAGRUNT, TERRAFORM_TERRASCAN, TERRAFORM_TFLINT, TSX_ESLINT, TYPESCRIPT_ES, TYPESCRIPT_PRETTIER, TYPESCRIPT_STANDARD, VBDOTNET_DOTNET_FORMAT, XML_XMLLINT, YAML_PRETTIER, YAML_V8R, YAML_YAMLLINT
To receive reports as email, please set variable EMAIL_REPORTER_EMAIL

MegaLinter now collects the files to analyse
Listing all files in directory [/tmp/lint], then filter with:
- File extensions: .conf
- Excluding .gitignored files [29]: /tmp/lint/megalinter-reports/IDE-config.txt, /tmp/lint/megalinter-reports/IDE-config/.markdownlint.json, /tmp/lint/megalinter-reports/IDE-config/.vscode/extensions.json, /tmp/lint/megalinter-reports/linters_logs/ERROR-DOCKERFILE_HADOLINT.log, /tmp/lint/megalinter-reports/linters_logs/ERROR-LOGSTASH_MUSTACHE.log, /tmp/lint/megalinter-reports/linters_logs/ERROR-RUBY_RUBOCOP.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-JSON_PRETTIER.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-LOGSTASH_MUSTACHE.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-MARKDOWN_MARKDOWNLINT.log, /tmp/lint/megalinter-reports/linters_logs/SUCCESS-RUBY_RUBOCOP.log,...(full list in DEBUG)
Kept [24] files on [72] found files

+----MATCHING LINTERS---+----------+----------------+------------+
| Descriptor | Linter   | Criteria | Matching files | Format/Fix |
+------------+----------+----------+----------------+------------+
| LOGSTASH   | mustache | .conf    | 21             | no         |
+------------+----------+----------+----------------+------------+

Unable to extract version with regex re.compile('\\d+(\\.\\d+)+') from mustache version (unknown)

❌ Linted [LOGSTASH] files with [mustache]: Found 2 error(s) - (0.85s)
- Using [mustache vERROR] https://github.com/breml/logstash-config
- MegaLinter key: [LOGSTASH_MUSTACHE]
- Rules config: identified by [mustache]
- Number of files analyzed: [21]
--Error detail:
error: 2 errors occurred:
        * /tmp/lint/pipeline/listening/00-inputs.conf: /tmp/lint/pipeline/listening/00-inputs.conf: /tmp/lint/pipeline/listening/00-inputs.conf:10:3 (149): no match found, expected: "#", "{" or [ \t\r\n]
          Parsing error at pos 8:0 [140] and [144] (after: '\n\n  '):
          -> expect closing curly bracket

        * /tmp/lint/pipeline/listening/05-paygops.conf: /tmp/lint/pipeline/listening/05-paygops.conf:4:5 (59): rule ifCond: Parsing error at pos 3:0 [53] and [59] (after: '\n\n    '):
          -> expect closing curly bracket




+----SUMMARY--+----------+---------------+-------+-------+--------+--------------+
| Descriptor  | Linter   | Mode          | Files | Fixed | Errors | Elapsed time |
+-------------+----------+---------------+-------+-------+--------+--------------+
| ❌ LOGSTASH | mustache | list_of_files |    21 |       |      2 |        0.85s |
+-------------+----------+---------------+-------+-------+--------+--------------+

[flavors] You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
[flavors] Use the following link to request the new flavor: https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%0A%0ALOGSTASH_MUSTACHE%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A

[Updated Sources Reporter] Unable to copy mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml to /tmp/lint/megalinter-reports/updated_sources/mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml ([Errno 2] No such file or directory: 'mega-linter-plugin-logstash/logstash.megalinter-descriptor.yml')
[Updated Sources Reporter] copied 4 fixed source files in folder /tmp/lint/megalinter-reports/updated_sources.
Download it from artifacts then copy-paste it in your local repo to apply linters updates
::set-output name=has_updated_sources::0
❌ Error(s) have been found during linting
To disable linters or customize their checks, you can use a .mega-linter.yml file at the root of your repository
More info at https://oxsecurity.github.io/megalinter/latest/configuration/
```

**Comment by nvuillam** [comment]
That seems great :)

**Review by nvuillam — APPROVED** [review]
Great, thanks a lot for your contribution :)

**Pull request merged**
