### PR TITLE
Don't add literal double quote characters to filenames

### LINKED ISSUE #1942: False-negative for setuptools in CSpell
I'm getting a false-negative for CSpell when "setuptools" is removed from the custom dictionary; see ScribeMD/docker-cache#177. This only occurs when CSpell is run through MegaLinter via pre-commit (as it is in our CI pipeline), but not when CSpell is run through the command line or when CSpell is run through MegaLinter without pre-commit. 

A false-negative occurs in the following scenarios: 
- Running MegaLinter through [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache)'s CI pipeline; see [our pre-commit config](https://github.com/ScribeMD/docker-cache/blob/main/.pre-commit-config.yaml), [CSpell config](https://github.com/ScribeMD/docker-cache/blob/main/cspell.config.yaml), and [MegaLinter config](https://github.com/ScribeMD/docker-cache/blob/main/.mega-linter.yaml).  We use the pre-commit hooks defined in [ScribeMD/pre-commit-hooks](https://github.com/ScribeMD/pre-commit-hooks/blob/main/.pre-commit-hooks.yaml).
- Running MegaLinter through pre-commit with `poetry run pre-commit run --all-files --hook-stage push` in [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache)

The correct behavior (successfully catching setuptools as an unrecognized word) occurs in the following scenarios:
- Running CSpell directly in ScribeMD/docker-cache with `npx cspell "**"`
- Running MegaLinter directly in ScribeMD/docker-cache with:

  ```
  npx -- mega-linter-runner@v6.10.0 --containername megalinter-full --remove-container --fix \
    --env CLEAR_REPORT_FOLDER=true --env LOG_LEVEL=debug --flavor javascript --release v6.10.0 
  ```

  or with `LOG_LEVEL=warning`
- Running through our CI pipeline in other repos; see ScribeMD/.github#85
- Incorrectly changing [our pre-commit config](https://github.com/ScribeMD/docker-cache/blob/main/.pre-commit-config.yaml) so that instead of:

  ```yaml
  - id: megalinter-incremental
    args: &megalinter-args [--flavor, javascript, --release, v6.10.0, --env, LOG_LEVEL=debug]
  ```

  I had:

  ```yaml
  - id: megalinter-incremental
    args: &megalinter-args [--flavor, javascript, --release, v6.10.0, LOG_LEVEL=debug]
  ```

  and then running MegaLinter via pre-commit with the following command:
  `poetry run pre-commit run --all-files --hook-stage push`.

Expected behavior: CSpell should catch setuptools as an unrecognized word.  The output should include `/tmp/lint/poetry.toml:6:4 - Unknown word (setuptools)`. Note: I erroneously thought it was included in CSpell's `python` dictionary but it is not; it is in the `python-common` dictionary.

Additional pertinent information: after running `poetry run pre-commit run --all-files --hook-stage push` on ScribeMD/docker-cache, the `megalinter.log` consists of the following output: 
```
MARKDOWN_REMARK_LINT has been temporary disabled in MegaLinter, please use a previous MegaLinter version or wait for the next one !
[File listing] Input file /tmp/lint/"poetry.toml not found
[File listing] Input file /tmp/lint/src/post.ts" not found
```
I'm noticing the stray quotes in lines two and three.  Consequently, I suspect that this bug has something to do with the interaction of quotation marks in pre-commit and MegaLinter.

Thanks for looking into this! I'm curious to see what you think!!

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Fixes #1942.

The extra quotes caused MegaLinter to fail to find the first and last files in the list, because the first has a literal double quote character prepended to it, and the last has one appended to it.

## Proposed Changes

1. Remove the extra double quotes.
2. Remove some unnecessary arguments to `child_process.spawnSync`.
3. Don't access empty `stdout` or `stderr` properties of return value of `child_process.spawnSync`.

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3287436399)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                   |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.07s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.59s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.29s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |1.85s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|7.01s       |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|2.14s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.21s       |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   21|     |                                                                          0|15.66s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  294|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3287436399)  |5.27s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  294|     |                                                                          0|5.05s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  294|    0|                                                                          0|6.78s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|0.79s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  170|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3287436399) |2.95s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  170|    0|                                                                          0|3.99s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  170|     |                                                                          0|2.06s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  170|    0|                                                                          0|0.65s       |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  170|     |                                                                          0|6.72s       |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  170|     |                                                                          0|11.2s       |
|:warning: PYTHON  |[pyright](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pyright)                                    |  170|     |[**273**](https://github.com/oxsecurity/megalinter/actions/runs/3287436399)|15.68s      |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                         |26.64s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.3s        |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |8.26s       |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |20.51s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  706|     |                                                                          0|17.02s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  533|    0|                                                                          0|0.72s       |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.0s        |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|3.12s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|42.55s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.28s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3287436399)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by Kurt-von-Laven** [comment]
Thanks for the helpful bug reports, @kcfedun-fincad and @mwarres. Please let me know if you have any feedback on the proposed fix.

**Comment by nvuillam** [comment]
what if there are spaces in file names ?

**Comment by kcfedun-fincad** [comment]
> what if there are spaces in file names ?

Having a filename with spaces in it will very likely break things. It looks like pre-commit doesn't do any escaping when passing the list of files (see `scripts/kc test.sh` below). Not wrapping the values for `MEGALINTER_FILES_TO_LINT` in quotes will cause confusion with the `docker run` command.

```bash
scripts/kctest.sh
---

#!/bin/bash
set -e

echo $@
```

```yaml
.pre-commit-config.yaml
---
...
      - id: kctest
        name: kctest
        language: script
        entry: scripts/kctest.sh
        pass_filenames: true
```

```bash
$ pre-commit run kctest -v
kctest...................................................................Passed
- hook id: kctest
- duration: 0s

.pre-commit-config.yaml .mega-linter.yml app.py scripts/kc test.sh scripts/kctest.sh
```

You may be better off performing additional logic at https://github.com/oxsecurity/megalinter/blob/main/megalinter/config.py#L123 and leaving the options joiner alone.

**Comment by Kurt-von-Laven** [comment]
Filenames containing spaces are handled correctly provided that we don’t pass an option such as `{shell: true}` to [`child_process.spawnSync`](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options). The POSIX shell quoting behaviors we are accustomed to don’t apply here. By default `spawnSync` invokes no shell whatsoever, instead invoking the process directly.

[This is what is presently happening on main](https://stackoverflow.com/a/48015471):

> The system shell will strip off quotes around parameters, so the program gets the unquoted value at the end. Spawning a process bypasses this step as it bypasses the shell, so the program gets those literal quotes as part of the parameter and doesn't know how to handle them appropriately.

**Comment by Kurt-von-Laven** [comment]
I went ahead and removed `{ verbatimWindowsArguments: true }`.

**Comment by nvuillam** [comment]
will it work ? ^^

**Comment by Kurt-von-Laven** [comment]
It works for me on Linux, WSL, and Windows with and without spaces in filenames.

**Comment by Kurt-von-Laven** [comment]
I tacked a few minor commits onto this pull request based on the discussion in #1987.

**Comment by nvuillam** [comment]
CI is broken because of linter upgrades, but i'm working on it in PR https://github.com/oxsecurity/megalinter/pull/1981

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://oxsecurity.github.io/megalinter/test-nuillam-runner) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/3303940169)

|     Descriptor     |                                                               Linter                                                                |Files|Fixed|                                  Errors                                   |Elapsed time|
|--------------------|-------------------------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.01s       |
|✅ BASH             |[shellcheck](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.25s       |
|✅ BASH             |[shfmt](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.03s       |
|✅ COPYPASTE        |[jscpd](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |2.09s       |
|✅ DOCKERFILE       |[hadolint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/dockerfile_hadolint)                              |  105|     |                                                                          0|7.2s        |
|✅ JSON             |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                          0|1.73s       |
|✅ JSON             |[jsonlint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/json_jsonlint)                                    |   19|     |                                                                          0|0.47s       |
|✅ JSON             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/json_v8r)                                              |   21|     |                                                                          0|14.99s      |
|:warning: MARKDOWN  |[markdownlint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/markdown_markdownlint)                        |  294|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/3303940169)  |5.03s       |
|✅ MARKDOWN         |[markdown-link-check](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/markdown_markdown_link_check)          |  294|     |                                                                          0|5.26s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/markdown_markdown_table_formatter)|  294|    0|                                                                          0|6.77s       |
|✅ OPENAPI          |[spectral](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|1.27s       |
|:warning: PYTHON    |[bandit](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_bandit)                                      |  170|     |[**55**](https://github.com/oxsecurity/megalinter/actions/runs/3303940169) |2.22s       |
|✅ PYTHON           |[black](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_black)                                        |  170|    0|                                                                          0|3.63s       |
|✅ PYTHON           |[flake8](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_flake8)                                      |  170|     |                                                                          0|1.88s       |
|✅ PYTHON           |[isort](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_isort)                                        |  170|    0|                                                                          0|0.41s       |
|✅ PYTHON           |[mypy](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_mypy)                                          |  170|     |                                                                          0|7.44s       |
|✅ PYTHON           |[pylint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_pylint)                                      |  170|     |                                                                          0|11.41s      |
|:warning: PYTHON    |[pyright](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/python_pyright)                                    |  170|     |[**271**](https://github.com/oxsecurity/megalinter/actions/runs/3303940169)|17.55s      |
|✅ REPOSITORY       |[checkov](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_checkov)                                |yes  |     |no                                                                         |26.47s      |
|:warning: REPOSITORY|[devskim](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_devskim)                                |yes  |     |[**59**](https://github.com/oxsecurity/megalinter/actions/runs/3303940169) |1.33s       |
|✅ REPOSITORY       |[dustilock](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_dustilock)                            |yes  |     |no                                                                         |2.5s        |
|✅ REPOSITORY       |[git_diff](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.03s       |
|✅ REPOSITORY       |[secretlint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |4.35s       |
|✅ REPOSITORY       |[syft](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_syft)                                      |yes  |     |no                                                                         |2.36s       |
|✅ REPOSITORY       |[trivy](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |17.77s      |
|✅ SPELL            |[cspell](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/spell_cspell)                                       |  706|     |                                                                          0|17.46s      |
|✅ SPELL            |[misspell](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/spell_misspell)                                   |  533|    0|                                                                          0|0.48s       |
|✅ XML              |[xmllint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.0s        |
|✅ YAML             |[prettier](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/yaml_prettier)                                    |   80|    0|                                                                          0|2.44s       |
|✅ YAML             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|43.09s      |
|✅ YAML             |[yamllint](https://oxsecurity.github.io/megalinter/test-nuillam-runner/descriptors/yaml_yamllint)                                    |   81|     |                                                                          0|1.43s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/3303940169)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**oxsecurity/megalinter/flavors/python@test-nvuillam-runner**](https://oxsecurity.github.io/megalinter/test-nuillam-runner/flavors/python/) (56 linters)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
