### PR TITLE
Testing: git push auto fixed files

### PR DESCRIPTION
**Pull request by lukelloyd1985**
## Proposed Changes

Testing git add, commit & push when there are fixed sources files

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
I will require later 
- add entry in CHANGELOG.md
- change the commit message to use "[Mega-Linter] Apply linters fixes (from core)"
But i validate it so you can make tests with alpha version (hosted on ghcr.io ^^ )

**Comment by nvuillam** [comment]
Build job for alpha flavors : https://github.com/oxsecurity/megalinter/actions/runs/11449333253/job/31854702104

**Comment by lukelloyd1985** [comment]
Yeah the plan was to get it all working/tested in alpha first and then make all the other changes (docs etc) before creating a PR to beta 😎

**Comment by nvuillam** [comment]
@lukelloyd1985 alpha full image + flavor images build are ok, you can proceed to your tests :)

**Comment by lukelloyd1985** [comment]
> > @lukelloyd1985 alpha full image + flavor images build are ok, you can proceed to your tests :)
> 
> Next thick question....
> 
> `docker pull oxsecurity/megalinter:alpha` doesn't work does it so how do I pull the alpha image in my pipeline?

ah think I've figured it out

`docker pull ghcr.io/oxsecurity/megalinter:alpha`?

**Comment by lukelloyd1985** [comment]
@nvuillam I don't know why/how I used `config.get_list` instead of `config.get` 🤷‍♀️🤦‍♂️

image

I'll correct and do another PR to alpha...

**Comment by nvuillam** [comment]
> > > @lukelloyd1985 alpha full image + flavor images build are ok, you can proceed to your tests :)
> > 
> > 
> > Next thick question....
> > `docker pull oxsecurity/megalinter:alpha` doesn't work does it so how do I pull the alpha image in my pipeline?
> 
> ah think I've figured it out
> 
> `docker pull ghcr.io/oxsecurity/megalinter:alpha`?

yes, alpha are pushed only on ghcr.io :)

**Pull request merged**
