### PR TITLE
Use uv.lock file to build docker images

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

## Proposed Changes

1. Updates the python project's version that was still kept at 7.13.0 even though multiple releases have been made since.
2. Uses a stage to include the dependencies before installing the project. Uses newer instructions and commands that are now available with uv: https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
There were also some missing licences that the build scripts were finding

**Comment by nvuillam** [comment]
@echoix looks great :)

For my culture, how is generated/maintained uv.lock ?

**Comment by echoix** [comment]
Manually, uv lock.
Otherwise, it should be weekly with renovate, just like the npm

There is uv sync --frozen to install following the lock file, similar to npm and cargo. 

It doesn't include the dev deps, only the ones that run the Megalinter core (in Python), the ones listed in pyproject.toml.

**Comment by echoix** [comment]
Otherwise using uv with operations on packages, or installing without mentionning --frozen and outdated updates it, like npm

**Comment by nvuillam** [comment]
Thank for the explanations :)

**Comment by echoix** [comment]
It's ready now!

**Pull request merged**
