### PR TITLE
enhancement: Gitleaks schema improvements

### LINKED ISSUE #3064: REPOSITORY_GITLEAKS_PR_COMMITS_SCAN missing from the configuration schme
**Describe the bug**
Hi, 

First of all, thank you for the great work and effort you put in this great tool 🙇 .

In the latest MegaLinter release version (v7.5.0), when one uses the Gitleaks linter related configuration value `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN`, added earlier this year and described in the [documentation](https://megalinter.io/7.5.0/descriptors/repository_gitleaks/) in the `.megalinter.yml` configuration file, it will make the v8r linter produce validation error as the configuration value key is not included in the MegaLinter config schema

The produced error from the output (MegaLinter executed in GitHub):

```text
  ℹ Processing ./.mega-linter.yml
  ℹ Found schema in https://www.schemastore.org/api/json/catalog.json ...
  ℹ Validating ./.mega-linter.yml against schema from https://raw.githubusercontent.com/megalinter/megalinter/main/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json ...
  ✖ ./.mega-linter.yml is invalid
  
  ./.mega-linter.yml# must NOT have additional properties
```

I know there is a workaround to put the configuration directly as an environment variable, but I'd prefer storing all configurations in the same place (i.e. the config file).

**To Reproduce**

- Define Megalinter configuration file (`.mega-linter.yml`) to the repository root
- Include `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: true` and enable `v8r` linter for YAML files.
- Run the linter to see `v8r` failing stating `.mega-linter.yml` has extra parameters:
  ```text
   ./.mega-linter.yml# must NOT have additional properties
  ```

**Expected behavior**
The source schema file should include the `REPOSITORY_GITLEAKS_PR_COMMITS_SCAN` parameter (if the parameter if still valid; if not then the documentation should be updated).

### PR DESCRIPTION
**Pull request by TommyE123**
# [GitLeaks](https://github.com/gitleaks/gitleaks) Add missing schema properties

## Context:
Three schema references were missing for `Gitleaks` which causes `YAML_V8R` to fail.
•	`REPOSITORY_GITLEAKS_PR_COMMITS_SCAN`
•	`REPOSITORY_GITLEAKS_PR_SOURCE_SHA`
•	`REPOSITORY_GITLEAKS_PR_TARGET_SHA`

## Testing: 
Shows they were missing from the schema

image
image

 

If there are any issues or concerns, please let me know, and I will address them promptly.
Thank you for reviewing this PR and I look forward to your feedback.
Tom

### CODE REVIEW

**Comment by echoix** [comment]
Were they added manually? Usually they are generated by a script, `build.sh --doc`. If this doesn't regenerate correctly, it's another issue.

**Comment by TommyE123** [comment]
Yes I added them manually.

I was just going off what @nvuillam said in the linked issue that was raised a while back!

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
The worse is that at some point when the command will be rerun it will get replaced by the actual contents from the descriptor.

**Comment by TommyE123** [comment]
Apologies @echoix,

I should have checked in more detail and wasn’t aware the schema was created off the back of the descriptors as well.
I’d like to try and do this properly if that’s ok?

Tom

**Comment by echoix** [comment]
You can run in your branch to see if the contents are different. Maybe it's the same? Maybe the full doc rebuild is done near releases, were these fields new?

**Comment by TommyE123** [comment]
Hi @echoix,

These variables are from a previous release and don't get added via the `build.sh --doc` command, which is why they're missing from the JSON schema. After looking at the `.automation/build.py` code, it seems like there's currently no support for automatically adding these types of variables to the schema.

While I considered trying to add that functionality, it would require careful planning and testing to ensure it properly handles different variable types and doesn't cause any unintended issues or conflicts with existing variables.

For now, I've reordered these missing variables to match the order that the `build.sh --doc` command would place them in. This should work until we can come up with a more permanent solution.

Does this approach sound reasonable? I'm open to any other suggestions you might have for dealing with these missed variables and keeping the schema in sync going forward.

Tom

**Comment by echoix** [comment]
Yes good

**Comment by echoix** [comment]
> Hi @echoix,
> 
> 
> 
> These variables are from a previous release and don't get added via the `build.sh --doc` command, which is why they're missing from the JSON schema. After looking at the `.automation/build.py` code, it seems like there's currently no support for automatically adding these types of variables to the schema.
> 
> 
> 
> While I considered trying to add that functionality, it would require careful planning and testing to ensure it properly handles different variable types and doesn't cause any unintended issues or conflicts with existing variables.
> 
> 
> 
> For now, I've reordered these missing variables to match the order that the `build.sh --doc` command would place them in. This should work until we can come up with a more permanent solution.
> 
> 
> 
> Does this approach sound reasonable? I'm open to any other suggestions you might have for dealing with these missed variables and keeping the schema in sync going forward.
> 
> 
> 
> Tom
> 
> 

It would be something very useful to have implemented in the docs generation, jsonschema docs generation or even normal build, as updating them manually is error prone (ie: forget to do it), as you found out recently.

I'm grateful for your work, but I'm blocked with the current CI that fails and can't fix them all at once. Nicolas would be able to force the merge of these PRs, but I can't just by myself.

**Comment by echoix** [comment]
I’ve been merging your PRs one by one, resolving the conflicts on the changelog as we waited too long to merge.
Again, thanks for your great work!

**Comment by nvuillam** [comment]
Indeed, thanks @TommyE123 for your great latest contributions, and thanks @echoix for all your validation & guidance work ❤️

**Pull request merged**
