### PR TITLE
Upgrade dotnet to v6

### PR DESCRIPTION
**Pull request by lextatic**
Added the project files for the `sample_project_fixes` tests.

But I think it won't be enough. It seems the command is being executed from the root of the repository, so it has to specify the workspace path where the project/sln file is located as the first CLI parameter when executing. Is something like this possible in the descriptor?

Maybe like this? (following what I saw in switft and repository descriptors)
```yaml
    cli_lint_extra_args:
      - "{{WORKSPACE}}"
      - "--verify-no-changes"
      - "--exclude"
      - "/"
      - "--include"
```

### CODE REVIEW

**Comment by lextatic** [comment]
Everything should be okay now, the tests failing indicate that they're still expecting old dotnet 5.0 dotnet-format paremeters (with `--check` instead of `--verify-no-changes`).

Isn't there anywhere else that has to upgrade from dotnet 5.0 to dotnet 6.0?

**Comment by nvuillam** [comment]
@lextatic my bad, DevSkim and tsqllint use dotnet too... and I've not factorized such commands yet... I forgot to update their descriptors !
Now channel 6.0 is in all of them, I just pushed a new commit

Install commands are the following, are they still ok for dotnot v6 ?

```
      RUN wget --tries=5 -q -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
          && chmod +x dotnet-install.sh \
          && ./dotnet-install.sh --install-dir /usr/share/dotnet -channel 6.0 -version latest
    - ENV PATH="${PATH}:/root/.dotnet/tools:/usr/share/dotnet"
```

**Comment by lextatic** [comment]
> Install commands are the following, are they still ok for dotnet v6 ?

I wouldn't know, will have to look into it. I think we're still missing something.

**Comment by lextatic** [comment]
@nvuillam So, I made some interesting discoveries. It seems [dotnet-format is now part of the dotnet 6.0 sdk](https://github.com/dotnet/format/issues/1268). With that we shouldn't need to run `dotnet tool install -g dotnet-format` anymore, and in fact when you install this it runs with an older version that isn't compatible with the `--verify-no-changes` argument.

Also, to use the dotnet format that comes with dotnet 6 we have to call `dotnet format` insead of `dotnet-format` (which executes the old, deprecated, dotnet-format tool). I'm not sure how to handle this change yet, looking into it.

**Comment by nvuillam** [comment]
So if I summarize well, we could do everything with just dotnet v6 install , and the only blocking stuff is DevSkim ?
What if we removed DevSkim from general docker image and let it only in Security flavor ?

**Comment by nvuillam** [comment]
If you find a way to work with dotnet V5 and V6 it would indeed be the best ^^

**Comment by echoix** [comment]
> If you find a way to work with dotnet V5 and V6 it would indeed be the best ^^

What I understand from using .NET, the idea of switching dotnet runtimes isn't really encountered, since the version selection just makes itself automatically without intervention. What we see is an error message when no compatible runtimes are installed for the app we want to run. 
It's really common on Windows to end up having each version/major version of dotnet installed, and there are no interventions to do to run a program. 
Just for fun, could you try installing both dotnet versions and see if it works without any extra configuration? 

I know it's not ideal to have an extra runtime in the release image for nothing.

**Comment by nvuillam** [comment]
I think we tried that @lextatic & myself,  but i'm not 100% sure, I never used dotnet so I have no clue about the solution, but let's try everything you think can be a good idea :)

**Comment by lextatic** [comment]
> > If you find a way to work with dotnet V5 and V6 it would indeed be the best ^^
> 
> What I understand from using .NET, the idea of switching dotnet runtimes isn't really encountered, since the version selection just makes itself automatically without intervention. What we see is an error message when no compatible runtimes are installed for the app we want to run. It's really common on Windows to end up having each version/major version of dotnet installed, and there are no interventions to do to run a program. Just for fun, could you try installing both dotnet versions and see if it works without any extra configuration?
> 
> I know it's not ideal to have an extra runtime in the release image for nothing.

@echoix It's true for dotnet runtime that several runtime versions can be installed and there's no "switching between runtimes". But dotnet-format is a SDK tool, not a runtime dotnet application and it will run using the whichever dotnet SDK you're using. On Windows, if you've got more than one SDK installed, it's usually the one being referenced in the %PATH environment variable. You can specify which SDK to run with a global.json file.

I was discussing with @nvuillam how to "switch sdks" in [this thread](https://github.com/oxsecurity/megalinter/pull/1646), but it might not be necessary as DevSkim might upgrade soon.

**Comment by lextatic** [comment]
@nvuillam Well, after some changes now the linter is running smoothly, I'm positive it's linting both csharp and vb okay, but it's still failing on both `test_failure` and I have no clue how to proceed.

**Comment by nvuillam** [comment]
https://github.com/microsoft/DevSkim is still in alpha, as soon as they officially are released we'll try with their version working in v6 :)

**Comment by nvuillam** [comment]
@lextatic DevSkim latest version is not working with v6 (and not anymore with v5 ^^)
I downgraded the DevSkim version for now, but it may be time to ressuscitate this PR :)

**Comment by lextatic** [comment]
> @lextatic DevSkim latest version is not working with v6 (and not anymore with v5 ^^) I downgraded the DevSkim version for now, but it may be time to ressuscitate this PR :)

Okay! Let's do this. Sorry for the blackout, I was just waiting for the resolution on this one. So, what's the plan?

**Comment by nvuillam** [comment]
I think you can:
- make your branch up to date with main branch (with merge conflicts)
- remove the downgrade of DevSkim version in repository descriptor
- build again
- see what happens in CI :)

**Comment by lextatic** [comment]
I've updated it with the latest `main` and also changed PR name and target to `main` branch but I'm not completely sure how to proceed now with DevSkim and build now.

**Comment by nvuillam** [comment]
@lextatic i took over you PR :p

**Comment by nvuillam** [comment]
@lextatic what could be wrong in this command ? ( it is supposed to not return 0 as there are formatting updates in files )

`dotnet format /tmp/lint/.automation/test/csharp --verify-no-changes --exclude / --include /tmp/lint/.automation/test/csharp/csharp_bad_01.cs /tmp/lint/.automation/test/csharp/csharp_bad_02.cs | tee /dev/tty2 2>&1 && exit "${PIPESTATUS[0]}"`

**Comment by lextatic** [comment]
> @lextatic i took over you PR :p

No problem ;P

> @lextatic what could be wrong in this command ? ( it is supposed to not return 0 as there are formatting updates in files )
> 
> `dotnet format /tmp/lint/.automation/test/csharp --verify-no-changes --exclude / --include /tmp/lint/.automation/test/csharp/csharp_bad_01.cs /tmp/lint/.automation/test/csharp/csharp_bad_02.cs | tee /dev/tty2 2>&1 && exit "${PIPESTATUS[0]}"`

Well, just `dotnet format /tmp/lint/.automation/test/csharp --verify-no-changes --exclude / --include /tmp/lint/.automation/test/csharp/csharp_bad_01.cs /tmp/lint/.automation/test/csharp/csharp_bad_02.c` is returning error code 2 here on Windows. Everything looks fine, I'll try to investigate it further.

**Comment by nvuillam** [comment]
This is still your PR, try new things with new commits if you like :)

**Comment by nvuillam** [comment]
Maybe an issue about absolute paths ?

**Comment by lextatic** [comment]
> Maybe an issue about absolute paths ?

It looks like it's not finding the `--include` files. I'm trying to figure it out. Maybe adding a `./` for relative path on them?

**Comment by lextatic** [comment]
It seems to be an issue with dotnet-format itself. I've posted an issue on their repo:

https://github.com/dotnet/format/issues/1770

Meanwhile I have some suggestions:

1. Since then dotnet 7.0 has already been officially released, what about upgrading it right to that instead of dotnet 6?

2. We could just remove the `--list-of-files` option and ignore this error for now. I don't think that would be a big deal since the new dotnet format is going to analyze all files in the project anyway because it looks for dependencies and other things. What I mean is, `--list-of-files`, or the `--include` option won't have any benefits in term of performance, and since it's not working properly we could just leave it out.

**Comment by lextatic** [comment]
@nvuillam Forgot to tag you in the previous comment, but I went on and decided to remove the `list_of_files` parameter for now and keep the dotnet6 since I wasn't able to make devskim and tsq-lint work with dotnet7. Please check the changes on `DotnetFormatLinter.py` to see if everything is okay there.

And there is still an issue with Terraform/Terrascan??? Can you check into that as well?

I had to sort the `csharp` and `vbdotnet` tests into separated `good` and `bad` folders in order to make it run properly, without the `--include` working I had to keep those files as distinct projects. I know it's not ideal, but we can revert this and put the `--include` paramenter back once I get an answer or fix from that issue I posted on the dotnet-format repo, but since the parameter is still not working even in the latest version of dotnet I thought it would be a better idea do leave it out.

**Comment by nvuillam** [comment]
@lextatic sorru for the delay...  go for dotnet v7 if it has retrocompability with v6 :) ( I wouldn't like dotnet6 users to not be able to use ML )

**Comment by bdovaz** [comment]
@lextatic note that the csharpier installation is set to 0.16.0 because in the main branch we are on .NET 5 but when you upgrade to .NET 7 you will probably have to remove "--version 0.16.0" to install the latest version.

**Comment by lextatic** [comment]
> @lextatic note that the csharpier installation is set to 0.16.0 because in the main branch we are on .NET 5 but when you upgrade to .NET 7 you will probably have to remove "--version 0.16.0" to install the latest version.

Thanks, I'm removing the version arguments from the CLI but I think more stuff had failed because of the upgrade. Feel free to contribute with this PR if you know how to handle it.

If we can't do it we can revert it back to .NET 6 as it was working fine and passing all tests there. Keeping it as .NET 6 isn't that bad since .NET 6 is the LTS and .NET 7 is just a STS, meaning both will be supported until the release of .NET 8.

**Comment by nvuillam** [comment]
Agreed that LTS is much netter than STS :)

**Comment by bdovaz** [comment]
> Agreed that LTS is much netter than STS, i thought dotnet v7 was also also lts bit if it's not the case it's probably better to remain on dotnet v6

@nvuillam I don't know if it is relevant to the use we make of it but just to keep it in mind:

https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/

**Comment by echoix** [comment]
It depends. If all the tools we need can run 7, we can use 7, dotnet always increases performance (it is always checked when integrating new changes, if it slows downs it isn't really accepted).

I don't think that the dotnet tools need to run the user's repo dotnet code, so we use the version we want.

**Comment by echoix** [comment]
@bdovaz same thoughts

**Comment by nvuillam** [comment]
If v7 is STS, i don't know about the user adoption

And as i do not use dotnet, i have no idea 😅

All I know for sure is that we need to stop being with dotnet v5 ^^

**Comment by bdovaz** [comment]
> If v7 is STS, i don't know about the user adoption
> 
> And as i do not use dotnet, i have no idea 😅
> 
> All I know for sure is that we need to stop being with dotnet v5 ^^

The only difference is the support time: https://dotnet.microsoft.com/en-us/platform/support/policy

In terms of stability and quality they assure that they have the same standards, it's not that .NET 7 is "beta" or something similar.

**Comment by echoix** [comment]
And we know a new one will exist after that.

**Comment by nvuillam** [comment]
So like @echoix said, all the apps we use are compliant, we could go with v7 and switch to v8 that will ne reales long before the end of v7 support, indeed :)

**Comment by lextatic** [comment]
I've made some tests and it seems like Devskim is blocking us again, also some other tests are failing that would need more time to investigate why.

So how about that?

Since it's already working fine with v6 we proceed with it for this PR and further investigate if we can upgrade to v7 on a future PR. At least this way we're out of v5 and on to a LTS version of .NET.

**Review by nvuillam — APPROVED** [review]
Great job , many many thanks for this huge contribution :)

**Comment by nvuillam** [comment]
@lextatic i think DevSkim is simply not compliant with v7... it's compliant with v6 for a few time, and after my request ^^

https://github.com/microsoft/DevSkim/issues/391

**Comment by bdovaz** [comment]
@lextatic @nvuillam the alpha versions are compatible with .NET 7, you can test them in a PR in draft if you want and wait until that version is stable:

https://www.nuget.org/packages/Microsoft.CST.DevSkim.CLI/0.8.8-alpha#supportedframeworks-body-tab

**Pull request merged**
