### PR TITLE
Fix Powershell Formatter appending new line

### PR DESCRIPTION
**Pull request by bdovaz**
Right now every time the formatter is run, it adds a new line break.

This PR fixes it:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1#-nonewline

I have the doubt @nvuillam @Kurt-von-Laven @echoix of the file encoding....

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1#-encoding

The Out-File command does not preserve the encoding and you have to pass one... Right now I'm passing it in this PR utf8 but I don't know if it's something that should be at least configurable....

**Edit:** I have not put "default" to the value of encoding because in more recent versions, it does not exist: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-7.3#-encoding

Which in fact, now I don't know what version of powershell is used in Megalinter, so that's the first thing to find out.

### CODE REVIEW

**Comment by nvuillam** [comment]
Isn't it a good practice to finish a code file with a new line ?

**Comment by bdovaz** [comment]
> Isn't it a good practice to finish a code file with a new line ?

@nvuillam You didn't understand me, if I don't do this PR, EVERY TIME the linter is executed, it adds a new line, that is, if I execute it 3 times, it adds 3 lines at the end. Look at the documentation I posted for `-NoNewline`.

**Comment by echoix** [comment]
> @nvuillam You didn't understand me, if I don't do this PR, EVERY TIME the linter is executed, it adds a new line, that is, if I execute it 3 times, it adds 3 lines at the end. Look at the documentation I posted for `-NoNewline`.


Oh that's awful

**Comment by bdovaz** [comment]
@nvuillam so what do we do? We leave the value of `-Encoding` configurable, right? If so:
1. What value do we set by default?
2. How do I make it configurable? Do you have any examples of any other linter?

**Comment by nvuillam** [comment]
powrshell version in MegaLinter is currently 7.3.1 -> https://megalinter.io/beta/descriptors/powershell_powershell_formatter/

Of there is an awful bug adding a new lint at each formatting, indeed it's better to never add it :)

**Comment by nvuillam** [comment]
And everybody probably uses UTF8, but you could add a new variable POWERSHELL_ENCODING with default utf8, that users could override (and you can get the value of this var in PowershellLinter.py )

**Review by nvuillam — APPROVED** [review]
Great <3

**Pull request merged**
