### PR TITLE
Removed hyperlinks to broken links

### PR DESCRIPTION
**Pull request by thelebdev**
Fixes #
Link to broken URLs

In the "Configuration in MegaLinter" section, there are references to the following broken links, which have been removed in this commit:
- https://megalinter.io/latest/6.16.0/configuration/#activation-and-deactivation
- https://megalinter.io/latest/6.16.0/configuration/#apply-fixes

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@thelebdev good catch :)

But these markdown files are generated, you have to update the source then [build again the project](https://megalinter.io/latest/contributing/#without-write-access) with `bash build.sh --doc` :)

https://github.com/oxsecurity/megalinter/blob/d9cc1b4179f513fcb50fa438babf54816f8037d5/.automation/build.py#L1173

**Comment by thelebdev** [comment]
Fell into the rookie mistake of not reading the contributing guide.
I'll take a look at it later and adjust accordingly.
Thanks for the feedback @nvuillam  :)

**Comment by bdovaz** [comment]
@nvuillam does this PR still make sense? The urls you mention do exist and are valid:

https://megalinter.io/beta/descriptors/spell_misspell/

**Comment by nvuillam** [comment]
We don't maintain previous versions of docs, so if it is solved in latest, it's ok :)

**Comment by bdovaz** [comment]
> We don't maintain previous versions of docs, so if it is solved in latest, it's ok :)

From what @nvuillam says, you can close the PR @thelebdev.

**Comment by nvuillam** [comment]
@bdovaz in such case you can do it yourself, with a nice explanation:)

**Comment by bdovaz** [comment]
@nvuillam I think it's a bit rude but ok haha.

Closed.

Explanation:

> We don't maintain previous versions of docs, so if it is solved in latest, it's ok :)

**Comment by nvuillam** [comment]
@bdovaz that's not rude if it is nicely explained, thanking anyway for the PR ... that's just maintenance to avoid to have too many PRs open ^^

**Pull request closed without merging**
