### PR TITLE
Add Vale linter

### PR DESCRIPTION
**Pull request by wesley-dean-flexion**
Fixes oxsecurity/megalinter#2401

## Proposed Changes

1. Add Vale prose checker to spell 

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

^ none of this is done -- just testing to see what CI/CD does (at @nvuillam's request) ; will update before making PR ready to be merged

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@wesley-dean-flexion  To solve the own MegaLinter issue, you can download the artifacts in the job page -> https://github.com/oxsecurity/megalinter/actions/runs/4308028827

Within it, you'll find an updated cspell.json that you can copy paste into your repo folder to overwrite the existing one in .github/linters :) 
(check these are not real typos before committing ^^ )

**Comment by nvuillam** [comment]
And if you did not try yet, to see issues before the looooong CI job, you can test locally :) https://megalinter.io/v6/contributing/#execute-the-tests-locally-visual-studio-code

**Comment by wesley-dean-flexion** [comment]
@nvuillam will do, but it may not be today

**Comment by nvuillam** [comment]
You need also to build to generate test class and update dockerfile, + to update the changelog ^^

https://megalinter.io/v6/contributing/#without-write-access

**Comment by nvuillam** [comment]
> @nvuillam will do, but it may not be today

That's the rule with open-source: no deadline, you do what you can when you can :)

**Comment by echoix** [comment]
Let's try it, it would be a good debugging to see if it was only dependabot that didn't work

**Comment by Kurt-von-Laven** [comment]
This reminds me of #2378. I suspect this may be technical debt we inherited from Super-Linter that currently none of us knows about unfortunately.

**Comment by nvuillam** [comment]
@wesley-dean-flexion FYI I added new commits on your branch to try to make the PR pass :)

**Comment by nvuillam** [comment]
It works locally... I hope the CI jobs will work too, I'm very excited to have Vale in MegaLinter, even if it means that we'll have to rewrite half the documentation because of my french-globbish 🤣

**Review by nvuillam — APPROVED** [review]
I'll merge once the CI is ok, many thanks @wesley-dean-flexion :)

**Pull request merged**
