### PR TITLE
added kubescape as a linter to  megalinter/descriptors/kubernetes.meg…

### PR DESCRIPTION
**Pull request by muandane**
kubernetes-linter-descriptor.yml

Feature: Kubescape security analysis as a kubernetes linter

## Proposed Changes

1. Install kubescape to do security checks on kubernetes manifests and helm charts
2. Add Kubescape to Ci_light if posssible 
3. For now i configured it to run only the DevOps framework but if people are willing other frameworks could be added. 

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@muandane this PR looks great, many thanks for submitting it :)

To add an embedded linter, you need additional actions and file, that you can see in the following documentation

https://megalinter.io/latest/contributing/#add-a-new-linter

Don't hesitate to ask if you need support, thanks again :)

**Comment by muandane** [comment]
@nvuillam i'm working on it and encountered an issue with documentation generation, but i couldn't find the doc URL in Megalinter Descriptor Schema or is it simply meant to be described by these two ["linter_repo:", "linter_url:"]

**Comment by bdovaz** [comment]
@muandane are you still working on this?

**Comment by nvuillam** [comment]
@bdovaz yes :)

**Review by nvuillam — APPROVED** [review]
Great PR, many thanks for your contribution @muandane :)

cc @EtienneDeneuve

**Pull request merged**
