### PR TITLE
Replace Trivy --security-checks parameter with --scanners parameter

### LINKED ISSUE #2324: Replace Trivy's deprecated parameter --security-checks by --scanners
It's a very easy PR to do, I'll do it in the afternoon if no one does it first

image

### PR DESCRIPTION
**Pull request by bdovaz**
https://github.com/aquasecurity/trivy/discussions/3519

Resolves #2324

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4117489155)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.38s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.19s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |1.98s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.56s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.36s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.24s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.76s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    0|[229](https://github.com/oxsecurity/megalinter/actions/runs/4117489155)|5.36s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.23s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|14.86s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.84s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4117489155) |1.94s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|3.64s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.67s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.6s        |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.57s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|10.43s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4117489155)|15.94s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |25.91s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.17s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |11.37s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.62s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|16.84s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.62s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.19s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.38s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|56.84s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.14s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4117489155)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam ok, I realized that it actually happened in the workflows we use: https://github.com/aquasecurity/trivy-action

I thought it was a descriptor thing. Actually it will be corrected automatically when this PR gets merged: https://github.com/aquasecurity/trivy-action/pull/201

But anyway, I have updated the descriptor and I have changed the parameter so that it affects us anyway.

**Comment by nvuillam** [comment]
You upgrade trivy version in this PR, that's already great :)

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4117635735)

| Descriptor  |                                                                   Linter                                                                   |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|--------------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.45s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.05s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.41s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.39s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.76s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.24s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.61s       |
|✅ JSON      |[v8r](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/json_v8r)                                              |   21|     |                                                                      0|13.06s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/markdown_markdownlint)                        |  309|    2|[229](https://github.com/oxsecurity/megalinter/actions/runs/4117635735)|6.37s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.83s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|15.45s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|0.96s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4117635735) |2.62s       |
|✅ PYTHON    |[black](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_black)                                        |  176|    0|                                                                      0|3.67s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.66s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.45s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.59s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_pylint)                                      |  176|     |                                                                      0|12.07s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4117635735)|17.82s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.7s       |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4117635735) |1.31s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.49s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.05s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |6.9s        |
|✅ REPOSITORY|[syft](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_syft)                                      |yes  |     |no                                                                     |3.34s       |
|❌ REPOSITORY|[trivy](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/repository_trivy)                                    |yes  |     |[1](https://github.com/oxsecurity/megalinter/actions/runs/4117635735)  |19.71s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/spell_cspell)                                       |  730|     |                                                                      0|18.14s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/spell_misspell)                                   |  551|    2|                                                                      0|0.54s       |
|✅ XML       |[xmllint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.6s        |
|✅ YAML      |[v8r](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|63.22s      |
|✅ YAML      |[yamllint](https://megalinter.io/test-bdoaz-replace-triy-deprecated-parameter/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.18s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4117635735)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam What do you think of the new errors that Trivy gives? There are a few new ones...

https://github.com/oxsecurity/megalinter/actions/runs/4117635735/jobs/7109181311

**Comment by nvuillam** [comment]
@bdovaz if you add `ds026` in .trivyignore it should be ok 😄

**Review by nvuillam — APPROVED** [review]
Wonderful to finally have an updated version of Trivy :)

**Comment by bdovaz** [comment]
@nvuillam another one has come out, do I ignore it too?

image

**Pull request merged**
