### PR TITLE
Fix jscpd linter error

### PR DESCRIPTION
**Pull request by bdovaz**
I got it in #2338 #2339 #2340 so it is an error that is currently in the `main` branch.

It probably has something to do with the fact that this linter (jscpd) has recently been updated and has become more restrictive or precise in certain cases.

### CODE REVIEW

**Comment by bdovaz** [comment]
@nvuillam we need to merge this ASAP because it affects all other PR

**Review by nvuillam — APPROVED** [review]
You're a life saver ^^

**Comment by nvuillam** [comment]
(I'll force merge once MegaLinter & Test mega-linter-runner are ok ^^ )

**Comment by nvuillam** [comment]
@bdovaz oops :/

image

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4147960518)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.37s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.13s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.64s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.74s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.86s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.66s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    0|[232](https://github.com/oxsecurity/megalinter/actions/runs/4147960518)|6.11s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.4s        |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|17.42s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.53s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4147960518) |1.91s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|4.13s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.63s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.51s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.52s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.03s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4147960518)|16.68s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.31s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.12s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |13.19s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.84s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|18.2s       |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.6s        |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.14s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.56s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|55.59s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.03s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4147960518)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam can you help me move that duplicate code out of place? I'm rusty on JavaScript best practices and new patterns and don't know how to get that repeated code out to another function/class/whatever.

**Comment by nvuillam** [comment]
Grmblmblmblm I don't understand, `"**/*.test.js",` is in both .jscpd.json config files... so megalinter-cli.test.js should be skipped >_<

**Comment by nvuillam** [comment]
I tried inline ignore... let's see what CI says

**Comment by bdovaz** [comment]
Could it be that the file passed (.jscpd.json) to it is not in the expected path?

https://github.com/kucherenko/jscpd/blob/a007bd7f9a2f1cc75a9f2894db7e7d87426e6626/packages/jscpd/src/init/cli.ts#L27

https://github.com/kucherenko/jscpd/blob/a007bd7f9a2f1cc75a9f2894db7e7d87426e6626/packages/jscpd/src/options.ts#L68

But if that were the case, more errors would come out of this linter, no? Because in the file you mention many paths are being ignored.

**Comment by bdovaz** [comment]
On top of that, it seems that they don't even update the CHANGELOG.md file in case there is any breaking change from the version we were using to the last one.

https://github.com/kucherenko/jscpd/issues/500

https://github.com/kucherenko/jscpd/blob/master/CHANGELOG.md

**Comment by nvuillam** [comment]
@bdovaz we'll never know :p 

Merged, you can update your other PR branches :)

**Pull request merged**
