### PR TITLE
Fix using default hadolint config file .hadolint.yml

### PR DESCRIPTION
**Pull request by KihyeokK**
The default `hadolint` config file present in the project is not being used properly, as file extensions .yaml and .yml are conflicting.

Fixes N/A

## Proposed Changes

1. As described in the [docs](https://megalinter.io/latest/descriptors/dockerfile_hadolint/), `hadolint` should be using `.hadolint.yaml` as the default configuration file. However, [the actual configuration file](https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.hadolint.yml) present in the project uses `.yml` as the file extension. This file name mismatch results in no default configuration file being used by `hadolint`. This PR enables `hadolint` to utilize the default configuration file present in the project as intended, by resolving the file name difference.

Please let me know if it is rather preferred to change the name of the config file present in the project to use `.yaml` instead of `.yml`, and leave other files unchanged. This may be preferred, since `hadolint` itself mentions [here](https://hub.docker.com/r/hadolint/hadolint) that it looks for `.hadolint.yaml` by default. I went with my approach to preserve consistency with other yaml files having the extension `.yml` in this project.

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
That's a good catch with an explanation with what's going on. 

As for what to choose, if it's the time to change something, I'd go with what the linter suggests. Furthermore, a quick stackoverflow answers links to a kinda direct answer: https://stackoverflow.com/a/22268973

https://yaml.org/faq.html
image

**Comment by KihyeokK** [comment]
Thank you for your feedback, I applied new changes to my commit :) 

> That's a good catch with an explanation with what's going on.
> 
> As for what to choose, if it's the time to change something, I'd go with what the linter suggests. Furthermore, a quick stackoverflow answers links to a kinda direct answer: https://stackoverflow.com/a/22268973
> 
> https://yaml.org/faq.html image

**Comment by KihyeokK** [comment]
Hello, could I get the approval for running the workflow checks again? The previous checks on my commits were failing due to Lychee linter checks, so I modified my commits to make sure that I did not make any spelling mistakes or dead links in the modified files which could lead to Lychee linter check failure.

If the Lychee linter checks still fail after running the workflows once again, I believe there are spelling/dead link issues with the already existing files, which might not have been modified to comply with Lychee linter checks when it was adopted recently to this repo. Would it be possible to merge my changes regardless of this check?

**Comment by echoix** [comment]
I completely agree with you. It's now running, and I'll let @nvuillam merge it if he thinks it doesn't have any other unforeseen impact. Other than that, great PR! (In the sense that to make it great, it finally only took one letter change in the file name, but the process and explanations were very complete!

**Comment by KihyeokK** [comment]
I appreciate the kind words :) As you mentioned the change is small but the process to find this little bug was definitely long, and I am really thankful that you saw through it!

**Comment by nvuillam** [comment]
I'm currently fixing CI in [another PR](https://github.com/oxsecurity/megalinter/pull/2766), when it will be fixed, merging or rebasing in your current branch will make the CI jobs ok :)

Thanks for your patience ^^

**Comment by nvuillam** [comment]
@KihyeokK internal MegaLinter CI is fixed, please can you merge main branch into yours ? :)

**Comment by KihyeokK** [comment]
@nvuillam Thank you, just merged👍 :)

**Review by nvuillam — APPROVED** [review]
Thanks for catching and fixing the issue @KihyeokK :)

**Pull request merged**
