### PR TITLE
[automation] Auto-update linters version, help and documentation

### PR DESCRIPTION
**Pull request by nvuillam**
[automation] Auto-update linters version, help and documentation

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
If passes, add the base image change in changelog. I hope it has a fixed golang stdlib version (not yet released on 3.19)

**Comment by echoix** [comment]
Regex for cfn-lint needs to be changed for the major version bump

**Comment by echoix** [comment]
> Regex for cfn-lint needs to be changed for the major version bump

What if we use the --format parsable? Or can we just use sarif? The output is very different

**Comment by nvuillam** [comment]
@echoix can't we just change the regex ? What is the new value returned ?

**Comment by echoix** [comment]
Yes you could, but might as well parse one that is meant to be parsable

**Comment by nvuillam** [comment]
Sorry, very hard to find time these days, i'll check this weekend 🥹

**Comment by echoix** [comment]
@nvuillam see my branch that I couldn't push when using Gitpod https://github.com/echoix/megalinter/tree/cpr2

There is phpstan that I don't really understand what to really fix. They don't show the results on internal errors since 1.11.5, but what is that error?

The go CVEs are still there

Changed the alpine image

cfn-lint needs to be redone after, I pinned it.

**Pull request merged**
