### PR TITLE
Upgrade PHPLint to v9

### LINKED ISSUE #2483: Upgrade PHPLint to v9
I think now we have PHP 8.1 as base version of MegaLinter v6, it's time to upgrade PHPLint from version 5.5 to 9.0

As I'm author of refactoring code to major version v9 of [PHPLint](https://github.com/overtrue/phplint), I wanted to said : 
- previous versions will be not supported in future months
- latest version 9.0.4 is now stable since at least one month 

Now about MegaLinter v6.

I've tried the recent version 6.21.0

```
 ----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-03-26T14:04:33Z
 - Image Revision: 66108018d9c2160896d8cf34d56f341592d23ffd
 - Image Version: 66108018d9c2160896d8cf34d56f341592d23ffd
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://megalinter.io/66108018d9c2160896d8cf34d56f341592d23ffd
```
And still have wrong links (that lead to 404) in Console Reporter on each linter
E.g: chunk of screenshot
megalinter-v621

 Strange because, when I rebuilt locally the PHP flavor, I've no such results. See in chunk of screenshot
megalinter-v6_phplint-v9

My local command was : 
```
docker build -f flavors/php/Dockerfile --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN .
```
With: `Docker version 23.0.1, build a5ee5b1` (docker buildkit enabled)

About MegaLinter v6 upgrade it will be more simple now, we previously used Composer only for PHPLint installation.
We can now remove it because it's no more necessary : PHIVE is able to install PHPLint v9

- https://github.com/oxsecurity/megalinter/blob/v6.21.0/megalinter/descriptors/php.megalinter-descriptor.yml#L20
- https://github.com/oxsecurity/megalinter/blob/v6.21.0/megalinter/descriptors/php.megalinter-descriptor.yml#L38

And PHIVE installation is much easier
Replace
https://github.com/oxsecurity/megalinter/blob/v6.21.0/megalinter/descriptors/php.megalinter-descriptor.yml#L38
By 
```
    install:
      dockerfile:
        - |
          RUN GITHUB_AUTH_TOKEN="$(cat /run/secrets/GITHUB_TOKEN)" && export GITHUB_AUTH_TOKEN && phive --no-progress install overtrue/phplint --force-accept-unsigned -g 
```

### PR DESCRIPTION
**Pull request by bdovaz**
Resolves #2483

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4973194776)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.34s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.59s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  116|     |                                                                      0|15.79s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   23|    0|                                                                      0|2.08s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   21|     |                                                                      0|0.18s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   23|     |                                                                      0|15.52s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  307|    0|[228](https://github.com/oxsecurity/megalinter/actions/runs/4973194776)|146.75s     |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  307|     |                                                                      0|6.26s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  307|    0|                                                                      0|19.94s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.24s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  188|     |[58](https://github.com/oxsecurity/megalinter/actions/runs/4973194776) |2.17s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  188|    2|                                                                      0|6.44s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  188|     |                                                                      0|1.92s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  188|    2|                                                                      0|0.79s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  188|     |                                                                      0|7.48s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  188|     |                                                                      0|12.7s       |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  188|     |[301](https://github.com/oxsecurity/megalinter/actions/runs/4973194776)|21.08s      |
|✅ PYTHON    |[ruff](https://megalinter.io/beta/descriptors/python_ruff)                                          |  188|    2|                                                                      0|0.42s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |31.59s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.34s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |15.2s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |25.87s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  612|     |                                                                      0|23.69s      |
|⚠️ SPELL     |[vale](https://megalinter.io/beta/descriptors/spell_vale)                                           |  219|     |[62](https://github.com/oxsecurity/megalinter/actions/runs/4973194776) |28.97s      |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.35s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |  156|    1|                                                                      0|4.48s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   98|     |                                                                      0|126.84s     |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |  157|     |                                                                      0|1.41s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4973194776)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam-update-phplint) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4973234671)

| Descriptor  |                                                          Linter                                                           |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|---------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-nuillam-update-phplint/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-nuillam-update-phplint/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-nuillam-update-phplint/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-nuillam-update-phplint/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.89s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-nuillam-update-phplint/descriptors/dockerfile_hadolint)                              |  116|     |                                                                      0|15.39s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam-update-phplint/descriptors/json_eslint_plugin_jsonc)              |   23|    0|                                                                      0|1.89s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-nuillam-update-phplint/descriptors/json_jsonlint)                                    |   21|     |                                                                      0|0.19s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-nuillam-update-phplint/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.6s        |
|✅ JSON      |[v8r](https://megalinter.io/test-nuillam-update-phplint/descriptors/json_v8r)                                              |   23|     |                                                                      0|15.97s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam-update-phplint/descriptors/markdown_markdownlint)                        |  307|    2|[228](https://github.com/oxsecurity/megalinter/actions/runs/4973234671)|149.72s     |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-nuillam-update-phplint/descriptors/markdown_markdown_link_check)          |  307|     |                                                                      0|6.18s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-nuillam-update-phplint/descriptors/markdown_markdown_table_formatter)|  307|    2|                                                                      0|19.7s       |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-nuillam-update-phplint/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.3s        |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_bandit)                                      |  188|     |[58](https://github.com/oxsecurity/megalinter/actions/runs/4973234671) |2.24s       |
|✅ PYTHON    |[black](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_black)                                        |  188|    0|                                                                      0|4.24s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_flake8)                                      |  188|     |                                                                      0|1.91s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_isort)                                        |  188|    0|                                                                      0|0.43s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_mypy)                                          |  188|     |                                                                      0|7.68s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_pylint)                                      |  188|     |                                                                      0|12.75s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_pyright)                                    |  188|     |[301](https://github.com/oxsecurity/megalinter/actions/runs/4973234671)|21.75s      |
|✅ PYTHON    |[ruff](https://megalinter.io/test-nuillam-update-phplint/descriptors/python_ruff)                                          |  188|    0|                                                                      0|0.11s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_checkov)                                |yes  |     |no                                                                     |32.35s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_devskim)                                |yes  |     |[913](https://github.com/oxsecurity/megalinter/actions/runs/4973234671)|4.95s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.49s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.03s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |14.55s      |
|✅ REPOSITORY|[syft](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.07s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-nuillam-update-phplint/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |25.25s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-nuillam-update-phplint/descriptors/spell_cspell)                                       |  625|     |                                                                      0|26.41s      |
|⚠️ SPELL     |[vale](https://megalinter.io/test-nuillam-update-phplint/descriptors/spell_vale)                                           |  219|     |[62](https://github.com/oxsecurity/megalinter/actions/runs/4973234671) |29.21s      |
|✅ XML       |[xmllint](https://megalinter.io/test-nuillam-update-phplint/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.02s       |
|✅ YAML      |[prettier](https://megalinter.io/test-nuillam-update-phplint/descriptors/yaml_prettier)                                    |  156|    0|                                                                      0|3.77s       |
|✅ YAML      |[v8r](https://megalinter.io/test-nuillam-update-phplint/descriptors/yaml_v8r)                                              |   98|     |                                                                      0|127.35s     |
|✅ YAML      |[yamllint](https://megalinter.io/test-nuillam-update-phplint/descriptors/yaml_yamllint)                                    |  157|     |                                                                      0|1.44s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4973234671)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam ready  to merge!

**Review by nvuillam — APPROVED** [review]
Great :)

**Comment by nvuillam** [comment]
Thanks a lot for the PR @bdovaz :)

**Pull request merged**
