### PR TITLE
Remove old unused automerge workflows

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
Also, what do the alpha workflows do?

**Comment by nvuillam** [comment]
@echoix alpha workflows build alpha versions when there is a branch named alpha :)

This is used when we want to do major updates and need to test with docker images without merging with main and generating a beta version

**Comment by nvuillam** [comment]
Damn, all those unstable websites are boring because of lychee, we should find a way to make the CI pipelines fail for nothing less often ^^

**Review by nvuillam — APPROVED** [review]
Good riddance ;)

**Comment by echoix** [comment]
> Damn, all those unstable websites are boring because of lychee, we should find a way to make the CI pipelines fail for nothing less often ^^

It's failing for linting errors after the long build that I find boring. We already lint, and building is already hard. It should fail if the actual linting (using the tool) fail, but not because of the content linted. I don't have a solution in mind, that's why I never suggested anything for it.

**Comment by echoix** [comment]
If lychee is bugging us, it should be bugging other users too.

**Comment by nvuillam** [comment]
Lychee is not bugged... it's just that in all the sites it checks, there are often who are down

But sometimes it's real dead links..

That's a tricky issue ^^

We might also consider disabling it in the deploy-DEV job, so at least if it fails, it's just 5mn of MegaLinter job re-run, not 30 mn of deploy-DEV job ^^

**Pull request merged**
