### PR TITLE
Replace deprecated spectral package

### PR DESCRIPTION
**Pull request by bdovaz**
Deprecated:

https://www.npmjs.com/package/@stoplight/spectral

New package:

https://www.npmjs.com/package/@stoplight/spectral-cli

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4147902489)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.39s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.15s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.87s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|10.43s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.06s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.26s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.62s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    1|[231](https://github.com/oxsecurity/megalinter/actions/runs/4147902489)|6.04s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.56s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    1|                                                                      0|17.98s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.77s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4147902489) |2.07s       |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    0|                                                                      0|3.82s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|3.82s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.52s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.25s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|12.3s       |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4147902489)|17.56s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.78s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.13s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |13.54s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |23.66s      |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|20.07s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.6s        |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.13s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.6s        |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|56.61s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|0.99s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4147902489)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam now they fail me for this other one :(

Do you know what it could be?

https://github.com/oxsecurity/megalinter/actions/runs/4148241571/jobs/7176029916

**Comment by nvuillam** [comment]
prettier not found... it smells a broken beta image :o :o :o

**Comment by nvuillam** [comment]
image

What the hell.... I don't understand how to build of the flavor has not failed :o

**Comment by nvuillam** [comment]
@bdovaz I repaired beta version, flavors are ok and full is currntly built  :)

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4151039600)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.17s       |
|✅ BASH      |[shfmt](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.52s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|6.91s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.79s       |
|✅ JSON      |[jsonlint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.23s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.61s       |
|✅ JSON      |[v8r](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.14s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/markdown_markdownlint)                        |  309|    2|[231](https://github.com/oxsecurity/megalinter/actions/runs/4151039600)|5.68s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.08s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|13.92s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.61s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4151039600) |1.91s       |
|✅ PYTHON    |[black](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_black)                                        |  176|    0|                                                                      0|3.19s       |
|✅ PYTHON    |[flake8](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.75s       |
|✅ PYTHON    |[isort](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.41s       |
|✅ PYTHON    |[mypy](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.89s       |
|✅ PYTHON    |[pylint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_pylint)                                      |  176|     |                                                                      0|10.33s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4151039600)|16.64s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.71s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4151039600) |1.34s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |3.03s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.47s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |6.7s        |
|✅ REPOSITORY|[syft](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.93s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |19.01s      |
|✅ SPELL     |[cspell](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/spell_cspell)                                       |  729|     |                                                                      0|16.77s      |
|✅ SPELL     |[misspell](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/spell_misspell)                                   |  550|    2|                                                                      0|0.44s       |
|✅ XML       |[xmllint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.65s       |
|✅ YAML      |[v8r](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|54.61s      |
|✅ YAML      |[yamllint](https://megalinter.io/bbb07b44639cd9bb2eafbc8e8543a3d2b1b21354/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.18s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4151039600)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Pull request merged**
