### PR TITLE
Sort schema enums

### PR DESCRIPTION
**Pull request by echoix**
Fixes #

## Proposed Changes

1. …
2. …
3. …

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
Needs to apply black

**Comment by echoix** [comment]
Oops, I’ll rebase to something without my other changes

**Comment by echoix** [comment]
Done and ready, all set

**Review by nvuillam — APPROVED** [review]
Great :)

**Pull request merged**
