### PR TITLE
Fix doc url

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/beta) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/2921751542)

|    Descriptor    |                                                        Linter                                                        |Files|Fixed|                                  Errors                                  |Elapsed time|
|------------------|----------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH           |[bash-exec](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.01s       |
|✅ BASH           |[shellcheck](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.23s       |
|✅ BASH           |[shfmt](https://oxsecurity.github.io/megalinter/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                         0|0.25s       |
|✅ COPYPASTE      |[jscpd](https://oxsecurity.github.io/megalinter/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |2.23s       |
|✅ DOCKERFILE     |[hadolint](https://oxsecurity.github.io/megalinter/beta/descriptors/dockerfile_hadolint)                              |  104|     |                                                                         0|17.09s      |
|✅ JSON           |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/beta/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                         0|2.32s       |
|✅ JSON           |[jsonlint](https://oxsecurity.github.io/megalinter/beta/descriptors/json_jsonlint)                                    |   18|     |                                                                         0|0.21s       |
|✅ JSON           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/json_v8r)                                              |   20|     |                                                                         0|11.21s      |
|:warning: MARKDOWN|[markdownlint](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdownlint)                        |  281|    0|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/2921751542) |4.36s       |
|✅ MARKDOWN       |[markdown-link-check](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_link_check)          |  281|     |                                                                         0|4.62s       |
|✅ MARKDOWN       |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/beta/descriptors/markdown_markdown_table_formatter)|  281|    0|                                                                         0|6.59s       |
|✅ OPENAPI        |[spectral](https://oxsecurity.github.io/megalinter/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.75s       |
|:warning: PYTHON  |[bandit](https://oxsecurity.github.io/megalinter/beta/descriptors/python_bandit)                                      |  166|     |[**51**](https://github.com/oxsecurity/megalinter/actions/runs/2921751542)|2.08s       |
|✅ PYTHON         |[black](https://oxsecurity.github.io/megalinter/beta/descriptors/python_black)                                        |  166|    1|                                                                         0|3.17s       |
|✅ PYTHON         |[flake8](https://oxsecurity.github.io/megalinter/beta/descriptors/python_flake8)                                      |  166|     |                                                                         0|1.72s       |
|✅ PYTHON         |[isort](https://oxsecurity.github.io/megalinter/beta/descriptors/python_isort)                                        |  166|    1|                                                                         0|0.52s       |
|✅ PYTHON         |[mypy](https://oxsecurity.github.io/megalinter/beta/descriptors/python_mypy)                                          |  166|     |                                                                         0|91.61s      |
|✅ PYTHON         |[pylint](https://oxsecurity.github.io/megalinter/beta/descriptors/python_pylint)                                      |  166|     |                                                                         0|17.13s      |
|✅ REPOSITORY     |[checkov](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                        |12.48s      |
|✅ REPOSITORY     |[git_diff](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.25s       |
|✅ REPOSITORY     |[secretlint](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |10.46s      |
|✅ REPOSITORY     |[trivy](https://oxsecurity.github.io/megalinter/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |20.98s      |
|✅ SPELL          |[cspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_cspell)                                       |  686|     |                                                                         0|20.03s      |
|✅ SPELL          |[misspell](https://oxsecurity.github.io/megalinter/beta/descriptors/spell_misspell)                                   |  516|    1|                                                                         0|0.68s       |
|✅ XML            |[xmllint](https://oxsecurity.github.io/megalinter/beta/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.01s       |
|✅ YAML           |[prettier](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_prettier)                                    |   79|    0|                                                                         0|2.76s       |
|✅ YAML           |[v8r](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_v8r)                                              |   22|     |                                                                         0|25.28s      |
|✅ YAML           |[yamllint](https://oxsecurity.github.io/megalinter/beta/descriptors/yaml_yamllint)                                    |   80|     |                                                                         0|1.18s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/2921751542)

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/2921812349)

|     Descriptor     |                                                                Linter                                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|--------------------|--------------------------------------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/bash_bash_exec)                                  |    7|     |                                                                         0|0.01s       |
|✅ BASH             |[shellcheck](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/bash_shellcheck)                                |    7|     |                                                                         0|0.26s       |
|✅ BASH             |[shfmt](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/bash_shfmt)                                          |    7|    0|                                                                         0|0.04s       |
|✅ COPYPASTE        |[jscpd](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.79s       |
|✅ DOCKERFILE       |[hadolint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/dockerfile_hadolint)                              |  104|     |                                                                         0|17.78s      |
|✅ JSON             |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|1.71s       |
|✅ JSON             |[jsonlint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|0.2s        |
|✅ JSON             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/json_v8r)                                              |   21|     |                                                                         0|9.43s       |
|:warning: MARKDOWN  |[markdownlint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/markdown_markdownlint)                        |  281|    2|[**5**](https://github.com/oxsecurity/megalinter/actions/runs/2921812349) |3.98s       |
|✅ MARKDOWN         |[markdown-link-check](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/markdown_markdown_link_check)          |  281|     |                                                                         0|4.65s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/markdown_markdown_table_formatter)|  281|    2|                                                                         0|5.21s       |
|✅ OPENAPI          |[spectral](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.75s       |
|:warning: PYTHON    |[bandit](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/python_bandit)                                      |  166|     |[**51**](https://github.com/oxsecurity/megalinter/actions/runs/2921812349)|2.11s       |
|✅ PYTHON           |[black](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/python_black)                                        |  166|    0|                                                                         0|2.88s       |
|✅ PYTHON           |[flake8](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/python_flake8)                                      |  166|     |                                                                         0|1.75s       |
|✅ PYTHON           |[isort](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/python_isort)                                        |  166|    0|                                                                         0|0.31s       |
|✅ PYTHON           |[mypy](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/python_mypy)                                          |  166|     |                                                                         0|90.52s      |
|✅ PYTHON           |[pylint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/python_pylint)                                      |  166|     |                                                                         0|15.61s      |
|✅ REPOSITORY       |[checkov](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_checkov)                                |yes  |     |no                                                                        |12.6s       |
|:warning: REPOSITORY|[devskim](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_devskim)                                |yes  |     |[**59**](https://github.com/oxsecurity/megalinter/actions/runs/2921812349)|1.1s        |
|✅ REPOSITORY       |[dustilock](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_dustilock)                            |yes  |     |no                                                                        |2.15s       |
|✅ REPOSITORY       |[git_diff](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_git_diff)                              |yes  |     |no                                                                        |0.04s       |
|✅ REPOSITORY       |[secretlint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_secretlint)                          |yes  |     |no                                                                        |3.18s       |
|✅ REPOSITORY       |[syft](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_syft)                                      |yes  |     |no                                                                        |1.89s       |
|✅ REPOSITORY       |[trivy](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/repository_trivy)                                    |yes  |     |no                                                                        |13.22s      |
|✅ SPELL            |[cspell](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/spell_cspell)                                       |  687|     |                                                                         0|18.51s      |
|✅ SPELL            |[misspell](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/spell_misspell)                                   |  517|    2|                                                                         0|0.38s       |
|✅ XML              |[xmllint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/xml_xmllint)                                       |    3|     |                                                                         0|0.0s        |
|✅ YAML             |[prettier](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/yaml_prettier)                                    |   79|    0|                                                                         0|2.22s       |
|✅ YAML             |[v8r](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/yaml_v8r)                                              |   22|     |                                                                         0|24.36s      |
|✅ YAML             |[yamllint](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/descriptors/yaml_yamllint)                                    |   80|     |                                                                         0|1.13s       |

See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/2921812349)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**oxsecurity/megalinter/flavors/python@v5**](https://oxsecurity.github.io/megalinter/test-nuillam-doc-url/flavors/python/) (54 linters)

**Comment by Kurt-von-Laven** [comment]
This reminded me that the link to the github.io page from https://github.com/oxsecurity/megalinter/ was out of date, so I updated it!

**Comment by nvuillam** [comment]
thanks :)

**Pull request merged**
