### PR TITLE
Create a slash PR bot to run our `./build.sh` command

### LINKED ISSUE #2351: Create a PR bot to run our `./build.sh` command [help wanted]
**Is your feature request related to a problem? Please describe.**
Making quick contributions can be hard for new users, or even maintainers, since we need to have a full (Linux) setup ready to run an update command to sync up the Dockerfiles (which is not that common for projects). 

**Describe the solution you'd like**
In some big repos over time, I often saw slack-like bots that you can post a command and it does tasks for you.
It would be nice to have a bot like this, so we could simply enter a comment with a single command saying to update the PR/sync the files by running our `./build.sh` command (on Linux), with the dependencies already defined in the task, and commit the new files to that PR.

**Describe alternatives you've considered**

During the last week, I tried to search for what tools like this exist, and I must not have used the good keywords, but didn't really find useful stuff in my quick searches.

**Additional context**

If anybody has some experience with tools like this and have opinions, or could guide us, or better, help us with a PR, it could be helpful here to reduce friction!

### PR DESCRIPTION
**Pull request by echoix**
Fixes #2351 

## Proposed Changes

1. Add a slash command dispatcher. 
2. Add a help command
3. Add a build command

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
I’ll add the change log later this afternoon, my time. 

The checkcov didn’t like the workflow_dispatch input arguments.

**Comment by echoix** [comment]
I could’ve force pushed to clean everything,(the only way to test was to make pushes). 

What’s fun with using workflow_dispatch type is that we can even test changes to a command that is in the PR (once the dispatcher and an empty one with the same name exists in the default branch). That way I didn’t have to commit to main each time I wanted to test.

The commands will only work for people with write access to the repo (it can be one of the 5 levels of permissions). It is configured in the slash command dispatcher.

**Comment by echoix** [comment]
More commands can be added by adding the name to the slash command dispatcher, and having a new workflow file called the same, but with `-command.yml` at the end

**Comment by echoix** [comment]
With cache on Python dependencies, running the /build command runs in about 1 min 30 s.

The eyes reaction is added when the command dispatcher processed the command comment. The rocket reaction is added when the command is launched, and the hurray reaction is added when command is completed (inside the command)

**Comment by echoix** [comment]
Oh, and the comment is edited during the run to show progress :)

**Comment by echoix** [comment]
## [🦙 MegaLinter](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0) status: ❌ [ERROR](https://github.com/echoix/megalinter/actions/runs/4156876680)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                              Errors                               |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/bash_bash_exec)                                  |    6|     |                                                                  0|0.02s       |
|✅ BASH      |[shellcheck](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/bash_shellcheck)                                |    6|     |                                                                  0|0.16s       |
|✅ BASH      |[shfmt](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/bash_shfmt)                                          |    6|    0|                                                                  0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                 |2.55s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/dockerfile_hadolint)                              |  105|     |                                                                  0|7.95s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                  0|1.75s       |
|✅ JSON      |[jsonlint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/json_jsonlint)                                    |   19|     |                                                                  0|0.23s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                 |0.68s       |
|✅ JSON      |[v8r](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/json_v8r)                                              |   21|     |                                                                  0|12.38s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/markdown_markdownlint)                        |  309|    2|[231](https://github.com/echoix/megalinter/actions/runs/4156876680)|5.46s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/markdown_markdown_link_check)          |  309|     |                                                                  0|5.08s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                  0|14.17s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/openapi_spectral)                                 |    1|     |                                                                  0|1.57s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/echoix/megalinter/actions/runs/4156876680) |2.24s       |
|✅ PYTHON    |[black](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_black)                                        |  176|    0|                                                                  0|3.36s       |
|✅ PYTHON    |[flake8](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_flake8)                                      |  176|     |                                                                  0|2.11s       |
|✅ PYTHON    |[isort](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_isort)                                        |  176|    0|                                                                  0|0.42s       |
|✅ PYTHON    |[mypy](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_mypy)                                          |  176|     |                                                                  0|6.68s       |
|✅ PYTHON    |[pylint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_pylint)                                      |  176|     |                                                                  0|10.36s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/echoix/megalinter/actions/runs/4156876680)|15.67s      |
|❌ REPOSITORY|[checkov](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_checkov)                                |yes  |     |[2](https://github.com/echoix/megalinter/actions/runs/4156876680)  |26.53s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/echoix/megalinter/actions/runs/4156876680) |1.22s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_dustilock)                            |yes  |     |no                                                                 |2.84s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_git_diff)                              |yes  |     |no                                                                 |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_secretlint)                          |yes  |     |no                                                                 |7.18s       |
|✅ REPOSITORY|[syft](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_syft)                                      |yes  |     |no                                                                 |0.89s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/repository_trivy)                                    |yes  |     |no                                                                 |18.79s      |
|✅ SPELL     |[cspell](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/spell_cspell)                                       |  729|     |                                                                  0|16.62s      |
|✅ SPELL     |[misspell](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/spell_misspell)                                   |  550|    2|                                                                  0|0.53s       |
|✅ XML       |[xmllint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/xml_xmllint)                                       |    3|    0|                                                                  0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/yaml_prettier)                                    |   81|    0|                                                                  0|2.48s       |
|✅ YAML      |[v8r](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/yaml_v8r)                                              |   23|     |                                                                  0|56.15s      |
|✅ YAML      |[yamllint](https://megalinter.io/ab54b5afd507f4d5b1d420da5829c2159e0259a0/descriptors/yaml_yamllint)                                    |   82|     |                                                                  0|1.19s       |

See detailed report in [MegaLinter reports](https://github.com/echoix/megalinter/actions/runs/4156876680)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
## [🦙 MegaLinter](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe) status: ⚠️ [WARNING](https://github.com/echoix/megalinter/actions/runs/4158257605)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                              Errors                               |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/bash_bash_exec)                                  |    6|     |                                                                  0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/bash_shellcheck)                                |    6|     |                                                                  0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/bash_shfmt)                                          |    6|    0|                                                                  0|0.37s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                 |2.81s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/dockerfile_hadolint)                              |  105|     |                                                                  0|9.0s        |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                  0|2.06s       |
|✅ JSON      |[jsonlint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/json_jsonlint)                                    |   19|     |                                                                  0|0.25s       |
|✅ JSON      |[v8r](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/json_v8r)                                              |   21|     |                                                                  0|11.71s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/markdown_markdownlint)                        |  309|    0|[231](https://github.com/echoix/megalinter/actions/runs/4158257605)|6.65s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/markdown_markdown_link_check)          |  309|     |                                                                  0|5.24s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                  0|15.27s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/openapi_spectral)                                 |    1|     |                                                                  0|1.64s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/echoix/megalinter/actions/runs/4158257605) |1.91s       |
|✅ PYTHON    |[black](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_black)                                        |  176|    0|                                                                  0|4.23s       |
|✅ PYTHON    |[flake8](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_flake8)                                      |  176|     |                                                                  0|1.77s       |
|✅ PYTHON    |[isort](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_isort)                                        |  176|    0|                                                                  0|0.75s       |
|✅ PYTHON    |[mypy](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_mypy)                                          |  176|     |                                                                  0|6.53s       |
|✅ PYTHON    |[pylint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_pylint)                                      |  176|     |                                                                  0|10.62s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/echoix/megalinter/actions/runs/4158257605)|15.87s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/repository_checkov)                                |yes  |     |no                                                                 |26.56s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/repository_git_diff)                              |yes  |     |no                                                                 |0.37s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/repository_secretlint)                          |yes  |     |no                                                                 |12.01s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/repository_trivy)                                    |yes  |     |no                                                                 |22.89s      |
|✅ SPELL     |[cspell](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/spell_cspell)                                       |  729|     |                                                                  0|16.68s      |
|✅ SPELL     |[misspell](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/spell_misspell)                                   |  550|    0|                                                                  0|0.86s       |
|✅ XML       |[xmllint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/xml_xmllint)                                       |    3|    0|                                                                  0|0.39s       |
|✅ YAML      |[prettier](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/yaml_prettier)                                    |   81|    0|                                                                  0|2.98s       |
|✅ YAML      |[v8r](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/yaml_v8r)                                              |   23|     |                                                                  0|57.63s      |
|✅ YAML      |[yamllint](https://megalinter.io/a2d282fd5c216442b490570d8b097ff618de3dfe/descriptors/yaml_yamllint)                                    |   82|     |                                                                  0|1.05s       |

See detailed report in [MegaLinter reports](https://github.com/echoix/megalinter/actions/runs/4158257605)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
So I added a skip comment for CKV_GHA_7, `Check: CKV_GHA_7: "The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty. "`. 
https://docs.bridgecrew.io/docs/the-build-output-cannot-be-affected-by-user-parameters-other-than-the-build-entry-point-and-the-top-level-source-location-github-actions-workflow_dispatch-inputs-must-be-empty

Since it is not really a build, where we wouldn't want the output to change, here we want it to react to what the slash command dispatcher sends it, to know which comment to target, and to make sure the correct repo is called. Also, it is only users with write permissions that can call a workflow run.

**Comment by nvuillam** [comment]
I'm not sure I understand everything... plz could you add a section in contributing documentation, with example ?

**Comment by echoix** [comment]
Ok, I'll write something soon. But it's for us, maintainers only, so that we could not require contributors to set up everything to run the ./build.sh. Only ask them to change the descriptors, and a quick comment to the PR with the following:

```
/build
```
will bring the PR up to date.

**Comment by echoix** [comment]
Is this enough?
image

**Comment by echoix** [comment]
@nvuillam Is this enough to be merged? I'm quite eager to start using it soon :)

**Comment by nvuillam** [comment]
Just add a screenshot of a comment with the `/build`, and it's ok for me :)

**Comment by echoix** [comment]
For now there are 3 code blocks with the exact contents of what is placed. To have a real use screenshot, it would have to either be already merged, or I re-setup a new repo with it merged into main. I tested in the beginning by committing to my branch and also main, and once sure that it works, I used the `ref=<the-branch-name>` to use the workflow of a branch. So I don't have a screenshot accessible now. You can see at the end of https://github.com/echoix/megalinter/pull/1 what it looks like.

**Comment by nvuillam** [comment]
Ok, you can add a screenshot in a next PR :)

**Review by nvuillam — APPROVED** [review]
Great , can't wait to see it in action :)

**Comment by echoix** [comment]
We'll be able to let users use the built-in web editor (pressing the period (`.`) key anywhere in github) to make simple edits, and fix the build without launching a real linux environment.

**Comment by echoix** [comment]
image
The 20 concurrent runners are already running, and I can't seem to find a way in github to specify priorities. It seems that they will be run only at the end of all the other builds

**Comment by nvuillam** [comment]
@echoix this is related to https://github.com/oxsecurity/megalinter/issues/2377 :/

**Comment by echoix** [comment]
> @echoix this is related to #2377 :/

Yes and no, yes, since there are already running jobs so the 20 is supposed to be hit https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
but no, since even with one Build & Deploy - DEV  job on a branch (at one point, which doesn't have a matrix), other jobs where queued.

But its nothing like in the repos inside OSGeo, on good days (with a lot of contributions, across GDAL, PROJ (popular libraries in GIS), and grass), every 20 minute job has to wait 2h30 to start.

**Comment by echoix** [comment]
Here we go, the 2s+4s jobs ran :)

**Pull request merged**
