### PR TITLE
Fix MegaLinter version displayed in logs

### PR DESCRIPTION
**Pull request by nvuillam**
Related to https://github.com/oxsecurity/megalinter/issues/2425

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4534925019)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.12s       |
|✅ BASH      |[shfmt](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.28s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.49s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/dockerfile_hadolint)                              |  115|     |                                                                      0|10.9s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.95s       |
|✅ JSON      |[jsonlint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.18s       |
|✅ JSON      |[v8r](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.17s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/markdown_markdownlint)                        |  311|    0|[230](https://github.com/oxsecurity/megalinter/actions/runs/4534925019)|6.47s       |
|⚠️ MARKDOWN  |[markdown-link-check](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/markdown_markdown_link_check)          |  311|     |[31](https://github.com/oxsecurity/megalinter/actions/runs/4534925019) |279.07s     |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/markdown_markdown_table_formatter)|  311|    0|                                                                      0|19.54s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.11s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_bandit)                                      |  184|     |[55](https://github.com/oxsecurity/megalinter/actions/runs/4534925019) |1.93s       |
|✅ PYTHON    |[black](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_black)                                        |  184|    0|                                                                      0|4.29s       |
|✅ PYTHON    |[flake8](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_flake8)                                      |  184|     |                                                                      0|1.31s       |
|✅ PYTHON    |[isort](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_isort)                                        |  184|    0|                                                                      0|0.69s       |
|✅ PYTHON    |[mypy](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_mypy)                                          |  184|     |                                                                      0|6.58s       |
|✅ PYTHON    |[pylint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_pylint)                                      |  184|     |                                                                      0|10.77s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/python_pyright)                                    |  184|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4534925019)|15.58s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.01s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.27s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |12.12s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |21.23s      |
|✅ SPELL     |[cspell](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/spell_cspell)                                       |  750|     |                                                                      0|18.83s      |
|✅ SPELL     |[misspell](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/spell_misspell)                                   |  570|    0|                                                                      0|0.8s        |
|✅ XML       |[xmllint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.28s       |
|✅ YAML      |[prettier](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.67s       |
|✅ YAML      |[v8r](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|43.26s      |
|✅ YAML      |[yamllint](https://megalinter.io/2a492117f1cd0ac692b361421c504b730db3facb/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.0s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4534925019)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by llaville** [comment]
@nvuillam Like it ! 

```
----------------------------------------------------------------------------------------------------
------------------------------------ MegaLinter, by OX Security ------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2023-04-01T14:20:57Z
 - Image Revision: a6134e1daea26bc9d745017dfc24883ac5e2859c
 - Image Version: v6.22.0
----------------------------------------------------------------------------------------------------
The MegaLinter documentation can be found at:
 - https://megalinter.io/6.22.0
----------------------------------------------------------------------------------------------------
```

And also in descriptors links, like this one 
```
- Using [phplint v5.5] https://megalinter.io/6.22.0/descriptors/php_phplint
```

**Comment by nvuillam** [comment]
@llaville the retag-push was not enough... I had to update the release workflows to build again from newest beta versions and add appropriate ENV vars & LABEL :)

**Comment by echoix** [comment]
Did you try pulling the image before, to populate the cache with what already exists? This way, maybe only the last layers would need to be "built"

**Comment by nvuillam** [comment]
https://github.com/oxsecurity/megalinter/blob/main/Dockerfile-release

Nope, but the performances are acceptable :)

**Comment by nvuillam** [comment]
I'm not even sure that those lines are necessary, as they are already in the base image... but as i have doubts I put them anyway ^^

Do you think they should be removed ?

```
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

**Comment by echoix** [comment]
I don't have a clue indeed, I haven't played with a similar case yet to know the behaviour.

But what I can imagine that could be an improvement over the Dockerfile-release, is to add a default value to the argument, for the base image at least, so it could be already there if we want to manually run the build, without entering every single argument at the command line.

But I'm wondering if it doesn't add extra useless layers (the env ones) when doing this. And what about basing a release on an already released base, does it still work (imagine without any commits in between)

**Comment by nvuillam** [comment]
We will never manually build a release version :p 

Indeed I also think about useless layers :p

**Pull request merged**
