### PR TITLE
JOB_SUMMARY_ADDITIONAL_MARKDOWN

### PR DESCRIPTION
**Pull request by nvuillam**
Allow to add custom messages at the end of PR / MR MegaLinter Summary using variable **JOB_SUMMARY_ADDITIONAL_MARKDOWN**

Fixes https://github.com/oxsecurity/megalinter/issues/4028

### CODE REVIEW

**Comment by echoix** [comment]
What do you mean by job summary?

**Comment by echoix** [comment]
Is it the markdown summery like described in https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/

**Comment by nvuillam** [comment]
@echoix look this request :) https://github.com/oxsecurity/megalinter/issues/4028

**Comment by echoix** [comment]
Yes I saw, but we didn't use that prefix yet, and it seemed to be confusing with the meaning of what I linked. (Only the name)

**Comment by nvuillam** [comment]
It's cross-reporter, so i didn't know how to name it

It is existing only in beta, do can still change if necessary, do you have suggestions ? :)

**Pull request merged**
