### PR TITLE
Fix packages url

### LINKED ISSUE #2335: The URL of the packages that have a fixed version, is not well resolved in the documentation
image

Wrong url: https://pypi.org/project/pyright==1.1.270/

Correct url: https://pypi.org/project/pyright/

### PR DESCRIPTION
**Pull request by bdovaz**
Fixes #2335

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/beta) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4147869100)

| Descriptor  |                                               Linter                                               |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/beta/descriptors/bash_bash_exec)                                  |    7|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/beta/descriptors/bash_shellcheck)                                |    7|     |                                                                      0|0.37s       |
|✅ BASH      |[shfmt](https://megalinter.io/beta/descriptors/bash_shfmt)                                          |    7|    0|                                                                      0|0.27s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/beta/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.47s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/beta/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|8.46s       |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/beta/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.39s       |
|✅ JSON      |[jsonlint](https://megalinter.io/beta/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[v8r](https://megalinter.io/beta/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.98s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/beta/descriptors/markdown_markdownlint)                        |  309|    1|[231](https://github.com/oxsecurity/megalinter/actions/runs/4147869100)|6.17s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/beta/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.18s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/beta/descriptors/markdown_markdown_table_formatter)|  309|    1|                                                                      0|14.53s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/beta/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.57s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/beta/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4147869100) |1.9s        |
|✅ PYTHON    |[black](https://megalinter.io/beta/descriptors/python_black)                                        |  176|    1|                                                                      0|4.98s       |
|✅ PYTHON    |[flake8](https://megalinter.io/beta/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.79s       |
|✅ PYTHON    |[isort](https://megalinter.io/beta/descriptors/python_isort)                                        |  176|    1|                                                                      0|0.64s       |
|✅ PYTHON    |[mypy](https://megalinter.io/beta/descriptors/python_mypy)                                          |  176|     |                                                                      0|6.51s       |
|✅ PYTHON    |[pylint](https://megalinter.io/beta/descriptors/python_pylint)                                      |  176|     |                                                                      0|10.53s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/beta/descriptors/python_pyright)                                    |  176|     |[276](https://github.com/oxsecurity/megalinter/actions/runs/4147869100)|15.67s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/beta/descriptors/repository_checkov)                                |yes  |     |no                                                                     |25.5s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/beta/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.28s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/beta/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |11.12s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/beta/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.5s       |
|✅ SPELL     |[cspell](https://megalinter.io/beta/descriptors/spell_cspell)                                       |  730|     |                                                                      0|17.08s      |
|✅ SPELL     |[misspell](https://megalinter.io/beta/descriptors/spell_misspell)                                   |  551|    0|                                                                      0|0.81s       |
|✅ XML       |[xmllint](https://megalinter.io/beta/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.39s       |
|✅ YAML      |[prettier](https://megalinter.io/beta/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|3.29s       |
|✅ YAML      |[v8r](https://megalinter.io/beta/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|55.21s      |
|✅ YAML      |[yamllint](https://megalinter.io/beta/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.05s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4147869100)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4151187364)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.18s       |
|✅ BASH      |[shfmt](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.94s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/dockerfile_hadolint)                              |  105|     |                                                                      0|7.9s        |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.92s       |
|✅ JSON      |[jsonlint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.64s       |
|✅ JSON      |[v8r](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.17s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/markdown_markdownlint)                        |  309|    0|[231](https://github.com/oxsecurity/megalinter/actions/runs/4151187364)|6.0s        |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.25s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|16.84s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.68s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_bandit)                                      |  176|     |[45](https://github.com/oxsecurity/megalinter/actions/runs/4151187364) |1.92s       |
|✅ PYTHON    |[black](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_black)                                        |  176|    0|                                                                      0|3.14s       |
|✅ PYTHON    |[flake8](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_flake8)                                      |  176|     |                                                                      0|1.68s       |
|✅ PYTHON    |[isort](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_isort)                                        |  176|    0|                                                                      0|0.47s       |
|✅ PYTHON    |[mypy](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_mypy)                                          |  176|     |                                                                      0|7.08s       |
|✅ PYTHON    |[pylint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_pylint)                                      |  176|     |                                                                      0|11.29s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/python_pyright)                                    |  176|     |[274](https://github.com/oxsecurity/megalinter/actions/runs/4151187364)|17.48s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.87s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4151187364) |1.24s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |3.47s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.03s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.71s       |
|✅ REPOSITORY|[syft](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.91s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |19.02s      |
|✅ SPELL     |[cspell](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/spell_cspell)                                       |  729|     |                                                                      0|17.78s      |
|✅ SPELL     |[misspell](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/spell_misspell)                                   |  550|    0|                                                                      0|0.47s       |
|✅ XML       |[xmllint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.56s       |
|✅ YAML      |[v8r](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|55.98s      |
|✅ YAML      |[yamllint](https://megalinter.io/02df3d6ec53ff4b1005915989e49b4c305322201/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.08s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4151187364)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by bdovaz** [comment]
@nvuillam can you approve? Thanks

**Review by nvuillam — APPROVED** [review]
great :)

**Pull request merged**
