### PR TITLE
Updates related to JSON Schema

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/oxsecurity/megalinter/issues/1621 and https://github.com/oxsecurity/megalinter/pull/1534

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://oxsecurity.github.io/megalinter/latest) status: :warning: [**WARNING**](https://github.com/oxsecurity/megalinter/actions/runs/2699626919)

|     Descriptor     |                                                         Linter                                                         |Files|Fixed|                                  Errors                                   |Elapsed time|
|--------------------|------------------------------------------------------------------------------------------------------------------------|-----|----:|---------------------------------------------------------------------------|------------|
|✅ BASH             |[bash-exec](https://oxsecurity.github.io/megalinter/latest/descriptors/bash_bash_exec)                                  |    7|     |                                                                          0|0.07s       |
|✅ BASH             |[shellcheck](https://oxsecurity.github.io/megalinter/latest/descriptors/bash_shellcheck)                                |    7|     |                                                                          0|0.58s       |
|✅ BASH             |[shfmt](https://oxsecurity.github.io/megalinter/latest/descriptors/bash_shfmt)                                          |    7|    0|                                                                          0|0.11s       |
|✅ COPYPASTE        |[jscpd](https://oxsecurity.github.io/megalinter/latest/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                         |5.01s       |
|✅ DOCKERFILE       |[hadolint](https://oxsecurity.github.io/megalinter/latest/descriptors/dockerfile_hadolint)                              |  102|     |                                                                          0|30.59s      |
|✅ JSON             |[eslint-plugin-jsonc](https://oxsecurity.github.io/megalinter/latest/descriptors/json_eslint_plugin_jsonc)              |   20|    0|                                                                          0|2.9s        |
|✅ JSON             |[jsonlint](https://oxsecurity.github.io/megalinter/latest/descriptors/json_jsonlint)                                    |   18|     |                                                                          0|6.97s       |
|✅ JSON             |[v8r](https://oxsecurity.github.io/megalinter/latest/descriptors/json_v8r)                                              |   20|     |                                                                          0|11.78s      |
|:warning: MARKDOWN  |[markdownlint](https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdownlint)                        |  276|    2|[**4**](https://github.com/oxsecurity/megalinter/actions/runs/2699626919)  |5.53s       |
|✅ MARKDOWN         |[markdown-link-check](https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdown_link_check)          |  276|     |                                                                          0|5.58s       |
|✅ MARKDOWN         |[markdown-table-formatter](https://oxsecurity.github.io/megalinter/latest/descriptors/markdown_markdown_table_formatter)|  276|    2|                                                                          0|6.21s       |
|✅ OPENAPI          |[spectral](https://oxsecurity.github.io/megalinter/latest/descriptors/openapi_spectral)                                 |    1|     |                                                                          0|1.17s       |
|:warning: PYTHON    |[bandit](https://oxsecurity.github.io/megalinter/latest/descriptors/python_bandit)                                      |  161|     |[**50**](https://github.com/oxsecurity/megalinter/actions/runs/2699626919) |3.19s       |
|✅ PYTHON           |[black](https://oxsecurity.github.io/megalinter/latest/descriptors/python_black)                                        |  161|    0|                                                                          0|4.29s       |
|✅ PYTHON           |[flake8](https://oxsecurity.github.io/megalinter/latest/descriptors/python_flake8)                                      |  161|     |                                                                          0|3.41s       |
|✅ PYTHON           |[isort](https://oxsecurity.github.io/megalinter/latest/descriptors/python_isort)                                        |  161|    0|                                                                          0|0.64s       |
|✅ PYTHON           |[mypy](https://oxsecurity.github.io/megalinter/latest/descriptors/python_mypy)                                          |  161|     |                                                                          0|125.54s     |
|✅ PYTHON           |[pylint](https://oxsecurity.github.io/megalinter/latest/descriptors/python_pylint)                                      |  161|     |                                                                          0|40.44s      |
|:warning: REPOSITORY|[devskim](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_devskim)                                |yes  |     |[**100**](https://github.com/oxsecurity/megalinter/actions/runs/2699626919)|1.44s       |
|✅ REPOSITORY       |[dustilock](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_dustilock)                            |yes  |     |no                                                                         |2.03s       |
|✅ REPOSITORY       |[git_diff](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_git_diff)                              |yes  |     |no                                                                         |0.04s       |
|✅ REPOSITORY       |[secretlint](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_secretlint)                          |yes  |     |no                                                                         |4.69s       |
|:warning: REPOSITORY|[semgrep](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_semgrep)                                |yes  |     |[**244**](https://github.com/oxsecurity/megalinter/actions/runs/2699626919)|63.94s      |
|✅ REPOSITORY       |[syft](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_syft)                                      |yes  |     |no                                                                         |2.48s       |
|✅ REPOSITORY       |[trivy](https://oxsecurity.github.io/megalinter/latest/descriptors/repository_trivy)                                    |yes  |     |no                                                                         |15.42s      |
|✅ SPELL            |[cspell](https://oxsecurity.github.io/megalinter/latest/descriptors/spell_cspell)                                       |  862|     |                                                                          0|28.87s      |
|✅ SPELL            |[misspell](https://oxsecurity.github.io/megalinter/latest/descriptors/spell_misspell)                                   |  697|    2|                                                                          0|0.66s       |
|✅ XML              |[xmllint](https://oxsecurity.github.io/megalinter/latest/descriptors/xml_xmllint)                                       |    3|     |                                                                          0|0.02s       |
|✅ YAML             |[prettier](https://oxsecurity.github.io/megalinter/latest/descriptors/yaml_prettier)                                    |   78|    0|                                                                          0|3.26s       |
|✅ YAML             |[v8r](https://oxsecurity.github.io/megalinter/latest/descriptors/yaml_v8r)                                              |   22|     |                                                                          0|30.62s      |
|✅ YAML             |[yamllint](https://oxsecurity.github.io/megalinter/latest/descriptors/yaml_yamllint)                                    |   79|     |                                                                          0|1.35s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/oxsecurity/megalinter/actions/runs/2699626919)

**Comment by bdovaz** [comment]
@nvuillam You have marked OUTPUT_FORMAT as deprecated but the OUTPUT_DETAIL parameter only works with tap reporter if the deprecated OUTPUT_FORMAT parameter is set:

https://github.com/oxsecurity/megalinter/blob/7b2c5402f3cd7d4e9454c9d60d3c7b738bcdd039/megalinter/reporters/TapReporter.py#L26

**Comment by nvuillam** [comment]
@bdovaz I hesitated to remove TAP reporter in v6, as SARIF has become the new standard... :)

Do you use TAP reporter ? if yes, how ?

**Comment by bdovaz** [comment]
> @bdovaz I hesitated to remove TAP reporter in v6, as SARIF has become the new standard... :)
> 
> Do you use TAP reporter ? if yes, how ?

As an intermediate format to achieve something like this:

https://adinermie.com/publishing-github-super-linter-terraform-quality-checks-to-azure-devops-pipelines/

**Comment by bdovaz** [comment]
Created a PR @nvuillam https://github.com/oxsecurity/megalinter/pull/1657

**Pull request merged**
