### PR TITLE
Upgrade markdown-links-check

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/test-nuillam-markdown-links-check) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4665955096)

| Descriptor  |                                                             Linter                                                              |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|---------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.14s       |
|✅ BASH      |[shfmt](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.22s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/dockerfile_hadolint)                              |  116|     |                                                                      0|14.61s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.71s       |
|✅ JSON      |[jsonlint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.18s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.7s        |
|✅ JSON      |[v8r](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/json_v8r)                                              |   21|     |                                                                      0|13.33s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/markdown_markdownlint)                        |  312|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4665955096)|5.67s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/markdown_markdown_link_check)          |  312|     |                                                                      0|5.15s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/markdown_markdown_table_formatter)|  312|    2|                                                                      0|15.91s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.51s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_bandit)                                      |  186|     |[54](https://github.com/oxsecurity/megalinter/actions/runs/4665955096) |4.34s       |
|✅ PYTHON    |[black](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_black)                                        |  186|    0|                                                                      0|3.58s       |
|✅ PYTHON    |[flake8](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_flake8)                                      |  186|     |                                                                      0|2.45s       |
|✅ PYTHON    |[isort](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_isort)                                        |  186|    0|                                                                      0|0.44s       |
|✅ PYTHON    |[mypy](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_mypy)                                          |  186|     |                                                                      0|6.89s       |
|✅ PYTHON    |[pylint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_pylint)                                      |  186|     |                                                                      0|10.89s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_pyright)                                    |  186|     |[251](https://github.com/oxsecurity/megalinter/actions/runs/4665955096)|15.86s      |
|✅ PYTHON    |[ruff](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/python_ruff)                                          |  186|    0|                                                                      0|0.09s       |
|✅ REPOSITORY|[checkov](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_checkov)                                |yes  |     |no                                                                     |31.74s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4665955096) |1.25s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |2.12s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.09s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |7.12s       |
|✅ REPOSITORY|[syft](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.82s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |22.85s      |
|✅ SPELL     |[cspell](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/spell_cspell)                                       |  754|     |                                                                      0|18.43s      |
|✅ SPELL     |[misspell](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/spell_misspell)                                   |  573|    2|                                                                      0|0.49s       |
|✅ XML       |[xmllint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.08s       |
|✅ YAML      |[prettier](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.43s       |
|✅ YAML      |[v8r](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|60.56s      |
|✅ YAML      |[yamllint](https://megalinter.io/test-nuillam-markdown-links-check/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.32s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4665955096)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by Kurt-von-Laven** [comment]
markdown-link-check is still broken at 3.11.1 according to tcort/markdown-link-check#246.

**Comment by nvuillam** [comment]
@Kurt-von-Laven I read that it's supposed to be fixeD... is it not ? :/

https://github.com/tcort/markdown-link-check/issues/246#issuecomment-1502883314

**Comment by Kurt-von-Laven** [comment]
3.11.0 was broken for everyone with a config file. 3.11.1 is broken for everyone without a config file.

**Comment by nvuillam** [comment]
So as we provide a default config file, it's ok ? °^^

**Comment by Kurt-von-Laven** [comment]
Good point! Yeah, it seems like there are some other less major bugs in 3.11.1, but hopefully enough people will find it preferable to 3.10 overall at this point.

**Pull request merged**
