### PR TITLE
bug: ansible-lint fix warning count violations

### LINKED ISSUE #3446: Unable to get number of errors with regex_number
Hi, not so serious bug, but...

**Describe the bug**
Here is a actions log where `trufflehog` pass, but still trying to capture number of errors.
```
 ##[group][32m✅ Linted [REPOSITORY] files with [trufflehog] successfully - (10.5s)[0m (expand for details)
 - Using [trufflehog v3.71.0] https://megalinter.io/7.10.0/descriptors/repository_trufflehog
 - MegaLinter key: [REPOSITORY_TRUFFLEHOG]
 - Rules config: identified by [trufflehog]
 ##[endgroup]
 Unable to get number of errors with regex_count and [0-9]+:[0-9]+.*error
```

**To Reproduce**
I think any success result, but you can try my [working branch](https://github.com/alexanderbazhenoff/ansible-collection-linux/tree/1_1_10).

**Expected behavior**
Expected no tries of getting number of errors :)

**Screenshots**

megalinter-out

### PR DESCRIPTION
**Pull request by TommyE123**
Fixes #3446

Currently the count for the warning violations regex errors and doesn’t display the correct count.

## Proposed Changes

Changed the regex to count the violations that `ansible-lint` outputs.
 
image

## Testing

I’ve checked this on both `Github` and `Azure pipelines` using 2 different repositories and the results are as expected.

Before:
 image

After:
image
 

If there are any issues or concerns, please let me know, and I will address them promptly.
Thank you for reviewing this PR and I look forward to your feedback.
Tom

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
@TommyE123 Do you think the ansible lint failure here is transient?

**Comment by nvuillam** [comment]
image

Not sure the new regex matches such output :(

**Comment by echoix** [comment]
Does it have to do with some env vars that change the logging format?

**Comment by TommyE123** [comment]
Well I'm angry now with myself!

I must have missed a scenario. However I think we need to use both mine and the existing regex but will check. Please don't merge and I will come back with a better more robust solution! 

I've also been looking at a better way to detect if ansible should be active in general.

Thank you both for all your hard work today getting everything merged. 🙂

Tom

**Comment by nvuillam** [comment]
@TommyE123 no problem haha ,thanks for your hard work :)

**Comment by TommyE123** [comment]
After some testing, I've discovered that the current regex only works when `quiet: false` is set or not specified in the `.ansible-lint` config file.

Setting `quiet: true` doesn't significantly reduce the log information across `Azure`, `GitHub`, and `GitLab` environments. In fact, it results in missing out on a valuable breakdown table of issues, as shown below as an example.
image

Given these findings, I'm closing this PR as the change doesn't work as initially intended. However, this does explain the behavior @alexanderbazhenoff encountered in https://github.com/oxsecurity/megalinter/issues/3446#issuecomment-2016942807.

I believe we can also close https://github.com/oxsecurity/megalinter/pull/3680 now, as this was the only outstanding issue there.

Tom

**Comment by alexanderbazhenoff** [comment]
No prob, I haven't had any time for sure for the last few months either. May be I'll take a look into ansible-lint output also once I get back to refactoring my four roles. Thanks for trying anyway.

**Pull request closed without merging**
