### PR TITLE
Use consistent spelling of 'flavor'

### PR DESCRIPTION
**Pull request by InputUsername**
Fixes #

I noticed the project spells it as `flavor` while some of the documentation pages used `flavour`, so I made the spelling consistent (`grep -lr flavour | xargs sed -i 's/flavour/flavor/'`).

## Proposed Changes

1. Consistently use the American spelling of `flavor` everywhere

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by echoix** [comment]
All the docs are automatically generated. Would you mind fixing in the source, then running

```
./build.sh --doc
```

And see if your changes are not overwritten?

**Comment by nvuillam** [comment]
@InputUsername well played :)

Please can you also update `.automation/build.py`, that is used to generate such docs ? :)

**Comment by echoix** [comment]
@nvuillam haha, I was faster !

**Comment by InputUsername** [comment]
@echoix Good call, thanks! I ran the script and as far as I can see nothing was overwritten. I've pushed the update. :smile:

**Comment by echoix** [comment]
I approved to run and will make it merge in the next hours!

**Review by echoix — APPROVED** [review]

**Review by nvuillam — APPROVED** [review]

**Pull request merged**
