### PR TITLE
Resolve error with purrr::keep in lintr

### LINKED ISSUE #2886: lintr crashes with any lints
**Describe the bug**
The R shim code used to extract the number of errors from the lintr`output seems to rely on outdated behavior in either the lintr or purrr libraries. Any code lints cause a crash.

**To Reproduce**

1. Create an R file with a trailing semicolon:`mkdir tester && cd tester && echo "a <- 1;" > source.R`
2. Run Megalinter, either in GitHub actions or locally
3. See error

```console
❌ Linted [R] files with [lintr]: Found 1 error(s) - (2.47s)
- Using [lintr v0.0.0] https://megalinter.io/7.3.0/descriptors/r_lintr
- MegaLinter key: [R_LINTR]
- Rules config: [.lintr]
- Number of files analyzed: [1]
[lintr] source.R - ERROR - 1 error(s)
--Error detail:
/tmp/lint/source.R:1:7: style: [semicolon_linter] Trailing semicolons are not needed.
a <- 1;
      ^
Error in `purrr::keep()`:
ℹ In index: 1.
ℹ With name: /tmp/lint/source.R.
Caused by error in `.fn()`:
! object '.type' not found
Backtrace:
     ▆
  1. ├─purrr::keep(lints, ~.type == "error")
  2. │ └─purrr:::where_if(.x, .p, ...)
  3. │   └─purrr:::map_(.x, .p, ..., .type = "logical", .purrr_error_call = .purrr_error_call)
  4. │     ├─purrr:::with_indexed_errors(...)
  5. │     │ └─base::withCallingHandlers(...)
  6. │     ├─purrr:::call_with_cleanup(...)
  7. │     └─purrr (local) .f(.x[[i]], ...)
  8. │       └─global .fn(...)
  9. └─base::.handleSimpleError(...)
 10.   └─purrr (local) h(simpleError(msg, call))
 11.     └─cli::cli_abort(...)
 12.       └─rlang::abort(...)
Execution halted
```

**Expected behavior**
Lints should not crash the linter.

**Screenshots**
Example of the same bug in GitHub actions:
Screenshot 2023-08-14 at 12 10 39 PM

**Additional context**
I think this change is sufficient to resolve the issue:

```diff
diff --git a/megalinter/linters/RLinter.py b/megalinter/linters/RLinter.py
index e9714da1bf..9cde7e4ca9 100644
--- a/megalinter/linters/RLinter.py
+++ b/megalinter/linters/RLinter.py
@@ -20,7 +20,7 @@ class RLinter(Linter):
         r_commands = [
             f"lints <- lintr::lint('{file}');",
             "print(lints);",
-            "errors <- purrr::keep(lints, ~ .type == 'error');",
+            "errors <- purrr::keep(lints, \(x) x$type == 'error');",
             "quit(save = 'no', status = if (length(errors) > 0) 1 else 0)",
         ]
         # Build shell command
```

### PR DESCRIPTION
**Pull request by nwiltsie**
Fixes #2886.

## Proposed Changes

1. Pass an anonymous function to `purrr::keep` rather than a formula as recommended by [the docs](https://purrr.tidyverse.org/reference/keep.html)

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nwiltsie** [comment]
Ah, what I had was valid R code that looked like badly-escaped python code. I got rid of the not-actually-an-escape-sequence, so that should fix it.

**Comment by nwiltsie** [comment]
Judging by the logs, I think the issue is that Megalinter is using an outdated regex to detect if lintr found any issues with the file. There were lints, but the test falsely believes that there were not...

```console
MegaLinter flavor is "all", no need to check match with linters

+----MATCHING LINTERS-+-----------------+----------------+------------+
| Descriptor | Linter | Criteria        | Matching files | Format/Fix |
+------------+--------+-----------------+----------------+------------+
| R          | lintr  | .r|.R|.Rmd|.RMD | 1              | no         |
+------------+--------+-----------------+----------------+------------+
::endgroup::
[lintr] CWD: /tmp/lint/.automation/test/r
[lintr] result: 0 Warning message:
Function with_defaults was deprecated in lintr version 3.0.0. Use linters_with_defaults or modify_defaults instead.
::warning file=/tmp/lint/.automation/test/r/r_bad_1.r,line=8,col=3::file=/tmp/lint/.automation/test/r/r_bad_1.r,line=8,col=3,[assignment_linter] Use <-, not =, for assignment.

...

::warning file=/tmp/lint/.automation/test/r/r_bad_1.r,line=43,col=1::file=/tmp/lint/.automation/test/r/r_bad_1.r,line=43,col=1,[trailing_blank_lines_linter] Trailing blank lines are superfluous.

[Text Reporter] Generated TEXT report: /tmp/0cc005a6-86ad-484f-b16a-c6e4929077b7/linters_logs/SUCCESS-R_LINTR.log
::group::✅ Linted [R] files with [lintr] successfully - (1.5s) (expand for details)
- Using [lintr v0.0.0] https://megalinter.io/test-nwiltsie-merge/descriptors/r_lintr
- MegaLinter key: [R_LINTR]
- Rules config: [/.automation/test/r/.lintr]
- Number of files analyzed: [1]
::endgroup::
[Post] No commands declared in user configuration
[Azure Comment Reporter] No Azure Token found, so skipped post of PR comment
[Gitlab Comment Reporter] No Gitlab Token found, so skipped post of MR comment

+----SUMMARY-+--------+------+-------+-------+--------+--------------+
| Descriptor | Linter | Mode | Files | Fixed | Errors | Elapsed time |
+------------+--------+------+-------+-------+--------+--------------+
| ✅ R       | lintr  | file |     1 |       |      0 |         1.5s |
+------------+--------+------+-------+-------+--------+--------------+

✅ Successfully linted all files without errors
Cleared MegaLinter runtime config for request bcb650b8-3d4c-11ee-b75b-0242ac110004
```

I think there's a mismatch between lintr's exit code and the test's expectation. lintr is saying that there are 0 _errors_ and thus failing the test.

In `main` lintr is crashing, which produces the expected error, so the test incorrectly "passes". I suspect if we added a test case with style-only lints but that _shouldn't_ produce any errors, `main` would start _correctly_ failing.

**Comment by nvuillam** [comment]
> Judging by the logs, I think the issue is that Megalinter is using an outdated regex to detect if lintr found any issues with the file. There were lints, but the test falsely believes that there were not...
> 
> ```
> MegaLinter flavor is "all", no need to check match with linters
> 
> +----MATCHING LINTERS-+-----------------+----------------+------------+
> | Descriptor | Linter | Criteria        | Matching files | Format/Fix |
> +------------+--------+-----------------+----------------+------------+
> | R          | lintr  | .r|.R|.Rmd|.RMD | 1              | no         |
> +------------+--------+-----------------+----------------+------------+
> ::endgroup::
> [lintr] CWD: /tmp/lint/.automation/test/r
> [lintr] result: 0 Warning message:
> Function with_defaults was deprecated in lintr version 3.0.0. Use linters_with_defaults or modify_defaults instead.
> ::warning file=/tmp/lint/.automation/test/r/r_bad_1.r,line=8,col=3::file=/tmp/lint/.automation/test/r/r_bad_1.r,line=8,col=3,[assignment_linter] Use <-, not =, for assignment.
> 
> ...
> 
> ::warning file=/tmp/lint/.automation/test/r/r_bad_1.r,line=43,col=1::file=/tmp/lint/.automation/test/r/r_bad_1.r,line=43,col=1,[trailing_blank_lines_linter] Trailing blank lines are superfluous.
> 
> [Text Reporter] Generated TEXT report: /tmp/0cc005a6-86ad-484f-b16a-c6e4929077b7/linters_logs/SUCCESS-R_LINTR.log
> ::group::✅ Linted [R] files with [lintr] successfully - (1.5s) (expand for details)
> - Using [lintr v0.0.0] https://megalinter.io/test-nwiltsie-merge/descriptors/r_lintr
> - MegaLinter key: [R_LINTR]
> - Rules config: [/.automation/test/r/.lintr]
> - Number of files analyzed: [1]
> ::endgroup::
> [Post] No commands declared in user configuration
> [Azure Comment Reporter] No Azure Token found, so skipped post of PR comment
> [Gitlab Comment Reporter] No Gitlab Token found, so skipped post of MR comment
> 
> +----SUMMARY-+--------+------+-------+-------+--------+--------------+
> | Descriptor | Linter | Mode | Files | Fixed | Errors | Elapsed time |
> +------------+--------+------+-------+-------+--------+--------------+
> | ✅ R       | lintr  | file |     1 |       |      0 |         1.5s |
> +------------+--------+------+-------+-------+--------+--------------+
> 
> ✅ Successfully linted all files without errors
> Cleared MegaLinter runtime config for request bcb650b8-3d4c-11ee-b75b-0242ac110004
> ```
> 
> I think there's a mismatch between lintr's exit code and the test's expectation. lintr is saying that there are 0 _errors_ and thus failing the test.
> 
> In `main` lintr is crashing, which produces the expected error, so the test incorrectly "passes". I suspect if we added a test case with style-only lints but that _shouldn't_ produce any errors, `main` would start _correctly_ failing.

@nwiltsie as I have no idea about how to use R,  would you like to try to implement what you suggest ? :)

**Comment by nwiltsie** [comment]
Hey @nvuillam, I unfortunately don't really have the time to dig deeper than this. I'll close this PR - as it's still linked to the original issue hopefully someone else can pick this up and resolve the test issues.

**Pull request closed without merging**
