### PR TITLE
Change clj-kondo installation from Docker image to installation script

### PR DESCRIPTION
**Pull request by bdovaz**
Upgrades to the latest version automatically

https://github.com/clj-kondo/clj-kondo/blob/master/doc/install.md#installation-script-macos-and-linux

Fixes #2367 

It also helps us to add arm64 compatibility when we finish #2273 since the docker image is only compatible with amd64.

https://hub.docker.com/r/cljkondo/clj-kondo/tags

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4205847866)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.16s       |
|✅ BASH      |[shfmt](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.43s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |3.68s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|21.21s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|3.3s        |
|✅ JSON      |[jsonlint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.38s       |
|✅ JSON      |[v8r](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/json_v8r)                                              |   21|     |                                                                      0|15.18s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/markdown_markdownlint)                        |  309|    0|[230](https://github.com/oxsecurity/megalinter/actions/runs/4205847866)|7.65s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|6.24s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|21.48s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|2.27s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4205847866) |2.59s       |
|✅ PYTHON    |[black](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_black)                                        |  183|    0|                                                                      0|5.05s       |
|✅ PYTHON    |[flake8](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_flake8)                                      |  183|     |                                                                      0|2.26s       |
|✅ PYTHON    |[isort](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_isort)                                        |  183|    0|                                                                      0|1.02s       |
|✅ PYTHON    |[mypy](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_mypy)                                          |  183|     |                                                                      0|9.4s        |
|✅ PYTHON    |[pylint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_pylint)                                      |  183|     |                                                                      0|14.43s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/python_pyright)                                    |  183|     |[246](https://github.com/oxsecurity/megalinter/actions/runs/4205847866)|23.06s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/repository_checkov)                                |yes  |     |no                                                                     |35.36s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.46s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |16.72s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |34.32s      |
|✅ SPELL     |[cspell](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/spell_cspell)                                       |  745|     |                                                                      0|28.09s      |
|✅ SPELL     |[misspell](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/spell_misspell)                                   |  566|    0|                                                                      0|1.0s        |
|✅ XML       |[xmllint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.53s       |
|✅ YAML      |[prettier](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|4.33s       |
|✅ YAML      |[v8r](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|71.21s      |
|✅ YAML      |[yamllint](https://megalinter.io/787f295563514d40c523d35aaf2b33b3df724ab6/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.41s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4205847866)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
Why is it needed to use the script rather than docker? The images seem up to date? Personally, I'd rather Docker images and copying a single file or a couple files if possible. With docker images, when possible, we are able to build way faster (buildkit helps!) and not invalidate too much layers too.

**Comment by bdovaz** [comment]
> Why is it needed to use the script rather than docker? The images seem up to date? Personally, I'd rather Docker images and copying a single file or a couple files if possible. With docker images, when possible, we are able to build way faster (buildkit helps!) and not invalidate too much layers too.

@echoix if you have read, the docker image only works on amd64 and not arm64 and on the other hand, we have to use specific tags per version.

With this change we get to be compatible with arm64 and always be in the latest version without changes needed.

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4205847852)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.04s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.49s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|14.51s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.79s       |
|✅ JSON      |[jsonlint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.21s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.65s       |
|✅ JSON      |[v8r](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.84s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/markdown_markdownlint)                        |  309|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4205847852)|5.51s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.32s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|14.84s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.69s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4205847852) |1.98s       |
|✅ PYTHON    |[black](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_black)                                        |  183|    0|                                                                      0|3.59s       |
|✅ PYTHON    |[flake8](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.83s       |
|✅ PYTHON    |[isort](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_isort)                                        |  183|    0|                                                                      0|0.4s        |
|✅ PYTHON    |[mypy](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_mypy)                                          |  183|     |                                                                      0|6.72s       |
|✅ PYTHON    |[pylint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_pylint)                                      |  183|     |                                                                      0|11.19s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/python_pyright)                                    |  183|     |[244](https://github.com/oxsecurity/megalinter/actions/runs/4205847852)|16.63s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.37s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4205847852) |1.31s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.59s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.05s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |8.21s       |
|✅ REPOSITORY|[syft](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.93s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |21.25s      |
|✅ SPELL     |[cspell](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/spell_cspell)                                       |  745|     |                                                                      0|17.22s      |
|✅ SPELL     |[misspell](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/spell_misspell)                                   |  566|    2|                                                                      0|0.53s       |
|✅ XML       |[xmllint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.52s       |
|✅ YAML      |[v8r](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|59.13s      |
|✅ YAML      |[yamllint](https://megalinter.io/d18b1c000723e944d4e51200c9a01a4b4de44e29/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.2s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4205847852)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by echoix** [comment]
I see. There's nothing wrong with this. Maybe one day we could look into making it as a build stage in order to keep the buildkit parallelism. In my apk go PR that isn't merged yet since I need to undo changes, I was able to do this quite easily by using a yaml multi line string ( the one that starts with a pipe character) and just making sure the first item started with "from" and the other one with "COPY". Then I had a block of docker commands that could be used as a stage

**Review by nvuillam — APPROVED** [review]
Great, as usual :)

**Pull request merged**
