### PR TITLE
Organize extends tests

### PR DESCRIPTION
**Pull request by bdovaz**
As I mention in #2371 there is quite a bit of chaos in the organization of test input files:

- I have organized the test input files by folder.
- I have created a test that does a mix of local and remote EXTENDS.
- I improved two asserts to use regular expressions instead of `in` which does not give so much security.
- I pass the repository branch by environment variable because right now there are fixed urls against the main branch and if we are testing in a branch, it is not possible to run the tests against the files in your branch.

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87) status: ❌ [ERROR](https://github.com/oxsecurity/megalinter/actions/runs/4217896046)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.36s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.76s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|16.32s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.18s       |
|✅ JSON      |[jsonlint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.25s       |
|✅ JSON      |[v8r](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/json_v8r)                                              |   21|     |                                                                      0|11.52s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/markdown_markdownlint)                        |  309|    0|[230](https://github.com/oxsecurity/megalinter/actions/runs/4217896046)|6.31s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.44s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/markdown_markdown_table_formatter)|  309|    0|                                                                      0|17.76s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.62s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4217896046) |1.9s        |
|✅ PYTHON    |[black](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_black)                                        |  183|    1|                                                                      0|4.54s       |
|❌ PYTHON    |[flake8](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_flake8)                                      |  183|     |[2](https://github.com/oxsecurity/megalinter/actions/runs/4217896046)  |3.68s       |
|✅ PYTHON    |[isort](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_isort)                                        |  183|    1|                                                                      0|0.77s       |
|✅ PYTHON    |[mypy](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_mypy)                                          |  183|     |                                                                      0|6.44s       |
|✅ PYTHON    |[pylint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_pylint)                                      |  183|     |                                                                      0|11.1s       |
|⚠️ PYTHON    |[pyright](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/python_pyright)                                    |  183|     |[247](https://github.com/oxsecurity/megalinter/actions/runs/4217896046)|16.82s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/repository_checkov)                                |yes  |     |no                                                                     |28.11s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.39s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |14.03s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |26.52s      |
|✅ SPELL     |[cspell](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/spell_cspell)                                       |  745|     |                                                                      0|18.8s       |
|✅ SPELL     |[misspell](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/spell_misspell)                                   |  566|    0|                                                                      0|0.89s       |
|✅ XML       |[xmllint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.36s       |
|✅ YAML      |[prettier](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.78s       |
|✅ YAML      |[v8r](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|54.76s      |
|✅ YAML      |[yamllint](https://megalinter.io/4432c8c2c22f520fc42112674d2bee159b232e87/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.1s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4217896046)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Review by nvuillam — APPROVED** [review]
Great :)
Will be merged once CI is ok ^^

**Comment by bdovaz** [comment]
@nvuillam it fails me a workflow but I don't understand why, I haven't touched anything related to those files:

https://github.com/oxsecurity/megalinter/actions/runs/4218051705/jobs/7322667444

image

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4218630953)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.03s       |
|✅ BASH      |[shellcheck](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.3s        |
|✅ BASH      |[shfmt](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.05s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.85s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/dockerfile_hadolint)                              |  114|     |                                                                      0|16.85s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.91s       |
|✅ JSON      |[jsonlint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.28s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.72s       |
|✅ JSON      |[v8r](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.61s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/markdown_markdownlint)                        |  309|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4218630953)|6.04s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/markdown_markdown_link_check)          |  309|     |                                                                      0|5.72s       |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/markdown_markdown_table_formatter)|  309|    2|                                                                      0|17.67s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.82s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_bandit)                                      |  183|     |[47](https://github.com/oxsecurity/megalinter/actions/runs/4218630953) |4.06s       |
|✅ PYTHON    |[black](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_black)                                        |  183|    1|                                                                      0|3.67s       |
|✅ PYTHON    |[flake8](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_flake8)                                      |  183|     |                                                                      0|1.89s       |
|✅ PYTHON    |[isort](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_isort)                                        |  183|    1|                                                                      0|0.49s       |
|✅ PYTHON    |[mypy](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_mypy)                                          |  183|     |                                                                      0|7.75s       |
|✅ PYTHON    |[pylint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_pylint)                                      |  183|     |                                                                      0|12.23s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/python_pyright)                                    |  183|     |[246](https://github.com/oxsecurity/megalinter/actions/runs/4218630953)|19.15s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_checkov)                                |yes  |     |no                                                                     |31.63s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4218630953) |1.41s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |1.48s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |9.42s       |
|✅ REPOSITORY|[syft](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_syft)                                      |yes  |     |no                                                                     |1.18s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |24.45s      |
|✅ SPELL     |[cspell](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/spell_cspell)                                       |  745|     |                                                                      0|19.41s      |
|✅ SPELL     |[misspell](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/spell_misspell)                                   |  566|    2|                                                                      0|0.64s       |
|✅ XML       |[xmllint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.03s       |
|✅ YAML      |[prettier](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.72s       |
|✅ YAML      |[v8r](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|58.15s      |
|✅ YAML      |[yamllint](https://megalinter.io/49ab2b819eec15bda018a83f61323fb5264d37d0/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.2s        |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4218630953)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
Probably something about future conflicts... i merged, we'll see :)

**Pull request merged**
