### PR TITLE
feat: add ruff linter

### LINKED ISSUE #2153: Replace flake8/isort with Ruff
[Ruff](https://github.com/charliermarsh/ruff) seems like almost a drop-in replacement for flake8/isort, at 10X the speed and with additional features. It would also likely make images smaller. Would be great to replace these tools - thanks for your consideration!

### PR DESCRIPTION
**Pull request by lars-reimann**
Fixes #2153

## Proposed Changes

1. Add the [`ruff` Python linter](https://github.com/charliermarsh/ruff).

### Author/Contributor
- [x] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [X] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by Kurt-von-Laven** [comment]
Ruff markets itself as a much faster replacement for flake8, isort, and possibly other linters we already include in the Python flavor. It feels like it defeats the purpose of adding Ruff to leave the linters it duplicates in, but on the other hand maybe we should wait to remove the other linters until MegaLinter v7. What do folks think?

**Comment by nvuillam** [comment]
I think ruff and the others can be both in MegaLinter for now, and users will decide which one they use :)

**Comment by lars-reimann** [comment]
Ruff can be configured either in `pyproject.toml` (preferred) or `ruff.toml`. Currently, I've chosen `pyproject.toml`. Would `ruff.toml` be a better choice since projects might need a `pyproject.toml` but might want to store their linter configuration in `.github/linters` or some external repo?

**Comment by echoix** [comment]
I think that in the middle-term future, we should find a way to properly handle what's defined in pyproject.toml, since it's where Python projects should go, and it's supposed to be there where the tools used are defined. But that means parsing that file, not only detecting its presence. 

That pyproject.toml handling doesn't need to be ready for the first inclusion of ruff.

@nvuillam @Kurt-von-Laven what are your opinions on this?

**Comment by nvuillam** [comment]
That could be an option on desceptors to avoid using the default config file while there is something in the pyproject, indeed :)

**Comment by lars-reimann** [comment]
Maybe `config_file_name` could accept an array of objects containing

1. the file name to look for
2. how to check that the file should be used as config (file exists, file contains some text matching a regex)
3. an further options needed for 2 (like the regex to look for).

The options could then be checked in order and the first matching file could be used. For `ruff` it would be something like

```yml
- config_file_name:
  - file: "pyproject.toml"
    check: matches_regex
    regex: "[tool\.ruff"
  - file: "ruff.toml"
    check: file_exists
  - file: ".ruff.toml"
    check: file_exists
```

Property names, `config_file_name` specifically, need some work.

**Comment by nvuillam** [comment]
I think we discussed that in another PR, that's definitely something to do :)

Meanwhile, config file name can be forced in local repo config

**Comment by nvuillam** [comment]
@lars-reimann the fixes number is computed from the list of files that are detected as updated after the linting :)

**Comment by lars-reimann** [comment]
Alright, this is done from my side then.

**Comment by nvuillam** [comment]
The PR looks great :)
I'll merge it after today's release so it can be used with beta version until next release :)

**Comment by Kurt-von-Laven** [comment]
Personally, I feel that we should make `LINTER_DEFAULT` the default config file for of all linters in one shot in a major release. That would keep MegaLinter as simple as possible and make it more user-friendly at the same time.

**Comment by lars-reimann** [comment]
Looks like Trivy was also happy this time round.

**Review by nvuillam — APPROVED** [review]
Great :)

Many many thanks for this contribution :)

**Comment by Kurt-von-Laven** [comment]
Note that Ruff only enables a tiny subset of available rules by default, so if one wishes to replace Bandit, Flake8, and isort for best performance, they would need to [configure Ruff explicitly](https://beta.ruff.rs/docs/tutorial/#rule-selection).

**Pull request merged**
