### PR TITLE
Update editorconfig-checker to 2.7.0 (refs #1282)

### PR DESCRIPTION
**Pull request by rasa**
### Author/Contributor
- [X] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Review by nvuillam — APPROVED** [review]
Thanks :) 
I suspect you did not use[ `bash build.sh`](https://megalinter.io/latest/contributing/#without-write-access) , but in that case it will work anyway , so once CI is ok it can be merged :)

**Comment by rasa** [comment]
> I suspect you did not use[ `bash build.sh`](https://megalinter.io/latest/contributing/#without-write-access)...

@nvuillam I didn't, my bad, sorry. Happy to close the PR and submit a new one that follows the program, if you prefer.

**Comment by nvuillam** [comment]
In that case it will do the same: read the yml descriptor file and propagate to all others, so it will be ok , u'll just know for next time:)

**Comment by Kurt-von-Laven** [comment]
Related to #1282

**Pull request merged**
