### PR TITLE
Hadolint: support both `Containerfile` and `Dockerfile`

### PR DESCRIPTION
**Pull request by sanmai-NL**
Fixes #

## Proposed Changes

A vendor-neutral name for `Dockerfile` is [`Containerfile`](https://www.mankier.com/5/Containerfile).

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
@sanmai-NL thanks for the PR :)

Just add "Containerfile" in **.cspell.json** and it will pass :)

**Comment by sanmai-NL** [comment]
@nvuillam Done. Can you finish the rest?

**Comment by nvuillam** [comment]
@sanmai-NL i think once the CI passes we are all good, just remove the "draft" status of the PR if you consider it ready for merge :)

**Comment by sanmai-NL** [comment]
@nvuillam Done.

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
Thanks! The failure is unrelated and I don't understand the cause yet, but your job is done :)

**Pull request merged**
