### PR TITLE
Downgrade revive & Temporary disable cljstyle

### PR DESCRIPTION
**Pull request by nvuillam**
Related cljstyle issue: https://github.com/greglook/cljstyle/issues/104

### CODE REVIEW

**Comment by bdovaz** [comment]
@nvuillam when things like this happen shouldn't we put a // TODO and a comment or a url to the Github issue? https://github.com/mgechev/revive/issues/956

Otherwise we don't know why we have pinned / downgraded to a particular version.

cc @echoix @Kurt-von-Laven

**Comment by echoix** [comment]
Normally when I find the issue that caused the downgrade, I subscribe to the issue and also at releases to the project so I know when to act upon. Like for the stylelint sass config guidelines, I undowngraded it the same morning when waking up.

**Comment by bdovaz** [comment]
> Normally when I find the issue that caused the downgrade, I subscribe to the issue and also at releases to the project so I know when to act upon. Like for the stylelint sass config guidelines, I undowngraded it the same morning when waking up.

Yes, I do the same, the TODO and the url was more so that anyone can be put in context and that the knowledge is not only in who found the problem initially.

**Comment by nvuillam** [comment]
indeed, usually i use downgraded: true and downgraded_reason: xxxx , I just forgot here, i'll correct that !

**Pull request merged**
