### PR TITLE
Fix PHPStan install & Upgrade stale action

### PR DESCRIPTION
**Pull request by nvuillam**

### CODE REVIEW

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4505018079)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.14s       |
|✅ BASH      |[shfmt](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.37s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.51s       |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/dockerfile_hadolint)                              |  115|     |                                                                      0|14.94s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|2.0s        |
|✅ JSON      |[jsonlint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.18s       |
|✅ JSON      |[v8r](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.74s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/markdown_markdownlint)                        |  311|    0|[230](https://github.com/oxsecurity/megalinter/actions/runs/4505018079)|5.67s       |
|✅ MARKDOWN  |[markdown-link-check](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/markdown_markdown_link_check)          |  311|     |                                                                      0|5.4s        |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/markdown_markdown_table_formatter)|  311|    0|                                                                      0|16.22s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.34s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_bandit)                                      |  184|     |[55](https://github.com/oxsecurity/megalinter/actions/runs/4505018079) |2.11s       |
|✅ PYTHON    |[black](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_black)                                        |  184|    0|                                                                      0|3.85s       |
|✅ PYTHON    |[flake8](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_flake8)                                      |  184|     |                                                                      0|1.78s       |
|✅ PYTHON    |[isort](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_isort)                                        |  184|    0|                                                                      0|0.75s       |
|✅ PYTHON    |[mypy](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_mypy)                                          |  184|     |                                                                      0|7.17s       |
|✅ PYTHON    |[pylint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_pylint)                                      |  184|     |                                                                      0|10.54s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/python_pyright)                                    |  184|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4505018079)|15.07s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/repository_checkov)                                |yes  |     |no                                                                     |27.91s      |
|✅ REPOSITORY|[git_diff](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.36s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |12.02s      |
|✅ REPOSITORY|[trivy](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |26.36s      |
|✅ SPELL     |[cspell](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/spell_cspell)                                       |  749|     |                                                                      0|18.55s      |
|✅ SPELL     |[misspell](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/spell_misspell)                                   |  569|    0|                                                                      0|0.85s       |
|✅ XML       |[xmllint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.39s       |
|✅ YAML      |[prettier](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.82s       |
|✅ YAML      |[v8r](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|61.13s      |
|✅ YAML      |[yamllint](https://megalinter.io/31da18a71f2c6fc419dc436b490565ef4e4f577d/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.08s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4505018079)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by nvuillam** [comment]
@llaville would you have an idea about how to solve this issue ?

https://github.com/oxsecurity/megalinter/actions/runs/4505019064/jobs/7930231095#step:7:329

It seems GPG key does not work anymore, or waits for something to push ENTER :/

**Comment by nvuillam** [comment]
## [🦙 MegaLinter](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf) status: ⚠️ [WARNING](https://github.com/oxsecurity/megalinter/actions/runs/4516409766)

| Descriptor  |                                                                 Linter                                                                 |Files|Fixed|                                Errors                                 |Elapsed time|
|-------------|----------------------------------------------------------------------------------------------------------------------------------------|-----|----:|-----------------------------------------------------------------------|------------|
|✅ BASH      |[bash-exec](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/bash_bash_exec)                                  |    6|     |                                                                      0|0.01s       |
|✅ BASH      |[shellcheck](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/bash_shellcheck)                                |    6|     |                                                                      0|0.13s       |
|✅ BASH      |[shfmt](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/bash_shfmt)                                          |    6|    0|                                                                      0|0.03s       |
|✅ COPYPASTE |[jscpd](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                     |2.8s        |
|✅ DOCKERFILE|[hadolint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/dockerfile_hadolint)                              |  115|     |                                                                      0|13.72s      |
|✅ JSON      |[eslint-plugin-jsonc](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                      0|1.82s       |
|✅ JSON      |[jsonlint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/json_jsonlint)                                    |   19|     |                                                                      0|0.14s       |
|✅ JSON      |[npm-package-json-lint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/json_npm_package_json_lint)          |yes  |     |no                                                                     |0.53s       |
|✅ JSON      |[v8r](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/json_v8r)                                              |   21|     |                                                                      0|12.23s      |
|⚠️ MARKDOWN  |[markdownlint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/markdown_markdownlint)                        |  311|    2|[230](https://github.com/oxsecurity/megalinter/actions/runs/4516409766)|5.51s       |
|⚠️ MARKDOWN  |[markdown-link-check](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/markdown_markdown_link_check)          |  311|     |[28](https://github.com/oxsecurity/megalinter/actions/runs/4516409766) |261.84s     |
|✅ MARKDOWN  |[markdown-table-formatter](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/markdown_markdown_table_formatter)|  311|    2|                                                                      0|15.06s      |
|✅ OPENAPI   |[spectral](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/openapi_spectral)                                 |    1|     |                                                                      0|1.07s       |
|⚠️ PYTHON    |[bandit](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_bandit)                                      |  184|     |[55](https://github.com/oxsecurity/megalinter/actions/runs/4516409766) |2.05s       |
|✅ PYTHON    |[black](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_black)                                        |  184|    0|                                                                      0|3.5s        |
|✅ PYTHON    |[flake8](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_flake8)                                      |  184|     |                                                                      0|1.33s       |
|✅ PYTHON    |[isort](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_isort)                                        |  184|    0|                                                                      0|0.43s       |
|✅ PYTHON    |[mypy](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_mypy)                                          |  184|     |                                                                      0|6.93s       |
|✅ PYTHON    |[pylint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_pylint)                                      |  184|     |                                                                      0|10.04s      |
|⚠️ PYTHON    |[pyright](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/python_pyright)                                    |  184|     |[250](https://github.com/oxsecurity/megalinter/actions/runs/4516409766)|15.84s      |
|✅ REPOSITORY|[checkov](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_checkov)                                |yes  |     |no                                                                     |26.62s      |
|⚠️ REPOSITORY|[devskim](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_devskim)                                |yes  |     |[61](https://github.com/oxsecurity/megalinter/actions/runs/4516409766) |1.02s       |
|✅ REPOSITORY|[dustilock](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_dustilock)                            |yes  |     |no                                                                     |3.12s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_git_diff)                              |yes  |     |no                                                                     |0.04s       |
|✅ REPOSITORY|[secretlint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_secretlint)                          |yes  |     |no                                                                     |5.84s       |
|✅ REPOSITORY|[syft](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_syft)                                      |yes  |     |no                                                                     |0.72s       |
|✅ REPOSITORY|[trivy](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/repository_trivy)                                    |yes  |     |no                                                                     |16.49s      |
|✅ SPELL     |[cspell](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/spell_cspell)                                       |  749|     |                                                                      0|17.79s      |
|✅ SPELL     |[misspell](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/spell_misspell)                                   |  569|    2|                                                                      0|0.45s       |
|✅ XML       |[xmllint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/xml_xmllint)                                       |    3|    0|                                                                      0|0.04s       |
|✅ YAML      |[prettier](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/yaml_prettier)                                    |   81|    0|                                                                      0|2.59s       |
|✅ YAML      |[v8r](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/yaml_v8r)                                              |   23|     |                                                                      0|42.94s      |
|✅ YAML      |[yamllint](https://megalinter.io/6c6eb2db40d04fd7b72f3332be2ed3c0ee40b6cf/descriptors/yaml_yamllint)                                    |   82|     |                                                                      0|1.06s       |

See detailed report in [MegaLinter reports](https://github.com/oxsecurity/megalinter/actions/runs/4516409766)

You could have same capabilities but better runtime performances if you request a new MegaLinter flavor.
- [Click here to request the new flavor](https://github.com/oxsecurity/megalinter/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Request%20new%20MegaLinter%20flavor&body=MegaLinter%20would%20run%20faster%20on%20my%20project%20if%20I%20had%20a%20flavor%20containing%20the%20following%20list%20of%20linters%3A%20%0A%0A%20-%20Add%20languages/linters%20list%20here%0A%0AWould%20it%20be%20possible%20to%20create%20one%20%3F%20Thanks%20%3Arelaxed%3A)

_MegaLinter is graciously provided by [OX Security](https://www.ox.security/?ref=megalinter)_

**Comment by ondrejmirtes** [comment]
I think you should be able to remove the whole `Phive` section from the PHPStan Dockerfile: https://github.com/oxsecurity/megalinter/blob/5e57679cd54d6b74109409c81de0fedba633e572/linters/php_phpstan/Dockerfile#L138-L150

**Comment by nvuillam** [comment]
Indeed it will reduce the size :)

**Pull request merged**
